<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue';
import LifecyclePanel from './LifecyclePanel.vue';
import {ElMessageBox} from 'element-plus';
import {usePreferences} from '../../../packages/ui/src/preferences.js';
import brandLogo from '../../../website/public/images/materialsx-icon.png';
import {ops,OpsError,type Finance} from './api.js';
import {reconciliationEvidenceSchema,releaseManifestSchema,type WorkspaceStatus,type WorkspaceControls,type ReleaseEntry,type userSchema,type auditEventSchema,type pendingBillingSchema,type billingOverviewSchema,type refundPreviewSchema} from '../../../packages/contracts/src/platform.js';
import type {z} from 'zod';
const {locale,theme,t}=usePreferences();
const totpRequired=ref(true);
const lastLoaded=ref<string|null>(null);
const signedIn=ref(false),busy=ref(false),tab=ref('overview'),message=ref(''),error=ref(false),email=ref(''),password=ref(''),otp=ref(''),reason=ref('');
const status=ref<WorkspaceStatus|null>(null),controls=ref<WorkspaceControls|null>(null),overview=ref<z.infer<typeof billingOverviewSchema>|null>(null),finance=ref<Finance|null>(null),users=ref<z.infer<typeof userSchema>[]>([]),userCursor=ref<string|null>(null),audit=ref<z.infer<typeof auditEventSchema>[]>([]),auditCursor=ref<string|null>(null),pending=ref<z.infer<typeof pendingBillingSchema>['items']>([]),releases=ref<ReleaseEntry[]>([]),selectedOrder=ref<Finance['items'][number]|null>(null),preview=ref<z.infer<typeof refundPreviewSchema>|null>(null),evidence=ref(''),manifestText=ref(''),search=ref('');
const mxRoutes=ref<Awaited<ReturnType<typeof ops.mxRoutes>>|null>(null);
const keys=new Map<string,string>();
async function mutation<T>(input:unknown,fn:(key:string)=>Promise<T>){const fp=JSON.stringify(input),key=keys.get(fp)??crypto.randomUUID();keys.set(fp,key);const out=await fn(key);keys.delete(fp);return out}
function clearData(){lastLoaded.value=null;status.value=null;controls.value=null;overview.value=null;finance.value=null;users.value=[];audit.value=[];pending.value=[];releases.value=[];mxRoutes.value=null;selectedOrder.value=null;preview.value=null;evidence.value='';manifestText.value='';reason.value='';keys.clear()}
async function action(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value=false;message.value='';try{await fn()}catch(e){error.value=true;if(e instanceof OpsError){const explanation=e.code==='RELEASE_GATES_NOT_SATISFIED'?t('发布证据不足，请核对部署审批文件与清单摘要','Publication gates unmet. Check deployment approvals and manifest hash'):e.code==='PUBLIC_RELEASE_UNVERIFIED'?t('无法核验公开安装文件，请核对 GitHub immutable Release、commit 和 asset digest','Public release verification failed. Check the immutable release, commit and asset digest'):t('操作未完成','Operation failed');message.value=explanation+`: ${e.code}`+(e.requestId?` · ${e.requestId}`:'');if(e.code==='UNAUTHENTICATED'){signedIn.value=false;clearData()}}else{message.value=t('连接失败或数据无效，请刷新核对结果。未确认的提交不要重复创建。','Connection failed or invalid data. Refresh to check the outcome before creating another operation.')}}finally{busy.value=false}}
async function refresh(){
 const [s,o,f,u,a,p,r,mx]=await Promise.allSettled([
  ops.status(),ops.overview(),ops.finance(),ops.users(),
  ops.audit(),ops.pending(),ops.releases(),ops.mxRoutes()
 ]);
 for(const result of [s,o,f,u,a,p,r,mx]){
  if(result.status==='rejected'&&result.reason instanceof OpsError&&result.reason.code==='UNAUTHENTICATED')throw result.reason;
 }
 const failed:string[]=[];
 if(s.status==='fulfilled'){status.value=s.value;controls.value={...s.value.controls}}else failed.push(t('服务控制','Service controls'));
 if(o.status==='fulfilled')overview.value=o.value;else failed.push(t('用量总览','Usage overview'));
 if(f.status==='fulfilled'){
  finance.value=f.value;
  if(selectedOrder.value)selectedOrder.value=f.value.items.find(v=>v.order.id===selectedOrder.value?.order.id)??null;
 }else failed.push(t('订单与退款','Orders and refunds'));
 if(u.status==='fulfilled'){users.value=u.value.items;userCursor.value=u.value.nextCursor}else failed.push(t('用户','Users'));
 if(a.status==='fulfilled'){audit.value=a.value.items;auditCursor.value=a.value.nextCursor}else failed.push(t('审计','Audit'));
 if(p.status==='fulfilled')pending.value=p.value.items;else failed.push(t('待核对调用','Pending requests'));
 if(r.status==='fulfilled')releases.value=r.value.items;else failed.push(t('版本目录','Release catalogue'));
 if(mx.status==='fulfilled')mxRoutes.value=mx.value;else failed.push(t('供应商与路由','Providers and routes'));
 preview.value=null;
 if(failed.length<8)lastLoaded.value=new Date().toLocaleString(locale.value==='zh'?'zh-CN':'en-US');
 if(failed.length){error.value=true;message.value=t('部分数据未能加载：','Some data could not be loaded: ')+failed.join('、')+t('。其他板块已更新，请稍后刷新。','; other sections were updated. Please refresh later.')}
}
async function login(){await action(async()=>{try{await ops.login({email:email.value,password:password.value,otp:otp.value});signedIn.value=true;await refresh()}finally{password.value='';otp.value=''}})}
async function logout(){await action(async()=>{await ops.logout();signedIn.value=false;clearData()})}
async function confirm(text:string){try{await ElMessageBox.confirm(text,t('确认操作','Confirm operation'),{confirmButtonText:t('确认','Confirm'),cancelButtonText:t('取消','Cancel'),type:'warning'});return true}catch{return false}}
function cash(raw:string|undefined){return raw===undefined?'—':fen(raw)}
function fen(raw:string){const n=BigInt(raw),abs=n<0n?-n:n;return `${n<0n?'-':''}${abs/100n}.${(abs%100n).toString().padStart(2,'0')}`}
async function setUser(user:z.infer<typeof userSchema>){if(!reason.value.trim()){message.value=t('请先填写操作原因','Enter an operation reason');return}const state=user.status==='active'?'suspended':'active';if(!await confirm(`${user.email}: ${state}\n${reason.value}`))return;await action(async()=>{const body={status:state,reason:reason.value.trim(),expectedVersion:user.version};await mutation([user.id,body],key=>ops.setStatus(user.id,body,key));await refresh()})}
async function saveControls(){const current=controls.value;if(!current||!reason.value.trim()){message.value=t('请填写原因','Enter a reason');return}if(!await confirm(t('保存暂停开关与公告？正在运行的调用仍可停止和结算。','Save admission switches and announcements? Running calls remain cancellable and settleable.')))return;await action(async()=>{const body={...current,reason:reason.value.trim()};await mutation(body,key=>ops.controls(body,key));await refresh()})}
async function refundPreview(id:string){await action(async()=>{preview.value=await ops.refundPreview(id)})}
async function decide(decision:'approve'|'reject'|'review'){const p=preview.value;if(!p||!reason.value.trim())return;if(!await confirm(`${decision}: ¥${fen(p.refund.amountFen)} / ${p.recoverCredits} ${selectedOrder.value?.order.channel==='wechat'?'paid-credit':'test-credit'}\n${reason.value}`))return;await action(async()=>{await ops.refundDecision({decision,reason:reason.value.trim(),expectedVersion:p.refund.version,orderVersion:p.orderVersion},p.refund.id);await refresh()})}
async function simulate(){const order=selectedOrder.value?.order;if(!order||!await confirm(t('仅模拟测试付款，不发生真实扣款。','Simulate test payment only. No real payment occurs.')))return;await action(async()=>{await ops.simulate(order.id);await refresh()})}
async function recheck(){const order=selectedOrder.value?.order;if(!order||!reason.value.trim()||!await confirm(t('使用原订单编号查询渠道？不会重新提交付款或退款。','Query the channel with the existing order ID? No new payment or refund submission occurs.')))return;await action(async()=>{await ops.recheck({orderId:order.id,reason:reason.value.trim(),expectedVersion:order.version},order.id);await refresh()})}
async function reconcile(){await action(async()=>{const body=reconciliationEvidenceSchema.parse(JSON.parse(evidence.value));const p=await ops.preview(body);if(!await confirm(`${t('核对预览','Reconciliation preview')}\n${JSON.stringify(p,null,2)}`))return;await ops.reconcile(body,body.requestId);evidence.value='';await refresh()})}
function choosePending(p:typeof pending.value[number]){evidence.value=JSON.stringify({requestId:p.requestId,expectedVersion:p.version,resolution:'waiver',sourceRef:'replace-with-evidence-id',reason:'',usage:null},null,2)}
async function draft(){await action(async()=>{const m=releaseManifestSchema.parse(JSON.parse(manifestText.value));if(!reason.value.trim()){message.value=t('请输入原因','Enter a reason');return};const body={action:'draft',id:m.id,manifest:m,expectedVersion:'0',reason:reason.value.trim()};await mutation(body,key=>ops.release(body,key));manifestText.value='';await refresh()})}
async function releaseAction(r:ReleaseEntry,kind:'publish'|'withdraw'){if(!reason.value.trim()){message.value=t('请输入原因','Enter a reason');return}if(!await confirm(`${kind}: ${r.manifest.id}\n${t('发布前须通过部署证据和公开 GitHub 安装文件核验。撤回只移出下载目录。','Publication requires deployment evidence and verified public GitHub assets. Withdrawal removes catalogue visibility only.')}`))return;await action(async()=>{const body={action:kind,id:r.manifest.id,manifest:null,expectedVersion:r.version,reason:reason.value.trim()};await mutation(body,key=>ops.release(body,key));await refresh()})}
async function moreUsers(){await action(async()=>{if(!userCursor.value)return;const page=await ops.users(userCursor.value);users.value.push(...page.items);userCursor.value=page.nextCursor})}
async function moreAudit(){await action(async()=>{if(!auditCursor.value)return;const page=await ops.audit(auditCursor.value);audit.value.push(...page.items);auditCursor.value=page.nextCursor})}
const filteredUsers=computed(()=>users.value.filter(u=>`${u.email} ${u.displayName} ${u.id}`.toLowerCase().includes(search.value.toLowerCase())));
const tabs=computed(()=>[{id:'overview',label:t('总览','Overview')},{id:'users',label:t('用户','Users')},{id:'finance',label:t('订单与退款','Orders and refunds')},{id:'usage',label:t('用量与核对','Usage and reconciliation')},{id:'providers',label:t('供应商与路由','Providers and routes')},{id:'releases',label:t('版本发布','Releases')},{id:'lifecycle',label:t('客服与上线','Support and launch')},{id:'audit',label:t('审计','Audit')}]);
watch(theme,v=>{document.documentElement.classList.toggle('dark',v==='dark')},{immediate:true});watch(locale,v=>{document.documentElement.lang=v==='zh'?'zh-CN':'en'},{immediate:true});
onMounted(async()=>{try{totpRequired.value=(await ops.authConfig()).totpRequired}catch{}});
onMounted(async()=>{try{await ops.session();signedIn.value=true;await action(refresh)}catch(e){if(!(e instanceof OpsError&&e.code==='UNAUTHENTICATED'))await action(async()=>{throw e})}});
</script>
<template>
<div :class="['ops',theme]">
  <header class="ops-topbar">
    <div class="ops-brand">
      <img class="ops-brand__mark" :src="brandLogo" alt="" />
      <div class="ops-brand__copy">
        <strong>MaterialsX</strong>
        <span>{{t('运营中心','Operations')}}</span>
      </div>
    </div>
    <div class="toolbar ops-toolbar">
      <el-button @click="locale=locale==='zh'?'en':'zh'">{{locale==='zh'?'English':'中文'}}</el-button>
      <el-button @click="theme=theme==='dark'?'light':'dark'">{{theme==='dark'?t('浅色','Light'):t('深色','Dark')}}</el-button>
      <el-button v-if="signedIn" :disabled="busy" @click="action(refresh)">{{t('刷新','Refresh')}}</el-button>
      <el-button v-if="signedIn" :disabled="busy" @click="logout">{{t('退出','Sign out')}}</el-button>
    </div>
  </header>
<nav v-if="signedIn" class="ops-nav" :aria-label="t('运营导航','Operations navigation')"><button v-for="v in tabs" :key="v.id" :class="{active:tab===v.id}" @click="tab=v.id">{{v.label}}</button></nav>
<main><p v-if="message" :class="['notice',{error}]" role="status">{{message}}</p>
<section v-if="!signedIn" class="login">
  <span class="login-eyebrow">{{t('安全访问','Secure access')}}</span>
  <h1>{{t('登录运营中心','Sign in to Operations')}}</h1>
  <p class="login-intro">{{t('管理用户、订单、用量和版本发布。','Manage accounts, orders, usage and releases.')}}</p>
  <el-form @submit.prevent="login" label-position="top"><el-form-item :label="t('邮箱','Email')"><el-input v-model="email" type="email" autocomplete="username" required /></el-form-item><el-form-item :label="t('密码','Password')"><el-input v-model="password" type="password" autocomplete="current-password" required /></el-form-item><el-form-item v-if="totpRequired" label="TOTP"><el-input v-model="otp" maxlength="6" inputmode="numeric" autocomplete="one-time-code" required /></el-form-item><el-button class="login-submit" native-type="submit" type="primary" :loading="busy">{{t('登录','Sign in')}}</el-button></el-form><p class="login-hint">{{totpRequired?t('需要管理员权限与 MFA。会话到期后重新登录。','Administrator role and MFA required. Sign in again when the session expires.'):t('本机管理员使用邮箱和密码登录。会话到期后重新登录。','Local administrators sign in with email and password. Sign in again when the session expires.')}}</p></section>
<template v-else><p v-if="lastLoaded">{{t('数据更新时间','Data last refreshed')}}: {{lastLoaded}}</p>
 <p class="notice">{{mxRoutes?.salesEnabled?t('本机 MX 销售已启用。现金、测试金额、积分与采购成本分别记录；这里不显示科研文件或对话内容。','Local MX sales are enabled. Cash, synthetic amounts, credits and procurement costs are tracked separately. Research files and conversations are not shown.'):t('MX 销售未启用。现金、测试金额、积分与采购成本分别记录；这里不显示科研文件或对话内容。','MX sales are disabled. Cash, synthetic amounts, credits and procurement costs are tracked separately. Research files and conversations are not shown.')}}</p>
 <div v-if="tab==='overview'"><div class="metrics"><article><small>{{t('真实收款 / 已退','Real payments / refunds')}}</small><b>¥{{cash(finance?.cashInFen)}} / {{cash(finance?.cashRefundedFen)}}</b></article><article><small>{{t('测试收款 / 已退','Synthetic payments / refunds')}}</small><b>¥{{cash(finance?.syntheticInFen)}} / {{cash(finance?.syntheticRefundedFen)}}</b></article><article><small>{{t('待核对调用','Pending calls')}}</small><b>{{overview?.pendingRequests??'—'}}</b></article><article><small>{{t('采购成本未知的调用','Calls with unknown procurement cost')}}</small><b>{{overview?.procurementUnknownRequests??'—'}}</b></article></div><section><h2>{{t('服务控制','Service controls')}}</h2><p>{{t('暂停开关只控制新订单和新云请求；不开放真实收款、不释放待核对预留。','Switches control new orders and cloud requests only. They neither enable live sales nor release pending holds.')}}</p><el-form v-if="controls" label-position="top"><el-form-item :label="t('暂停新云调用','Pause new cloud calls')"><el-switch v-model="controls.cloudPaused" /></el-form-item><el-form-item :label="t('暂停新订单','Pause new orders')"><el-switch v-model="controls.salesPaused" /></el-form-item><el-form-item :label="t('中文公告','Chinese announcement')"><el-input v-model="controls.announcementZh" type="textarea" maxlength="1000" /></el-form-item><el-form-item label="English announcement"><el-input v-model="controls.announcementEn" type="textarea" maxlength="1000" /></el-form-item><el-form-item :label="t('操作原因','Operation reason')"><el-input v-model="reason" maxlength="256" /></el-form-item><el-button :disabled="busy||!reason.trim()" @click="saveControls">{{t('保存控制','Save controls')}}</el-button></el-form></section></div>
 <section v-if="tab==='users'"><h2>{{t('用户管理','User management')}}</h2><div class="toolbar"><el-input v-model="search" :placeholder="t('搜索已加载用户','Search loaded users')" /><el-input v-model="reason" maxlength="256" :placeholder="t('停用 / 恢复原因','Suspension / activation reason')" /></div><el-table :data="filteredUsers"><el-table-column prop="email" :label="t('邮箱','Email')" min-width="230"/><el-table-column prop="displayName" :label="t('名称','Name')"/><el-table-column prop="role" :label="t('角色','Role')"/><el-table-column prop="status" :label="t('状态','Status')"/><el-table-column prop="version" :label="t('版本','Version')"/><el-table-column :label="t('操作','Actions')" min-width="150"><template #default="{row}"><el-button :disabled="busy||row.role==='admin'||!reason.trim()" @click="setUser(row)">{{row.status==='active'?t('停用并撤销会话','Suspend and revoke'):t('恢复','Activate')}}</el-button></template></el-table-column></el-table><el-button v-if="userCursor" :disabled="busy" @click="moreUsers">{{t('更多用户','More users')}}</el-button><p>{{t('当前不提供任意赠送积分、改价或账户删除。管理员恢复使用部署 CLI。','Credits, prices and account deletion are not editable here. Administrator recovery uses the deployment CLI.')}}</p></section>
 <section v-if="tab==='finance'"><h2>{{t('订单与退款','Orders and refunds')}}</h2><p>{{t('最近100笔订单；明细保留渠道证据和 Worker 状态。','Latest 100 orders; details include channel evidence and worker state.')}}</p><el-table :data="finance?.items??[]"><el-table-column :label="t('订单 / 账户','Order / account')" min-width="260"><template #default="{row}"><el-button link @click="selectedOrder=row;preview=null">{{row.order.product.name}}</el-button><small>{{row.order.id}}<br/>{{row.accountId}}</small></template></el-table-column><el-table-column :label="t('金额 / 已退','Amount / refunded')"><template #default="{row}">¥{{fen(row.order.amountFen)}} / {{fen(row.order.refundedFen)}}</template></el-table-column><el-table-column :label="t('状态','State')"><template #default="{row}">{{row.order.state}}</template></el-table-column><el-table-column :label="t('渠道','Channel')"><template #default="{row}">{{row.order.channel}}</template></el-table-column></el-table>
 <article v-if="selectedOrder"><h3>{{selectedOrder.order.id}}</h3><el-input v-model="reason" :placeholder="t('核算、退款或查询原因','Review, refund or query reason')" maxlength="256"/><div class="toolbar"><el-button v-if="finance?.mode==='test'&&selectedOrder.order.state==='pending'" :disabled="busy" @click="simulate">{{t('仅测试：模拟付款','Test only: simulate payment')}}</el-button><el-button :disabled="busy||!reason.trim()" @click="recheck">{{t('查询渠道 / 恢复核对','Query channel / resume reconciliation')}}</el-button></div><h3>{{t('退款申请','Refund requests')}}</h3><el-table :data="selectedOrder.refunds"><el-table-column prop="id" label="ID" min-width="220"/><el-table-column :label="t('金额','Amount')"><template #default="{row}">¥{{fen(row.amountFen)}}</template></el-table-column><el-table-column prop="approval" :label="t('审批','Approval')"/><el-table-column prop="execution" :label="t('执行','Execution')"/><el-table-column :label="t('核算','Review')"><template #default="{row}"><el-button :disabled="busy" @click="refundPreview(row.id)">{{t('预览','Preview')}}</el-button></template></el-table-column></el-table><div v-if="preview"><p>{{t('可批准','Eligible')}}: {{preview.eligible}} · {{t('需回收积分','Credits to recover')}} {{preview.recoverCredits}} · {{t('预留','Held')}} {{preview.heldCredits}} · {{preview.explanation}}</p><div class="toolbar"><el-button :disabled="busy||!reason.trim()" @click="decide('review')">{{t('进入核算','Mark reviewing')}}</el-button><el-button :disabled="busy||!reason.trim()||!preview.eligible" @click="decide('approve')">{{t('批准原路退款','Approve original-channel refund')}}</el-button><el-button :disabled="busy||!reason.trim()" @click="decide('reject')">{{t('拒绝','Reject')}}</el-button></div></div><h3>{{t('已核验渠道证据','Verified channel evidence')}}</h3><el-table :data="selectedOrder.evidence"><el-table-column prop="source" :label="t('来源','Source')"/><el-table-column prop="state" :label="t('状态','State')"/><el-table-column prop="transactionId" :label="t('交易编号','Transaction ID')" min-width="220"/><el-table-column prop="refundFen" :label="t('退款分','Refund fen')"/></el-table><h3>Worker</h3><el-table :data="selectedOrder.jobs"><el-table-column prop="kind" :label="t('类别','Kind')"/><el-table-column prop="state" :label="t('状态','State')"/><el-table-column prop="attempts" :label="t('查询次数','Attempts')"/><el-table-column prop="lastError" :label="t('错误码','Error code')"/></el-table></article></section>
 <section v-if="tab==='usage'"><h2>{{t('用量核对','Usage reconciliation')}}</h2><p>{{t('真实积分已结算 / 预留','Paid credits settled / held')}} {{overview?.paidChargedCredits??'—'}} / {{overview?.paidHeldCredits??'—'}}</p><p>{{t('已核验采购成本','Verified procurement cost')}} ¥{{cash(overview?.knownProcurementFen)}} · {{t('成本未知的请求','Requests with unknown costs')}} {{overview?.procurementUnknownRequests??'—'}}. {{t('这不是利润。未知不计为零。','This is not profit. Unknown costs are not zero.')}}</p><el-button :disabled="busy" @click="action(async()=>{const v=await ops.verify();message=t('账本校验通过','Ledger verified')+' · '+v.grants})">{{t('校验账本','Verify ledger')}}</el-button><el-table :data="pending"><el-table-column prop="requestId" :label="t('请求','Request')" min-width="220"/><el-table-column prop="unit" :label="t('积分类型','Unit')"/><el-table-column prop="reservedCredits" :label="t('保留预留','Retained hold')"/><el-table-column prop="jobStatus" :label="t('队列','Queue')"/><el-table-column prop="reason" :label="t('原因','Reason')"/><el-table-column :label="t('处理','Action')"><template #default="{row}"><el-button @click="choosePending(row)">{{t('填写证据','Prepare evidence')}}</el-button></template></el-table-column></el-table><h3>{{t('核对证据 JSON','Reconciliation evidence JSON')}}</h3><p>{{t('选择 usage / no-call / waiver，提供可核实的 evidence ID 和原因。默认模板不是核对结论；waiver 由平台承担，采购成本仍未知。','Choose usage / no-call / waiver and supply a verifiable evidence ID and reason. The template is not evidence; waiver is borne by the platform and procurement cost remains unknown.')}}</p><el-input v-model="evidence" type="textarea" :rows="10" maxlength="16000"/><el-button :disabled="busy||!evidence" @click="reconcile">{{t('预览并核对','Preview and reconcile')}}</el-button></section>
 <section v-if="tab==='providers'"><h2>{{t('供应商与路由','Providers and routes')}}</h2><p v-if="!mxRoutes">{{t('当前 Go 服务尚未提供 MX 路由快照；请升级 Go 服务后刷新。','The current Go service has no MX route snapshot. Upgrade it and refresh.')}}</p><template v-else><p>{{t('联合发布版本','Joint release version')}} <code>{{mxRoutes.releaseId}}</code> · {{mxRoutes.releaseStatus}}。{{mxRoutes.salesEnabled?t('MX 销售已启用；计价与账户准入由服务端控制。','MX sales are enabled; server-side pricing and account admission apply.'):t('销售尚未启用。','Sales are not enabled.')}}</p><p>{{t('探针报告时间','Probe report time')}}：{{mxRoutes.probeReportedAt??t('未同步','Not synchronized')}}。{{t('导入报告仅供诊断，不代表独立账单已核验。','Imported reports are diagnostic and do not verify independent invoices.')}}</p><div class="metrics"><article><small>{{t('采购价版本','Procurement version')}}</small><b>{{mxRoutes.purchaseVersionId}}</b></article><article><small>{{t('汇率版本','Exchange version')}}</small><b>{{mxRoutes.fxVersionId}}</b></article><article><small>{{t('零售价版本','Retail version')}}</small><b>{{mxRoutes.retailVersionId}}</b></article></div><el-table :data="mxRoutes.routes"><el-table-column prop="slotId" :label="t('模型槽位','Model slot')" min-width="170"/><el-table-column prop="proxyAlias" label="LiteLLM alias" min-width="180"/><el-table-column prop="credentialRef" :label="t('密钥引用','Credential reference')" min-width="190"/><el-table-column prop="protocol" :label="t('路由协议','Route protocol')"/><el-table-column prop="routeVersionId" :label="t('路由版本','Route version')" min-width="240"/><el-table-column :label="t('运行准入 / 探针','Admission / probe')" min-width="240"><template #default="{row}">{{row.salesEnabled?t('已开放','Available'):row.runtimeEnabled?t('仅诊断启用','Diagnostic only'):t('关闭','Disabled')}} · {{row.probeStatus==='reported'?`${row.discovery} / ${row.selectedProtocol||'—'} / usage ${row.usageComplete?'✓':'?'}`:t('未同步探针证据','Probe evidence not synchronized')}}</template></el-table-column></el-table></template><p>{{t('暂停新请求使用总览控制；LiteLLM 配置发布与回滚在独立服务执行，并须同步真实探针、账单与联合发布证据。此页不接收明文密钥，也不把进程开关当作供应商健康。','Pause new requests in Overview. Publish or restore LiteLLM configuration in its independent service, then synchronize probe, invoice and joint-release evidence. This page accepts no plaintext keys and does not infer supplier health from a process switch.')}}</p></section>
 <section v-if="tab==='releases'"><h2>{{t('版本发布目录','Release catalogue')}}</h2><p>{{t('创建不可变清单草稿，部署人员审核 M4 证据后才能发布下载目录。GitHub 必须已公开发布 immutable Release；这里不上传安装包、不修改 GitHub、不热更新 Skills。','Create an immutable manifest draft. Deployment staff approve M4 evidence before catalogue publication. GitHub must already have a public immutable release. This interface does not upload assets, modify GitHub or hot-update Skills.')}}</p><el-input v-model="reason" maxlength="256" :placeholder="t('草稿 / 发布 / 撤回原因','Draft / publication / withdrawal reason')"/><el-table :data="releases"><el-table-column :label="t('版本','Version')"><template #default="{row}">{{row.manifest.id}} · {{row.manifest.channel}}</template></el-table-column><el-table-column prop="state" :label="t('状态','State')"/><el-table-column prop="version" :label="t('记录版本','Record version')"/><el-table-column :label="t('操作','Actions')" min-width="250"><template #default="{row}"><el-button v-if="row.state==='draft'" :disabled="busy||!reason.trim()" @click="releaseAction(row,'publish')">{{t('核验并发布目录','Verify and publish catalogue')}}</el-button><el-button v-if="row.state==='published'" :disabled="busy||!reason.trim()" @click="releaseAction(row,'withdraw')">{{t('撤回目录','Withdraw from catalogue')}}</el-button></template></el-table-column></el-table><h3>{{t('新版本清单 JSON','New release manifest JSON')}}</h3><p>docs/m5/release-manifest.example.json · {{t('替换所有占位内容后提交；签名与平台测试仍需服务端证据。','Replace placeholders before submitting. Signature and platform tests still require server evidence.')}}</p><el-input v-model="manifestText" type="textarea" :rows="12" maxlength="60000"/><el-button :disabled="busy||!manifestText||!reason.trim()" @click="draft">{{t('登记草稿','Register draft')}}</el-button></section>
 <LifecyclePanel v-if="tab==='lifecycle'" />
 <section v-if="tab==='audit'"><h2>{{t('审计事件','Audit events')}}</h2><el-table :data="audit"><el-table-column prop="createdAt" :label="t('时间 UTC','Time UTC')" min-width="220"/><el-table-column prop="actorId" :label="t('操作者','Actor')" min-width="200"/><el-table-column prop="action" :label="t('动作','Action')" min-width="200"/><el-table-column prop="targetId" :label="t('对象','Target')" min-width="200"/><el-table-column prop="result" :label="t('结果','Result')"/><el-table-column prop="reason" :label="t('原因','Reason')" min-width="220"/></el-table><el-button v-if="auditCursor" :disabled="busy" @click="moreAudit">{{t('更多历史','More history')}}</el-button></section>
</template></main><footer>© 2026 吉林大学 AI-DAOS 团队</footer></div>
</template>
