<script setup lang="ts">
import {onMounted,ref} from 'vue';
import {usePreferences} from '../../../packages/ui/src/preferences.js';
import {ops,OpsError} from './api.js';
import {statementInputSchema,type Ticket,type costsSchema,type alertsSchema,type readinessSchema,type enrollmentsSchema} from '../../../packages/contracts/src/lifecycle.js';
import type {z} from 'zod';
const {t}=usePreferences();const busy=ref(false),message=ref(''),tickets=ref<Ticket[]>([]),cursor=ref<string|null>(null),selected=ref<Ticket|null>(null),body=ref(''),state=ref<'open'|'waiting_user'|'resolved'|'closed'>('waiting_user'),statement=ref(''),costs=ref<z.infer<typeof costsSchema>|null>(null),alerts=ref<z.infer<typeof alertsSchema>['items']>([]),readiness=ref<z.infer<typeof readinessSchema>|null>(null),attachment=ref(''),reason=ref(''),accountId=ref(''),enrollmentVersion=ref('0');
const enrollments=ref<z.infer<typeof enrollmentsSchema>['items']>([]);
const keys=new Map<string,string>();async function mutate<T>(input:unknown,fn:(key:string)=>Promise<T>){const fp=JSON.stringify(input),key=keys.get(fp)??crypto.randomUUID();keys.set(fp,key);const result=await fn(key);keys.delete(fp);return result}
async function action(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;message.value='';try{await fn()}catch(e){message.value=e instanceof OpsError?e.code:t('连接失败或输入数据不符合合同；刷新核对结果。','Connection failed or input is invalid. Refresh to check the outcome.')}finally{busy.value=false}}
async function refresh(){const [a,b,c,d,e]=await Promise.all([ops.tickets(),ops.costs(),ops.alerts(),ops.readiness(),ops.enrollments()]);tickets.value=a.items;cursor.value=a.nextCursor;costs.value=b;alerts.value=c.items;readiness.value=d;enrollments.value=e.items;if(selected.value)selected.value=tickets.value.find(v=>v.id===selected.value?.id)??null}
async function more(){if(!cursor.value)return;const page=await ops.tickets(cursor.value);tickets.value.push(...page.items);cursor.value=page.nextCursor}
async function reply(){const v=selected.value;if(!v||!body.value.trim())return;const input={body:body.value,state:state.value,expectedVersion:v.version};selected.value=await mutate([v.id,input],key=>ops.replyTicket(v.id,input,key));body.value='';await refresh()}
async function importCosts(){const input=statementInputSchema.parse(JSON.parse(statement.value));await mutate(input,key=>ops.importCosts(input,key));statement.value='';await refresh()}
async function ack(id:string){await mutate([id,reason.value],key=>ops.acknowledgeAlert(id,reason.value,key));await refresh()}
async function enroll(next:'active'|'revoked'){const input={state:next,reason:reason.value,expectedVersion:enrollmentVersion.value};await mutate([accountId.value,input],key=>ops.enroll(accountId.value,input,key));enrollmentVersion.value=(BigInt(enrollmentVersion.value)+1n).toString();await refresh()}
function yuan(raw:string){const n=BigInt(raw);return `${n/100000000n}.${(n%100000000n).toString().padStart(8,'0')}`}
onMounted(()=>action(refresh));
</script>
<template><section><div class="toolbar"><h2>{{t('客服、成本与 Beta 验收','Support, costs and Beta readiness')}}</h2><el-button :disabled="busy" @click="action(refresh)">{{t('刷新','Refresh')}}</el-button></div><p v-if="message" role="status">{{message}}</p>
<article><h3>{{t('上线门槛','Launch gates')}}</h3><p>Worker: {{readiness?.workerHealthy?t('正常','Healthy'):t('未就绪','Not ready')}} · {{t('正式上线可用','Ready for launch')}}: {{readiness?.ready??false}}</p><p>{{t('退款规则：完全未使用订单全额退款。验收证据由部署人员核实；此页面不能自行勾选通过。','Refund policy: full refunds for fully unused orders. Deployment staff verify evidence; this page cannot mark gates passed.')}}</p><el-tag v-for="gate in readiness?.missing" :key="gate" type="warning">{{gate}}</el-tag><h4>{{t('Beta 招募名单','Beta enrollment')}}</h4><p>{{t('名单登记不会开启正式收款或模型调用。发布门槛与付费订阅仍须满足。','Enrollment does not enable sales or model calls. Launch gates and paid subscription remain required.')}}</p><el-table :data="enrollments"><el-table-column prop="accountId" label="Account ID"/><el-table-column prop="state" :label="t('状态','State')"/><el-table-column prop="version" :label="t('版本','Version')"/><el-table-column><template #default="{row}"><el-button @click="accountId=row.accountId;enrollmentVersion=row.version">{{t('选择','Select')}}</el-button></template></el-table-column></el-table>
<el-input v-model="accountId" :placeholder="t('用户 ID','Account ID')"/><el-input v-model="enrollmentVersion" :placeholder="t('当前版本；新记录为 0','Current version; 0 for new entry')"/><el-input v-model="reason" maxlength="256" :placeholder="t('操作原因','Operation reason')"/><div class="toolbar"><el-button :disabled="busy||!accountId||!reason" @click="action(()=>enroll('active'))">{{t('纳入 Beta','Enroll')}}</el-button><el-button :disabled="busy||!accountId||!reason" @click="action(()=>enroll('revoked'))">{{t('撤销准入','Revoke')}}</el-button></div></article>
<article><h3>{{t('工单','Tickets')}}</h3><el-table :data="tickets"><el-table-column prop="subject" :label="t('标题','Subject')"/><el-table-column prop="accountId" :label="t('用户','Account')"/><el-table-column prop="state" :label="t('状态','State')"/><el-table-column><template #default="{row}"><el-button @click="selected=row;attachment=''">{{t('查看','View')}}</el-button></template></el-table-column></el-table><el-button v-if="cursor" :disabled="busy" @click="action(more)">{{t('更多','More')}}</el-button>
<div v-if="selected"><h4>{{selected.subject}} · {{selected.referenceId}}</h4><div v-for="event in selected.events" :key="event.id" class="event"><small>{{event.createdAt}} · {{event.actorId}} · {{event.state}}</small><p>{{event.body}}</p></div><el-button v-for="a in selected.attachments" :key="a.id" :disabled="busy" @click="action(async()=>{attachment=(await ops.supportAttachment(a.id)).text})">{{t('查看授权附件','View consented attachment')}}: {{a.name}}</el-button><pre v-if="attachment">{{attachment}}</pre><el-input v-model="body" type="textarea" :rows="4" maxlength="8000"/><el-select v-model="state"><el-option v-for="v in ['open','waiting_user','resolved','closed']" :key="v" :label="v" :value="v"/></el-select><el-button :disabled="busy||!body||selected.state==='closed'" @click="action(reply)">{{t('回复并更新状态','Reply and update state')}}</el-button></div></article>
<article><h3>{{t('供应商实际账单','Actual supplier statements')}}</h3><p>{{t('已确认成本','Confirmed cost')}}: ¥{{costs?yuan(costs.actualMicrofen):'—'}} · {{t('已对账请求','Reconciled requests')}} {{costs?.statementRequests??'—'}} · {{t('未知成本请求','Unknown-cost requests')}} {{costs?.unknownRequests??'—'}}</p><p>{{t('每一行必须对应本系统已发出的请求、原路由版本、原账单编号及 SHA-256。金额为整数 microfen（1元=100,000,000 microfen）。未知成本不计为零，也不据此显示利润。导入仅确认供应商成本，不改变用户消费。','Each line must match a dispatched request, its original route, statement reference and SHA-256. Amounts use integer microfen (1 CNY = 100,000,000 microfen). Unknown costs are not zero; no profit is calculated. Import confirms supplier cost without changing user charges.')}}</p><el-input v-model="statement" type="textarea" :rows="8" maxlength="60000" placeholder='{"lines":[{"requestId":"...","routeVersionId":"...","sourceRef":"...","sourceSha256":"...","costMicrofen":"...","reason":"..."}]}'/><el-button :disabled="busy||!statement" @click="action(importCosts)">{{t('导入并追加审计','Import and append audit')}}</el-button><el-table :data="costs?.items??[]"><el-table-column prop="requestId" label="Request ID"/><el-table-column prop="sourceRef" :label="t('账单来源','Statement')"/><el-table-column prop="costMicrofen" label="microfen"/></el-table></article>
<article><h3>{{t('告警','Alerts')}}</h3><el-table :data="alerts"><el-table-column prop="kind" :label="t('类型','Kind')"/><el-table-column prop="targetId" :label="t('对象','Target')"/><el-table-column prop="state" :label="t('状态','State')"/><el-table-column><template #default="{row}"><el-button :disabled="busy||!reason||row.state==='acknowledged'" @click="action(()=>ack(row.id))">{{t('确认已处理','Acknowledge')}}</el-button></template></el-table-column></el-table><p>{{t('确认告警不会释放积分、结算任务或重新发起支付。邮件发送结果不确定时进入人工处理。','Acknowledging an alert does not release credits, settle tasks or retry payments. Uncertain email delivery requires manual handling.')}}</p></article></section></template>
<style scoped>.event{border-top:1px solid var(--border);padding:10px 0}.event p,pre{white-space:pre-wrap;overflow-wrap:anywhere}.el-tag{margin:4px}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}article{margin:16px 0}.el-input{margin-bottom:10px}</style>
