const priceRows = [
  ['gpt-5.6-sol', '175 / 1050 / 17.5 / 218.75', 'standard'],
  ['gpt-5.6-sol ≥272k', '350 / 1575 / 35 / 437.5', 'standard'],
  ['claude-opus-5-5', '140 / 700 / 7 / 175', 'pilot'],
  ['claude-fable-5-1', '350 / 1750 / 8.75 / 437.5', 'paused'],
];

export const architectureContent = {
  'zh-CN': {
    nav: '0.3 架构', eyebrow: 'MATERIALSX 0.3 / SYSTEM FLOW', title: '从研究问题到 MX 点结算，一条链路讲清楚。',
    lead: '官网介绍产品，桌面完成研究与购买；独立的账户网关负责资金和用量，LiteLLM 连接模型供应商，计费后台核对每笔交易。',
    nodes: [
      {tag: '01 / PUBLIC', title: '官方网站', body: '介绍能力、版本状态与使用方式，提供公开下载入口；不持有账户余额、支付凭据或供应商密钥。', meta: '公开展示层'},
      {tag: '02 / USER', title: 'MaterialsX 桌面端', body: '在一个工作台管理项目、资料、Skills 与 MOOS；登录后查看 MX 钱包、充值订单、可用模型和本人任务账单。', meta: '研究与购买入口'},
      {tag: '03 / CONTROL', title: '账户与计费网关', body: '验证身份与支付回调，保存唯一 MX 账本；模型请求先锁定价格和预留点数，取得可信用量后结算。', meta: '资金与计价事实源'},
      {tag: '04 / OPERATIONS', title: '独立计费管理端', body: '具名员工按角色查看订单、钱包、用量、退款、价目、对账与审计；业务写入经账户网关审核。', meta: '财务与运营视图'},
      {tag: '05 / MODEL', title: 'LiteLLM 与供应链', body: '独立代理按已发布路由调用 RootFlowAI；上游 API Key 只留在服务端私有配置，代理管理界面供授权运维使用。', meta: '模型路由与采购侧'},
    ],
    flowTitle: '一次付费模型任务，怎样闭环？',
    flow: [
      {title: '充值到账', body: '桌面选择 ¥10 / 50 / 100 / 500 商品；微信支付经服务端验签后，一次性发放 100 / 500 / 1000 / 5000 MX 点。'},
      {title: '选择模型', body: '桌面只展示账户已准入的模型；网关把模型路由与采购、汇率、零售价版本固定到请求。'},
      {title: '调用与预留', body: '网关先预留点数，再让独立 LiteLLM 使用服务端密钥调用供应商；客户端不直接接触上游 Key。'},
      {title: '用量结算', body: '根据普通输入、输出、缓存读取、缓存创建四类可信 Token 用量扣点；用量缺失则保留待核对状态。'},
      {title: '财务核对', body: '计费后台把已消费收入、供应商实际账单和退款分开核对，记录差异、审计和可计算的毛利。'},
    ],
    price: {
      title: '统一购买 MX 点，按所选模型用量扣点', lead: '固定兑换为 ¥1 = 10 MX 点。下表为 2026-10-07 审核快照的零售价，单位是“MX 点 / 每百万个对应类别 Token”；依次为普通输入 / 输出 / 缓存读取 / 缓存创建。实际可选模型以登录后的目录为准。',
      model: '模型与档位', rate: '输入 / 输出 / 缓存读 / 缓存写', state: '当前状态', rows: priceRows,
      states: {standard: '受限开放', pilot: '受限开放', paused: '暂停新收费调用'},
      foot: '参考官方美元价的约 5 折只用于历史比较；供应商站内额度按已核定口径 1 额度 = ¥1 估算采购成本。充值款、已消费收入与模型采购成本分别入账，毛利不等于净利润。',
    },
    boundaryTitle: '部署与数据边界',
    boundaries: ['官网静态发布；桌面项目和本地模型留在用户设备。', '账户网关、计费 Web、LiteLLM 分别部署、检查健康和回滚。', 'MX 余额与订单只在 MaterialsX 业务库；LiteLLM 使用独立数据库。', '供应商密钥只在 LiteLLM 私有环境；密钥、采购价和管理入口不进入客户端或公开页面。'],
    status: '0.3.0-preview.1 安装包已公开，计费服务仍在试点：本机四档可真实下单，已验证一笔 ¥10 实付到账及 GPT 5.6 钱包扣点/供应商账单核对；Opus 尚待同等级实付核对，Fable 暂停新收费调用，GPT-6 已移出。正式收费发行仍取决于生产部署与跨平台验收。',
  },
  'zh-TW': {
    nav: '0.3 架構', eyebrow: 'MATERIALSX 0.3 / SYSTEM FLOW', title: '從研究問題到 MX 點結算，看清整條鏈路。',
    lead: '官網介紹產品，桌面端完成研究與購買；獨立帳戶閘道負責資金和用量，LiteLLM 連接模型供應商，計費後台核對交易。',
    nodes: [
      {tag: '01 / PUBLIC', title: '官方網站', body: '介紹功能、版本狀態與下載方式；不保存餘額、支付憑證或供應商密鑰。', meta: '公開展示層'},
      {tag: '02 / USER', title: 'MaterialsX 桌面端', body: '在同一工作台管理專案、資料、Skills 與 MOOS；登入後查看 MX 錢包、充值訂單、可用模型及個人帳單。', meta: '研究與購買入口'},
      {tag: '03 / CONTROL', title: '帳戶與計費閘道', body: '驗證身份與支付回調，維護唯一 MX 帳本；模型請求先鎖價和預留點數，再依可信用量結算。', meta: '資金與計價事實來源'},
      {tag: '04 / OPERATIONS', title: '獨立計費管理端', body: '具名員工按角色檢視訂單、錢包、用量、退款、價格、對帳與審計；寫入交由帳戶閘道審核。', meta: '財務與營運視圖'},
      {tag: '05 / MODEL', title: 'LiteLLM 與供應鏈', body: '獨立代理按已發布路由呼叫 RootFlowAI；上游 API Key 僅存於服務端私有設定，管理介面限授權運維。', meta: '模型路由與採購側'},
    ],
    flowTitle: '一次付費模型任務如何閉環？',
    flow: [
      {title: '充值入帳', body: '桌面選擇 ¥10 / 50 / 100 / 500；微信付款經服務端驗簽後，發放 100 / 500 / 1000 / 5000 MX 點。'},
      {title: '選擇模型', body: '桌面只顯示帳戶可用模型；閘道固定路由、採購、匯率及零售價格版本。'},
      {title: '呼叫與預留', body: '閘道先預留點數，再由 LiteLLM 使用服務端密鑰呼叫供應商；客戶端不接觸上游 Key。'},
      {title: '用量結算', body: '按普通輸入、輸出、快取讀取及建立四類可信 Token 用量扣點；缺項保留待核對。'},
      {title: '財務核對', body: '管理端分別核對消費收入、供應商帳單和退款，記錄差異、審計及可計算毛利。'},
    ],
    price: {title: '統一購買 MX 點，按模型用量扣點', lead: '固定兌換 ¥1 = 10 MX 點。以下為 2026-10-07 審核快照的零售價，單位是每百萬對應類別 Token 的 MX 點；順序為普通輸入 / 輸出 / 快取讀取 / 快取建立。可用模型以登入後目錄為準。', model: '模型與檔位', rate: '輸入 / 輸出 / 快取讀 / 快取寫', state: '目前狀態', rows: priceRows, states: {standard: '受限開放', pilot: '受限開放', paused: '暫停新收費呼叫'}, foot: '相對官方美元參考價約五折僅供歷史比較；供應商額度按已核定口徑 1 額度 = ¥1 估算採購成本。充值、消費收入與採購成本分別入帳；毛利不等於淨利。'},
    boundaryTitle: '部署與資料邊界', boundaries: ['官網靜態發布；桌面專案與本地模型留在使用者設備。', '帳戶閘道、計費 Web、LiteLLM 分別部署、健康檢查與回滾。', 'MX 餘額和訂單只在 MaterialsX 業務資料庫；LiteLLM 使用獨立資料庫。', '供應商密鑰只在 LiteLLM 私有環境；密鑰與採購價不進入客戶端或公開頁面。'],
    status: '0.3.0-preview.1 安裝檔已公開，計費服務仍在試點：本機四檔可真實下單，已驗證一筆 ¥10 付款入帳及 GPT 5.6 扣點與供應商帳單；Opus 尚待同級驗證，Fable 暫停新收費呼叫，GPT-6 已移除。正式收費發行仍需生產部署及跨平台驗收。',
  },
  en: {
    nav: '0.3 architecture', eyebrow: 'MATERIALSX 0.3 / SYSTEM FLOW', title: 'From research question to MX Points settlement.',
    lead: 'The website explains the product; the desktop handles research and purchases. An independent account gateway owns billing, LiteLLM connects model suppliers, and a separate console reconciles transactions.',
    nodes: [
      {tag: '01 / PUBLIC', title: 'Official website', body: 'Explains capabilities, release status, and downloads. It holds no wallet balances, payment credentials, or supplier keys.', meta: 'Public presentation'},
      {tag: '02 / USER', title: 'MaterialsX desktop', body: 'One workspace for projects, sources, Skills, and MOOS. Signed-in users see their MX wallet, orders, eligible models, and usage.', meta: 'Research and purchase'},
      {tag: '03 / CONTROL', title: 'Account and billing gateway', body: 'Authenticates users and payment callbacks, owns the MX ledger, locks prices and reserves points before model calls, then settles trusted usage.', meta: 'Financial source of truth'},
      {tag: '04 / OPERATIONS', title: 'Separate billing console', body: 'Role-based staff views for orders, wallets, usage, refunds, prices, reconciliation, and audit. Writes go through the account gateway.', meta: 'Finance and operations'},
      {tag: '05 / MODEL', title: 'LiteLLM and supply', body: 'An independent proxy routes to RootFlowAI. Upstream API keys stay in private server configuration; its admin UI is for authorized operators.', meta: 'Routing and procurement'},
    ],
    flowTitle: 'How one paid model task closes the loop', flow: [
      {title: 'Top up', body: 'Choose ¥10 / 50 / 100 / 500 on desktop. A verified WeChat payment grants 100 / 500 / 1000 / 5000 MX Points once.'},
      {title: 'Select a model', body: 'The desktop shows eligible models. The gateway locks the route and procurement, FX, and retail price versions.'},
      {title: 'Reserve and route', body: 'The gateway reserves points, then LiteLLM calls the supplier with a server-side key. No upstream key reaches the client.'},
      {title: 'Settle usage', body: 'Trusted input, output, cache-read, and cache-create token counts determine the charge. Missing usage stays pending reconciliation.'},
      {title: 'Reconcile', body: 'The billing console compares consumed revenue, supplier invoices, and refunds, recording differences, audit events, and measurable gross profit.'},
    ],
    price: {title: 'Buy MX Points once; pay for each model’s usage', lead: 'Fixed conversion: ¥1 = 10 MX Points. These are retail snapshot rates as of 2026-10-07, in MX Points per million tokens of each category: input / output / cache read / cache create. Actual eligibility is shown after sign-in.', model: 'Model and tier', rate: 'Input / output / cache read / cache create', state: 'Current status', rows: priceRows, states: {standard: 'Limited access', pilot: 'Limited access', paused: 'New paid calls paused'}, foot: 'The approximate 50% of official USD reference prices is a historical comparison. Supplier quota uses the confirmed 1 quota = ¥1 assumption for cost estimates. Top-ups, earned revenue, and supplier costs are recorded separately; gross profit is not net profit.'},
    boundaryTitle: 'Deployment and data boundaries', boundaries: ['Static public site; local projects and models stay on user devices.', 'Account gateway, billing Web, and LiteLLM deploy, health-check, and roll back separately.', 'MX balances and orders live only in the MaterialsX business database; LiteLLM uses its own database.', 'Supplier keys remain in LiteLLM private configuration; keys and procurement costs never reach public or client pages.'],
    status: 'The 0.3.0-preview.1 installers are public, while billing remains a pilot. All four tiers can create real orders locally; one ¥10 payment and one GPT 5.6 wallet charge reconciled to a supplier bill have been verified. Opus needs equivalent verification; new Fable paid calls are paused; GPT-6 was removed. A general paid release still requires production and cross-platform acceptance.',
  },
  ja: {
    nav: '0.3 構成', eyebrow: 'MATERIALSX 0.3 / SYSTEM FLOW', title: '研究課題から MX ポイント精算までの全体像。',
    lead: '公式サイトは製品を案内し、デスクトップで研究と購入を行います。独立したアカウントゲートウェイが課金を管理し、LiteLLM がモデル供給元に接続、別の管理画面で取引を照合します。',
    nodes: [
      {tag: '01 / PUBLIC', title: '公式サイト', body: '機能、リリース状況、ダウンロードを案内します。残高、決済認証情報、供給元キーは保持しません。', meta: '公開案内'},
      {tag: '02 / USER', title: 'MaterialsX デスクトップ', body: 'プロジェクト、資料、Skills、MOOS を扱う作業環境。ログイン後、MX 残高、注文、利用可能モデルと利用明細を確認できます。', meta: '研究と購入'},
      {tag: '03 / CONTROL', title: 'アカウント・課金ゲートウェイ', body: '本人と決済通知を検証し、MX 台帳を管理。モデル呼び出し前に価格を固定してポイントを確保し、信頼できる使用量で精算します。', meta: '資金と価格の正本'},
      {tag: '04 / OPERATIONS', title: '独立した課金管理画面', body: '担当者は権限に応じて注文、残高、使用量、返金、価格、照合、監査を確認。変更はゲートウェイ経由です。', meta: '財務・運用'},
      {tag: '05 / MODEL', title: 'LiteLLM と供給網', body: '独立プロキシが RootFlowAI にルーティング。上流 API Key はサーバーの非公開設定に置き、管理画面は許可された運用者のみ利用します。', meta: 'モデル経路と調達'},
    ],
    flowTitle: '有料モデルの一回の処理', flow: [
      {title: 'チャージ', body: 'デスクトップで ¥10 / 50 / 100 / 500 を選択。WeChat 決済の検証後、100 / 500 / 1000 / 5000 MX ポイントを一度だけ付与します。'},
      {title: 'モデル選択', body: '利用資格のあるモデルだけを表示。ゲートウェイが経路、調達、為替、販売価格の版を固定します。'},
      {title: '確保と呼び出し', body: 'ポイントを先に確保し、LiteLLM がサーバー側のキーで供給元へ接続。クライアントに上流キーは渡しません。'},
      {title: '使用量の精算', body: '通常入力、出力、キャッシュ読み取り・作成の信頼できる Token 数で課金。不明な項目は照合待ちにします。'},
      {title: '財務照合', body: '消費収益、供給元請求、返金を別々に照合し、差額・監査・算定可能な粗利を記録します。'},
    ],
    price: {title: 'MX ポイントを購入し、モデルの使用量に応じて支払う', lead: '固定換算は ¥1 = 10 MX ポイント。以下は 2026-10-07 時点の販売価格で、各区分 100 万 Token あたりの MX ポイントです。順序は通常入力 / 出力 / キャッシュ読取 / 作成。実際の利用可否はログイン後の一覧をご確認ください。', model: 'モデル・区分', rate: '入力 / 出力 / キャッシュ読取 / 作成', state: '現状', rows: priceRows, states: {standard: '限定提供', pilot: '限定提供', paused: '新規有料呼出を停止'}, foot: '公式 USD 参考価格のおよそ 50% は過去時点の比較です。調達費の概算は確認済みの 1 枠 = ¥1 を使用。チャージ、消費収益、調達費は別々に記帳し、粗利は純利益ではありません。'},
    boundaryTitle: '配置とデータの境界', boundaries: ['公式サイトは静的公開。ローカルのプロジェクトとモデルは利用者の端末に保持。', 'ゲートウェイ、課金 Web、LiteLLM は個別に配置・監視・ロールバック。', 'MX 残高と注文は MaterialsX の業務 DB のみ。LiteLLM は独立 DB を使用。', '供給元キーは LiteLLM の非公開設定のみ。キーと調達価格を公開ページやクライアントへ渡しません。'],
    status: '0.3.0-preview.1 のインストーラーは公開中で、課金サービスは試験運用中です。ローカルでは四つの枠で実決済注文を作成でき、¥10 の一件の入金と供給元請求に照合した GPT 5.6 のポイント消費を確認済みです。Opus は同等の確認待ち、Fable の新規有料呼出は停止中、GPT-6 は除外済みです。正式な有料版には本番環境と複数 OS の検証が必要です。',
  },
};
