// Website copy for the actual desktop task starter and its connected research tools.
// Keep capability boundaries explicit: a catalog entry is not an installed model.
export const researchContent = {
  'zh-CN': {
    nav: '新建研究任务',
    tasks: {
      eyebrow: 'START WITH A QUESTION', title: '今天要推进什么研究任务？',
      lead: '从一个问题开始，按研究阶段选择任务；所需资料可以在发送前补充。',
      guideTitle: '第一次使用？从一个问题开始',
      guide: '选择任务后，先在输入框补上你的材料、目标或文件。发送前可以修改；结果中的数据与引用仍需核对。',
      stageTitle: '按研究阶段选择', stageNote: '从问题、文献和已有数据入手；不需要先学会写提示词。',
      stages: ['刚开始研究', '选题与文献', '材料数据', '实验与分析', '结构与模拟', '论文与成果'],
      count: '6 个常用任务',
      cards: [
        ['帮我明确研究问题', '把模糊想法整理成目标、约束和下一步', '说出材料体系、想改进的性能与现有条件。'],
        ['从哪里查论文', '确定关键词、检索范围和可信来源', '先写下研究主题，核对找到的是摘要还是全文。'],
        ['带我读一篇论文', '解释方法、结果和证据，不跳过局限', '需要论文 PDF；关键数据回到原文页码。'],
        ['看懂实验表格', '先核对单位、缺失值、重复样和异常值', '需要实验数据；先说明列含义与测试条件。'],
        ['设计第一个对照实验', '确定变量、对照组、重复和评价指标', '补充设备、时间、成本和可用材料。'],
        ['检查一个研究结论', '辨别证据、推断和还缺少的验证', '提供结论与来源，找出最小验证实验。'],
      ],
      flow: ['选一个任务', '补充材料与目标', '检查并发送', '复核结果与来源'],
      foot: '点击桌面端任务卡仅填写输入框，不会自动发送或运行工具。也可以直接描述自己的问题。',
      imageAlt: 'MaterialsX 新建研究任务首页，显示按研究阶段选择和六个常用任务的真实界面',
      imageCaption: '真实开发版界面 · 新建研究任务',
    },
    potentials: {
      link: '探索机器学习势',
      eyebrow: 'MACHINE-LEARNED POTENTIALS', title: '机器学习势，先找到适用的，再运行。',
      description: '材料模型目录收录通用与专用原子势。你可以按材料体系、元素、周期性和任务筛选候选，查看权重、许可与运行状态，再下载或加载可用模型。',
      steps: ['描述结构与目标：如晶体能量、原子受力或结构弛豫', '核对元素、电荷、自旋、训练域与模型许可', '下载并加载实际可用的权重，执行受控计算', '查看能量、受力、收敛状态、报告和 3D 结构'],
      note: '目录收录不等于权重已安装；并非每个条目都有公开权重或可在当前设备运行。AI 的推荐需通过适用域检查与真实计算回执。',
      imageAlt: 'MaterialsX 机器学习势目录的真实界面，显示具体权重和安装状态', imageCaption: '真实开发版界面 · 机器学习势目录',
    },
    moos: {
      link: '查看 MOOS 数据连接',
      eyebrow: 'RESEARCH DATA · MOOS MCP', title: '让既有配方与工艺，成为下一轮实验的依据。',
      description: '配置 MOOS MCP 后，MaterialsX 可只读检索实验配方、原始用量、制备步骤、测试条件和原文证据。先找可比记录，再提出受约束的候选配方与验证实验。',
      steps: ['检索相关材料、配方和工艺记录', '保留单位、测试条件、页码及待复核状态', '比较可比样本，找出变量与性能差异', '生成候选配方和下一轮对照实验，等待实测验证'],
      note: 'MOOS 是独立服务，需要先部署并连接。候选优化是研究建议，不是已验证配方；历史记录也不会被自动改写。',
      imageAlt: 'MaterialsX 数据与 MCP 页面显示 MOOS 服务连接状态及只读查询说明', imageCaption: '真实开发版界面 · MOOS 连接状态',
    },
    local: {
      link: '连接本地 LLM',
      eyebrow: 'LOCAL LLM', title: '模型也可以运行在你的电脑上。',
      description: '在 LM Studio 加载模型并启动本机 API，再在 MaterialsX 中切换到本地模型、填写服务地址并检测。科研资料与对话可在本机处理。',
      steps: ['在 LM Studio 加载支持所需任务的模型', '启动本机 API：通常为 http://localhost:1234/v1', '在 MaterialsX 设置中检测模型和引擎兼容性'],
      note: '软件不预装聊天模型权重。本地模型的工具调用、文件阅读和长任务质量取决于模型及运行环境；启用前请做兼容性检测。',
      imageAlt: 'MaterialsX 设置抽屉中的本地模型服务地址及检测按钮', imageCaption: '真实开发版界面 · 本地模型设置',
    },
  },
  'zh-TW': {
    nav: '建立研究任務',
    tasks: {
      eyebrow: 'START WITH A QUESTION', title: '今天要推進什麼研究任務？',
      lead: '從一個問題開始，依研究階段選擇任務；所需資料可在送出前補充。',
      guideTitle: '第一次使用？從一個問題開始',
      guide: '選擇任務後，先在輸入框補上材料、目標或檔案。送出前可以修改；結果中的數據與引用仍需核對。',
      stageTitle: '依研究階段選擇', stageNote: '從問題、文獻和現有資料著手；不必先學會寫提示詞。',
      stages: ['剛開始研究', '選題與文獻', '材料資料', '實驗與分析', '結構與模擬', '論文與成果'], count: '6 個常用任務',
      cards: [
        ['幫我釐清研究問題', '把模糊想法整理成目標、限制和下一步', '說明材料體系、目標性能與現有條件。'],
        ['從哪裡查論文', '確定關鍵詞、檢索範圍和可信來源', '先寫研究主題，分清摘要與全文。'],
        ['帶我讀一篇論文', '解釋方法、結果與證據，不略過限制', '需要論文 PDF；關鍵數據回到原文頁碼。'],
        ['看懂實驗表格', '先核對單位、缺失值、重複樣和異常值', '需要實驗資料；先說明欄位與測試條件。'],
        ['設計第一個對照實驗', '確定變數、對照組、重複與評價指標', '補充設備、時間、成本與可用材料。'],
        ['檢查研究結論', '分辨證據、推論及尚缺的驗證', '提供結論與來源，尋找最小驗證實驗。'],
      ],
      flow: ['選擇任務', '補充材料與目標', '檢查並送出', '複核結果與來源'],
      foot: '點擊桌面版任務卡只會填入輸入框，不會自動送出或執行工具。也可直接描述問題。',
      imageAlt: 'MaterialsX 建立研究任務首頁，顯示六個常用任務的實際介面', imageCaption: '實際開發版介面 · 建立研究任務',
    },
    potentials: {
      link: '探索機器學習勢',
      eyebrow: 'MACHINE-LEARNED POTENTIALS', title: '機器學習勢：先確認適用，再開始計算。',
      description: '材料模型目錄收錄通用及專用的原子勢。依材料體系、元素、週期性和任務篩選，查看權重、授權與執行狀態，再下載或載入可用模型。',
      steps: ['描述結構與目標，如能量、原子受力或結構鬆弛', '核對元素、電荷、自旋、訓練領域及授權', '下載並載入可用權重，執行受控計算', '查看能量、受力、收斂狀態、報告與 3D 結構'],
      note: '目錄收錄不代表權重已安裝。部分項目沒有公開權重或無法在目前設備執行；推薦仍需適用領域檢查和真實執行回執。',
      imageAlt: 'MaterialsX 機器學習勢目錄的實際介面', imageCaption: '實際開發版介面 · 機器學習勢目錄',
    },
    moos: {
      link: '查看 MOOS 資料連接',
      eyebrow: 'RESEARCH DATA · MOOS MCP', title: '讓既有配方與製程支持下一輪實驗。',
      description: '設定 MOOS MCP 後，可唯讀檢索實驗配方、原始用量、製備步驟、測試條件與原文證據。先找可比記錄，再提出受限制的候選配方和驗證實驗。',
      steps: ['檢索相關材料、配方與製程', '保留單位、測試條件、頁碼和待複核狀態', '比較條件相容的樣本與性能差異', '提出候選配方和對照實驗，等待實測驗證'],
      note: 'MOOS 是獨立服務，須先部署並連接。候選優化是研究建議，並非已驗證配方；歷史紀錄不會被自動改寫。',
      imageAlt: 'MaterialsX 資料與 MCP 頁面中的 MOOS 連線狀態', imageCaption: '實際開發版介面 · MOOS 連線狀態',
    },
    local: {
      link: '連接本機 LLM',
      eyebrow: 'LOCAL LLM', title: '模型也能在自己的電腦上運行。',
      description: '在 LM Studio 載入模型並啟動本機 API，接著在 MaterialsX 選擇本機模型、填入服務位址並檢測。研究資料與對話可在本機處理。',
      steps: ['在 LM Studio 載入符合任務需求的模型', '啟動本機 API：通常是 http://localhost:1234/v1', '在 MaterialsX 設定中檢測模型與引擎相容性'],
      note: '軟體不預裝對話模型權重。工具呼叫、檔案閱讀及長任務品質取決於模型與環境，啟用前請做相容性檢測。',
      imageAlt: 'MaterialsX 設定中的本機模型服務位址與檢測按鈕', imageCaption: '實際開發版介面 · 本機模型設定',
    },
  },
  en: {
    nav: 'Start a task',
    tasks: {
      eyebrow: 'START WITH A QUESTION', title: 'What research will you move forward today?',
      lead: 'Start with a question, choose a stage, and add the materials you need before sending.',
      guideTitle: 'New here? Begin with one question',
      guide: 'Choose a task, then add your material system, goal, or files in the composer. Edit before sending, and verify data and citations in the result.',
      stageTitle: 'Choose a research stage', stageNote: 'Begin with a problem, papers, or existing data. No prompt-writing experience needed.',
      stages: ['Getting started', 'Topics & literature', 'Materials data', 'Experiments & analysis', 'Structures & simulation', 'Papers & outputs'], count: '6 common tasks',
      cards: [
        ['Clarify my research question', 'Turn an early idea into goals, constraints, and next steps', 'Describe the material, target property, and what you already have.'],
        ['Find relevant papers', 'Set keywords, search scope, and trustworthy sources', 'Start with a topic; distinguish abstracts from full papers.'],
        ['Read a paper with me', 'Understand methods, results, evidence, and limitations', 'Requires a PDF; return to source pages for key values.'],
        ['Understand an experiment table', 'Check units, missing values, replicates, and outliers', 'Requires data; explain columns and test conditions first.'],
        ['Design a first controlled experiment', 'Specify variables, controls, repeats, and measures', 'Add available equipment, time, cost, and materials.'],
        ['Check a research claim', 'Separate evidence, inference, and missing validation', 'Provide the claim and source; identify a minimal test.'],
      ],
      flow: ['Choose a task', 'Add context or files', 'Review and send', 'Verify results and sources'],
      foot: 'In the desktop app, choosing a card only fills the composer. It does not send a message or run tools. You can also describe your own task.',
      imageAlt: 'Actual MaterialsX new research task screen with stages and six starter tasks', imageCaption: 'Actual development UI · New research task',
    },
    potentials: {
      link: 'Explore atomic potentials',
      eyebrow: 'MACHINE-LEARNED POTENTIALS', title: 'Find a suitable atomic potential before you calculate.',
      description: 'Explore general and specialized potentials in the materials model catalog. Screen by system, elements, periodicity, and task. Inspect weights, license, and runtime status before downloading or loading an eligible model.',
      steps: ['Describe the structure and task: energy, forces, or relaxation', 'Check elements, charge, spin, training domain, and license', 'Download and load eligible weights for a bounded run', 'Inspect energy, forces, convergence, report, and 3D structure'],
      note: 'A catalog listing is not an installed checkpoint. Some entries have no public weights or cannot run on your device. AI recommendations still require applicability checks and real execution receipts.',
      imageAlt: 'Actual MaterialsX machine-learned potential catalog with model and installation status', imageCaption: 'Actual development UI · Potential catalog',
    },
    moos: {
      link: 'Connect MOOS data',
      eyebrow: 'RESEARCH DATA · MOOS MCP', title: 'Use past formulations and processes to plan the next experiment.',
      description: 'With MOOS MCP configured, query formulations, original amounts, preparation steps, test conditions, and source evidence in read-only mode. Compare compatible records before proposing constrained formulation candidates and validation experiments.',
      steps: ['Search relevant formulations and process records', 'Keep units, test conditions, page citations, and review status', 'Compare compatible samples and property differences', 'Propose candidates and controls for experimental validation'],
      note: 'MOOS is a separate service and must be configured. An optimization candidate is a research suggestion, not a validated formulation. Historical records are never silently changed.',
      imageAlt: 'Actual MaterialsX Data and MCP screen showing MOOS read-only connection status', imageCaption: 'Actual development UI · MOOS connection',
    },
    local: {
      link: 'Connect a local LLM',
      eyebrow: 'LOCAL LLM', title: 'Run your language model on your own computer.',
      description: 'Load a model in LM Studio and start its local API. In MaterialsX, select Local model, enter the service URL, and test the connection. Research files and conversations can be processed on-device.',
      steps: ['Load a model suited to your task in LM Studio', 'Start the local API, usually http://localhost:1234/v1', 'Check model and agent-engine compatibility in MaterialsX'],
      note: 'Chat-model weights are not bundled. Tool use, file reading, and long-task reliability depend on the model and runtime; run the compatibility check first.',
      imageAlt: 'Actual MaterialsX local model settings with URL and compatibility controls', imageCaption: 'Actual development UI · Local model settings',
    },
  },
  ja: {
    nav: '研究タスクを始める',
    tasks: {
      eyebrow: 'START WITH A QUESTION', title: '今日はどの研究を進めますか？',
      lead: '一つの問いから始め、研究段階でタスクを選びます。必要な資料は送信前に追加できます。',
      guideTitle: '初めての方は、一つの問いから',
      guide: 'タスクを選び、材料系・目標・ファイルを入力欄に追加してください。送信前に編集でき、結果の数値と引用は確認が必要です。',
      stageTitle: '研究段階から選ぶ', stageNote: '課題、論文、既存データから着手できます。プロンプト作成の経験は不要です。',
      stages: ['研究を始める', 'テーマと文献', '材料データ', '実験と分析', '構造とシミュレーション', '論文と成果'], count: 'よく使う 6 タスク',
      cards: [
        ['研究課題を明確にする', '曖昧な着想を目標・制約・次の行動へ', '材料系、目標物性、手元の条件を説明します。'],
        ['論文の探し方を決める', 'キーワード、検索範囲、信頼できる情報源を決める', '研究テーマを書き、要旨と全文を区別します。'],
        ['論文を一緒に読む', '方法、結果、根拠、限界を理解する', 'PDF が必要です。重要な数値は原文ページで確認します。'],
        ['実験表を理解する', '単位、欠損、反復、外れ値を先に確認', '実験データが必要です。列と測定条件を説明します。'],
        ['最初の対照実験を設計', '変数、対照群、反復、評価指標を定める', '装置、時間、費用、材料の条件を追加します。'],
        ['研究上の主張を検証', '証拠、推論、必要な追加検証を分ける', '主張と出典を示し、最小限の検証を探します。'],
      ],
      flow: ['タスクを選ぶ', '材料と目標を追加', '確認して送信', '結果と出典を検証'],
      foot: 'デスクトップ版のカードは入力欄を埋めるだけで、送信やツール実行は自動で行いません。自由に課題を記述することもできます。',
      imageAlt: 'MaterialsX の研究タスク作成画面。段階別分類と六つの入門タスクを表示', imageCaption: '実際の開発版画面 · 研究タスク作成',
    },
    potentials: {
      link: '原子ポテンシャルを探す',
      eyebrow: 'MACHINE-LEARNED POTENTIALS', title: '適切な原子ポテンシャルを選んでから計算。',
      description: '材料モデル目録から汎用・専用ポテンシャルを探せます。材料系、元素、周期性、目的で候補を絞り、重み・ライセンス・実行状態を確認してから使用します。',
      steps: ['構造と目的を記述：エネルギー、原子間力、構造緩和など', '元素、電荷、スピン、学習領域、ライセンスを確認', '使用できる重みをダウンロード・読み込み、範囲を決めて計算', 'エネルギー、力、収束、報告、3D 構造を確認'],
      note: '目録掲載は重みのインストールを意味しません。公開重みがない項目や手元の環境で動かない項目もあります。推薦には適用範囲と実行結果の確認が必要です。',
      imageAlt: 'MaterialsX の機械学習ポテンシャル目録とインストール状態', imageCaption: '実際の開発版画面 · ポテンシャル目録',
    },
    moos: {
      link: 'MOOS データをつなぐ',
      eyebrow: 'RESEARCH DATA · MOOS MCP', title: '既存の配合・工程を次の実験の根拠に。',
      description: 'MOOS MCP を設定すると、配合、元の分量、調製工程、試験条件、出典を読み取り専用で検索できます。比較可能な記録から候補配合と検証実験を検討します。',
      steps: ['関連する材料、配合、工程を検索', '単位、試験条件、ページ、確認状態を保持', '条件が合う試料の性能差を比較', '候補配合と対照実験を提案し、実測で検証'],
      note: 'MOOS は別サービスであり、導入と接続が必要です。最適化候補は研究提案で、検証済み配合ではありません。元の記録を自動で変更しません。',
      imageAlt: 'MaterialsX のデータと MCP 画面にある MOOS 接続状態', imageCaption: '実際の開発版画面 · MOOS 接続',
    },
    local: {
      link: 'ローカル LLM を使う',
      eyebrow: 'LOCAL LLM', title: '言語モデルを自分のパソコンで動かす。',
      description: 'LM Studio でモデルとローカル API を起動し、MaterialsX でローカルモデルを選択、URL を入力して接続を確認します。研究資料と会話を端末内で処理できます。',
      steps: ['LM Studio でタスクに合うモデルを読み込む', '通常 http://localhost:1234/v1 のローカル API を起動', 'MaterialsX でモデルと Agent エンジンの互換性を確認'],
      note: '会話モデルの重みは同梱されません。ツール利用、ファイル読解、長いタスクの安定性はモデルと環境に依存します。先に互換性を確認してください。',
      imageAlt: 'MaterialsX のローカルモデル URL と互換性確認を示す設定画面', imageCaption: '実際の開発版画面 · ローカルモデル設定',
    },
  },
};
