import { createScienceBridge,molecularScienceParameters } from "./science-bridge.js";
import { defineTool } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import type { AtomisticRuntime } from "../../atomistic/src/runtime.js";

/** Project-scoped IDs only. Import requires the desktop picker; no LLM-provided paths/code/downloads. */
export function createAtomisticTools(runtime:AtomisticRuntime,projectId:string,onView?:(structureId:string)=>void,automation?:Parameters<typeof createScienceBridge>[4],scope?:Parameters<typeof createScienceBridge>[2]) {
  const text=(value:unknown)=>({content:[{type:"text" as const,text:JSON.stringify(value)}],details:undefined});
  const id=Type.String({pattern:"^[a-zA-Z0-9][a-zA-Z0-9_.:-]{0,127}$"});
  const bridge=createScienceBridge(runtime,projectId,scope,onView,automation);
  return [
    defineTool({name:bridge.tool.name,label:"MaterialsX science",description:bridge.tool.description,parameters:molecularScienceParameters,async execute(_id,args,signal){return text(await bridge.execute(args,signal));}}),
    defineTool({name:"inspect_atomic_structure",label:"Inspect atomic structure",description:"Read an already imported structure by ID in this project. Reports occupancy, PBC and blocking issues; at most 16 atom coordinates are returned to bound model context. The calculator uses the full immutable structure.",parameters:Type.Object({structureId:id},{additionalProperties:false}),async execute(_id,args){const s=runtime.inspect({...args,projectId});return text({...s,atoms:s.atoms.slice(0,16),atomCount:s.atoms.length,coordinatesTruncated:s.atoms.length>16});}}),
    defineTool({name:"run_atomistic_calculation",label:"Run local single point",description:"Use materials_science select first and supply its eligible assessmentId and candidate evidenceIds. Run CPU single-point screening with an explicitly selected installed core potential. Returns a job ID; get_atomistic_job with wait=true waits for completion. Hard compatibility gates are enforced; for explainable selection use materials_science select first. No DFT accuracy claim. For optimization use relax_atomic_structure; For bounded fixed-cell MD use run_atomic_md.",parameters:Type.Object({assessmentId:id,evidenceIds:Type.Array(id,{minItems:1,maxItems:20}),potentialId:Type.String({pattern:"^[a-z][a-z0-9.-]{0,95}$"})},{additionalProperties:false}),async execute(_id,args,signal){const s=await runtime.startSelected({projectId,proposal:{assessmentId:args.assessmentId,selectedPotentialId:args.potentialId,evidenceIds:args.evidenceIds}},signal);signal?.addEventListener("abort",()=>runtime.cancel({projectId,runId:s.job.id}),{once:true});if(signal?.aborted)runtime.cancel({projectId,runId:s.job.id});return text({job:s.job,outputDirectory:s.outputDirectory});}}),
    defineTool({name:"relax_atomic_structure",label:"Relax local structure",description:"Use materials_science select with secondaryId=relaxation first and supply assessmentId and candidate evidenceIds. Run bounded FIRE local optimization with an eligible installed potential. Default preference is fixed cell. Variable cell is only for an explicit user request and needs explicit pressure (GPa, positive compression) and isotropic/full strain choice; never infer them. A job can complete without convergence; query the real stopReason. No DFT accuracy or global stability claim.",parameters:Type.Object({assessmentId:id,evidenceIds:Type.Array(id,{minItems:1,maxItems:20}),potentialId:Type.String({pattern:"^[a-z][a-z0-9.-]{0,95}$"}),options:Type.Object({optimizer:Type.Literal("FIRE"),cellMode:Type.Union([Type.Literal("fixed"),Type.Literal("variable")]),cellConstraint:Type.Union([Type.Literal("none"),Type.Literal("hydrostatic"),Type.Literal("full")]),externalPressureGPa:Type.Union([Type.Number({minimum:-10,maximum:10}),Type.Null()]),maxSteps:Type.Integer({minimum:1,maximum:500}),fmaxEvPerAngstrom:Type.Number({minimum:.001,maximum:.2})},{additionalProperties:false})},{additionalProperties:false}),async execute(_id,args,signal){const s=await runtime.startSelected({projectId,proposal:{assessmentId:args.assessmentId,selectedPotentialId:args.potentialId,evidenceIds:args.evidenceIds},options:args.options},signal);signal?.addEventListener("abort",()=>runtime.cancel({projectId,runId:s.job.id}),{once:true});if(signal?.aborted)runtime.cancel({projectId,runId:s.job.id});return text({job:s.job,options:s.relaxation!.options,outputDirectory:s.outputDirectory});}}),
    defineTool({name:"run_atomic_md",label:"Run short local MD",description:"Select with materials_science secondaryId=md first. CPU exploratory fixed-cell NVE/NVT, <=2000 steps. Temperature is initialization for NVE, target for NVT. NVT requires explicit friction fs^-1; NVE forbids it. Query to terminal and read real frames/diagnostics; never infer long-term stability or DFT accuracy. No arbitrary paths or scripts.",parameters:Type.Object({assessmentId:id,evidenceIds:Type.Array(id,{minItems:1,maxItems:20}),potentialId:Type.Union([Type.Literal("mace-mp-0b3-medium"),Type.Literal("chgnet-0.3.0"),Type.Literal("chgnet-r2scan")]),mdOptions:Type.Object({ensemble:Type.Union([Type.Literal("nve"),Type.Literal("nvt")]),steps:Type.Integer({minimum:1,maximum:2000}),timestepFs:Type.Number({minimum:.01,maximum:1}),temperatureK:Type.Number({minimum:1,maximum:1000}),sampleEvery:Type.Integer({minimum:1,maximum:2000}),seed:Type.Integer({minimum:0,maximum:4294967295}),frictionInverseFs:Type.Union([Type.Number({minimum:.001,maximum:.1}),Type.Null()])},{additionalProperties:false})},{additionalProperties:false}),async execute(_id,args,signal){const run=await runtime.startSelected({projectId,proposal:{assessmentId:args.assessmentId,selectedPotentialId:args.potentialId,evidenceIds:args.evidenceIds},mdOptions:args.mdOptions},signal);signal?.addEventListener('abort',()=>runtime.cancel({projectId,runId:run.job.id}),{once:true});if(signal?.aborted)runtime.cancel({projectId,runId:run.job.id});return text({job:run.job,mdOptions:run.md!.options});}}),
    defineTool({name:"get_atomistic_job",label:"Get atomistic job",description:"Read the persisted local job and actual energy/stress/force summary. wait=true waits up to 30 seconds without repeated model calls. Full N×3 forces are in the hashed result artifact. Failed/cancelled/interrupted jobs are not successful results; scientific quality remains needs_review.",parameters:Type.Object({runId:id,wait:Type.Optional(Type.Boolean())},{additionalProperties:false}),async execute(_id,args,signal){
      const query={projectId,runId:args.runId};let s=runtime.get(query);const deadline=Date.now()+30_000;
      while(args.wait&&!["completed","failed","cancelled","interrupted"].includes(s.job.status)&&Date.now()<deadline){if(signal?.aborted)throw Error("CANCELLED");await new Promise(r=>setTimeout(r,250));s=runtime.get(query);}
      const result=s.result?{...s.result,forcesEvPerAngstrom:s.result.forcesEvPerAngstrom.slice(0,16),forcesTruncated:s.result.atomCount>16,maxForceEvPerAngstrom:Math.max(...s.result.forcesEvPerAngstrom.map(f=>Math.hypot(...f)))}:null;
      return text({job:s.job,result,md:s.md??null,relaxation:s.relaxation?{options:s.relaxation.options,progress:s.relaxation.progress,summary:s.relaxation.summary?{...s.relaxation.summary,displacementsAngstrom:s.relaxation.summary.displacementsAngstrom.slice(0,16),displacementsTruncated:s.relaxation.summary.displacementsAngstrom.length>16}:null,partialArtifactId:s.relaxation.partialArtifactId}:null,artifacts:s.artifacts,outputDirectory:s.outputDirectory});}}),
    defineTool({name:"cancel_atomistic_job",label:"Cancel atomistic job",description:"Cancel a queued/running local job in this project and stop its process tree.",parameters:Type.Object({runId:id},{additionalProperties:false}),async execute(_id,args){return text({cancelled:runtime.cancel({...args,projectId})});}}),
    defineTool({name:"list_atomistic_jobs",label:"List atomistic jobs",description:"List this project's local job summaries and imported structure IDs. Runtime readiness is separate from scientific validation.",parameters:Type.Object({},{additionalProperties:false}),async execute(){return text({runtimes:runtime.status(),structures:runtime.listStructures(projectId).map(s=>({id:s.id,atomCount:s.atoms.length,pbc:s.pbc,issues:s.issues})),jobs:runtime.list(projectId).map(s=>({job:s.job,structureId:s.structure.id,potentialId:s.plan.potentialId}))});}}),
  ];
}
