import { z } from 'zod';
import { localId, runnablePotentialId } from './atomistic-runtime.js';
import { atomicStructureSchema } from './atomistic.js';
const hash=z.string().regex(/^[a-f0-9]{64}$/), text=z.string().min(1).max(2000), vec=z.tuple([z.number(),z.number(),z.number()]);
export const extensionManifestSchema=z.strictObject({version:z.literal('m6.6-v1'),entries:z.array(z.strictObject({potentialId:z.literal('chgnet-r2scan'),family:z.literal('chgnet'),bytes:z.number().int().positive().max(8*1048576),sha256:hash,url:z.url().refine(u=>u.startsWith('https://raw.githubusercontent.com/CederGroupHub/chgnet/b9a6c15860237297a5a5169660e83b2e61a78e76/')),sourceRevision:z.literal('b9a6c15860237297a5a5169660e83b2e61a78e76'),environmentProfileId:z.literal('chgnet-0.3.0-cpu-v1'),license:z.literal('BSD-3-Clause-LBNL'),licenseSha256:hash,readmeSha256:hash,reviewedAt:z.iso.date(),functional:z.literal('r2SCAN')})).max(1)});
export type ExtensionManifest=z.infer<typeof extensionManifestSchema>;
export const packageRequestSchema=z.strictObject({potentialId:z.literal('chgnet-r2scan')});
export const packageStatusSchema=z.strictObject({potentialId:z.literal('chgnet-r2scan'),state:z.enum(['absent','downloading','paused','installed','disabled','failed']),bytes:z.number().int().nonnegative(),totalBytes:z.number().int().positive(),sha256:hash,error:z.string().max(200).nullable(),runtimeReady:z.boolean(),quality:z.literal('needs_review')});
export type PackageStatus=z.infer<typeof packageStatusSchema>;
export const holdoutSchema=z.strictObject({version:z.literal('m6.6-v1'),id:localId,title:text,kind:z.enum(['dft-heldout','synthetic-test']),units:z.strictObject({energy:z.literal('eV-total'),forces:z.literal('eV/angstrom'),positions:z.literal('angstrom')}),source:z.strictObject({citation:text,license:text,licenseConfirmed:z.boolean(),labelProvenanceSha256:hash}),settings:z.strictObject({code:text,version:text,functional:z.enum(['PBE+U','r2SCAN']),hubbardU:z.record(z.string(),z.number()),pseudopotentialSha256:z.array(hash).min(1).max(118),cutoffEv:z.number().positive(),kpointMesh:z.tuple([z.number().int().positive(),z.number().int().positive(),z.number().int().positive()]),spin:text,charge:text,energyReference:text,corrections:text,forceConvergenceEvPerAngstrom:z.number().positive(),electronicConvergenceEv:z.number().positive()}),audits:z.array(z.strictObject({potentialId:runnablePotentialId,trainingOverlap:z.enum(['independent-reviewed','overlap','unknown']),reviewer:text,evidenceSha256:hash,reviewedAt:z.iso.date(),matchedTheory:z.boolean(),matchedEnergyReference:z.boolean()})).min(1).max(3),samples:z.array(z.strictObject({id:localId,domain:z.enum(['bulk','multi-element','defect','surface']),structure:atomicStructureSchema,energyEv:z.number(),forcesEvPerAngstrom:z.array(vec).min(1).max(256)})).min(1).max(100)}).superRefine((d,c)=>{
 if(new Set(d.samples.map(s=>s.id)).size!==d.samples.length||new Set(d.audits.map(a=>a.potentialId)).size!==d.audits.length)c.addIssue({code:'custom',message:'duplicate sample/audit'});
 const structures=new Set<string>();
 for(const s of d.samples){const g=JSON.stringify({cell:s.structure.cell,pbc:s.structure.pbc,atoms:s.structure.atoms.map(a=>({element:a.element,position:a.position}))});if(structures.has(g))c.addIssue({code:'custom',message:'duplicate holdout geometry'});structures.add(g);
 if(s.structure.atoms.length!==s.forcesEvPerAngstrom.length||s.structure.atoms.length>256||s.structure.atoms.some(a=>a.occupancy!==1)||s.structure.issues.some(i=>i.severity==='blocking')||!s.structure.pbc.every(Boolean)||s.structure.charge!==null||s.structure.spinMultiplicity!==null)c.addIssue({code:'custom',message:'invalid label mapping or unsupported geometry/electronic state'});
 }
});
export type Holdout=z.infer<typeof holdoutSchema>;
export const evaluationRequestSchema=z.strictObject({projectId:localId,datasetId:localId,potentialId:runnablePotentialId});
export const predictionSchema=z.strictObject({sampleId:localId,runId:localId,potentialId:runnablePotentialId,potentialSha256:hash,structureSha256:hash,energyEv:z.number(),forcesEvPerAngstrom:z.array(vec).min(1).max(256)});
export type Prediction=z.infer<typeof predictionSchema>;
export const evaluationReportSchema=z.strictObject({version:z.literal('m6.6-v1'),id:localId,datasetId:localId,datasetSha256:hash,policySha256:hash,potentialId:runnablePotentialId,potentialSha256:hash,createdAt:z.iso.datetime(),status:z.enum(['passed-screening','failed','blocked']),productionApproved:z.literal(false),quality:z.literal('needs_review'),reasonCodes:z.array(localId).max(30),totalSamples:z.number().int().positive(),completedSamples:z.number().int().nonnegative(),domains:z.array(z.strictObject({domain:z.enum(['bulk','multi-element','defect','surface']),samples:z.number().int().nonnegative(),required:z.number().int().positive(),energyMaeEvPerAtom:z.number().nonnegative().nullable(),forceRmseEvPerAngstrom:z.number().nonnegative().nullable(),passed:z.boolean()})).length(4),predictions:z.array(predictionSchema).max(100),limitations:z.array(text).min(1).max(10)});
export type EvaluationReport=z.infer<typeof evaluationReportSchema>;
export const evaluationStatusSchema=z.strictObject({id:localId,projectId:localId,datasetId:localId,potentialId:runnablePotentialId,status:z.enum(['queued','running','completed','failed','cancelled','interrupted']),completedSamples:z.number().int().nonnegative(),totalSamples:z.number().int().positive(),activeRunId:localId.nullable(),error:z.string().max(200).nullable(),report:evaluationReportSchema.nullable()});
export type EvaluationStatus=z.infer<typeof evaluationStatusSchema>;
export const qualityMatrixSchema=z.strictObject({version:z.literal('m6.6-v1'),platform:z.string().max(100),policySha256:hash,rows:z.array(z.strictObject({potentialId:runnablePotentialId,functional:text,installed:z.boolean(),portable:z.boolean(),domainStatus:z.enum(['blocked-reference-data-missing','failed','passed-screening']),productionApproved:z.literal(false),reportId:localId.nullable(),devices:z.strictObject({cpu:z.enum(['available-unverified','absent']),cuda:z.literal('unverified'),mps:z.literal('unverified')})})).max(3),releaseGates:z.array(z.strictObject({id:localId,status:z.enum(['passed','pending','failed']),detail:text})).min(1).max(15)});
export type QualityMatrix=z.infer<typeof qualityMatrixSchema>;
