/** Client-executed tool names; the gateway never executes or grants them. */
export const researchDirectToolNames = [
  "research_subtask",
  "research_browser",
  "materials_science",
  "potential_search",
  "skill_search",
  "read_skill",
  "read_material_file",
  "skill_resource",
  "skill_capabilities",
  "research_data",
  "recipe_proposal",
  "research_delivery",
  "paper_search",
  "paper_get",
  "paper_fetch",
  "paper_read",
  "paper_export",
  "official_document",
  "environment_check",
  "environment_repair",
  "materials_rpsme_extract",
  "campaign_job",
  "method_package_search",
  "research_quality",
  "research_methods",
  "research_method_run",
  "experiment_data",
  "experiment_analyze",
  "next_experiment_data",
  "next_experiment_design"
] as const;
export const cloudHostToolNames = [...new Set([...researchDirectToolNames,
 "agent_exec", "agent_wait", "exec_command", "write_stdin", "apply_patch", "task_control",
 "read", "write", "edit", "bash", "ls", "git_status", "find_tools", "invoke_material_tool",
])].sort();
