import {potentialCatalogSchema as historicalCatalog,hubEntrySchema} from './potential-hub.js';
import {z} from 'zod';
import {nativePotentialSchema} from './potential-native.js';
import {selectionRequestSchema as priorRequest,currentScientificScopeSchema as priorScope} from './potential-molecules.js';
export const COMPOSITE_ID='mace-mp-0b3-medium-d3-bj-pbe-si' as const;
export const interactionSchema=z.enum(['short-range','long-range-required','dispersion-required','spin-required','field-required','delta-required','multi-head-required']);
export const selectionRequestSchema=priorRequest.extend({interaction:interactionSchema.optional()});
export type SelectionRequest=z.infer<typeof selectionRequestSchema>;
export const currentScientificScopeSchema=z.strictObject({...priorScope.shape,interaction:interactionSchema.optional()}).superRefine((v,c)=>{if((v.permission==='relaxation')!==!!v.options||(v.permission==='md')!==!!v.mdOptions)c.addIssue({code:'custom',message:'permission requires matching explicit options'});});
export type ScientificScope=z.infer<typeof currentScientificScopeSchema>;
export const compositionProfileSchema=z.strictObject({version:z.literal('m6.15-v1'),id:z.literal(COMPOSITE_ID),operator:z.literal('sum'),baseline:z.strictObject({id:z.literal('mace-mp-0b3-medium'),weightSha256:z.string().regex(/^[a-f0-9]{64}$/),reference:z.literal('PBE+U; pure Si has no Hubbard U'),dispersion:z.literal('not-added')}),correction:z.strictObject({kind:z.literal('d3-bj-two-body'),functional:z.literal('pbe'),s6:z.literal(1),s8:z.literal(0.7875),a1:z.literal(0.4289),a2Bohr:z.literal(4.4407),potentialCutoffAngstrom:z.literal(10),coordinationCutoffAngstrom:z.literal(5),atm:z.literal(false),electrostatics:z.literal(false)}),scope:z.strictObject({elements:z.tuple([z.literal('Si')]),maxAtoms:z.literal(128),minimumCellSingularValueAngstrom:z.literal(4),minimumVolumePerAtomAngstrom3:z.literal(5),minimumDistanceAngstrom:z.literal(2.3),tasks:z.tuple([z.literal('singlepoint'),z.literal('relaxation')]),cell:z.literal('fixed'),mode:z.literal('exploratory')})});
export const physicsExpansionSchema=z.strictObject({version:z.literal('m6.15-v1'),entry:z.strictObject({potentialId:z.literal(COMPOSITE_ID),family:z.literal('mace'),adapter:z.literal('mace-ase'),basePotentialId:z.literal('mace-mp-0b3-medium'),environmentProfileId:z.literal('mace-mp0b3-d3bj-si-cpu-v1'),dependencyLockSha256:z.string().regex(/^[a-f0-9]{64}$/),sourceRevision:z.string().regex(/^[a-f0-9]{40}$/),url:z.url(),sha256:z.string().regex(/^[a-f0-9]{64}$/),bytes:z.number().int().positive(),license:z.literal('MIT'),notices:z.array(z.strictObject({path:z.string().regex(/^docs\/m6\/licenses\/[a-zA-Z0-9.-]+$/),sha256:z.string().regex(/^[a-f0-9]{64}$/)})).min(2).max(8),reviewedAt:z.iso.datetime(),elements:z.tuple([z.literal('Si')]),loadedMemoryMiB:z.number().positive(),dtype:z.literal('float64')}),potential:nativePotentialSchema,profile:compositionProfileSchema,profileSha256:z.string().regex(/^[a-f0-9]{64}$/),engine:z.strictObject({name:z.literal('NEP_CPU-D3-only'),revision:z.string().regex(/^[a-f0-9]{40}$/),sources:z.array(z.strictObject({path:z.string().regex(/^(vendor\/nep-cpu\/[a-zA-Z0-9_.-]+|atomistic\/(d3_runner.cpp|composed.py))$/),sha256:z.string().regex(/^[a-f0-9]{64}$/)})).min(10).max(12)})}).superRefine((m,c)=>{const p=m.potential,e=m.entry;const paths=m.engine.sources.map(s=>s.path),expected=['LICENSE','dftd3para.h','ewald_nep.cpp','ewald_nep.h','neighbor_nep.cpp','neighbor_nep.h','nep.cpp','nep.h','nep_utilities.h'].map(s=>'vendor/nep-cpu/'+s).concat(['atomistic/d3_runner.cpp','atomistic/composed.py']);if(new Set(paths).size!==11||expected.some(s=>!paths.includes(s)))c.addIssue({code:'custom',message:'fixed source closure required'});if(p.id!==COMPOSITE_ID||p.family!=='MACE'||p.environment.adapter!=='mace-ase'||p.environment.profileId!==e.environmentProfileId||p.environment.codeRevision!==e.sourceRevision||p.weights.sha256!==e.sha256||p.weights.bytes!==e.bytes||p.weights.url!==e.url||m.profile.baseline.weightSha256!==e.sha256||JSON.stringify(p.declared.elements)!=='["Si"]'||JSON.stringify(p.declared.periodicity)!=='["bulk"]'||JSON.stringify(p.declared.domains)!=='["inorganic-crystals"]'||p.declared.conservative!=='yes'||p.declared.headPolicy!=='single'||p.declared.chargeInput!=='unsupported'||p.declared.spinInput!=='unsupported'||p.licenses.weights.expression!=='MIT'||p.licenses.redistribution!=='permitted-with-notices'||p.environment.matrix.some(r=>r.status==='verified'&&(r.platform!=='macos-arm64'||r.device!=='cpu')))c.addIssue({code:'custom',message:'unreviewed composition/baseline/physics identity'});});
export const physicsSchemas={CompositionProfile:compositionProfileSchema,PhysicsExpansion:physicsExpansionSchema,SelectionRequest:selectionRequestSchema,ScientificScope:currentScientificScopeSchema};

const componentValues=z.strictObject({energyEv:z.number().finite(),forcesEvPerAngstrom:z.array(z.tuple([z.number().finite(),z.number().finite(),z.number().finite()])).min(1).max(128),stress:z.array(z.number().finite()).length(6)});
export const compositionResultSchema=z.strictObject({version:z.literal('m6.15-v1'),profileSha256:z.string().regex(/^[a-f0-9]{64}$/),baseline:componentValues,correction:componentValues,total:componentValues,units:z.strictObject({energy:z.literal('eV'),forces:z.literal('eV/angstrom'),stress:z.literal('eV/angstrom^3')}),stressOrder:z.literal('xx,yy,zz,yz,xz,xy'),stressSign:z.literal('positive-tension'),quality:z.literal('needs_review')}).superRefine((v,c)=>{
 const close=(a:number,b:number)=>Math.abs(a-b)<=1e-9*Math.max(1,Math.abs(a),Math.abs(b));
 const n=v.total.forcesEvPerAngstrom.length;
 if(v.baseline.forcesEvPerAngstrom.length!==n||v.correction.forcesEvPerAngstrom.length!==n||!close(v.total.energyEv,v.baseline.energyEv+v.correction.energyEv)||v.total.stress.some((x,i)=>!close(x,v.baseline.stress[i]!+v.correction.stress[i]!))||v.total.forcesEvPerAngstrom.some((f,i)=>f.some((x,k)=>!close(x,(v.baseline.forcesEvPerAngstrom[i]?.[k]??NaN)+(v.correction.forcesEvPerAngstrom[i]?.[k]??NaN)))))c.addIssue({code:'custom',message:'component energy/forces/stress must add to total'});
});
export type CompositionResult=z.infer<typeof compositionResultSchema>;
export const composedSchemas={...physicsSchemas,CompositionResult:compositionResultSchema};

// Validate current workflow metadata through the historical invariants, allowing only this audited composition ID.
export const currentPotentialCatalogSchema=z.strictObject({...historicalCatalog.shape,entries:z.array(z.strictObject(hubEntrySchema.shape)).min(1).max(5000)}).superRefine((v,c)=>{
 const projected={...v,entries:v.entries.map(e=>e.id===COMPOSITE_ID&&e.entityType==='workflow'?{...e,entityType:'checkpoint' as const}:e)};
 const r=historicalCatalog.safeParse(projected);if(!r.success)for(const issue of r.error.issues)c.addIssue({...issue});
 const e=v.entries.find(e=>e.id===COMPOSITE_ID);
 if(e&&(e.entityType!=='workflow'||e.execution.legacyId!==COMPOSITE_ID||e.capabilities.compositionRole!=='composite'||JSON.stringify(e.capabilities.requiredComponents)!=='["mace-mp-0b3-medium","NEP_CPU-PBE-D3(BJ)-two-body"]'||JSON.stringify(e.capabilities.longRange)!=='["dispersion"]'))c.addIssue({code:'custom',message:'unknown executable composition workflow'});
});
