import { z } from 'zod';
import { localId } from './atomistic-runtime.js';
import { mountedId,selectionAssessmentSchema,currentSelectionAssessmentSchema,molecularSelectionAssessmentSchema } from './potential-packages.js';
import { selectionRequestSchema } from './atomistic-selection.js';
import {selectionRequestSchema as molecularRequest} from './potential-molecules.js';
import {selectionRequestSchema as physicsRequest} from './potential-physics.js';
import { atomisticBudgetSchema } from './atomistic.js';
import { relaxationOptionsSchema } from './atomistic-relaxation.js';
export const analysisRequestSchema=z.strictObject({projectId:localId,structureId:localId,prompt:z.string().min(1).max(4096),locale:z.enum(['zh','en']),domain:selectionRequestSchema.shape.domain,mode:selectionRequestSchema.shape.mode,task:z.enum(['singlepoint','relaxation']),options:relaxationOptionsSchema.optional(),budget:atomisticBudgetSchema,maxDownloadBytes:z.number().int().min(0).max(512*1024**2)}).refine(v=>(v.task==='relaxation')===!!v.options,'explicit relaxation options required');
export const freezeAnalysisSchema=z.strictObject({assessmentId:localId,potentialId:mountedId,evidenceIds:z.array(localId).min(1).max(20),reason:z.string().min(1).max(2048)});
export const analysisPlanSchema=z.strictObject({version:z.literal('m6.9-v1'),id:localId,createdAt:z.iso.datetime(),request:analysisRequestSchema,assessment:selectionAssessmentSchema,potentialId:mountedId,potentialSha256:z.string().regex(/^[a-f0-9]{64}$/),dependencyLockSha256:z.string().regex(/^[a-f0-9]{64}$/),downloadBytes:z.number().int().nonnegative(),evidenceIds:z.array(localId).min(1).max(20),reason:z.string().min(1).max(2048),planSha256:z.string().regex(/^[a-f0-9]{64}$/)});
export const workflowSchema=z.strictObject({version:z.literal('m6.9-v1'),id:localId,plan:analysisPlanSchema,state:z.enum(['awaiting_approval','downloading','checking','queued','running','completed','failed','cancelled','interrupted']),createdAt:z.iso.datetime(),updatedAt:z.iso.datetime(),authorizedAt:z.iso.datetime().nullable(),runId:localId.nullable(),error:z.string().max(512).nullable(),events:z.array(z.strictObject({at:z.iso.datetime(),state:z.string().max(32),detail:z.string().max(1024)})).max(200)});
export const molecularAnalysisRequestSchema=analysisRequestSchema.extend({interaction:molecularRequest.shape.interaction});
export const molecularAnalysisPlanSchema=analysisPlanSchema.extend({request:molecularAnalysisRequestSchema,assessment:molecularSelectionAssessmentSchema});
export const molecularWorkflowSchema=workflowSchema.extend({plan:molecularAnalysisPlanSchema});
export const currentAnalysisRequestSchema=analysisRequestSchema.extend({interaction:physicsRequest.shape.interaction});
export type AnalysisRequest=z.infer<typeof currentAnalysisRequestSchema>;
export const currentAnalysisPlanSchema=analysisPlanSchema.extend({request:currentAnalysisRequestSchema,assessment:currentSelectionAssessmentSchema});
export type AnalysisPlan=z.infer<typeof currentAnalysisPlanSchema>;
export const currentWorkflowSchema=workflowSchema.extend({plan:currentAnalysisPlanSchema});
export type PotentialWorkflow=z.infer<typeof currentWorkflowSchema>;
export const analysisScopeSchema=z.strictObject({projectId:localId,conversationId:localId,structureId:localId,maxDownloadBytes:z.number().int().min(0).max(512*1024**2),maxSteps:z.number().int().min(1).max(500),permission:z.enum(['singlepoint','relaxation'])});
export type AnalysisScope=z.infer<typeof analysisScopeSchema>;
