import {z} from 'zod';
import {signedCatalogReleaseSchema} from './potential-discovery.js';
import {atomicStructureSchema,atomisticPlanSchema,atomisticArtifactSchema,atomisticResultSchema} from './atomistic.js';
import {catalogId} from './potential-hub.js';
const sha=z.string().regex(/^[a-f0-9]{64}$/), bytes=z.number().int().nonnegative();
export const catalogBundleSchema=z.strictObject({version:z.literal('m6.12-v1'),baselineSha256:sha,releases:z.array(signedCatalogReleaseSchema).min(1).max(256)});
export const offlineCollectionSchema=z.strictObject({version:z.literal('m6.12-v1'),createdAt:z.iso.datetime(),kind:z.literal('reviewed-checkpoints'),entries:z.array(z.strictObject({potentialId:catalogId,sha256:sha,bytes:bytes,dependencyLockSha256:sha,sourceRevision:z.string().min(1).max(200),notices:z.array(z.strictObject({sha256:sha,bytes:bytes})).min(1).max(10)})).min(1).max(50)}).refine(v=>new Set(v.entries.map(e=>e.potentialId)).size===v.entries.length,'duplicate checkpoint');
export const storageSelectionSchema=z.strictObject({ids:z.array(z.string().regex(/^(package|partial|quarantine|catalog|literature):[a-zA-Z0-9_.:-]+$/)).min(1).max(100),inventorySha256:sha}).refine(v=>new Set(v.ids).size===v.ids.length,'duplicate selection');
export interface PotentialStorageItem {id:string;kind:'package'|'partial'|'quarantine'|'catalog'|'literature'|'protected';label:{zh:string;en:string};bytes:number;removable:boolean;reason:{zh:string;en:string}}
export interface PotentialStorageInventory {version:'m6.12-v1';items:PotentialStorageItem[];totalBytes:number;reclaimableBytes:number;inventorySha256:string;scannedAt:string}
export const reproductionPayloadSchema=z.strictObject({version:z.literal('m6.12-v1'),runId:z.string().min(1).max(128),completedAt:z.iso.datetime(),platform:z.string().max(100),quality:z.literal('needs_review'),structure:atomicStructureSchema,plan:atomisticPlanSchema,result:atomisticResultSchema,artifacts:z.array(atomisticArtifactSchema).min(1).max(20),environment:z.strictObject({dependencyLockSha256:sha,sourceRevision:z.string().max(200).nullable(),versions:z.record(z.string(),z.string().max(100)),registeredArtifact:z.boolean()}),taskOptions:z.record(z.string(),z.unknown()).nullable(),bitwiseReproductionGuaranteed:z.literal(false)}).superRefine((v,c)=>{if(v.runId!==v.result.runId||v.plan.id!==v.result.planId||v.structure.id!==v.plan.structureId||v.plan.potentialId!==v.result.potentialId||v.plan.potentialSha256!==v.result.potentialSha256||v.artifacts.some(a=>a.runId!==v.runId||a.projectId!==v.plan.projectId||a.partial))c.addIssue({code:'custom',message:'receipt scope mismatch'});});
export const reproductionReceiptSchema=z.strictObject({payload:reproductionPayloadSchema,payloadSha256:sha});
export const distributionSchemas={CatalogBundle:catalogBundleSchema,OfflineCollection:offlineCollectionSchema,StorageSelection:storageSelectionSchema,ReproductionReceipt:reproductionReceiptSchema};
