<script setup lang="ts">
import {ref,watch,onUnmounted} from 'vue';
import {ElDrawer} from 'element-plus';
import MarkdownContent from './MarkdownContent.vue';
import type {AgentWorkspaceOverview,AgentWorkspacePolicy,BrowserAsset} from '../../../../../packages/contracts/src/agent-workspace.js';
const props=defineProps<{projectId:string;locale:'zh'|'en';active:boolean}>(),emit=defineEmits<{example:[string]}>();
const state=ref<AgentWorkspaceOverview|null>(null),error=ref(''),busy=ref(false),origins=ref(''),url=ref('https://arxiv.org/'),preview=ref<{kind:'image'|'text';content:string}|null>(null),title=ref('');let generation=0;
const t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
async function refresh(keepEdits=false){const id=props.projectId,g=++generation,value=await window.materialsx.getAgentWorkspace(id);if(id!==props.projectId||g!==generation)return;if(keepEdits&&state.value)value.policy=state.value.policy;state.value=value;if(!keepEdits)origins.value=value.policy.origins.join('\n');}
watch(()=>[props.projectId,props.active],()=>{preview.value=null;if(props.active)void perform(refresh);},{immediate:true});
const polling=setInterval(()=>{if(props.active&&!busy.value)void perform(()=>refresh(true));},2000);onUnmounted(()=>{generation++;clearInterval(polling);});
async function perform(action:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';try{await action();}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function save(){if(!state.value)return;const policy:AgentWorkspacePolicy={...state.value.policy,origins:origins.value.split(/\s+/).filter(Boolean).map(s=>new URL(s).origin)};await window.materialsx.saveAgentWorkspacePolicy(props.projectId,policy);await refresh();}
async function open(){await window.materialsx.browserAction(props.projectId,{action:'open',url:url.value});await refresh();}
async function screenshot(){await window.materialsx.browserAction(props.projectId,{action:'screenshot'});await refresh();}
async function closeBrowser(){await window.materialsx.closeResearchBrowser(props.projectId,true);await refresh();}
async function cancelChild(id:string){await window.materialsx.cancelResearchSubtask(props.projectId,id);await refresh();}
async function download(){await window.materialsx.browserAction(props.projectId,{action:'download',url:url.value});await refresh();}
async function showAsset(asset:BrowserAsset){preview.value=await window.materialsx.previewBrowserAsset(props.projectId,asset.id);title.value=t(asset.kind==='screenshot'?'网页截图':asset.kind==='visual-report'?'图像分析报告':'下载文件',asset.kind==='screenshot'?'Page screenshot':asset.kind==='visual-report'?'Image report':'Downloaded file');}
async function childPreview(id:string,path:string){preview.value={kind:'text',content:await window.materialsx.previewResearchSubtask(props.projectId,id,path)};title.value=t('子任务产物','Subtask artifact');}
function example(){emit('example',t('分两个步骤核对材料数据：先将资料核对交给一个只读子任务，说明该分工的价值、输入文件及完成要求；再由主任务综合真实证据和缺失条件。不要新增计算或编造数据。','Plan two steps to review the materials data: delegate an independent read-only source check with a reason, input files and acceptance; then synthesize actual evidence and missing conditions in the parent. Do not compute or fabricate data.'));}
const status=(v:string)=>({prepared:t('准备中','Prepared'),running:t('执行中','Running'),completed:t('已交付','Delivered'),cancelled:t('已取消','Cancelled'),failed:t('失败','Failed'),unknown:t('待核对','Needs reconciliation')})[v]??v;
</script>
<template>
<section class="agent-workspace-panel" data-testid="agent-workspace-panel">
 <header class="heading"><div><h2>{{t('研究分工与浏览器','Research subtasks & browser')}}</h2><p>{{t('核对资料，保存网页和下载文件，查看每一步的真实结果。','Check sources, save pages and downloads, and inspect actual results.')}}</p></div><button class="secondary-button" :disabled="busy" @click="perform(refresh)">{{t('刷新','Refresh')}}</button></header>
 <p v-if="error" class="error" role="alert">{{error}}</p>
 <div v-if="state" class="cards">
  <article class="card"><h3>{{t('只读研究分工','Read-only research delegation')}}</h3><p>{{t('适合独立的资料核对和证据整理。主任务负责计算与综合，最多顺序运行 3 个子任务，共用原截止时间。','For independent source checks and evidence organization. The parent calculates and synthesizes; up to three sequential children share the original deadline.')}}</p><label><input data-testid="subtask-opt-in" type="checkbox" v-model="state.policy.subtasksEnabled"/>{{t('允许此项目使用研究子任务','Allow research subtasks in this project')}}</label><button class="secondary-button" :disabled="busy" @click="perform(save)">{{t('保存权限','Save permissions')}}</button><button class="secondary-button" @click="example">{{t('复制分工示例到对话','Use delegation example in chat')}}</button></article>
  <article class="card"><h3>{{t('研究浏览器','Research browser')}}</h3><p>{{t('在独立窗口手动登录；允许的网站内可浏览、截图和下载。Agent 不填写密码或导出登录凭证。','Log in manually in an isolated window. Browse, capture and download within approved origins. The Agent does not enter passwords or export session credentials.')}}</p><label>{{t('允许的网站，每行一个 HTTPS 入口','Approved HTTPS origins, one per line')}}<textarea data-testid="browser-origins" v-model="origins" placeholder="https://arxiv.org"/></label><label><input type="checkbox" data-testid="browser-share" v-model="state.policy.shareBrowserContent"/>{{t('允许本地 Agent 读取此项目浏览器内容','Allow local Agent access to project browser content')}}</label><button class="secondary-button" :disabled="busy" @click="perform(save)">{{t('保存权限','Save permissions')}}</button><label>{{t('网页或下载地址','Page or download URL')}}<input data-testid="browser-url" v-model="url"/></label><div class="actions"><button data-testid="browser-open" class="primary-button" :disabled="busy" @click="perform(open)">{{t('打开浏览器','Open browser')}}</button><button class="secondary-button" :disabled="busy||!state.browser.open" @click="perform(screenshot)">{{t('保存截图','Save screenshot')}}</button><button class="secondary-button" :disabled="busy||!state.browser.open" @click="perform(download)">{{t('下载文件','Download file')}}</button><button class="secondary-button" :disabled="busy" @click="perform(closeBrowser)">{{t('关闭并清除登录信息','Close & clear login')}}</button></div><p class="muted">{{t('最多下载 8 MiB。PDF 阅读请使用论文库；模型读图需要已加载的视觉模型，截图预览不代表模型已读图。','Downloads are limited to 8 MiB. Read PDFs in the paper library. Image inspection requires a loaded vision model; preview does not imply model perception.')}}</p></article>
 </div>
 <h3>{{t('子任务记录','Subtask history')}}</h3><div class="cards"><article v-for="child in state?.subtasks" :key="child.id" class="card child"><span class="badge">{{status(child.status)}}</span><h3>{{child.input.objective}}</h3><p>{{child.input.reason}}</p><p class="muted path">{{t('主任务','Parent')}} {{child.parentTaskId}} · {{child.parentStepId}}</p><p>{{t('模型请求','Model requests')}} {{child.execution?.requests.length??0}} · {{t('工具回执','Tool receipts')}} {{child.execution?.attempts.length??0}}</p><p v-if="child.error" class="error">{{child.error}}</p><div class="actions"><button v-for="a in child.artifacts" :key="a.path" class="secondary-button" @click="perform(()=>childPreview(child.id,a.path))">{{a.path.split('/').at(-1)}}</button><button v-if="child.status==='running'" class="secondary-button" @click="perform(()=>cancelChild(child.id))">{{t('取消子任务','Cancel subtask')}}</button></div></article></div><p v-if="!state?.subtasks.length" class="muted">{{t('尚无子任务。简单问题会继续直接执行。','No subtasks yet. Simple tasks continue to execute directly.')}}</p>
 <h3>{{t('截图、下载与图像报告','Screenshots, downloads & image reports')}}</h3><div class="cards"><button v-for="asset in state?.assets" :key="asset.id" class="card asset" @click="perform(()=>showAsset(asset))"><span class="badge">{{t(asset.kind==='screenshot'?'截图':asset.kind==='visual-report'?'图像报告':'文件',asset.kind==='screenshot'?'Screenshot':asset.kind==='visual-report'?'Image report':'File')}}</span><p class="path">{{asset.sourceUrl}}</p><p>{{(asset.bytes/1024).toFixed(1)}} KiB · {{asset.mime}}</p><small class="path">SHA256 {{asset.sha256}}</small></button></div>
 <ElDrawer :model-value="!!preview" class="agent-workspace-drawer" :title="title" size="min(1000px,96vw)" @close="preview=null"><img v-if="preview?.kind==='image'" :src="preview.content" :alt="title"/><MarkdownContent v-else-if="preview" :content="preview.content"/></ElDrawer>
</section>
</template>
<style scoped>
.agent-workspace-panel{width:100%;max-width:1120px;min-width:0;margin:20px auto;font-size:13px}.heading{display:flex;justify-content:space-between;gap:18px;flex-wrap:wrap;align-items:center}.heading h2{margin:0;font-size:17px}.heading p,.muted{color:var(--muted);line-height:1.7}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,330px),1fr));gap:16px;margin:20px 0}.card{min-width:0;display:flex;flex-direction:column;align-items:flex-start;gap:14px;border:1px solid var(--line);border-radius:16px;background:var(--panel);color:var(--text);padding:22px;text-align:left;line-height:1.7}.card h3,.card p{margin:0}.card h3{font-size:15px}.card label{display:flex;flex-wrap:wrap;gap:8px;width:100%;font-size:13px}.card label input[type=checkbox]{width:auto;flex:none}.card textarea,.card input:not([type=checkbox]){width:100%;box-sizing:border-box;min-width:0;border:1px solid var(--line);border-radius:10px;color:var(--text);background:var(--panel-2);padding:10px 12px;font:inherit}.card textarea{min-height:90px;resize:vertical}.actions{display:flex;flex-wrap:wrap;gap:8px}.badge{border:1px solid var(--line);border-radius:8px;font-size:12px;padding:4px 9px}.asset{cursor:pointer}.asset:hover{background:var(--panel-2)}.path,.error{overflow-wrap:anywhere}.error{color:var(--danger,#b54a3d)}img{max-width:100%;height:auto}
:global(.agent-workspace-drawer.el-drawer){--el-drawer-bg-color:var(--panel);background:var(--panel);color:var(--text)}:global(.agent-workspace-drawer .el-drawer__header){color:var(--text)}
</style>
