<script setup lang="ts">
import {ref,onMounted} from 'vue';
import type {AgentMatrix,McpConfiguration} from '../../../../../packages/contracts/src/agent-configuration.js';
import {useWorkspaceStore} from '../stores/workspace';
const workspace=useWorkspaceStore(),connection=ref<{status:string;detail:string}|null>(null);
const locale=ref<'zh'|'en'>('zh'),matrix=ref<AgentMatrix|null>(null),config=ref<McpConfiguration|null>(null),busy=ref(false),error=ref('');
const t=(zh:string,en:string)=>locale.value==='zh'?zh:en;
async function refresh(){[matrix.value,config.value]=await Promise.all([window.materialsx.getAgentMatrix(),window.materialsx.getMcpConfiguration()]);}
async function act(fn:()=>Promise<unknown>){busy.value=true;error.value='';try{await fn();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{busy.value=false;}}
async function choose(){const path=await window.materialsx.chooseMcpDirectory();if(path&&config.value)config.value.directory=path;}
async function testConnection(){await workspace.refreshDiagnostics();connection.value=workspace.connections.find(c=>c.id==='mcp-local')??null;}
async function save(){if(!config.value)return;config.value=await window.materialsx.saveMcpConfiguration({...config.value,revision:config.value.revision+1},config.value.revision);await refresh();await testConnection();}
onMounted(()=>void act(refresh));
</script>
<template>
 <section class="agent-connections" data-testid="agent-connections"><header><div><h2>{{t('模型与引擎能力','Model & engine capabilities')}}</h2><p>{{t('查看当前模型支持的工具、协议和输入长度。','View supported tools, protocols and input limits for each model.')}}</p></div><button class="secondary-button" @click="locale=locale==='zh'?'en':'zh'">{{locale==='zh'?'English':'中文'}}</button><button class="secondary-button" :disabled="busy" @click="act(refresh)">{{t('刷新记录','Refresh records')}}</button></header>
 <div class="agent-grid"><article v-for="r in matrix?.rows" :key="r.source+r.engine"><strong>{{r.engine==='pi'?'Pi':'Codex App Server'}} · {{r.source==='local'?t('本地模型','Local model'):t('平台模型','Platform model')}}</strong><p>{{r.modelId||t('尚未检测','Not checked')}} · {{r.protocol}}</p><span>{{({available:t('可用','Available'),limited:t('受限','Limited'),unsupported:t('不支持','Unsupported'),unverified:t('未验证','Unverified')})[r.status]}}</span><p>{{r.reason[locale]}}</p><small>{{t('窗口 / 输出上限','Window / output limit')}}: {{r.contextWindow??t('未知','Unknown')}} / {{r.maxOutputTokens??t('未知','Unknown')}}</small><small>{{r.checks.join(' · ')||t('尚无检测回执','No check receipts')}} · {{r.testedAt||'—'}}</small><small>{{t('图片输入暂未验证。','Image input has not been verified.')}}</small></article></div>
 <article v-if="config" class="mcp-editor"><h2>MOOS MCP</h2><p>{{t('查询 MOOS 中的配方、工艺、性能和原文证据。此连接仅支持读取。','Read recipes, processes, properties and source evidence from MOOS. This connection is read-only.')}}</p><label><input v-model="config.enabled" type="checkbox"/>{{t('启用连接','Enable connection')}}</label><label>{{t('已构建的 MCP 目录','Built MCP directory')}}<input v-model="config.directory" :placeholder="t('包含 dist/src/server.js 的目录','Directory containing dist/src/server.js')"/><button class="secondary-button" :disabled="busy" @click="act(choose)">{{t('选择目录','Choose directory')}}</button></label><label>{{t('本机后端地址','Loopback backend origin')}}<input v-model="config.origin"/></label>
 <div class="mcp-actions"><button class="primary-button" :disabled="busy" @click="act(save)">{{t('保存并测试连接','Save & test connection')}}</button><button class="secondary-button" :disabled="busy" @click="act(testConnection)">{{t('测试已保存的连接','Test saved connection')}}</button></div>
 <p v-if="connection" role="status" :data-state="connection.status">{{connection.status==='ready'?t('连接正常','Connected'):t('连接尚未就绪','Connection not ready')}} · {{connection.detail}}</p>
 <details><summary>{{t('启动与检索说明','Startup & search help')}}</summary><p>{{t('先启动 MOOS 后端，再选择 services/materials-mcp 目录并保存。MaterialsX 会自动启动 MCP，无须另开 MCP 终端。','Start the MOOS backend, select services/materials-mcp and save. MaterialsX starts MCP automatically; no separate MCP terminal is needed.')}}</p><p>{{t('在研究任务对话中直接检索 MOOS。默认仅查询已审核记录；需要候选配方时，请在本次提问中明确允许读取待复核记录。','Search MOOS directly in a research-task conversation. Searches default to reviewed records. To use candidate recipes, explicitly request unreviewed sources in this task.')}}</p><p>{{t('无结果时换用水性、waterborne、aqueous 等关键词；检查后续页。关键词命中不等于配方适用，需读取组分、工艺和证据后判断。','Try waterborne or aqueous and check later pages. A keyword match does not establish recipe suitability; read ingredients, processes and evidence.')}}</p></details></article>
 <details><summary>{{t('基础包版本与许可','Base package versions & licenses')}}</summary><p v-for="p in matrix?.licenses" :key="p.name">{{p.name}} · {{p.license}} · {{p.scope}}</p><p>{{matrix?.platform}} · Pi {{matrix?.versions.pi}} · Codex {{matrix?.versions.codex}} · MCP {{matrix?.versions.mcp}}</p><p>{{t('云模型使用平台账户；运行前确认数据范围和积分预算。','Cloud models use a platform account. Confirm data access and credit budget before each run.')}}</p></details><p v-if="error" role="alert">{{error}}</p></section>
</template>
<style scoped>
.agent-connections{margin-top:22px;max-width:100%;min-width:0;color:var(--text)}header{display:flex;align-items:flex-start;gap:12px;flex-wrap:wrap}header>div{flex:1;min-width:220px}h2{font-size:17px;margin:0 0 12px}p,small,label,details{font-size:12px;line-height:1.7}p,small{color:var(--muted)}.agent-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:18px 0}.agent-grid article,.mcp-editor{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:20px;min-width:0;overflow-wrap:anywhere}.mcp-actions{display:flex;gap:8px;flex-wrap:wrap}[data-state=ready]{color:var(--text)}small{display:block}.mcp-editor{display:grid;gap:12px;margin-bottom:18px}label{display:flex;gap:8px;flex-wrap:wrap;align-items:center}input:not([type=checkbox]){flex:1;min-width:180px;padding:9px;border:1px solid var(--line);border-radius:7px;background:var(--panel-2);color:var(--text)}@media(max-width:800px){.agent-grid{grid-template-columns:1fr}}
</style>
