<script setup lang="ts">
import {ref,onMounted} from 'vue';
import type {AgentMatrix,McpConfiguration} from '../../../../../packages/contracts/src/agent-configuration.js';
const locale=ref<'zh'|'en'>('zh'),matrix=ref<AgentMatrix|null>(null),config=ref<McpConfiguration|null>(null),busy=ref(false),error=ref('');
const t=(zh:string,en:string)=>locale.value==='zh'?zh:en;
async function refresh(){[matrix.value,config.value]=await Promise.all([window.materialsx.getAgentMatrix(),window.materialsx.getMcpConfiguration()]);}
async function act(fn:()=>Promise<unknown>){busy.value=true;error.value='';try{await fn();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{busy.value=false;}}
async function choose(){const path=await window.materialsx.chooseMcpDirectory();if(path&&config.value)config.value.directory=path;}
async function save(){if(!config.value)return;config.value=await window.materialsx.saveMcpConfiguration({...config.value,revision:config.value.revision+1},config.value.revision);await refresh();}
onMounted(()=>void act(refresh));
</script>
<template>
 <section class="agent-connections" data-testid="agent-connections"><header><div><h2>{{t('模型与引擎能力','Model & engine capabilities')}}</h2><p>{{t('按版本、协议和操作系统查看检测结果。协议通过不等于科研任务合格。','Inspect version, protocol and OS-specific evidence. Protocol success is not research qualification.')}}</p></div><button class="secondary-button" @click="locale=locale==='zh'?'en':'zh'">{{locale==='zh'?'English':'中文'}}</button><button class="secondary-button" :disabled="busy" @click="act(refresh)">{{t('刷新记录','Refresh records')}}</button></header>
 <div class="agent-grid"><article v-for="r in matrix?.rows" :key="r.source+r.engine"><strong>{{r.engine==='pi'?'Pi':'Codex App Server'}} · {{r.source==='local'?t('本地模型','Local model'):t('平台模型','Platform model')}}</strong><p>{{r.modelId||t('尚未检测','Not checked')}} · {{r.protocol}}</p><span>{{({available:t('可用','Available'),limited:t('受限','Limited'),unsupported:t('不支持','Unsupported'),unverified:t('未验证','Unverified')})[r.status]}}</span><p>{{r.reason[locale]}}</p><small>{{t('窗口 / 输出上限','Window / output limit')}}: {{r.contextWindow??t('未知','Unknown')}} / {{r.maxOutputTokens??t('未知','Unknown')}}</small><small>{{r.checks.join(' · ')||t('尚无检测回执','No check receipts')}} · {{r.testedAt||'—'}}</small><small>{{t('图片能力未验证；不会自动发送图片或切换云端。','Vision is unverified. Images and cloud fallback are not automatic.')}}</small></article></div>
 <article v-if="config" class="mcp-editor"><h2>MOOS MCP</h2><p>{{t('内置只读连接；仅本机 HTTP。关闭连接不会删除项目、来源或产物。其他远程 MCP 的授权与团队接入按后续阶段开放。','Builtin read-only connection, loopback HTTP only. Disabling does not remove projects or artifacts. Remote MCP and team authorization follow later stages.')}}</p><label><input v-model="config.enabled" type="checkbox"/>{{t('启用连接','Enable connection')}}</label><label>{{t('已构建的 MCP 目录','Built MCP directory')}}<input v-model="config.directory" :placeholder="t('包含 dist/src/server.js 的目录','Directory containing dist/src/server.js')"/><button class="secondary-button" :disabled="busy" @click="act(choose)">{{t('选择目录','Choose directory')}}</button></label><label>{{t('本机后端地址','Loopback backend origin')}}<input v-model="config.origin"/></label><button class="primary-button" :disabled="busy" @click="act(save)">{{t('保存连接设置','Save connection settings')}}</button></article>
 <details><summary>{{t('基础包版本与许可','Base package versions & licenses')}}</summary><p v-for="p in matrix?.licenses" :key="p.name">{{p.name}} · {{p.license}} · {{p.scope}}</p><p>{{matrix?.platform}} · Pi {{matrix?.versions.pi}} · Codex {{matrix?.versions.codex}} · MCP {{matrix?.versions.mcp}}</p><p>{{t('无供应商 Key 配置。更换云模型须使用平台账户并逐轮确认项目外发范围和积分预算。','No supplier Key configuration. Cloud use requires a platform account and per-run approval of export scope and credit budget.')}}</p></details><p v-if="error" role="alert">{{error}}</p></section>
</template>
<style scoped>
.agent-connections{margin-top:22px;max-width:100%;min-width:0;color:var(--text)}header{display:flex;align-items:flex-start;gap:12px;flex-wrap:wrap}header>div{flex:1;min-width:220px}h2{font-size:17px;margin:0 0 12px}p,small,label,details{font-size:12px;line-height:1.7}p,small{color:var(--muted)}.agent-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:18px 0}.agent-grid article,.mcp-editor{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:20px;min-width:0;overflow-wrap:anywhere}small{display:block}.mcp-editor{display:grid;gap:12px;margin-bottom:18px}label{display:flex;gap:8px;flex-wrap:wrap;align-items:center}input:not([type=checkbox]){flex:1;min-width:180px;padding:9px;border:1px solid var(--line);border-radius:7px;background:var(--panel-2);color:var(--text)}@media(max-width:800px){.agent-grid{grid-template-columns:1fr}}
</style>
