<script setup lang="ts">
import type {PotentialCatalog} from '../../../../../packages/contracts/src/potential-hub.js';
import { computed, ref, onMounted, onUnmounted, watch } from "vue";
import type { AtomicStructure } from "../../../../../packages/contracts/src/atomistic.js";
import type { MountedRuntimeStatus } from "../../../../../packages/contracts/src/potential-packages.js";
import { relaxationOptionsSchema } from "../../../../../packages/contracts/src/atomistic-relaxation.js";
import type { ScientificSnapshot as AtomisticSnapshot } from "../../../../../packages/contracts/src/atomistic-dynamics.js";
import type { RelaxationOptions } from "../../../../../packages/contracts/src/atomistic-relaxation.js";
import type { SelectionAssessment } from "../../../../../packages/contracts/src/potential-packages.js";
import type { SelectionRequest } from "../../../../../packages/contracts/src/atomistic-selection.js";
import {mdOptionsSchema,defaultMDOptions,type MDOptions} from "../../../../../packages/contracts/src/atomistic-dynamics.js";
import ScientificValidationPanel from "./ScientificValidationPanel.vue";
import AtomicArtifactCard from "./AtomicArtifactCard.vue";
import { openAtomicView } from "../utils/atomic-viewer";
const props=defineProps<{projectId:string|null;locale:"zh"|"en";catalog:PotentialCatalog|null;localAgent:boolean;conversationId?:string|null}>();
const emit=defineEmits<{"use-example":[prompt:string]}>();
const runtimes=ref<MountedRuntimeStatus[]>([]);const structure=ref<AtomicStructure|null>(null);const runs=ref<AtomisticSnapshot[]>([]);
const potential=ref<string>("chgnet-0.3.0");const busy=ref(false);const error=ref("");
const assessment=ref<SelectionAssessment|null>(null);const imported=ref<AtomicStructure[]>([]);const sample=ref('si-diamond');
const interaction=ref<'short-range'|'long-range-required'|'dispersion-required'|'spin-required'|'field-required'|'delta-required'|'multi-head-required'>('short-range');const charge=ref(0),spinMultiplicity=ref(1),addDisplayBox=ref(true);
const domain=ref<SelectionRequest['domain']>('inorganic-crystals');const mode=ref<SelectionRequest['mode']>('production');
watch([structure,domain,mode,interaction],()=>assessment.value=null);
async function filter(){if(!props.projectId||!structure.value)return;busy.value=true;error.value='';try{assessment.value=await window.materialsx.assessPotentials({projectId:props.projectId,structureId:structure.value.id,domain:domain.value,mode:mode.value,interaction:interaction.value,task:task.value});}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function annotate(){if(!props.projectId||!structure.value)return;busy.value=true;error.value='';try{structure.value=await window.materialsx.annotateAtomicElectronicState({projectId:props.projectId,structureId:structure.value.id,charge:charge.value,spinMultiplicity:spinMultiplicity.value,addDisplayBox:addDisplayBox.value});domain.value='molecules';mode.value='exploratory';potential.value='ani-2x-ensemble';await refresh();}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function importSample(){if(!props.projectId)return;busy.value=true;error.value='';try{structure.value=await window.materialsx.importAtomicSample({projectId:props.projectId,sampleId:sample.value});await refresh();}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function useChat(){if(!structure.value||!props.projectId||!validOptions.value)return;
 try{if(!props.localAgent){if(!props.conversationId)throw Error(t('先选择或创建一个项目对话','Choose or create a project conversation first'));await window.materialsx.setScientificScope({projectId:props.projectId,conversationId:props.conversationId,structureId:structure.value.id,domain:domain.value,mode:mode.value,interaction:interaction.value,permission:task.value,...(task.value==='relaxation'?{options:relaxationOptionsSchema.parse(options.value)}:task.value==='md'?{mdOptions:mdOptionsSchema.parse(mdOptions.value)}:{})});}
 emit('use-example',`@materials-mlip-${task.value} ${examplePrompt.value} ${t('请先按','First assess with')} domain=${domain.value}, mode=${mode.value} ${t('筛选兼容势并引用真实证据，再执行已授权任务。','and cite actual evidence, then execute the authorized task.')}`);
 }catch(e){error.value=String(e);}}
const mdOptions=ref<MDOptions>({...defaultMDOptions});
watch(()=>mdOptions.value.ensemble,e=>mdOptions.value.frictionInverseFs=e==='nvt'?.01:null);
const task=ref<'singlepoint'|'relaxation'|'md'>('singlepoint');
const options=ref<RelaxationOptions>({optimizer:'FIRE',cellMode:'fixed',cellConstraint:'none',externalPressureGPa:null,maxSteps:100,fmaxEvPerAngstrom:.05});
watch(()=>options.value.cellMode,mode=>{options.value.cellConstraint=mode==='fixed'?'none':'hydrostatic';options.value.externalPressureGPa=null;});
watch(task,()=>assessment.value=null);
const validOptions=computed(()=>task.value==='md'?mdOptionsSchema.safeParse(mdOptions.value).success:task.value!=='relaxation'||relaxationOptionsSchema.safeParse(options.value).success);
const reasonLabels:Record<string,string>={COMPOSITION_ATOM_LIMIT:'组合势仅限128原子',COMPOSITION_CELL_LIMIT:'组合势晶胞尺寸或密度超出验收范围',COMPOSITION_MINIMUM_DISTANCE:'组合势要求周期原子间距至少2.3 Å',DISPERSION_CORRECTION_REQUIRED:'需要已验收的显式色散修正',ADVANCED_PHYSICS_NOT_VERIFIED:'此高级物理路线尚未验证',NEP_NATIVE_ATOM_LIMIT:'超过硅 NEP 的256原子范围',NEP_NATIVE_CELL_LIMIT:'NEP 晶胞尺寸或密度超出验证范围',FIXED_CELL_ONLY:'仅支持固定晶胞',ELECTRONIC_STATE_REQUIRED:'需明确总电荷和自旋',NEUTRAL_SINGLET_REQUIRED:'ANI-2x 仅中性单重态',ELECTRON_COUNT_PARITY_MISMATCH:'电子数与单重态不兼容',MOLECULE_REQUIRES_ISOLATED_BOUNDARY:'分子接口仅非周期边界',LONG_RANGE_PHYSICS_UNAVAILABLE:'当前接口不提供显式长程静电',EXPLICIT_DISPLAY_BOX_REQUIRED:'优化需明确非周期显示盒',MOLECULAR_ATOM_COUNT_LIMIT:'分子接口限 128 原子',POTENTIAL_DISABLED:'模型已禁用',VERIFIED_RUNTIME_UNAVAILABLE:'没有已核验的本机运行时',WEIGHT_IDENTITY_UNVERIFIED:'权重身份未核验',LICENSE_REVIEW_REQUIRED:'许可尚未准入',HEAD_NOT_RESOLVED:'模型 head 未明确',STRUCTURE_HAS_BLOCKING_ISSUES:'结构存在阻断项',BULK_PBC_REQUIRED:'需要三维周期晶体',DOMAIN_OUTSIDE_POLICY:'超出此适配器的材料域',ELECTRONIC_STATE_NOT_SUPPORTED:'不支持显式电荷或自旋输入',ELEMENT_NOT_SUPPORTED:'权重不覆盖所需元素',REQUIRED_OUTPUT_UNKNOWN:'能量/力/应力能力不完整',MD_EXECUTOR_UNAVAILABLE:'MD 执行器待 M6.5',DOMAIN_NOT_VALIDATED:'缺少独立 DFT 领域验证',ATOM_COUNT_LIMIT:'超过原子数预算',MEMORY_PREFLIGHT_FAILED:'内存预算低于模型加载观测值及余量',STEP_LIMIT:'超过优化步数上限',CONSERVATIVE_FORCES_REQUIRED:'未确认保守力'};
const domainLabels:Record<string,string>={'inorganic-crystals':'无机晶体',molecules:'分子',polymers:'高分子',surfaces:'表面',interfaces:'界面',unknown:'未知'};
const t=(zh:string,en:string)=>props.locale==="zh"?zh:en;
const modelName=(id:string)=>props.catalog?.entries.find(e=>e.id===id)?.name??id;
let timer:ReturnType<typeof setInterval>|undefined;let generation=0;
async function refresh(){const current=props.projectId;const version=generation;runtimes.value=await window.materialsx.getAtomisticRuntime();
  try{const items=current?await window.materialsx.listAtomisticRuns(current):[];if(current===props.projectId&&version===generation){runs.value=items;imported.value=current?await window.materialsx.listAtomicStructures(current):[];}}catch(e){error.value=String(e);}}
async function choose(){if(!props.projectId)return;busy.value=true;error.value="";const current=props.projectId;
  try{const value=await window.materialsx.chooseAtomicStructure(current);if(current===props.projectId)structure.value=value;}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function start(){if(!props.projectId||!structure.value)return;busy.value=true;error.value="";
  try{const a=await window.materialsx.assessPotentials({projectId:props.projectId,structureId:structure.value.id,domain:domain.value,mode:mode.value,interaction:interaction.value,task:task.value});
    assessment.value=a;const candidate=a.selection.candidates.find(c=>c.potentialId===potential.value);if(!candidate)throw Error(a.selection.exclusions.find(c=>c.potentialId===potential.value)?.reasonCodes.join(', ')??'POTENTIAL_EXCLUDED');
    await window.materialsx.startSelectedPotential({projectId:props.projectId,proposal:{assessmentId:a.id,selectedPotentialId:potential.value,evidenceIds:candidate.evidenceIds},...(task.value==='relaxation'?{options:relaxationOptionsSchema.parse(options.value)}:task.value==='md'?{mdOptions:mdOptionsSchema.parse(mdOptions.value)}:{})});await refresh();}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function useOutput(run:AtomisticSnapshot){if(!props.projectId)return;const projectId=props.projectId;busy.value=true;try{const value=await window.materialsx.useAtomicOutput({projectId,runId:run.job.id});if(projectId===props.projectId){structure.value=value;task.value=run.md?'md':'relaxation';}}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function cancel(run:AtomisticSnapshot){try{await window.materialsx.cancelAtomisticRun(run.job.projectId,run.job.id);await refresh();}catch(e){error.value=String(e);}}
async function reveal(run:AtomisticSnapshot){try{await window.materialsx.revealArtifact(run.outputDirectory);}catch(e){error.value=String(e);}}
const examplePrompt=computed(()=>{
 if(!structure.value)return '';
 const goal=task.value==='md'?t(`执行固定晶胞 ${mdOptions.value.ensemble.toUpperCase()} 短程 MD，参数 ${JSON.stringify(mdOptions.value)}；报告真实步数、时间、轨迹和对应数值诊断，不声称长期稳定性`,`run fixed-cell ${mdOptions.value.ensemble.toUpperCase()} short MD with options ${JSON.stringify(mdOptions.value)}; report real steps, time, trajectory and ensemble diagnostics without long-term stability claims`):task.value==='singlepoint'?t('运行单点计算','run a single point'):t(`执行 FIRE 结构优化：${options.value.cellMode==='fixed'?'固定晶胞':`变胞，${options.value.cellConstraint==='hydrostatic'?'仅各向同性体积变化':'体积与形状'}，外压 ${options.value.externalPressureGPa} GPa（正值压缩）`}，最多 ${options.value.maxSteps} 步，fmax ${options.value.fmaxEvPerAngstrom} eV/Å。明确报告实际收敛或达到步数上限未收敛`, `run FIRE relaxation with ${options.value.cellMode} cell, constraint ${options.value.cellConstraint}, pressure ${options.value.externalPressureGPa??'not applicable'} GPa, maximum ${options.value.maxSteps} steps and fmax ${options.value.fmaxEvPerAngstrom} eV/Å. Report actual convergence or a nonconverged step limit`);
 return t(`请使用受控本地科学工具，用 ${potential.value} 对本项目已导入结构 ${structure.value.id} ${goal}，并查询任务直到终态，读取真实结果与文件；保留需科学复核标记。`, `Use local science tools with ${potential.value} on imported structure ${structure.value.id} to ${goal}. Query until terminal, read the real results and files, and retain needs_review.`);
});
const terminal=(s:string)=>["completed","failed","cancelled","interrupted"].includes(s);
const state=(s:string)=>t(({queued:"排队中",validating:"检查输入",loading_model:"加载模型",running:"计算中",cancelling:"正在取消",completed:"已完成 · 需科学复核",failed:"失败",cancelled:"已取消",interrupted:"已中断"} as Record<string,string>)[s]??s,s);
watch(()=>props.projectId,()=>{generation++;structure.value=null;runs.value=[];error.value="";void refresh();});
onMounted(async()=>{await refresh();timer=setInterval(()=>{if(runs.value.some(r=>!terminal(r.job.status)))void refresh();},1000);});
onUnmounted(()=>{if(timer)clearInterval(timer);generation++;});
</script>
<template>
 <section class="atomistic-run-panel" data-testid="atomistic-run-panel" :data-structure-id="structure?.id??''">
  <div class="heading"><div><h3>{{t('结构计算','Structure calculations')}}</h3></div><button class="secondary-button" @click="refresh">{{t('刷新任务','Refresh jobs')}}</button></div>
  <p class="hint">{{t('导入晶体或分子，选择模型与任务，查看计算结果和三维结构。本地计算不消耗云端积分。','Import a crystal or molecule, choose a model and task, then view results and the 3D structure. Local calculations use no cloud credits.')}}</p>
  <details class="supported-models"><summary>{{t('支持哪些结构与模型？','Supported structures & models')}}</summary><p class="hint">{{t('晶体按各模型的元素和结构范围匹配。MACE + D3 与 NEP 当前仅支持纯硅周期结构；ANI-2x 仅支持中性单重态的孤立分子，可做单点计算与 FIRE 优化。模型适用范围和独立验证状态会在计算前检查。','Crystal support depends on each model’s elements and structural scope. MACE + D3 and NEP currently support periodic pure silicon only. ANI-2x supports neutral singlet isolated molecules for single-point calculations and FIRE optimization. Model scope and independent validation are checked before running.')}}</p></details>
  <ScientificValidationPanel :project-id="projectId" :locale="locale" @changed="refresh"/>
  <details class="supported-models"><summary>{{t('本地计算环境','Local compute environments')}} · {{runtimes.filter(r=>r.installed).length}} {{t('个已就绪','ready')}}</summary><div class="runtime-list"><span v-for="r in runtimes" :key="r.potentialId">{{modelName(r.potentialId)}} · {{r.installed?t('已就绪','Ready'):t('未安装','Not installed')}}</span></div></details>
  <p v-if="runtimes.length && !runtimes.some(r=>r.installed)" class="hint">{{t('开发安装：npm run m6:runtime:dev。可移植构建：npm run m6:runtime（需至少 8 GiB 空间）。','Development: npm run m6:runtime:dev. Portable build: npm run m6:runtime (requires 8 GiB free disk).')}}</p>
  <div class="actions"><label>{{t('内置样本','Bundled sample')}} <select v-model="sample" data-testid="science-sample"><option v-for="id in ['si-diamond','nacl-rocksalt','si-triclinic','water','ethanol-neutral']" :key="id">{{id}}</option></select></label><button class="secondary-button" :disabled="!projectId||busy" @click="importSample">{{t('导入样本','Import sample')}}</button>
  <label v-if="imported.length">{{t('已有结构','Imported structures')}} <select :value="structure?.id??''" @change="structure=imported.find(s=>s.id===($event.target as HTMLSelectElement).value)??null"><option value="">—</option><option v-for="s in imported" :key="s.id" :value="s.id">{{s.id.slice(0,8)}} · {{s.atoms.length}} atoms</option></select></label></div>
  <div class="actions"><label>{{t('物理需求','Interaction requirement')}} <select v-model="interaction" data-testid="science-interaction"><option value="short-range">{{t('短程探索','Short-range screening')}}</option><option value="dispersion-required">{{t('显式 D3 色散（纯硅探索）','Explicit D3 dispersion (Si screening)')}}</option><option value="spin-required">{{t('自旋物理（尚未验证）','Spin physics (unverified)')}}</option><option value="field-required">{{t('外场（尚未验证）','External fields (unverified)')}}</option><option value="delta-required">{{t('Δ-learning（尚未验证）','Delta learning (unverified)')}}</option><option value="multi-head-required">{{t('多头任务（尚未验证）','Multi-head task (unverified)')}}</option><option value="long-range-required">{{t('必须显式长程静电','Explicit long-range electrostatics required')}}</option></select></label><label>{{t('材料类型','Material type')}} <select v-model="domain" data-testid="science-domain"><option v-for="d in ['inorganic-crystals','molecules','polymers','surfaces','interfaces','unknown']" :key="d" :value="d">{{locale==='zh'?domainLabels[d]:d}}</option></select></label><label>{{t('用途','Purpose')}} <select v-model="mode" data-testid="science-mode"><option value="production">{{t('正式计算（需独立验证）','Production (independent validation required)')}}</option><option value="exploratory">{{t('探索试算（需科学复核）','Exploratory (needs review)')}}</option></select></label><button class="secondary-button" :disabled="!structure||busy" @click="filter">{{t('查找适用模型','Find eligible models')}}</button></div>
  <details v-if="assessment" open data-testid="science-assessment"><summary>{{t('选势结果','Selection assessment')}} · {{assessment.id}}</summary><p>{{assessment.rankingBasis}}</p><p v-if="!assessment.selection.candidates.length">{{t('没有可执行候选；请查看排除原因。','No eligible candidate; see exclusions.')}}</p><article v-for="c in assessment.selection.candidates" :key="c.potentialId"><strong>{{c.potentialId}}</strong> · {{c.reason[locale]}}<p>{{c.evidenceIds.join(', ')}}</p><button class="secondary-button" @click="potential=c.potentialId as typeof potential">{{t('选择此势','Choose potential')}}</button></article><div class="selection-exclusions"><article v-for="c in assessment.selection.exclusions" :key="c.potentialId"><strong>{{c.potentialId}}</strong><p v-for="code in c.reasonCodes" :key="code">{{locale==='zh'?reasonLabels[code]:''}} <code>{{code}}</code></p></article></div><p v-for="l in assessment.selection.limitations" :key="l.en">{{l[locale]}}</p><p>{{assessment.selection.validationPlan}}</p></details>
  <div class="actions"><label>{{t('计算任务','Task')}} <select v-model="task" data-testid="atomic-task"><option value="singlepoint">{{t('单点计算','Single point')}}</option><option value="md">{{t('短程分子动力学 · NVE/NVT','Short molecular dynamics · NVE/NVT')}}</option><option value="relaxation">{{t('结构优化 · FIRE','Structure relaxation · FIRE')}}</option></select></label><button class="secondary-button" :disabled="!projectId||busy||!runtimes.some(r=>r.installed)" @click="choose">{{busy?t('处理中…','Working…'):t('导入结构文件','Import structure')}}</button>
   <select v-model="potential" :aria-label="t('计算势函数','Calculation potential')"><option v-for="r in runtimes" :key="r.potentialId" :value="r.potentialId" :disabled="!r.installed">{{modelName(r.potentialId)}}</option></select>
   <button class="primary-button" data-testid="atomic-start" :disabled="!structure||busy||!validOptions||structure.issues.some(i=>i.severity==='blocking')||(!structure.pbc.every(Boolean)&&potential!=='ani-2x-ensemble')||!runtimes.some(r=>r.potentialId===potential&&r.installed)" @click="start">{{task==='md'?t('运行短程 MD','Run short MD'):task==='relaxation'?t('运行结构优化','Run relaxation'):t('运行单点计算','Run single point')}}</button></div>
  <div v-if="task==='relaxation'" class="relaxation-options" data-testid="relaxation-options">
   <label>{{t('晶胞','Cell')}} <select v-model="options.cellMode" data-testid="relax-cell"><option value="fixed">{{t('固定晶胞（默认）','Fixed cell (default)')}}</option><option value="variable">{{t('优化晶胞（显式启用）','Optimize cell (explicit)')}}</option></select></label>
   <label>{{t('最大步数','Maximum steps')}} <input v-model.number="options.maxSteps" data-testid="relax-steps" type="number" min="1" max="500"></label>
   <label>fmax (eV/Å) <input v-model.number="options.fmaxEvPerAngstrom" data-testid="relax-fmax" type="number" min="0.001" max="0.2" step="0.001"></label>
   <template v-if="options.cellMode==='variable'"><label>{{t('应变约束','Strain constraint')}} <select v-model="options.cellConstraint" data-testid="relax-constraint"><option value="hydrostatic">{{t('仅各向同性体积变化','Isotropic volume only')}}</option><option value="full">{{t('体积与形状','Volume and shape')}}</option></select></label><label>{{t('外压（GPa，正值压缩）','Pressure (GPa, positive compression)')}} <input v-model.number="options.externalPressureGPa" data-testid="relax-pressure" type="number" min="-10" max="10" step="0.1"></label></template>
   <p class="hint">{{t('固定晶胞以最大原子力向量模长判定；变胞同时要求晶胞广义力达标。单任务最多 600 秒；超时不冒充收敛。','Fixed-cell convergence uses maximum atomic force norm; variable cell also requires cell filter forces. A job is limited to 600 seconds; a timeout is not convergence.')}}</p>
  </div>
  <div v-if="task==='md'" class="relaxation-options" data-testid="md-options">
   <label>{{t('系综','Ensemble')}} <select v-model="mdOptions.ensemble" data-testid="md-ensemble"><option value="nve">NVE · Velocity Verlet</option><option value="nvt">NVT · Langevin</option></select></label>
   <label>{{t('步数','Steps')}} <input v-model.number="mdOptions.steps" data-testid="md-steps" type="number" min="1" max="2000"></label>
   <label>Δt (fs) <input v-model.number="mdOptions.timestepFs" data-testid="md-timestep" type="number" min="0.01" max="1" step="0.01"></label>
   <label>{{t('温度','Temperature')}} (K) <input v-model.number="mdOptions.temperatureK" data-testid="md-temperature" type="number" min="1" max="1000"></label>
   <label>{{t('采样间隔（步）','Sample interval (steps)')}} <input v-model.number="mdOptions.sampleEvery" data-testid="md-sample" type="number" min="1" :max="mdOptions.steps"></label>
   <label>{{t('随机种子','Random seed')}} <input v-model.number="mdOptions.seed" data-testid="md-seed" type="number" min="0" max="4294967295"></label>
   <label v-if="mdOptions.ensemble==='nvt'">{{t('摩擦系数','Friction')}} (fs⁻¹) <input v-model.number="mdOptions.frictionInverseFs" data-testid="md-friction" type="number" min="0.001" max="0.1" step="0.001"></label>
   <p class="hint">{{t('固定晶胞、CPU，默认 200 步 × 0.5 fs = 100 fs，每 10 步采样。NVE 温度为初速度初始化；NVT 为恒温目标，摩擦系数必须明确。最长 2000 步 / 600 秒；含 H/He 时步长 ≤0.25 fs。默认短程不足以通过 1000 fs NVE 漂移诊断。','Fixed cell, CPU; default 200 × 0.5 fs = 100 fs, sample every 10 steps. NVE temperature initializes velocities; NVT temperature is the thermostat target with explicit friction. Maximum 2000 steps / 600 seconds; H/He requires ≤0.25 fs. Default duration is insufficient for the 1000 fs NVE drift diagnostic.')}}</p>
  </div>
  <p v-if="!projectId" class="hint">{{t('先在左侧选择或创建本地项目。','Choose or create a local project first.')}}</p>
  <div v-if="structure" class="structure-summary"><strong>{{structure.atoms.length}} {{t('个原子','atoms')}} · {{[...new Set(structure.atoms.map(a=>a.element))].join(', ')}}</strong><span>PBC {{structure.pbc.map(v=>v?'T':'F').join(' ')}} · Å</span>
   <button class="secondary-button" @click="openAtomicView({kind:'import',projectId:projectId!,structureId:structure.id})">{{t('查看结构 3D','View structure in 3D')}}</button>
   <p v-for="(issue,i) in structure.issues.filter(i=>i.severity==='blocking')" :key="i" class="error">{{issue.code}}：{{issue.detail}}</p>
   <details v-if="structure.issues.some(i=>i.severity==='warning')"><summary>{{t('解析提示','Parser notes')}} · {{structure.issues.filter(i=>i.severity==='warning').length}}</summary><p v-for="(issue,i) in structure.issues.filter(i=>i.severity==='warning')" :key="i">{{issue.detail}}</p></details>
   <p v-if="structure.pbc.some(Boolean)&&!structure.pbc.every(Boolean)" class="hint">{{t('结构已读取；当前核心计算要求三维周期边界。','Structure imported; the current core calculators require bulk periodic boundaries.')}}</p>
   <div v-if="!structure.pbc.some(Boolean)" class="actions molecular-state" data-testid="molecular-state">
    <p class="hint">{{t('孤立分子：电荷与自旋必须由输入文件或你明确声明。ANI-2x 仅支持 charge=0、multiplicity=1；无显式长程静电。','Isolated molecule: explicitly declare charge and spin. ANI-2x supports charge=0 and multiplicity=1 only, without explicit long-range electrostatics.')}} {{structure.charge??'—'}} / {{structure.spinMultiplicity??'—'}}</p>
    <label>{{t('总电荷','Total charge')}} <input v-model.number="charge" data-testid="molecular-charge" type="number" min="-20" max="20"></label>
    <label>{{t('自旋多重度','Spin multiplicity')}} <input v-model.number="spinMultiplicity" data-testid="molecular-spin" type="number" min="1" max="21"></label>
    <label><input v-model="addDisplayBox" type="checkbox">{{t('无盒时添加非周期显示盒（优化所需；不是物理体积）','Add a nonperiodic display box if absent (needed for optimization; not physical volume)')}}</label>
    <button class="secondary-button" data-testid="molecular-annotate" :disabled="busy" @click="annotate">{{t('确认并创建带电子态的新结构','Confirm and create annotated structure')}}</button>
   </div>
   <button class="secondary-button" data-testid="science-use-chat" :disabled="busy||!validOptions" @click="useChat">{{localAgent?t('填入本地模型请求','Use in local model chat'):t('授权范围并填入平台请求','Set scope and use in platform chat')}}</button>
  </div>
  <p v-if="error" class="error" role="alert">{{error}}</p>
  <article v-for="run in runs" :key="run.job.id" class="run-card"><div class="heading"><strong>{{run.plan.potentialId}} · {{state(run.job.status)}}</strong><button v-if="!terminal(run.job.status)" class="secondary-button" @click="cancel(run)">{{t('取消','Cancel')}}</button><button v-else class="secondary-button" @click="reveal(run)">{{t('查看输出文件','Reveal outputs')}}</button></div>
   <small>{{run.plan.task.kind}} <span v-if="run.relaxation">· {{run.relaxation.options.cellMode}} / {{run.relaxation.options.cellConstraint}} · fmax {{run.relaxation.options.fmaxEvPerAngstrom}} eV/Å</span> · {{run.job.id}}</small>
   <p v-if="run.md?.progress">MD {{run.md.options.ensemble.toUpperCase()}} · {{run.md.progress.step}} / {{run.md.options.steps}} · {{run.md.progress.timeFs}} fs · {{run.md.progress.temperatureK.toFixed(2)}} K</p>
   <p v-if="run.md?.summary" class="hint">{{t('已完成请求步数 · 短程轨迹需科学复核','Requested steps completed · Short trajectory needs review')}} · {{run.md.summary.frameCount}} {{t('帧','frames')}}</p>
   <button v-if="run.md?.trajectoryArtifactId" class="secondary-button" :disabled="busy" @click="useOutput(run)">{{t('用最后有效帧新建轨迹段（不续算）','Use last valid frame for a new segment (no resume)')}}</button>
   <p v-if="run.relaxation?.progress">{{t('优化记录','Optimization progress')}}: {{run.relaxation.progress.step}} / {{run.relaxation.options.maxSteps}} · |F|max {{run.relaxation.progress.maxForceEvPerAngstrom.toPrecision(5)}} eV/Å · {{t('晶胞广义力','Filter force')}} {{run.relaxation.progress.maxFilterForceEvPerAngstrom.toPrecision(5)}} eV/Å</p>
   <p v-if="run.relaxation?.summary" class="hint">{{run.relaxation.summary.stopReason==='converged'?t('已收敛 · 需科学复核','Converged · Needs scientific review'):t('达到步数上限 · 未收敛 · 需科学复核','Step limit · Not converged · Needs scientific review')}}</p>
   <button v-if="run.relaxation&&(run.relaxation.summary||run.relaxation.partialArtifactId)" class="secondary-button" :disabled="busy" @click="useOutput(run)">{{run.relaxation.summary?t('用最终结构新建任务','Use final structure for a new task'):t('用最后有效结构新建任务','Use last valid geometry for a new task')}}</button><p v-if="run.result">{{t('总能量','Total energy')}} {{run.result.energyEv.toFixed(8)}} eV · {{run.result.atomCount}} {{t('原子；力和应力见结果 JSON','atoms; forces and stress in result JSON')}}</p><p v-if="run.result" class="hint">{{t('需科学复核：尚无独立 DFT 参考标签。','Needs scientific review: no independent DFT reference labels.')}}</p><p v-if="run.job.error" class="error">{{run.job.error}}</p>
   <AtomicArtifactCard :run="run" :locale="locale" />
  </article>
 </section>
</template>
<style scoped>
.supported-models{margin:12px 0;font-size:12px;color:var(--muted);line-height:1.7}.supported-models summary{cursor:pointer}
.atomistic-run-panel {border:1px solid var(--line);border-radius:14px;padding:20px;background:var(--panel);margin:0 0 22px;color:var(--text);}
.heading,.actions {display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.actions{justify-content:flex-start;margin:16px 0}.actions>label{min-width:0;max-width:100%}.heading h3{margin:4px 0}.hint,small{color:var(--muted);font-size:13px;line-height:1.6}.runtime-list{display:flex;gap:16px;flex-wrap:wrap;font-size:12px;color:var(--muted)}select{min-width:0;max-width:100%;padding:9px;border:1px solid var(--line);border-radius:8px;background:var(--panel);color:var(--text)}.structure-summary,.run-card{border-top:1px solid var(--line);padding:14px 0}.structure-summary>span{margin-left:12px;font-size:12px;color:var(--muted)}.error{color:var(--danger,#d05252);overflow-wrap:anywhere;font-size:13px}.run-card small{display:block;margin:8px 0}
.relaxation-options{display:flex;gap:14px;flex-wrap:wrap;font-size:13px;margin-bottom:18px}.relaxation-options label{display:flex;gap:6px;align-items:center}.relaxation-options input{width:100px;padding:8px;border:1px solid var(--line);border-radius:8px;background:var(--panel);color:var(--text)}.relaxation-options .hint{width:100%;margin:0}
details{font-size:13px;color:var(--muted);margin:12px 0;line-height:1.6}details p{font-size:13px;overflow-wrap:anywhere}summary{cursor:pointer}.structure-summary>.secondary-button{margin-top:12px}
.selection-exclusions{max-height:360px;overflow:auto;border:1px solid var(--line);border-radius:8px;padding:12px;margin:14px 0}.selection-exclusions article{border-bottom:1px solid var(--line);padding:10px 0}.selection-exclusions p{margin:4px 0}.selection-exclusions code{font-size:11px;color:var(--muted)}
</style>
