<script setup lang="ts">
import {computed,ref,shallowRef,watch,onMounted,onUnmounted} from 'vue';
import {ElDrawer} from 'element-plus';
import type {z} from 'zod';
import {trajectoryPayloadSchema,mdFrameSchema,mdComparisonSchema,trajectorySceneSchema} from '../../../../../packages/contracts/src/atomistic-dynamics.js';
import {atomicFrameEventSchema} from '../../../../../packages/contracts/src/atomic-viewer.js';
import {atomicTrajectoryRequest,closeAtomicTrajectory} from '../utils/atomic-viewer';
import {distance,angle} from '../../../../../packages/atomistic/src/viewer-geometry.js';
import {appearanceTheme} from '../utils/appearance';
const props=defineProps<{locale:'zh'|'en';projectId:string|null}>();const t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
const visible=computed({get:()=>!!atomicTrajectoryRequest.value,set:(v:boolean)=>{if(!v)closeAtomicTrajectory();}});
const payload=shallowRef<z.infer<typeof trajectoryPayloadSchema>|null>(null),current=shallowRef<z.infer<typeof mdFrameSchema>|null>(null),comparison=shallowRef<z.infer<typeof mdComparisonSchema>|null>(null);
const iframe=ref<HTMLIFrameElement|null>(null),ready=ref(false),rendered=ref(false),loading=ref(false),playing=ref(false),index=ref(0),speed=ref(5),style=ref<'ball-stick'|'sphere'|'stick'>('ball-stick'),showCell=ref(true),showBonds=ref(true),error=ref(''),notice=ref(''),exporting=ref(false),frameKey=ref(0),otherId=ref(''),others=ref<Array<{id:string;potentialId:string}>>([]),metric=ref<'temperature'|'energy'>('temperature');
const frameUrl=new URL('atomic-viewer.html',window.location.href).href;
const selected=ref<number[]>([]),coordinatePage=ref(0),limited=ref(false);
const cache=new Map<number,z.infer<typeof mdFrameSchema>>();let pngRequest:{projectId:string;runId:string;frame:number}|null=null;let generation=0,frameGeneration=0,playTimer:ReturnType<typeof setTimeout>|undefined,renderTimer:ReturnType<typeof setTimeout>|undefined;
function stop(){playing.value=false;if(playTimer)clearTimeout(playTimer);playTimer=undefined;}
function dispose(){stop();pngRequest=null;generation++;frameGeneration++;cache.clear();if(renderTimer)clearTimeout(renderTimer);iframe.value?.contentWindow?.postMessage({type:'dispose'},'*');ready.value=false;rendered.value=false;}
function draw(){if(!ready.value||!current.value||!payload.value)return;rendered.value=false;iframe.value?.contentWindow?.postMessage(trajectorySceneSchema.parse({type:'trajectory',projectId:payload.value.projectId,structure:payload.value.structure,frame:current.value,style:style.value,showCell:showCell.value,showBonds:showBonds.value,theme:appearanceTheme.value}),'*');if(renderTimer)clearTimeout(renderTimer);renderTimer=setTimeout(()=>{stop();error.value=t('3D 渲染超时；可以导出真实轨迹。','3D render timed out; the real trajectory remains exportable.');},8000);}
async function loadFrame(n:number){const q=atomicTrajectoryRequest.value,p=payload.value;if(!q||!p)return;const g=generation,f=++frameGeneration;loading.value=true;error.value='';
 try{let v=cache.get(n);if(!v){v=mdFrameSchema.parse(await window.materialsx.readAtomicTrajectoryFrame({...q,frame:n}));if(g!==generation||f!==frameGeneration)return;cache.set(n,v);while(cache.size>5)cache.delete(cache.keys().next().value!);}if(g!==generation||f!==frameGeneration)return;current.value=v;index.value=n;draw();}
 catch(e){if(g===generation&&f===frameGeneration){stop();error.value=String(e);}}finally{if(g===generation&&f===frameGeneration)loading.value=false;}}
async function load(){dispose();const g=generation,q=atomicTrajectoryRequest.value;payload.value=null;current.value=null;comparison.value=null;otherId.value='';others.value=[];notice.value='';error.value='';index.value=0;coordinatePage.value=0;selected.value=[];exporting.value=false;limited.value=false;frameKey.value++;if(!q)return;loading.value=true;
 try{const p=trajectoryPayloadSchema.parse(await window.materialsx.readAtomicTrajectory(q));if(g!==generation)return;payload.value=p;const boot=generation;renderTimer=setTimeout(()=>{if(boot===generation&&!ready.value)error.value=t('3D 不可用，保留坐标表与导出。','3D unavailable; coordinates and export remain accessible.');},8000);const jobs=await window.materialsx.listAtomisticRuns(q.projectId);if(g!==generation)return;others.value=jobs.filter(r=>r.job.id!==q.runId&&r.job.status==='completed'&&r.md?.summary&&r.plan.structureSha256===jobs.find(r=>r.job.id===q.runId)?.plan.structureSha256&&r.plan.potentialId!==jobs.find(r=>r.job.id===q.runId)?.plan.potentialId&&JSON.stringify(r.md.options)===JSON.stringify(p.index.options)).map(r=>({id:r.job.id,potentialId:r.plan.potentialId}));await loadFrame(0);}
 catch(e){if(g===generation)error.value=String(e);}finally{if(g===generation)loading.value=false;}}
function schedule(){if(!playing.value||!rendered.value||loading.value||!payload.value)return;if(playTimer)clearTimeout(playTimer);if(index.value>=payload.value.index.entries.length-1){stop();return;}playTimer=setTimeout(()=>{playTimer=undefined;void loadFrame(index.value+1);},1000/speed.value);}
function togglePlay(){if(playing.value){stop();return;}playing.value=true;if(index.value>= (payload.value?.index.entries.length??1)-1)void loadFrame(0);else schedule();}
function scrub(event:Event){stop();void loadFrame(Number((event.target as HTMLInputElement).value));}
async function message(event:MessageEvent){if(event.source!==iframe.value?.contentWindow||!(event.origin===window.location.origin||(location.protocol==='file:'&&event.origin==='null')))return;const parsed=atomicFrameEventSchema.safeParse(event.data);if(!parsed.success)return;const v=parsed.data;if(v.type==='ready'){if(renderTimer)clearTimeout(renderTimer);ready.value=true;draw();}else if(v.type==='rendered'){if(renderTimer)clearTimeout(renderTimer);rendered.value=true;limited.value=v.limited;schedule();}else if(v.type==='selected'){selected.value=v.indices;}else if(v.type==='png'&&pngRequest){const q=pngRequest,g=generation;pngRequest=null;try{const saved=await window.materialsx.exportAtomicTrajectoryPng({request:q,png:v.png});if(g===generation)notice.value=saved?t('已导出选帧 PNG。','Selected-frame PNG exported.'):t('已取消导出','Export cancelled');}catch(e){if(g===generation)error.value=String(e);}finally{if(g===generation)exporting.value=false;}}else if(v.type==='error'){stop();error.value=v.message;exporting.value=false;pngRequest=null;}}
function exportPNG(){const q=atomicTrajectoryRequest.value;if(!q||!current.value||!rendered.value)return;stop();pngRequest={...q,frame:index.value};exporting.value=true;iframe.value?.contentWindow?.postMessage({type:'png'},'*');}
function retry(){stop();ready.value=false;rendered.value=false;error.value='';frameKey.value++;const g=generation;if(renderTimer)clearTimeout(renderTimer);renderTimer=setTimeout(()=>{if(g===generation&&!ready.value)error.value=t('3D 不可用，保留坐标表与导出。','3D unavailable; coordinates and export remain accessible.');},8000);}
const coordinateRows=computed(()=>payload.value?.structure.atoms.slice(coordinatePage.value*50,(coordinatePage.value+1)*50).map((a,n)=>({id:a.id,element:a.element,n:coordinatePage.value*50+n,position:current.value?.positionsAngstrom[coordinatePage.value*50+n],velocity:current.value?.velocitiesAngstromPerFs[coordinatePage.value*50+n]}))??[]);
const selectedDistance=computed(()=>{const p=current.value?.positionsAngstrom;if(!p||selected.value.length<2)return null;return distance(p[selected.value[0]!]!,p[selected.value[1]!]!);});
const selectedAngle=computed(()=>{const p=current.value?.positionsAngstrom;if(!p||selected.value.length!==3)return null;return angle(p[selected.value[0]!]!,p[selected.value[1]!]!,p[selected.value[2]!]!);});
async function exportTrajectory(){const q=atomicTrajectoryRequest.value;if(!q)return;const g=generation;exporting.value=true;try{const saved=await window.materialsx.exportAtomicTrajectory(q);if(g===generation)notice.value=saved?t('已导出带时间和 Å/fs 速度列的真实 extxyz 轨迹。','Real extxyz trajectory exported with time and Å/fs velocity columns.'):t('已取消导出','Export cancelled');}catch(e){if(g===generation)error.value=String(e);}finally{if(g===generation)exporting.value=false;}}
async function compare(){const q=atomicTrajectoryRequest.value;if(!q||!otherId.value)return;const g=generation;try{const v=mdComparisonSchema.parse(await window.materialsx.compareAtomicMD({projectId:q.projectId,runIds:[q.runId,otherId.value]}));if(g===generation)comparison.value=v;}catch(e){if(g===generation)error.value=String(e);}}
const series=computed(()=>{if(comparison.value)return comparison.value.series;if(!payload.value?.history)return [];return [payload.value.history];});
const curves=computed(()=>{if(!payload.value||!series.value.length)return [];const values=series.value.map(rows=>rows.map(r=>metric.value==='temperature'?r.temperatureK:(r.totalEnergyEv-rows[0]!.totalEnergyEv)/payload.value!.structure.atoms.length*1000));const all=values.flat(),low=Math.min(...all),high=Math.max(...all),maxT=Math.max(...series.value.map(r=>r.at(-1)!.timeFs));return series.value.map((rows,i)=>({color:i===0?'#49a4aa':'#d38f4e',name:comparison.value?.potentialIds[i]??payload.value!.potentialId,points:rows.filter((_r,n)=>n%Math.max(1,Math.ceil(rows.length/300))===0||n===rows.length-1).map(r=>{const value=metric.value==='temperature'?r.temperatureK:(r.totalEnergyEv-rows[0]!.totalEnergyEv)/payload.value!.structure.atoms.length*1000;return `${40+560*r.timeFs/(maxT||1)},${180-150*(value-low)/(high-low||1)}`;}).join(' '),low,high,maxT}));});
watch(atomicTrajectoryRequest,()=>void load(),{immediate:true});watch(()=>props.projectId,(p)=>{if(atomicTrajectoryRequest.value&&atomicTrajectoryRequest.value.projectId!==p)closeAtomicTrajectory();});watch([style,showCell,showBonds,appearanceTheme],draw);watch(speed,schedule);
onMounted(()=>window.addEventListener('message',message));onUnmounted(()=>{dispose();window.removeEventListener('message',message);});
</script>
<template><ElDrawer v-model="visible" :title="t('分子动力学 · 真实轨迹','Molecular dynamics · Real trajectory')" size="min(1060px, 96vw)" :with-header="false" destroy-on-close @closed="dispose">
 <div class="controls heading"><h2>{{t('分子动力学 · 真实轨迹','Molecular dynamics · Real trajectory')}}</h2><button class="icon-button" aria-label="关闭分子动力学轨迹" @click="closeAtomicTrajectory">×</button></div>
 <section v-if="payload" class="trajectory-panel" data-testid="trajectory-panel" :data-frame="index" :data-time-fs="current?.step.timeFs" :data-rendered="rendered">
  <p class="warning">{{payload.partial?t('部分轨迹：任务未完成，以下仅为已保存的有效帧。','Partial trajectory: task incomplete; only saved valid frames are available.'):t('已完成请求步数 · 需科学复核','Requested steps completed · Needs scientific review')}} · {{t('短程轨迹不能证明长期热稳定性。','A short trajectory does not establish long-term thermal stability.')}}</p>
  <div class="controls"><button class="secondary-button" data-testid="md-play" :disabled="loading||!ready||!!error" @click="togglePlay">{{playing?t('暂停','Pause'):t('播放','Play')}}</button><label>{{t('播放速度','Playback speed')}} <select v-model.number="speed"><option v-for="n in [1,2,5,10,20]" :value="n" :key="n">{{n}} {{t('帧/秒','frames/s')}}</option></select></label><select v-model="style"><option value="ball-stick">{{t('球棍','Ball and stick')}}</option><option value="sphere">{{t('空间填充','Space filling')}}</option><option value="stick">{{t('棍状','Stick')}}</option></select><label><input v-model="showCell" type="checkbox">{{t('晶胞','Cell')}}</label><label><input v-model="showBonds" type="checkbox">{{t('推断键','Inferred bonds')}}</label><button class="secondary-button" :disabled="exporting" data-testid="md-export" @click="exportTrajectory">{{t('导出轨迹 extxyz','Export extxyz trajectory')}}</button><button class="secondary-button" data-testid="md-export-png" :disabled="!rendered||exporting||loading||!!error" @click="exportPNG">{{t('导出选帧 PNG','Export selected-frame PNG')}}</button><button class="secondary-button" @click="iframe?.contentWindow?.postMessage({type:'reset'},'*')">{{t('重置视角','Reset view')}}</button><button v-if="error" class="secondary-button" @click="retry">{{t('重试 3D','Retry 3D')}}</button></div>
  <p>{{payload.index.options.ensemble.toUpperCase()}} · Δt {{payload.index.options.timestepFs}} fs · {{payload.index.options.temperatureK}} K · {{t('每','every')}} {{payload.index.options.sampleEvery}} {{t('步采样；含初始和最后有效帧','steps; initial and last valid frame retained')}} · {{payload.index.entries.length}} {{t('帧','frames')}}</p>
  <input class="scrubber" data-testid="md-scrubber" :value="index" type="range" min="0" :max="payload.index.entries.length-1" step="1" @input="scrub"><p v-if="current">{{t('帧','Frame')}} {{index+1}} / {{payload.index.entries.length}} · {{t('实际步数','Actual step')}} {{current.step.step}} · t={{current.step.timeFs}} fs · T={{current.step.temperatureK.toFixed(2)}} K · Epot={{current.step.potentialEnergyEv.toFixed(6)}} eV · Ekin={{current.step.kineticEnergyEv.toFixed(6)}} eV</p>
  <iframe ref="iframe" :key="frameKey" :src="frameUrl" class="scene" sandbox="allow-scripts allow-same-origin" :title="t('本地原子轨迹 3D','Local atomic trajectory 3D')" />
  <p v-if="limited">{{t('推断键达到显示预算；真实坐标仍完整。','Inferred-bond display budget reached; real coordinates remain complete.')}}</p>
  <p>{{t('位置：未包裹笛卡尔坐标 Å；速度：Å/fs；时间：fs。颜色表示元素，键为几何推断。播放速度不等于模拟的物理时间速度。','Positions: unwrapped Cartesian Å; velocities: Å/fs; time: fs. Element colors and geometry-inferred bonds. Playback speed is not simulation physical-time speed.')}}</p>
  <div v-if="payload.summary" class="diagnostics"><strong>{{t('数值诊断','Numerical diagnostics')}}</strong><p v-if="payload.summary.options.ensemble==='nve'">{{t('NVE 总能量漂移','NVE total-energy drift')}} {{payload.summary.nveDriftMevPerAtomPerPs?.toPrecision(5)}} meV/atom/ps · {{payload.summary.nveVerdict}} ({{t('至少 1000 fs，绝对值 ≤1','minimum 1000 fs, absolute slope ≤1')}})</p><p v-else>{{t('NVT 后半程平均温度','NVT final-half mean temperature')}} {{payload.summary.nvtMeanTemperatureK?.toFixed(2)}} K · {{payload.summary.nvtVerdict}} ({{t('至少 500 fs，温度偏差 ≤20%；工程诊断','minimum 500 fs, relative error ≤20%; engineering diagnostic')}})</p><p>{{payload.summary.stepsPerSecond.toFixed(2)}} steps/s · {{t('峰值内存','Peak memory')}} {{payload.summary.peakMemoryMiB.toFixed(1)}} MiB · {{t('计算时间','Calculation time')}} {{payload.summary.elapsedSeconds.toFixed(2)}} s</p></div>
  <div v-if="others.length&&!payload.partial" class="diagnostics"><strong>{{t('同输入、同初速度的模型对比','Same input / initial velocities: model comparison')}}</strong><div class="controls"><select v-model="otherId" data-testid="md-compare-select"><option value="">—</option><option v-for="r in others" :key="r.id" :value="r.id">{{r.potentialId}} · {{r.id.slice(0,8)}}</option></select><button class="secondary-button" data-testid="md-compare" :disabled="!otherId" @click="compare">{{t('读取真实对比','Read real comparison')}}</button></div></div>
  <div v-if="curves.length" :data-testid="comparison?'md-comparison':'md-observables'"><select v-model="metric"><option value="temperature">T (K)</option><option value="energy">ΔEtotal/N (meV/atom)</option></select><p v-for="curve in curves" :key="curve.name" :style="{color:curve.color}">{{curve.name}}</p><svg viewBox="0 0 640 220" role="img" :aria-label="t('两模型真实逐步曲线','Two-model real per-step curves')"><path d="M40 25 V180 H600" fill="none" stroke="currentColor"/><polyline v-for="curve in curves" :key="curve.name" :points="curve.points" fill="none" :stroke="curve.color" stroke-width="2"/><text x="40" y="210">0 fs</text><text x="525" y="210">{{curves[0]?.maxT}} fs</text><text x="43" y="24">{{curves[0]?.high.toPrecision(4)}}</text><text x="43" y="177">{{curves[0]?.low.toPrecision(4)}}</text></svg><p v-if="comparison">{{t('能量是各模型相对自身初始值的变化，不能直接比较未对齐的总能量。模型一致不等于准确。','Energy curves show change from each model’s own initial energy. Unaligned total energies are not compared. Agreement does not establish accuracy.')}}</p></div>
  <p v-if="selectedDistance!==null">{{t('已选原子距离（显示笛卡尔，未用最小镜像）','Selected distance (display Cartesian, no MIC)')}} {{selectedDistance.toFixed(5)}} Å <span v-if="selectedAngle!==null"> · {{selectedAngle.toFixed(3)}}°</span></p>
  <details :open="!!error" data-testid="md-coordinate-table"><summary>{{t('当前真实帧坐标与速度','Current real-frame coordinates and velocities')}} · {{payload.structure.atoms.length}} {{t('原子','atoms')}}</summary><table><thead><tr><th>ID</th><th>{{t('元素','Element')}}</th><th>r (Å)</th><th>v (Å/fs)</th></tr></thead><tbody><tr v-for="a in coordinateRows" :key="a.id" :class="{selected:selected.includes(a.n)}"><td>{{a.id}}</td><td>{{a.element}}</td><td>{{a.position?.map(v=>v.toFixed(5)).join(', ')}}</td><td>{{a.velocity?.map(v=>v.toFixed(6)).join(', ')}}</td></tr></tbody></table><div class="controls" v-if="payload.structure.atoms.length>50"><button class="secondary-button" :disabled="coordinatePage===0" @click="coordinatePage--">{{t('上一页','Previous')}}</button><span>{{coordinatePage+1}} / {{Math.ceil(payload.structure.atoms.length/50)}}</span><button class="secondary-button" :disabled="(coordinatePage+1)*50>=payload.structure.atoms.length" @click="coordinatePage++">{{t('下一页','Next')}}</button></div></details>
  <details><summary>{{t('参数与文件证据','Parameters and file evidence')}}</summary><pre>{{payload.index.options}}</pre><p v-if="current">Frame SHA256 {{payload.index.entries[index]?.frame.sha256}}</p><p>{{t('检查点未保存完整积分器和随机数状态；复用结构将创建新轨迹段，不是续算。','Checkpoints lack complete integrator/RNG state. Geometry reuse creates a new segment, not a continuation.')}}</p></details>
 </section><p v-if="loading">{{t('正在按帧读取本地轨迹…','Reading local trajectory frame…')}}</p><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice">{{notice}}</p>
</ElDrawer></template>
<style scoped>.trajectory-panel{color:var(--text)}.heading{justify-content:space-between}.heading h2{font-size:20px;margin:0}.controls{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:14px 0}.controls select,select{padding:8px;border:1px solid var(--line);border-radius:8px;background:var(--panel);color:var(--text)}.scene{width:100%;height:460px;border:1px solid var(--line);border-radius:12px;background:var(--panel)}.scrubber{width:100%;accent-color:var(--accent)}p{font-size:13px;line-height:1.65;color:var(--muted);overflow-wrap:anywhere}.warning,.diagnostics{padding:12px;border:1px solid var(--line);border-radius:10px;background:var(--panel-2)}.diagnostics{margin:14px 0}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;border-bottom:1px solid var(--line);padding:8px}.selected{background:var(--panel-2)}.error{color:var(--danger,#d05252)}svg{width:100%;height:auto;max-height:280px;color:var(--muted);font-size:12px}details{font-size:13px;line-height:1.6}pre{white-space:pre-wrap}</style>
