<script setup lang="ts">
import {ref,computed,watch,onMounted,onUnmounted} from 'vue';
import {ElDrawer} from 'element-plus';
import {atomicComparisonRequest,closeAtomicComparison} from '../utils/atomic-viewer';
import {appearanceTheme} from '../utils/appearance';
import {relaxationComparisonSchema,comparisonCommandSchema,comparisonEventSchema} from '../../../../../packages/contracts/src/atomistic-relaxation.js';
import type {z} from 'zod';
const props=defineProps<{locale:'zh'|'en';projectId:string|null}>();
const t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
const visible=computed({get:()=>!!atomicComparisonRequest.value,set:(v:boolean)=>{if(!v)closeAtomicComparison();}});
const payload=ref<z.infer<typeof relaxationComparisonSchema>|null>(null),error=ref(''),frameError=ref(''),ready=ref(false),rendered=ref(false),notice=ref('');
const frame=ref<HTMLIFrameElement|null>(null),frameKey=ref(0),page=ref(0);
const style=ref<'ball-stick'|'sphere'|'stick'>('ball-stick'),color=ref<'element'|'displacement'|'force'>('displacement'),sync=ref(true),cell=ref(true);
const frameUrl=new URL('atomic-comparison.html',window.location.href).href;
let generation=0,timer:ReturnType<typeof setTimeout>|undefined,bootTimer:ReturnType<typeof setTimeout>|undefined;
const magnitude=computed(()=>payload.value?.summary.displacementsAngstrom.map(v=>Math.hypot(...v))??[]);
const max=computed(()=>Math.max(0,...(color.value==='force'?payload.value?.forcesEvPerAngstrom.map(v=>Math.hypot(...v))??[]:magnitude.value)));
const rows=computed(()=>payload.value?.after.atoms.slice(page.value*50,(page.value+1)*50)??[]);
const chart=computed(()=>{const data=payload.value?.history??[];const low=Math.min(...data.map(r=>r.energyEv)),high=Math.max(...data.map(r=>r.energyEv));return data.map((r,i)=>`${20+i*460/Math.max(1,data.length-1)},${130-(r.energyEv-low)*110/Math.max(1e-9,high-low)}`).join(' ');});
function send(value:unknown){frame.value?.contentWindow?.postMessage(comparisonCommandSchema.parse(value),'*');}
function draw(){if(ready.value&&payload.value)send({type:'comparison',payload:payload.value,style:style.value,colorBy:color.value,showCell:cell.value,sync:sync.value,theme:appearanceTheme.value});}
async function load(){const query=atomicComparisonRequest.value;const version=++generation;send({type:'dispose'});payload.value=null;error.value='';frameError.value='';ready.value=false;rendered.value=false;notice.value='';page.value=0;if(bootTimer)clearTimeout(bootTimer);if(!query)return;
 try{const result=relaxationComparisonSchema.parse(await window.materialsx.readAtomicComparison(query));if(generation===version){payload.value=result;cell.value=result.before.pbc.some(Boolean);}}catch(e){if(generation===version)error.value=String(e);}}
function receive(event:MessageEvent){if(event.source!==frame.value?.contentWindow||!(event.origin===location.origin||(location.protocol==='file:'&&event.origin==='null')))return;
 const parsed=comparisonEventSchema.safeParse(event.data);if(!parsed.success)return;const item=parsed.data;
 if(item.type==='ready'){ready.value=true;if(bootTimer)clearTimeout(bootTimer);draw();}else if(item.type==='rendered')rendered.value=true;else{frameError.value=item.message;rendered.value=false;}}
function loaded(){if(!ready.value)bootTimer=setTimeout(()=>{if(!ready.value)frameError.value='VIEWER_INITIALIZATION_TIMEOUT';},8000);}
function retry(){frameKey.value++;ready.value=false;rendered.value=false;frameError.value='';}
async function exportFinal(){const query=atomicComparisonRequest.value;if(!query)return;const version=generation;try{const job=await window.materialsx.getAtomisticRun(query.projectId,query.runId);const artifact=job.artifacts.find(a=>a.relativePath.endsWith('/final.json'));if(!artifact)throw Error('FINAL_ARTIFACT_MISSING');const saved=await window.materialsx.exportAtomicStructure({kind:'artifact',...query,artifactId:artifact.id});if(generation===version)notice.value=saved?t('已导出最终结构。','Final structure exported.'):t('已取消导出。','Export cancelled.');}catch(e){if(generation===version)error.value=String(e);}}
async function reveal(){const query=atomicComparisonRequest.value;if(!query)return;try{const job=await window.materialsx.getAtomisticRun(query.projectId,query.runId);await window.materialsx.revealArtifact(job.outputDirectory);}catch(e){error.value=String(e);}}
watch(atomicComparisonRequest,()=>void load());watch(()=>props.projectId,closeAtomicComparison);
watch([style,color,sync,cell,appearanceTheme],()=>{if(timer)clearTimeout(timer);timer=setTimeout(draw,40);});
onMounted(()=>{window.addEventListener('message',receive);void load();});onUnmounted(()=>{generation++;send({type:'dispose'});window.removeEventListener('message',receive);if(timer)clearTimeout(timer);if(bootTimer)clearTimeout(bootTimer);});
</script>
<template>
 <el-drawer v-model="visible" direction="rtl" size="min(1200px, 98vw)" :with-header="false" destroy-on-close class="atomic-comparison-drawer">
  <section data-testid="atomic-comparison-panel"><div class="heading"><div><span class="eyebrow">M6.3 · LOCAL RELAXATION</span><h2>{{t('优化前后对比','Before / after relaxation')}}</h2></div><button class="icon-button" :aria-label="t('关闭优化对比','Close relaxation comparison')" @click="closeAtomicComparison">×</button></div>
   <p v-if="error" class="error" role="alert">{{error}}</p><template v-if="payload">
    <p class="status">{{payload.summary.stopReason==='converged'?t('已收敛','Converged'):t('达到步数上限 · 未收敛','Step limit · Not converged')}} · {{payload.summary.completedSteps}} {{t('步','steps')}} · {{t('需科学复核','Needs scientific review')}}</p>
    <p class="hint">FIRE · {{payload.summary.options.cellMode}} / {{payload.summary.options.cellConstraint}} · fmax {{payload.summary.options.fmaxEvPerAngstrom}} eV/Å · {{t('外压','External pressure')}} {{payload.summary.options.externalPressureGPa??'—'}} GPa</p>
    <div class="metrics"><span>{{t('总能量','Total energy')}}: {{payload.summary.initial.energyEv.toFixed(7)}} → {{payload.summary.final.energyEv.toFixed(7)}} eV</span><span>ΔE {{(payload.summary.final.energyEv-payload.summary.initial.energyEv).toPrecision(6)}} eV</span><span>{{payload.before.pbc.some(Boolean)?t('体积','Volume'):t('显示盒体积（非物理）','Display box volume (not physical)')}} {{payload.summary.initial.volumeAngstrom3.toFixed(4)}} → {{payload.summary.final.volumeAngstrom3.toFixed(4)}} Å³</span></div>
    <p class="hint">|F|max {{payload.summary.final.maxForceEvPerAngstrom.toPrecision(5)}} eV/Å · {{t('最大过滤器广义力','Maximum cell filter force')}} {{payload.summary.final.maxFilterForceEvPerAngstrom.toPrecision(5)}} eV/Å</p>
    <div class="controls"><label>{{t('样式','Style')}} <select v-model="style"><option value="ball-stick">{{t('球棍','Ball and stick')}}</option><option value="sphere">{{t('球','Spheres')}}</option><option value="stick">{{t('棒','Sticks')}}</option></select></label><label>{{t('最终结构着色','Final structure colors')}} <select v-model="color" data-testid="comparison-color"><option value="displacement">{{t('位移模长','Displacement magnitude')}}</option><option value="element">{{t('元素','Element')}}</option><option value="force">{{t('力模长','Force magnitude')}}</option></select></label><label><input v-model="sync" type="checkbox" data-testid="comparison-sync">{{t('同步视角','Synchronize views')}}</label><label><input v-model="cell" type="checkbox">{{payload.before.pbc.some(Boolean)?t('晶胞边框','Cell borders'):t('显示盒边框（非周期）','Display box borders (nonperiodic)')}}</label><button class="secondary-button" :disabled="!rendered" @click="send({type:'reset'})">{{t('重置视图','Reset views')}}</button></div>
    <div class="captions"><strong>{{t('优化前 · 元素着色','Before · Element colors')}}</strong><strong>{{t('优化后 · 真实最终坐标','After · Real final positions')}}</strong></div>
    <div class="viewport" :data-ready="rendered"><iframe v-if="!frameError" :key="frameKey" ref="frame" :src="frameUrl" sandbox="allow-scripts allow-same-origin" :title="t('本地优化前后 3D 对比','Local before / after 3D comparison')" @load="loaded" /><div v-else class="fallback"><strong>{{t('3D 暂不可用','3D unavailable')}}</strong><p>{{frameError}}</p><p>{{t('仍可查阅坐标、报告并导出最终结构。','Coordinates, reports and final structure export remain available.')}}</p><button class="secondary-button" @click="retry">{{t('重试查看器','Retry viewer')}}</button></div></div>
    <p v-if="color!=='element'" class="hint"><span class="scale" /> 0 → {{max.toPrecision(5)}} {{color==='force'?'eV/Å':'Å'}} · {{t('按本视图最大值缩放','Scaled to this view maximum')}}</p>
    <p class="hint">{{t('原子 ID、元素与顺序已校验一致。位移 = 最终 − 初始笛卡尔坐标；未做最小镜像，包含晶胞形变。未对齐或修改计算坐标。近邻连线为显示推断；局部优化不证明全局稳定或 DFT 精度。','Atom IDs, elements and order are verified. Displacement = final minus initial Cartesian position, without MIC, including cell strain. No coordinate alignment or mutation. Neighbor lines are display inference; local optimization does not establish global stability or DFT accuracy.')}}</p>
    <div class="controls"><button class="secondary-button" @click="exportFinal">{{t('导出最终结构','Export final structure')}}</button><button class="secondary-button" @click="reveal">{{t('打开双语报告与每步记录','Reveal bilingual reports and step records')}}</button></div><p v-if="notice" role="status" class="hint">{{notice}}</p>
    <details open class="history"><summary>{{t('真实优化步的总能量','Total energy of actual optimization steps')}} · {{payload.history.length}} {{t('条记录（含初始单点）','records (including initial single point)')}}</summary><svg viewBox="0 0 500 150" role="img" :aria-label="t('每步总能量曲线','Total energy per step')"><line x1="20" y1="135" x2="485" y2="135" /><polyline :points="chart" /><text x="20" y="148">0</text><text x="445" y="148">{{payload.summary.completedSteps}}</text></svg><p class="hint">{{t('变胞含外压时优化目标为 E+pV；总能量曲线不要求单调下降。','With variable-cell pressure the objective is E+pV; total energy need not decrease monotonically.')}}</p></details>
    <details open><summary>{{t('优化后坐标与位移','Final positions and displacement')}} · {{payload.after.atoms.length}}</summary><div class="table-wrap"><table><thead><tr><th>ID</th><th>{{t('元素','Element')}}</th><th>x / y / z (Å)</th><th>|Δr| (Å)</th></tr></thead><tbody><tr v-for="(a,i) in rows" :key="a.id"><td>{{a.id}}</td><td>{{a.element}}</td><td>{{a.position.map(v=>v.toFixed(5)).join(' / ')}}</td><td>{{magnitude[page*50+i]?.toFixed(6)}}</td></tr></tbody></table></div><div class="controls"><button class="secondary-button" :disabled="page===0" @click="page--">{{t('上一页','Previous')}}</button><span>{{page+1}} / {{Math.ceil(payload.after.atoms.length/50)}}</span><button class="secondary-button" :disabled="(page+1)*50>=payload.after.atoms.length" @click="page++">{{t('下一页','Next')}}</button></div></details>
   </template>
  </section>
 </el-drawer>
</template>
<style scoped>
:global(.atomic-comparison-drawer){--el-drawer-bg-color:var(--panel);color:var(--text)}.heading,.controls,.metrics{display:flex;flex-wrap:wrap;align-items:center;gap:12px}.heading{justify-content:space-between}h2{font-size:22px;margin:6px 0}.status{font-weight:600}.hint{font-size:12px;line-height:1.7;color:var(--muted)}.error{color:var(--danger,#d05252);overflow-wrap:anywhere}.metrics{font-size:13px}.controls{margin:16px 0;font-size:13px}label{display:flex;align-items:center;gap:6px}select{padding:7px;border:1px solid var(--line);border-radius:8px;color:var(--text);background:var(--panel)}.captions{display:flex;text-align:center;font-size:13px;margin:12px 0}.captions strong{width:50%}.viewport{height:clamp(320px,48vh,470px);border:1px solid var(--line);border-radius:12px;overflow:hidden}iframe{width:100%;height:100%;border:0}.fallback{padding:24px;font-size:13px}.scale{display:inline-block;width:100px;height:10px;background:linear-gradient(90deg,var(--accent),var(--danger));border-radius:5px}details{margin:20px 0;font-size:13px;border-top:1px solid var(--line);padding-top:14px}summary{cursor:pointer}svg{width:100%;max-height:160px;margin-top:16px}svg line{stroke:var(--line)}svg polyline{fill:none;stroke:var(--accent);stroke-width:2}svg text{fill:var(--muted);font-size:10px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px;font-variant-numeric:tabular-nums}th,td{padding:9px;text-align:left;border-bottom:1px solid var(--line);white-space:nowrap}th{color:var(--muted)}input{accent-color:var(--accent)}
</style>
