<script setup lang="ts">
import {ref,watch,onUnmounted,computed} from 'vue';
import {ElDrawer} from 'element-plus';
import {Clock,RefreshCw,Play,FolderOpen} from '@lucide/vue';
import MarkdownContent from './MarkdownContent.vue';
import type {CampaignOverview,LongJob} from '../../../../../packages/contracts/src/campaigns.js';
const props=defineProps<{projectId:string;locale:'zh'|'en';active:boolean}>(),emit=defineEmits<{example:[text:string]}>();
const state=ref<CampaignOverview|null>(null),busy=ref(false),error=ref(''),preview=ref(''),selected=ref<LongJob|null>(null);
const form=ref({label:'',script:'',inputs:'',outputs:'result.json',args:'',maxComputeSeconds:3600,maxElapsedSeconds:172800,heapMiB:256,maxOutputMiB:4,approved:false});
const t=(zh:string,en:string)=>props.locale==='en'?en:zh;
const status=(s:string)=>({prepared:t('准备中','Prepared'),queued:t('已提交','Queued'),running:t('计算中','Running'),completed:t('计算结束，待复核','Finished; review required'),cancelled:t('已取消','Cancelled'),failed:t('计算失败','Failed'),unknown:t('回执待核对','Receipt unconfirmed')}[s]??s);
const configurations=computed(()=>{const byLabel=new Map();for(const c of [...(state.value?.configurations??[])].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)))byLabel.set(c.input.label,c);return [...byLabel.values()] as CampaignOverview['configurations'];});
const seconds=(n:number)=>Math.round(n/1000)+' s';
async function perform(fn:()=>Promise<unknown>){busy.value=true;error.value='';try{await fn();}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function load(){state.value=await window.materialsx.getCampaigns(props.projectId);}
async function example(){await window.materialsx.installCampaignExample(props.projectId);await load();}
async function choose(){const p=await window.materialsx.chooseLongJobFile(props.projectId);if(p)form.value.script=p;}
const lines=(s:string)=>s.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);
async function save(){const f=form.value;await window.materialsx.configureLongJob(props.projectId,{label:f.label,script:f.script,inputs:lines(f.inputs),outputs:lines(f.outputs),args:lines(f.args),maxComputeSeconds:f.maxComputeSeconds,maxElapsedSeconds:f.maxElapsedSeconds,heapMiB:f.heapMiB,maxOutputMiB:f.maxOutputMiB,detachApproved:true,pauseModelWhileComputing:true});f.approved=false;await load();}
async function query(job:LongJob){selected.value=await window.materialsx.queryLongJob(props.projectId,job.id);await load();}
async function cancel(job:LongJob){selected.value=await window.materialsx.cancelLongJob(props.projectId,job.id);await load();}
async function logs(job:LongJob){const l=await window.materialsx.getLongJobLogs(props.projectId,job.id);preview.value='````text\nstdout:\n'+(l.stdout??t('日志尚未生成','Log not available'))+'\n\nstderr:\n'+(l.stderr??t('日志尚未生成','Log not available'))+'\n````'+(l.truncated?'\n'+t('仅显示前 8 KiB。','Showing the first 8 KiB.'):'');}
async function file(job:LongJob,path:string){preview.value=await window.materialsx.previewLongJob(props.projectId,job.id,path);}
const polling=setInterval(()=>{if(!props.active||busy.value||!state.value)return;const jobs=state.value.jobs.filter(j=>['prepared','queued','running'].includes(j.status)).slice(0,16);if(jobs.length)void perform(async()=>{for(const j of jobs){const next=await window.materialsx.queryLongJob(props.projectId,j.id);if(selected.value?.id===j.id)selected.value=next;}await load();});},2000);
onUnmounted(()=>clearInterval(polling));
watch(()=>[props.projectId,props.active],()=>{if(props.active)void perform(load);},{immediate:true});
</script>
<template>
<section class="campaign-panel" data-testid="campaign-panel">
  <header class="heading"><div><h2>{{t('长期计算','Long-running computation')}}</h2><p>{{t('计算可在应用关闭后继续。先查询原任务，再恢复研究。','Computation can continue after the app closes. Query the original job before resuming research.')}}</p></div><button class="secondary-button" :disabled="busy" @click="perform(load)"><RefreshCw :size="15"/>{{t('刷新','Refresh')}}</button></header>
  <p v-if="error" class="error" role="alert">{{error}}</p>
  <div class="metrics" v-if="state"><span>{{t('模型','Model')}} {{seconds(state.timings.modelMs)}}</span><span>{{t('排队','Queue')}} {{seconds(state.timings.queueMs)}}</span><span>{{t('下载','Download')}} {{seconds(state.timings.downloadMs)}}</span><span>{{t('计算','Compute')}} {{seconds(state.timings.computeMs)}}</span><span>{{t('研究等待','Research wait')}} {{seconds(state.timings.waitingMs)}}</span></div>
  <div class="notice">{{t('当前支持 macOS 本地 Node 脚本：离线沙箱、固定输入、真实文件回执。SSH / Slurm 尚未接入。计算结束不代表科学结论已验证。','Currently supports local Node scripts on macOS: offline sandbox, frozen inputs and real file receipts. SSH / Slurm is not connected. Completion does not validate scientific conclusions.')}}</div>
  <div class="heading"><h3>{{t('已批准的计算配置','Approved configurations')}}</h3><button data-testid="campaign-example" class="secondary-button" :disabled="busy||!state?.providerAvailable" @click="perform(example)"><Play :size="15"/>{{t('添加 NIST 参考示例','Add NIST reference example')}}</button></div>
  <p v-if="state&&state.configurations.length>configurations.length" class="muted">{{t('显示每个名称的最新配置；历史配置随原任务保留。','Showing the latest configuration per name. Historical configurations remain attached to their original tasks.')}}</p>
  <div class="cards"><article v-for="c in configurations" :key="c.id" class="card"><Clock :size="20"/><h3>{{c.input.label}}</h3><p class="path">{{c.input.script}}</p><p>{{t('计算上限','Compute cap')}} {{c.input.maxComputeSeconds}} s · {{t('总期限','Total limit')}} {{c.input.maxElapsedSeconds/3600}} h</p><small>{{c.createdAt}} · {{c.sha256.slice(0,12)}}</small><button class="secondary-button" @click="emit('example',t('@materials-long-compute 使用已批准的配置 '+c.id+' 进行后台参考计算。用 campaign_job 提交，等待时结束本轮；恢复前查询原任务。','@materials-long-compute Run the approved configuration '+c.id+' using campaign_job. End this turn while waiting; query the original job before resuming.'))">{{t('填入对话','Use in chat')}}</button></article></div>
  <details class="configuration"><summary>{{t('添加自己的计算配置','Add a computation configuration')}}</summary><div class="fields"><label>{{t('名称','Name')}}<input v-model="form.label"/></label><label>{{t('项目内脚本路径','Script within project')}}<div class="actions"><input v-model="form.script" placeholder="analysis/run.mjs"/><button class="secondary-button" :disabled="busy" @click="perform(choose)"><FolderOpen :size="15"/></button></div></label><label>{{t('输入文件，每行一个项目内路径','Input files, one project path per line')}}<textarea v-model="form.inputs"/></label><label>{{t('输出文件名，每行一个','Output filenames, one per line')}}<textarea v-model="form.outputs"/></label><label>{{t('参数，每行一个','Arguments, one per line')}}<textarea v-model="form.args"/></label><label>{{t('计算时限（秒）','Compute limit (seconds)')}}<input type="number" v-model.number="form.maxComputeSeconds" min="1" max="604800"/></label><label>{{t('总期限（秒，最多7天）','Elapsed limit (seconds, up to 7 days)')}}<input type="number" v-model.number="form.maxElapsedSeconds" min="1" max="604800"/></label><label>{{t('Node 堆上限（MiB）','Node heap limit (MiB)')}}<input type="number" v-model.number="form.heapMiB" min="64" max="4096"/></label><label>{{t('产物总量上限（MiB）','Output limit (MiB)')}}<input type="number" v-model.number="form.maxOutputMiB" min="1" max="16"/></label></div><p class="notice">{{t('只运行你已审核的自包含脚本。依赖须列为输入；此配置不支持 Python、第三方包安装或网络访问。堆上限不是操作系统内存硬限额。','Use reviewed, self-contained scripts. Include dependencies as inputs. Python, third-party package installation and network access are not supported. Heap limit is not an operating-system memory cap.')}}</p><label class="approval"><input type="checkbox" v-model="form.approved"/>{{t('我批准该脚本及输入在应用退出后继续计算，并在计算期间暂停模型会话。','I approve this script and its inputs to continue after app exit, with the model session paused while computing.')}}</label><button class="primary-button" :disabled="busy||!form.approved||!state?.providerAvailable" @click="perform(save)">{{t('保存配置','Save configuration')}}</button></details>
  <h3>{{t('计算任务','Computation jobs')}}</h3><div class="cards"><button v-for="j in state?.jobs" :key="j.id" class="card job" @click="selected=j;preview=''"><span class="badge">{{status(j.status)}}</span><h3>{{state?.configurations.find(c=>c.id===j.configurationId)?.input.label}}</h3><p class="path">{{j.id}}</p><p>{{t('进程','Process')}} {{j.worker?.pid??'—'}} · {{t('平台积分','Platform credits')}} 0</p><small>{{j.createdAt}}</small><p v-if="j.error">{{j.error}}</p></button></div><p v-if="!state?.jobs.length" class="muted">{{t('尚未提交计算。保存配置后，可从对话提交到原有研究任务。','No jobs submitted. After saving a configuration, submit through a research conversation.')}}</p>
  <ElDrawer :model-value="!!selected" class="campaign-drawer" :title="t('计算详情','Job details')" size="min(780px, 96vw)" @close="selected=null;preview=''">
    <div v-if="selected" class="details"><h3>{{status(selected.status)}}</h3><p class="path">{{selected.id}}</p><p>{{t('原研究任务','Research task')}} {{selected.taskId}}</p><p>{{t('截止时间','Deadline')}} {{new Date(selected.elapsedUntil).toLocaleString()}}</p><p>{{selected.worker?.environment.node}} · {{selected.worker?.environment.platform}} / {{selected.worker?.environment.arch}} · PID {{selected.worker?.pid??'—'}}</p><p v-if="selected.error" class="error">{{selected.error}}</p><div class="actions"><button class="secondary-button" :disabled="busy" @click="perform(()=>query(selected!))">{{t('查询真实状态','Query actual state')}}</button><button class="secondary-button" :disabled="busy" @click="perform(()=>logs(selected!))">{{t('查看运行日志','View logs')}}</button><button v-if="!['completed','failed','cancelled'].includes(selected.status)" class="secondary-button" :disabled="busy" @click="perform(()=>cancel(selected!))">{{t('请求取消','Request cancellation')}}</button></div><p class="notice">{{t('取消请求不是取消回执。待核对状态不会自动重新提交。计算完成后，在对话的任务面板核对并恢复。','A cancellation request is not a cancellation receipt. Unconfirmed jobs are never automatically resubmitted. Once finished, reconcile and resume in the conversation task panel.')}}</p><div class="artifacts"><button v-for="a in selected.artifacts" :key="a.path" class="secondary-button" :disabled="busy" @click="perform(()=>file(selected!,a.path))">{{a.path.split('/').at(-1)}} · {{a.bytes}} B</button></div><MarkdownContent v-if="preview" :content="preview"/></div>
  </ElDrawer>
</section>
</template>
<style scoped>
.campaign-panel{width:100%;min-width:0;margin:20px 0}.heading{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.heading h2,.heading h3{margin:0}.heading p{color:var(--muted);line-height:1.7}.metrics{display:flex;gap:12px;flex-wrap:wrap;margin:18px 0}.metrics span,.badge{border:1px solid var(--line);padding:7px 12px;border-radius:10px;font-size:12px}.notice{color:var(--muted);background:var(--panel-2);padding:14px 18px;border-radius:12px;line-height:1.75;font-size:13px;margin:16px 0}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:14px;margin:18px 0}.card{min-width:0;padding:20px;border:1px solid var(--line);border-radius:16px;background:var(--panel);color:var(--text);text-align:left;display:flex;flex-direction:column;gap:12px}.card h3,.card p{margin:0;line-height:1.6}.card small,.muted{color:var(--muted)}.card .secondary-button{align-self:flex-start}.job{cursor:pointer}.job:hover{background:var(--panel-2)}.path{overflow-wrap:anywhere;font-size:13px}.configuration{border:1px solid var(--line);border-radius:14px;padding:20px;margin:22px 0}.configuration summary{cursor:pointer;font-weight:600}.fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:16px;margin:20px 0}.fields label{display:flex;flex-direction:column;gap:8px;font-size:13px}.fields input,.fields textarea{min-width:0;width:100%;box-sizing:border-box;padding:10px 12px;border-radius:9px;border:1px solid var(--line);background:var(--panel);color:var(--text)}.fields textarea{min-height:80px;resize:vertical}.fields .actions{flex-wrap:nowrap}.approval{display:flex;gap:10px;line-height:1.7;margin:20px 0;font-size:13px}.approval input{flex:none}.details{line-height:1.7}.artifacts{display:flex;flex-wrap:wrap;gap:10px;margin:20px 0}.error{color:var(--danger,#b54a3d);overflow-wrap:anywhere}.badge{align-self:flex-start}
:global(.campaign-drawer.el-drawer){background:var(--panel);color:var(--text)}:global(.campaign-drawer .el-drawer__header){color:var(--text)}
</style>
