<script setup lang="ts">
import {ref,watch,computed} from 'vue';
import {ElDrawer} from 'element-plus';
import {FileChartColumn,Upload,RefreshCw} from '@lucide/vue';
import ExperimentConfigEditor from './ExperimentConfigEditor.vue';
import MarkdownContent from './MarkdownContent.vue';
import type {ExperimentOverview,ExperimentDataset,ExperimentConfigInput,ExperimentRun} from '../../../../../packages/contracts/src/experiments.js';
const props=defineProps<{projectId:string;projectPath:string;locale:'zh'|'en'}>();
const emit=defineEmits<{changed:[];example:[text:string]}>();
const state=ref<ExperimentOverview>({datasets:[],configurations:[],runs:[]}),busy=ref(false),error=ref(''),editing=ref<ExperimentDataset|null>(null),selected=ref<string[]>([]),independent=ref(false),reason=ref(''),preview=ref(''),previewName=ref(''),previewOpen=ref(false);
const t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
const latest=(id:string)=>state.value.configurations.filter(c=>c.input.datasetId===id).sort((a,b)=>b.revision-a.revision)[0];
const choices=computed(()=>state.value.datasets.map(d=>({dataset:d,config:latest(d.id)})));
const svg=computed(()=>previewName.value.endsWith('.svg')?'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(preview.value))):'');
async function load(){const id=props.projectId,r=await window.materialsx.getExperiments(id);if(props.projectId===id){state.value=r;selected.value=selected.value.filter(id=>r.configurations.some(c=>c.id===id&&latest(c.input.datasetId)?.id===id));}}
async function perform(fn:()=>Promise<unknown>){busy.value=true;error.value='';try{await fn();}catch(e){error.value=String(e);}finally{busy.value=false;}}
watch(()=>props.projectId,()=>{state.value={datasets:[],configurations:[],runs:[]};selected.value=[];editing.value=null;previewOpen.value=false;void perform(load);},{immediate:true});
async function importData(){await perform(async()=>{const id=props.projectId,d=await window.materialsx.importExperiment(id);if(props.projectId!==id)return;await load();if(d)editing.value=d;emit('changed');});}
async function save(input:ExperimentConfigInput){await perform(async()=>{const id=props.projectId,c=await window.materialsx.configureExperiment(id,input);if(props.projectId!==id)return;editing.value=null;await load();selected.value=[c.id];emit('changed');});}
async function run(){await perform(async()=>{const id=props.projectId;await window.materialsx.runExperiment(id,{configurationIds:[...selected.value],independentReplicates:independent.value,reason:reason.value});if(props.projectId===id)await load();});}
async function show(r:ExperimentRun,path:string){await perform(async()=>{const id=props.projectId,text=await window.materialsx.previewExperiment(id,r.id,path);if(props.projectId!==id)return;preview.value=text;previewName.value=path.split('/').at(-1)!;previewOpen.value=true;});}
function reveal(r:ExperimentRun){const a=r.artifacts[0];if(a)void perform(()=>window.materialsx.revealArtifact(props.projectPath+'/'+a.path));}
watch(()=>selected.value.length,n=>{if(n<2)independent.value=false;});
function example(){emit('example',t('@materials-tensile-analysis 分析本项目已配置的应力—应变数据。读取真实试样与配置 ID，按保存的拟合区间和剔除理由计算斜率与观测峰值；不声明独立重复。生成曲线、数据表、中文报告和复算包，结论待复核。','@materials-tensile-analysis Analyze the configured engineering tensile inputs in this project. Read actual specimen and configuration IDs. Use saved fit intervals and exclusions; do not declare independent replicates. Produce curves, a data table, report and replay bundle; conclusions require review.'));}
</script>
<template>
<div class="experiment-panel" data-testid="experiment-panel">
  <article class="experiment-card"><header><div><span class="eyebrow">EXPERIMENT ANALYSIS</span><h2>{{t('应力—应变分析','Stress–strain analysis')}}</h2><p>{{t('导入原始记录，确认测量条件与拟合区间，再计算并查看结果。','Import original records, confirm measurement conditions and a fit interval, then calculate and inspect results.')}}</p></div><div class="actions"><button class="secondary-button" :disabled="busy" @click="perform(load)"><RefreshCw :size="15"/>{{t('刷新','Refresh')}}</button><button class="primary-button" :disabled="busy" @click="importData"><Upload :size="15"/>{{t('导入 CSV / XLSX','Import CSV / XLSX')}}</button></div></header>
    <p class="help">{{t('支持 UTF-8 CSV 与单工作表 XLSX（纯数值记录，最多 10000 行）。原文件保留；每次设置变更和计算均留下新版本。','Supports UTF-8 CSV and single-sheet XLSX (numeric records, up to 10,000 rows). Original files are preserved; edits and calculations create new versions.')}}</p>
    <p v-if="error" role="alert" class="error">{{error}}</p><p v-if="busy" role="status">{{t('正在处理…','Processing…')}}</p>
  </article>
  <article v-if="editing" class="experiment-card"><ExperimentConfigEditor :key="editing.id+':'+(latest(editing.id)?.revision??0)" :dataset="editing" :current="latest(editing.id)" :locale="locale" :busy="busy" @save="save" @cancel="editing=null"/></article>
  <article class="experiment-card"><h2>{{t('试样与分析设置','Specimens & settings')}}</h2>
    <div v-if="!choices.length" class="empty"><FileChartColumn :size="25"/><strong>{{t('先导入一份拉伸记录','Import a tensile record to begin')}}</strong><p>{{t('请选择工程应力—应变或力—位移原始数据，不会根据列名猜测单位。','Choose original engineering stress–strain or force–displacement records. Units are not guessed from column names.')}}</p></div>
    <div v-for="{dataset:d,config:c} in choices" :key="d.id" class="input-row"><label class="check"><input v-if="c" v-model="selected" type="checkbox" :value="c.id" :disabled="busy"/><div><strong>{{c?.input.specimenId||d.title}}</strong><p>{{d.title}} · {{d.rows}} {{t('行','rows')}} · {{c?t('设置版本','Settings revision')+' '+c.revision:t('待设置','Needs settings')}}</p><small v-if="c">{{c.input.xColumn}} ({{c.input.xUnit}}) → {{c.input.yColumn}} ({{c.input.yUnit}}) · {{c.input.fitRange.join('–')}}</small></div></label><button class="secondary-button" :disabled="busy" @click="editing=d">{{t('设置 / 编辑区间','Settings / edit interval')}}</button><details class="raw-preview"><summary>{{t('预览原始列（前 8 行）','Preview original columns (first 8 rows)')}}</summary><div class="table-scroll"><table><thead><tr><th>{{t('行号','Row')}}</th><th v-for="col in d.columns" :key="col">{{col}}</th></tr></thead><tbody><tr v-for="(row,i) in d.preview" :key="i"><td>{{row.row}}</td><td v-for="col in d.columns" :key="col">{{row.values[col]}}</td></tr></tbody></table></div></details></div>
    <div v-if="selected.length" class="run-form"><label class="check"><input v-model="independent" type="checkbox" :disabled="selected.length<2"/>{{t('所选记录是相同条件下、不同试样的独立重复试验','Selected records are independent replicate specimens under identical conditions')}}</label><input v-model="reason" data-testid="experiment-reason" maxlength="2000" :placeholder="t('记录本次计算目的','Record the purpose of this calculation')"/><div class="actions"><button class="primary-button" data-testid="run-experiment" :disabled="busy||!reason.trim()" @click="run">{{t('计算并生成报告','Calculate & create report')}}</button><button class="secondary-button" :disabled="busy" @click="example">{{t('交给 Agent 分析','Analyze with Agent')}}</button></div></div>
  </article>
  <article class="experiment-card"><h2>{{t('结果与复算','Results & replay')}}</h2><p class="help">{{t('图表、报告和复算包来自实际计算。结果仍需科研复核；修改输入或区间后，旧结果标记为历史版本。','Charts, reports and replay bundles come from actual calculations. Scientific review is required. Edits mark prior results as historical.')}}</p>
    <p v-if="!state.runs.length" class="help">{{t('尚无计算结果。','No calculations yet.')}}</p>
    <div v-for="r in [...state.runs].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))" :key="r.id" class="result-row"><header><strong>{{new Date(r.createdAt).toLocaleString()}}</strong><span class="badge">{{r.status==='stale'?t('历史版本','Historical'):t('待复核','Review required')}}</span></header><p>{{r.request.reason}}</p><div class="actions"><button v-for="a in r.artifacts.filter(a=>/report.md|chart.svg|points.csv|result.json|environment.json|replay.mjs$/.test(a.path))" :key="a.path" class="secondary-button" :disabled="busy" @click="show(r,a.path)">{{a.path.endsWith('report.md')?t('报告','Report'):a.path.endsWith('chart.svg')?t('应力—应变图','Stress–strain chart'):a.path.endsWith('points.csv')?t('数据表','Data table'):a.path.split('/').at(-1)}}</button></div><button v-if="r.artifacts[0]" class="secondary-button" :disabled="busy" @click="reveal(r)">{{t('打开产物目录','Open output folder')}}</button><small>{{t('项目内产物目录','Project output folder')}}: {{r.artifacts[0]?.path.split('/').slice(0,-1).join('/')}}</small></div>
  </article>
  <ElDrawer v-model="previewOpen" :title="previewName" size="min(1080px,96vw)" class="experiment-preview-drawer" append-to-body><MarkdownContent v-if="previewName.endsWith('.md')" :content="preview"/><img v-else-if="svg" class="experiment-chart" :src="svg" :alt="t('应力—应变曲线与拟合区间','Stress–strain curves with fit intervals')"/><pre v-else class="experiment-preview">{{preview}}</pre></ElDrawer>
</div>
</template>
<style scoped>
:global(.experiment-preview-drawer.el-drawer){background:var(--panel);color:var(--text);border-left:1px solid var(--line)}
:global(.experiment-preview-drawer .el-drawer__header){color:var(--text)}

.raw-preview{flex-basis:100%;min-width:0;font-size:13px}.table-scroll{overflow:auto;margin-top:12px;max-height:260px}table{border-collapse:collapse;font-size:12px}th,td{padding:8px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}.experiment-panel{display:grid;gap:18px;min-width:0;max-width:100%;box-sizing:border-box}.experiment-card{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:22px;min-width:0;overflow-wrap:anywhere}.experiment-card h2{font-size:17px;margin:0 0 10px}.experiment-card header,.input-row,.actions{display:flex;gap:12px;align-items:flex-start;justify-content:space-between;flex-wrap:wrap}.actions{justify-content:flex-start;align-items:center}.help,.experiment-card p{font-size:13px;line-height:1.7;color:var(--muted)}.input-row,.result-row{padding:18px 0;border-top:1px solid var(--line)}.input-row:first-of-type{margin-top:16px}.input-row p{margin:5px 0}.input-row small,.result-row small{display:block;color:var(--muted);font-size:12px;margin-top:9px;overflow-wrap:anywhere}.input-row .check{flex:1;min-width:0}.check{display:flex;gap:10px;align-items:flex-start;font-size:13px;line-height:1.6}.check input{width:auto}.run-form{display:grid;gap:16px;margin-top:16px;border-top:1px solid var(--line);padding-top:18px}.run-form>input{box-sizing:border-box;width:100%;min-width:0;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:10px;border-radius:8px;font:inherit}.badge{font-size:12px;border:1px solid var(--line);border-radius:6px;padding:4px 8px;color:var(--muted)}.empty{display:grid;justify-items:center;text-align:center;padding:30px 12px;color:var(--muted);gap:12px}.error{color:var(--danger)!important}.experiment-chart{width:100%;height:auto}.experiment-preview{white-space:pre-wrap;overflow-wrap:anywhere;max-width:100%;font-size:12px;color:var(--text)}@media(max-width:780px){.experiment-card{padding:16px}.experiment-card header,.input-row{flex-direction:column;align-items:stretch}}
</style>
