<script setup lang="ts">
import {ref} from 'vue';
import type {EnvironmentReceipt} from '../../../../../packages/contracts/src/papers.js';
const locale=ref<'zh'|'en'>('zh'),busy=ref(false),receipt=ref<EnvironmentReceipt|null>(null),error=ref('');
const t=(zh:string,en:string)=>locale.value==='zh'?zh:en;
async function run(action:'check'|'repair'){busy.value=true;error.value='';try{receipt.value=await window.materialsx.managedEnvironment(action);}catch(e){error.value=String(e);}finally{busy.value=false;}}
</script>
<template><section class="managed-environment" data-testid="managed-environment"><header><div><h2>{{t('论文解析环境','Document parsing environment')}}</h2><p>{{t('检查内置 Python 与解析依赖。修复只创建受管副本，不修改系统 Python。','Verify bundled Python and parsing dependencies. Repair creates an owned copy without changing system Python.')}}</p></div><button class="secondary-button" @click="locale=locale==='zh'?'en':'zh'">{{locale==='zh'?'English':'中文'}}</button></header><div class="environment-actions"><button class="secondary-button" :disabled="busy" @click="run('check')">{{t('检查环境','Check environment')}}</button><button class="secondary-button" :disabled="busy" @click="run('repair')">{{t('修复受管环境','Repair managed environment')}}</button><span v-if="busy">{{t('正在校验文件与依赖…','Verifying files and dependencies…')}}</span></div><p>{{t('请先停止运行中的任务。仅恢复已锁定的内置依赖；安装包源文件损坏时需重新安装。','Stop active tasks first. Only locked bundled dependencies are restored; reinstall if the bundle itself is damaged.')}}</p><div v-if="receipt"><strong>{{({ready:t('环境就绪','Ready'),repaired:t('修复完成','Repaired'),'rolled-back':t('修复未启用，原环境可用','Repair not activated; previous environment ready'),unavailable:t('环境不可用','Unavailable')})[receipt.status]}}</strong><p>{{receipt.detail}}</p><small>{{receipt.python}}<br/>{{Object.entries(receipt.versions).map(([k,v])=>k+' '+v).join(' · ')}}<br/>{{receipt.lockSha256}}</small></div><p v-if="error" role="alert">{{error}}</p></section></template>
<style scoped>.managed-environment{padding:22px;border:1px solid var(--line);border-radius:14px;background:var(--panel);color:var(--text);min-width:0;box-sizing:border-box;max-width:100%;overflow-wrap:anywhere;margin-top:18px}.managed-environment header,.environment-actions{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:center}.environment-actions{justify-content:flex-start}.managed-environment h2{font-size:17px;margin:0}.managed-environment p,.managed-environment small{font-size:13px;line-height:1.7;color:var(--muted)}[role=alert]{color:var(--danger)!important}@media(max-width:780px){.managed-environment{padding:16px}}</style>
