<script setup lang="ts">
import {reactive,ref} from 'vue';
import type {ResearchSnapshot} from '../../../../../packages/contracts/src/research-project.js';
import type {StudyInput,ResearchStudy} from '../../../../../packages/contracts/src/next-experiment.js';
const props=defineProps<{study:ResearchStudy|null;sources:ResearchSnapshot[];revision:number;locale:'zh'|'en';busy:boolean}>(),emit=defineEmits<{save:[input:StudyInput];cancel:[]}>();
const t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
const old=props.study?.input;
const form=reactive({materialSystem:old?.materialSystem??'',question:old?.question??'',experimentalUnit:old?.experimentalUnit??'',measurementConditions:old?.measurementConditions??'',
  metric:old?.response.metric??'reported',property:old?.response.property??'',unit:old?.response.unit??'',direction:old?.response.direction??'maximize',target:old?.response.target===null||old?.response.target===undefined?'':String(old.response.target),
  hypotheses:old?.hypotheses.map(h=>({...h}))??[{statement:'',alternative:'',falsification:''}],
  factors:old?.factors.map(f=>({...f,levels:f.levels.join(', '),control:old.control[f.key]!}))??[{key:'factor_1',label:'',unit:'',kind:'continuous' as const,levels:'',costPerUnitCny:0,control:0}],
  blocks:old?.blocks.join('\n')??'batch-1',replicates:old?.replicates??2,baseCostCny:old?.baseCostCny??100,minutesPerRun:old?.minutesPerRun??30,costBasis:old?.costBasis??'',
  maxCostCny:old?.maxCostCny??10000,maxMinutes:old?.maxMinutes??10000,maxRuns:old?.maxRuns??100,manufacturabilityNotes:old?.manufacturabilityNotes??'',constraints:JSON.stringify(old?.constraints??[],null,2)});
const sourceIds=ref((old?.snapshotIds??[]).filter(id=>props.sources.some(s=>s.id===id))),error=ref('');
function submit(){try{error.value='';const factors=form.factors.map(({control,levels,...f})=>({...f,levels:levels.split(/[,，\s]+/).filter(Boolean).map(Number)}));
  const value:StudyInput={expectedProjectRevision:props.revision,materialSystem:form.materialSystem,question:form.question,experimentalUnit:form.experimentalUnit,measurementConditions:form.measurementConditions,
    hypotheses:form.hypotheses.map(h=>({...h})),snapshotIds:[...sourceIds.value],response:{metric:form.metric,property:form.property,unit:form.metric==='reported'?form.unit:'MPa',direction:form.direction,target:form.target.trim()===''?null:Number(form.target)},factors,constraints:JSON.parse(form.constraints),
    control:Object.fromEntries(form.factors.map(f=>[f.key,f.control])),blocks:form.blocks.split('\n').map(v=>v.trim()).filter(Boolean),replicates:form.replicates,baseCostCny:form.baseCostCny,minutesPerRun:form.minutesPerRun,costBasis:form.costBasis,maxCostCny:form.maxCostCny,maxMinutes:form.maxMinutes,maxRuns:form.maxRuns,manufacturabilityNotes:form.manufacturabilityNotes};
  emit('save',JSON.parse(JSON.stringify(value)));}catch(e){error.value=String(e);}}
</script>
<template>
<form class="study-form" @submit.prevent="submit">
  <p class="field-help">{{t('填写实际条件。保存后生成新版本；历史方案保留原条件。费用和时间为估算，不会触发付款或设备运行。','Enter actual conditions. Saving creates a new version. Cost and time are estimates; no payment or equipment execution occurs.')}}</p>
  <div class="two"><label>{{t('材料体系','Material system')}}<input v-model="form.materialSystem" data-field="material" required maxlength="300"/></label><label>{{t('研究问题','Research question')}}<input v-model="form.question" data-field="question" required/></label></div>
  <div class="two"><label>{{t('实验单元（每个重复独立制备什么）','Experimental unit (independently prepared per replicate)')}}<textarea v-model="form.experimentalUnit" data-field="unit" required/></label><label>{{t('统一测量条件（与数据来源保持一致）','Measurement conditions (match the source)')}}<textarea v-model="form.measurementConditions" data-field="conditions" required/></label></div>
  <details v-if="sources.length"><summary>{{t('关联研究来源（可选）','Study sources (optional)')}}</summary><label v-for="s in sources" :key="s.id" class="source-check"><input v-model="sourceIds" type="checkbox" :value="s.id"/>{{s.title}} · {{s.sha256.slice(0,12)}}</label></details>
  <h3>{{t('响应指标','Response')}}</h3><div class="two"><label>{{t('数据类型','Source metric')}}<select v-model="form.metric"><option value="reported">{{t('已导入观测值','Imported observation')}}</option><option value="fitSlopeMPa">{{t('UA.8 拟合斜率（MPa）','UA.8 fitted slope (MPa)')}}</option><option value="observedPeakStressMPa">{{t('UA.8 观测峰值应力（MPa）','UA.8 observed peak stress (MPa)')}}</option></select></label><label>{{t('指标名称（与来源 property 一致）','Property (match the source property)')}}<input v-model="form.property" data-field="property" required/></label><label>{{t('原始单位','Original unit')}}<input v-if="form.metric==='reported'" v-model="form.unit" data-field="response-unit" required/><input v-else value="MPa" disabled/></label><label>{{t('优化方向','Direction')}}<select v-model="form.direction"><option value="maximize">{{t('提高','Maximize')}}</option><option value="minimize">{{t('降低','Minimize')}}</option></select></label><label>{{t('目标值（可选）','Target (optional)')}}<input v-model="form.target" type="number" step="any"/></label></div>
  <h3>{{t('研究假设','Hypotheses')}}</h3><fieldset v-for="(h,i) in form.hypotheses" :key="i"><label>{{t('假设','Hypothesis')}}<textarea v-model="h.statement" data-field="hypothesis" required/></label><label>{{t('替代解释','Alternative explanation')}}<textarea v-model="h.alternative" data-field="alternative" required/></label><label>{{t('什么结果会否定假设','Falsifying result')}}<textarea v-model="h.falsification" data-field="falsification" required/></label><button v-if="i>0" type="button" class="secondary-button" @click="form.hypotheses.splice(i,1)">{{t('移除','Remove')}}</button></fieldset><button v-if="form.hypotheses.length<10" type="button" class="secondary-button" @click="form.hypotheses.push({statement:'',alternative:'',falsification:''})">{{t('添加假设','Add hypothesis')}}</button>
  <h3>{{t('变量与对照','Factors and control')}}</h3><fieldset v-for="(f,i) in form.factors" :key="i" class="two"><label>{{t('变量 ID（英文字母、数字、下划线）','Factor ID (letters, digits, underscore)')}}<input v-model="f.key" required pattern="[a-z][a-z0-9_]{0,39}"/></label><label>{{t('变量名称','Factor name')}}<input v-model="f.label" data-field="factor-label" required/></label><label>{{t('单位','Unit')}}<input v-model="f.unit" data-field="factor-unit" required/></label><label>{{t('变量类型','Factor type')}}<select v-model="f.kind"><option value="continuous">{{t('连续','Continuous')}}</option><option value="discrete">{{t('离散','Discrete')}}</option></select></label><label>{{t('水平（2–5 个递增数值，逗号分隔）','Levels (2–5 increasing numbers, comma-separated)')}}<input v-model="f.levels" data-field="levels" required placeholder="0, 10, 20"/></label><label>{{t('对照值','Control value')}}<input v-model.number="f.control" data-field="control" type="number" step="any" required/></label><label>{{t('高于最低水平每单位增加的成本（元）','Additional CNY per unit above minimum')}}<input v-model.number="f.costPerUnitCny" type="number" step="any" min="0" required/></label><button v-if="i>0" type="button" class="secondary-button" @click="form.factors.splice(i,1)">{{t('移除变量','Remove factor')}}</button></fieldset>
  <button v-if="form.factors.length<3" type="button" class="secondary-button" @click="form.factors.push({key:'factor_'+(form.factors.length+1),label:'',unit:'',kind:'continuous',levels:'',costPerUnitCny:0,control:0})">{{t('添加变量','Add factor')}}</button>
  <div class="two"><label>{{t('批次/区组（每行一个，各区组包含全部点）','Blocks (one per line; all points in each block)')}}<textarea v-model="form.blocks" required/></label><label>{{t('每点每区组独立制备数（1–5）','Independent preparations per point/block (1–5)')}}<input v-model.number="form.replicates" type="number" min="1" max="5" required/></label></div>
  <h3>{{t('成本与运行上限','Cost and limits')}}</h3><div class="two"><label>{{t('每单元基础成本（元）','Base CNY per unit')}}<input v-model.number="form.baseCostCny" type="number" min="0.01" step="any" required/></label><label>{{t('每单元预计分钟数','Estimated minutes per unit')}}<input v-model.number="form.minutesPerRun" type="number" min="0.01" step="any" required/></label><label>{{t('总费用上限（元）','Cost limit (CNY)')}}<input v-model.number="form.maxCostCny" type="number" min="0.01" step="any" required/></label><label>{{t('总时间上限（分钟）','Time limit (minutes)')}}<input v-model.number="form.maxMinutes" type="number" min="0.01" step="any" required/></label><label>{{t('单轮实验单元上限（2–400）','Units per design limit (2–400)')}}<input v-model.number="form.maxRuns" type="number" min="2" max="400" required/></label></div>
  <label>{{t('成本估算依据','Cost estimate basis')}}<textarea v-model="form.costBasis" data-field="cost-basis" required/></label><label>{{t('可加工性与待确认限制','Manufacturability and unresolved limits')}}<textarea v-model="form.manufacturabilityNotes" data-field="manufacturability" required/></label>
  <details><summary>{{t('高级线性约束','Advanced linear constraints')}}</summary><p class="field-help">terms · min · max · reason；{{t('没有上下限时使用 null，例如','Use null for an unbounded side, e.g.')}} [{"terms":{"factor_1":1},"min":null,"max":20,"reason":"process limit"}]</p><textarea v-model="form.constraints" rows="5"/></details>
  <p v-if="error" role="alert">{{error}}</p><div class="actions"><button class="primary-button" type="submit" :disabled="busy">{{t('保存研究条件','Save study')}}</button><button class="secondary-button" type="button" :disabled="busy" @click="emit('cancel')">{{t('取消','Cancel')}}</button></div>
</form>
</template>
<style scoped>
.study-form{display:grid;gap:16px;color:var(--text)}h3{margin:8px 0 0;font-size:15px}.two{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}label{display:grid;gap:7px;font-size:13px}fieldset{border:1px solid var(--line);border-radius:10px;padding:16px;min-width:0;display:grid;gap:14px}input,select,textarea{width:100%;min-width:0;box-sizing:border-box;background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:7px;padding:9px;font:inherit}textarea{resize:vertical}.source-check{display:flex;align-items:center;margin-top:10px}.source-check input{width:auto}.actions{display:flex;gap:10px;flex-wrap:wrap}@media(max-width:650px){.two{grid-template-columns:1fr}}
</style>
