<script setup lang="ts">
import {computed,ref,watch} from 'vue';
import {ElDrawer} from 'element-plus';
import {FlaskConical,RefreshCw} from '@lucide/vue';
import NextExperimentEditor from './NextExperimentEditor.vue';
import ExperimentFeedbackEditor from './ExperimentFeedbackEditor.vue';
import MarkdownContent from './MarkdownContent.vue';
import type {NextExperimentOverview,StudyInput,FeedbackInput,NextDesignInput,NextExperimentDesign} from '../../../../../packages/contracts/src/next-experiment.js';
import type {ExperimentRun} from '../../../../../packages/contracts/src/experiments.js';
import type {ResearchSnapshot} from '../../../../../packages/contracts/src/research-project.js';
const props=defineProps<{projectId:string;projectPath:string;active:boolean;locale:'zh'|'en'}>(),emit=defineEmits<{changed:[];example:[text:string]}>();
const t=(zh:string,en:string)=>props.locale==='zh'?zh:en,state=ref<NextExperimentOverview|null>(null),snapshots=ref<ResearchSnapshot[]>([]),runs=ref<ExperimentRun[]>([]),busy=ref(false),error=ref(''),editor=ref(false),feedbackOpen=ref(false),preview=ref('');
const method=ref<NextDesignInput['method']>('factorial'),points=ref(8),seed=ref(2026),reason=ref(''),previewName=ref('');
const latest=computed(()=>state.value?.designs.filter(d=>d.studyId===state.value?.study?.id).at(-1));
const messages:Record<string,[string,string]>={NEED_EIGHT_DISTINCT_REVIEWED_CONDITIONS:['至少需要 8 个不同变量组合的已核对测量结果','Need at least 8 distinct reviewed measured conditions'],SURROGATE_DID_NOT_BEAT_TRAINING_MEAN_BASELINE:['留出验证未优于均值基线；请补数据或使用 DOE','Holdout did not beat the mean baseline; collect data or use DOE'],RUN_BUDGET_EXCEEDED:['完整方案的实验单元数超过上限','Complete design exceeds the unit limit'],ESTIMATED_COST_BUDGET_EXCEEDED:['完整方案的预计费用超过上限','Complete design exceeds the cost limit'],ESTIMATED_TIME_BUDGET_EXCEEDED:['完整方案的预计时间超过上限','Complete design exceeds the time limit'],DUPLICATE_SOURCE_IDENTITY:['同一来源被重复用作实验单元','A source was reused as an experimental unit'],SURROGATE_LIMIT_64_CONDITIONS:['当前代理模型最多支持 64 个不同组合','The current surrogate supports up to 64 distinct conditions'],NO_NEW_TREATMENT_POINTS:['没有可用的新处理点','No new treatment points'],DUPLICATE_TREATMENT_POINTS:['存在重复处理点；请调整离散水平或采样数','Duplicate treatment points; adjust discrete levels or sample count'],INSUFFICIENT_NEW_FEASIBLE_POINTS:['可用的新组合不足，请减少候选数','Not enough new feasible combinations; reduce candidate count']};
function explanation(s:string){if(s.startsWith('CONSTRAINTS_BREAK_FULL_FACTORIAL'))return t('约束排除了部分组合，不能继续称为全因子设计。请调整水平或选择空间填充。','Constraints remove combinations from the full factorial; adjust levels or use space-filling.');if(s.startsWith('CONSTRAINTS_BREAK_LATIN_HYPERCUBE'))return t('约束破坏了分层采样。请调整范围；系统不会静默删除点。','Constraints break stratification. Adjust bounds; points are never silently dropped.');return messages[s]?t(...messages[s]):s;}
async function load(){const id=props.projectId,[o,p,e]=await Promise.all([window.materialsx.getNextExperiments(id),window.materialsx.getResearchProject(id),window.materialsx.getExperiments(id)]);if(props.projectId!==id)return;state.value=o;snapshots.value=p.snapshots.filter(s=>p.project.selected.includes(s.id)&&!s.data.accessDenied);runs.value=e.runs;}
async function perform(fn:()=>Promise<unknown>){busy.value=true;error.value='';try{await fn();}catch(e){error.value=String(e);}finally{busy.value=false;}}
watch(()=>props.projectId,()=>{state.value=null;editor.value=false;feedbackOpen.value=false;preview.value='';void perform(load);},{immediate:true});
watch(()=>props.active,value=>{if(value)void perform(load);});
async function save(input:StudyInput){await perform(async()=>{await window.materialsx.saveResearchStudy(props.projectId,input);editor.value=false;await load();emit('changed');});}
async function record(input:FeedbackInput){await perform(async()=>{await window.materialsx.recordExperimentFeedback(props.projectId,JSON.parse(JSON.stringify(input)));feedbackOpen.value=false;await load();emit('changed');});}
async function design(){if(!state.value?.study)return;await perform(async()=>{await window.materialsx.designNextExperiments(props.projectId,{studyId:state.value!.study!.id,method:method.value,points:points.value,seed:seed.value,reason:reason.value});await load();});}
function reveal(){if(latest.value?.artifacts[0])void window.materialsx.revealArtifact(props.projectPath+'/'+latest.value.artifacts[0].path);}
async function show(d:NextExperimentDesign,name:string){await perform(async()=>{const a=d.artifacts.find(a=>a.path.endsWith('/'+name));if(!a)throw Error('ARTIFACT_NOT_FOUND');preview.value=await window.materialsx.previewNextExperiment(props.projectId,d.id,a.path);previewName.value=name;});}
</script>
<template>
<section data-testid="next-experiment-panel" class="next-experiments" v-if="state">
  <article class="study-card"><header><div class="title"><FlaskConical :size="22"/><div><h2>{{t('下一轮实验','Next experiments')}}</h2><p>{{t('研究条件、实验安排与结果反馈','Study conditions, experimental schedule and outcomes')}}</p></div></div><div class="actions"><button class="secondary-button" :disabled="busy" @click="perform(load)"><RefreshCw :size="14"/>{{t('刷新','Refresh')}}</button><button class="primary-button" :disabled="busy" @click="editor=true">{{state.study?t('编辑条件','Edit study'):t('建立研究条件','Set up study')}}</button></div></header>
    <template v-if="state.study"><div class="study-summary"><strong>{{state.study.input.question}}</strong><span>{{state.study.input.materialSystem}} · {{state.study.input.response.property}} / {{state.study.input.response.unit}}</span><span>{{state.study.input.experimentalUnit}} · {{state.study.input.measurementConditions}}</span></div><div class="stats"><div><small>{{t('独立制备 / 点 / 区组','Preparations / point / block')}}</small><strong>{{state.study.input.replicates}}</strong></div><div><small>{{t('区组','Blocks')}}</small><strong>{{state.study.input.blocks.length}}</strong></div><div><small>{{t('费用上限','Cost limit')}}</small><strong>¥ {{state.study.input.maxCostCny}}</strong></div><div><small>{{t('单轮实验上限','Units per design')}}</small><strong>{{state.study.input.maxRuns}}</strong></div></div><details><summary>{{t('假设与限制','Hypotheses and limits')}}</summary><div v-for="(h,i) in state.study.input.hypotheses" :key="i"><p>{{h.statement}}</p><p>{{t('替代解释','Alternative')}}: {{h.alternative}}</p><p>{{t('否定条件','Falsification')}}: {{h.falsification}}</p></div><p>{{state.study.input.manufacturabilityNotes}}</p><p>{{state.study.input.costBasis}}</p></details></template>
    <p v-else class="field-help">{{t('先定义变量、测量条件、对照和费用上限，再生成方案。','Define factors, measurement conditions, control and cost limits before generating a plan.')}}</p>
  </article>
  <p v-if="error" class="error" role="alert">{{error}}</p>
  <article v-if="state.study" class="study-card"><header><h3>{{t('生成实验安排','Generate a design')}}</h3><button class="secondary-button" :disabled="busy" @click="emit('example',t('@materials-next-experiment 根据当前研究条件生成下一轮实验方案。先读取真实反馈，数据不足时采用 DOE，输出候选表、带对照和独立重复的随机实验顺序及方案报告。','@materials-next-experiment Design the next experiments using the saved study. Read actual feedback; use DOE when data are insufficient. Deliver candidates, a randomized schedule with controls and independent preparations, and a report.'))">{{t('在对话中使用','Use in chat')}}</button></header>
    <form class="design-form" @submit.prevent="design"><label>{{t('设计方法','Method')}}<select v-model="method"><option value="factorial">{{t('全因子 DOE','Full factorial DOE')}}</option><option value="latin-hypercube">{{t('空间填充（LHS）','Space-filling (LHS)')}}</option><option value="bayesian">{{t('贝叶斯优化','Bayesian optimization')}}</option><option value="active-learning">{{t('主动学习','Active learning')}}</option></select></label><label>{{t('采样点数（全因子忽略此项）','Points (ignored for factorial)')}}<input v-model.number="points" type="number" min="1" max="32" :disabled="method==='factorial'" required/></label><label>{{t('随机种子','Random seed')}}<input v-model.number="seed" type="number" min="1" max="4294967295" required/></label><label class="wide">{{t('本轮目的','Purpose of this round')}}<input v-model="reason" data-field="design-reason" required/></label><button class="primary-button" :disabled="busy">{{t('生成方案','Generate plan')}}</button></form><p class="field-help">{{t('每个区组包含全部对照和处理点。预算不足会阻止整个方案，不会悄悄减少重复。优化需通过真实反馈和留出验证门槛。','Every block includes all controls and treatments. Budget limits block the complete plan rather than reduce replicates. Optimization requires source-linked feedback and a holdout gate.')}}</p>
  </article>
  <article v-if="latest" class="study-card"><header><div><h3>{{latest.result.status==='planned'?t('本轮候选与安排','Candidates and schedule'):t('本轮方案需要调整','This design needs adjustment')}}</h3><p>{{latest.request.method}} · {{latest.createdAt}} · {{latest.historical?t('历史方案','Historical plan'):t('当前输入','Current inputs')}}{{latest.sourceInvalid?' · '+t('来源失效','Source invalid'):''}}</p></div><span class="status">{{t('尚未执行实体实验','Physical experiments not executed')}}</span></header>
    <div class="stats"><div><small>{{t('实验单元','Planned units')}}</small><strong>{{latest.result.schedule.length}}</strong></div><div><small>{{t('预计费用','Estimated cost')}}</small><strong>¥ {{latest.result.estimatedCostCny.toFixed(2)}}</strong></div><div><small>{{t('预计时间','Estimated time')}}</small><strong>{{latest.result.estimatedMinutes}} min</strong></div><div><small>{{t('不同测量组合','Measured conditions')}}</small><strong>{{latest.result.optimization.uniqueConditions}}</strong></div></div>
    <p v-for="s in latest.result.reasons" :key="s" class="notice">{{explanation(s)}}</p>
    <div class="table-wrap"><table><thead><tr><th>{{t('候选','Candidate')}}</th><th v-for="f in state.study?.input.factors" :key="f.key">{{f.label}} / {{f.unit}}</th><th>CNY</th><th>{{t('预测','Prediction')}}</th><th>{{t('后验标准差','Posterior SD')}}</th></tr></thead><tbody><tr v-for="(p,i) in latest.result.points" :key="p.id"><td>{{i===0?t('对照','Control'):p.id}}</td><td v-for="f in state.study?.input.factors" :key="f.key">{{Number(p.factors[f.key]?.toPrecision(5))}}</td><td>{{p.costCny.toFixed(2)}}</td><td>{{p.prediction?.toPrecision(5)??'—'}}</td><td>{{p.sd?.toPrecision(5)??'—'}}</td></tr></tbody></table></div>
    <details><summary>{{t('优化门槛与基线','Optimization gate and baselines')}}</summary><p>{{latest.result.optimization.enabled?t('已通过固定留出门槛；仍需科研复核','Passed fixed holdout gate; scientific review still required'):t('尚未启用代理优化','Surrogate optimization is not enabled')}}</p><p v-for="s in latest.result.optimization.reasons" :key="s">{{explanation(s)}}</p><p v-if="latest.result.optimization.validation">RMSE: {{latest.result.optimization.validation.rmse?.toPrecision(5)}} · {{t('均值基线','Mean baseline')}}: {{latest.result.optimization.validation.baselineRmse?.toPrecision(5)}}</p><p v-for="b in latest.result.baselines" :key="b.method">{{b.method}} · {{b.points}} · {{t('预测收益 / 成本','Acquisition / cost')}}: {{b.meanAcquisitionPerCost?.toPrecision(5)??'—'}}</p><p class="field-help">{{t('以上为候选的模型评分，不能说明实际实验优于 DOE 或随机方案。后验标准差尚未做测量误差校准。','These are model scores, not measured superiority over DOE or random designs. Posterior SD is not calibrated measurement error.')}}</p></details>
    <div class="actions"><button v-for="name in ['report.md','candidates.csv','schedule.csv','design.json','replay.mjs']" :key="name" class="secondary-button" :disabled="busy" @click="show(latest!,name)">{{name}}</button><button class="secondary-button" :disabled="busy" @click="reveal">{{t('打开文件夹','Show files')}}</button></div>
  </article>
  <article v-if="state.study" class="study-card"><header><div><h3>{{t('实验反馈','Experimental outcomes')}}</h3><p>{{t('记录测量、失败与条件偏离；更正保留历史。','Record measurements, failures and deviations; corrections preserve history.')}}</p></div><button class="primary-button" :disabled="busy||!state.designs.some(d=>d.studyId===state!.study!.id&&d.result.status==='planned')" @click="feedbackOpen=true">{{t('登记实验结果','Record an outcome')}}</button></header><p v-if="!state.feedback.length" class="field-help">{{t('完成实体实验后，导入测量数据并关联对应实验单元。','After physical experiments, import measurements and link each experimental unit.')}}</p><div v-for="f in state.feedback.slice().reverse()" :key="f.id" class="feedback-row"><strong>{{f.input.plannedRunId}} · {{f.input.outcome}} · {{f.value??'—'}} {{f.unit}}</strong><small>{{f.input.reviewed?t('已核对数据','Data checked'):t('待核对数据','Data review pending')}} · {{f.createdAt}} · {{f.sourceIdentity??t('用户失败记录，无测量','User report, no measurement')}}</small><p>{{f.input.notes}}</p><small v-if="f.deviations.length">{{f.deviations.join(' · ')}}</small><small v-if="state.feedback.some(n=>n.input.supersedes===f.id)">{{t('已被更正替代，优化不再使用','Superseded; excluded from optimization')}}</small></div></article>
  <details v-if="state.designs.length" class="study-card"><summary>{{t('方案与条件历史','Design and study history')}}</summary><div v-for="d in state.designs.slice().reverse()" :key="d.id" class="history"><span>{{d.createdAt}} · {{d.request.method}} · {{d.result.status}} · {{d.studyId.slice(0,8)}}</span><button class="secondary-button" :disabled="busy" @click="show(d,'report.md')">{{t('查看方案','View report')}}</button></div><p>{{t('研究条件版本','Study versions')}}: {{state.studies.length}} · {{t('项目版本','Project revision')}}: {{state.projectRevision}}</p></details>
  <ElDrawer v-model="editor" class="next-experiment-drawer" :title="t('研究条件','Study settings')" size="min(900px,96vw)" append-to-body><NextExperimentEditor v-if="editor" :study="state.study" :sources="snapshots" :revision="state.projectRevision" :locale="locale" :busy="busy" @save="save" @cancel="editor=false"/><p v-if="error" role="alert" class="error">{{error}}</p></ElDrawer>
  <ElDrawer v-model="feedbackOpen" class="next-experiment-drawer" :title="t('登记实验结果','Record an outcome')" size="min(900px,96vw)" append-to-body><ExperimentFeedbackEditor v-if="feedbackOpen&&state.study" :study="state.study" :revision="state.projectRevision" :designs="state.designs.filter(d=>!d.sourceInvalid)" :feedback="state.feedback" :runs="runs" :snapshots="snapshots" :locale="locale" :busy="busy" @save="record"/><p v-if="error" role="alert" class="error">{{error}}</p></ElDrawer>
  <ElDrawer :model-value="!!preview" class="next-experiment-drawer" :title="previewName" size="min(1100px,96vw)" append-to-body @update:model-value="preview=''"><MarkdownContent v-if="previewName.endsWith('.md')" :content="preview"/><pre v-else class="artifact">{{preview}}</pre></ElDrawer>
</section>
</template>
<style scoped>
.next-experiments{display:grid;gap:18px;min-width:0;max-width:100%;color:var(--text)}.study-card{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:22px;min-width:0;overflow-wrap:anywhere}header,.actions,.title{display:flex;gap:12px;align-items:center}header{justify-content:space-between;flex-wrap:wrap}.actions{flex-wrap:wrap}h2,h3{margin:0;font-size:17px}p{font-size:13px;line-height:1.7;color:var(--muted)}.study-summary{display:grid;gap:8px;margin:20px 0;font-size:14px}.study-summary span,small{color:var(--muted);font-size:12px}.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:18px 0}.stats>div{display:grid;gap:9px;background:var(--panel-2);padding:14px;border-radius:9px}.stats strong{font-size:20px}.design-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin:18px 0}.design-form .wide{grid-column:1/-1}label{display:grid;gap:7px;font-size:13px}input,select{box-sizing:border-box;width:100%;min-width:0;padding:9px;background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:7px;font:inherit}.table-wrap{overflow:auto;max-width:100%;margin:18px 0}table{border-collapse:collapse;width:100%;font-size:13px;white-space:nowrap}td,th{padding:12px;text-align:left;border-bottom:1px solid var(--line)}th{color:var(--muted);font-weight:500}.status{font-size:12px;color:var(--muted)}.notice,.error{padding:12px;border:1px solid var(--line);border-radius:8px;background:var(--panel-2);overflow-wrap:anywhere}.error{color:var(--danger)}.feedback-row{display:grid;gap:8px;padding:15px 0;border-top:1px solid var(--line);font-size:13px}.feedback-row p{margin:0}.history{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid var(--line);font-size:13px}.artifact{white-space:pre-wrap;overflow-wrap:anywhere;max-width:100%;font-size:12px;color:var(--text)}details summary{cursor:pointer;font-size:13px}
:global(.next-experiment-drawer.el-drawer){background:var(--panel);color:var(--text)}:global(.next-experiment-drawer .el-drawer__header){color:var(--text);margin-bottom:18px}
@media(max-width:780px){.stats{grid-template-columns:repeat(2,minmax(0,1fr))}.design-form{grid-template-columns:1fr}.study-card{padding:16px}.history{flex-wrap:wrap}}
</style>
