<script setup lang="ts">
import {ref,watch,computed} from 'vue';
import {ElDrawer,ElMessageBox} from 'element-plus';
import {Search,BookOpen,Download,FileOutput,RefreshCw} from '@lucide/vue';
import type {PaperRecord,PaperSearchResult,PaperReading} from '../../../../../packages/contracts/src/papers.js';
const props=defineProps<{projectId:string;locale:'zh'|'en'}>();
const emit=defineEmits<{example:[text:string]}>();
const t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
const papers=ref<PaperRecord[]>([]),result=ref<PaperSearchResult|null>(null),query=ref(''),english=ref(''),from=ref(''),to=ref(''),publicTerms=ref(false),external=ref(false),busy=ref(false),error=ref('');
const selected=ref<string[]>([]),detail=ref<PaperRecord|null>(null),reading=ref<PaperReading|null>(null),drawer=ref(false),firstPage=ref(1),lastPage=ref<number|null>(null),exportPath=ref('');
const records=computed(()=>result.value?.provider==='arxiv'?papers.value.filter(r=>result.value!.items.some(p=>p.paperId===r.paper.paperId)):papers.value);
const state=(s:string)=>({metadata_only:t('摘要与元数据','Abstract & metadata'),downloaded:t('PDF 已下载','PDF downloaded'),partially_read:t('部分页面已读','Some pages read'),fully_read:t('全文文字已读','Full text read')}[s]??s);
let generation=0;
const cancel=()=>window.materialsx.cancelPaperOperations(props.projectId);
async function load(){const id=props.projectId,g=++generation;const rows=await window.materialsx.listPapers(id);if(id===props.projectId&&g===generation)papers.value=rows;}
watch(()=>props.projectId,()=>{result.value=null;selected.value=[];detail.value=null;drawer.value=false;error.value='';void load().catch(e=>error.value=String(e));},{immediate:true});
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await fn();}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function search(page=0){await run(async()=>{result.value=await window.materialsx.searchPapers(props.projectId,{query:query.value,...(english.value?{queryEnglish:english.value}:{}),source:external.value?'arxiv':'local-first',...(from.value?{from:from.value}:{}),...(to.value?{to:to.value}:{}),page,publicQueryConfirmed:true});await load();});}
async function open(r:PaperRecord){detail.value=r;reading.value=r.reading;drawer.value=true;firstPage.value=1;lastPage.value=r.reading?Math.min(5,r.reading.totalPages):null;}
async function download(r:PaperRecord){await run(async()=>{await ElMessageBox.confirm(t('下载固定版本 PDF，仅供本机研究使用。不会发布或转售全文。','Download the fixed PDF version for local research only. This does not authorize redistribution.'),t('下载论文','Download paper'),{confirmButtonText:t('下载','Download'),cancelButtonText:t('取消','Cancel')});const updated=await window.materialsx.fetchPaper(props.projectId,{paperId:r.paper.paperId,grant:'personal-research'});await load();if(detail.value?.paper.paperId===r.paper.paperId)detail.value=updated;});}
async function read(){const id=detail.value?.paper.paperId;if(!id)return;await run(async()=>{reading.value=await window.materialsx.readPaper(props.projectId,{paperId:id,fromPage:firstPage.value,...(lastPage.value!==null?{toPage:lastPage.value}:{})});await load();detail.value=papers.value.find(r=>r.paper.paperId===id)??null;});}
async function exportSelected(format:'bibtex'|'json'|'csv'|'markdown'){await run(async()=>{exportPath.value=(await window.materialsx.exportPapers(props.projectId,{paperIds:selected.value,format})).path;});}
</script>
<template>
<section class="paper-library" data-testid="paper-library">
  <header><div><h2>{{t('论文库','Paper library')}}</h2><p>{{t('优先复用项目和 MOOS；补充 arXiv 预印本。保留版本、页码和来源。','Reuse project and MOOS sources first; supplement with arXiv preprints. Preserve versions, pages and sources.')}}</p></div><button class="secondary-button" :disabled="busy" @click="run(load)"><RefreshCw :size="14"/>{{t('刷新','Refresh')}}</button></header>
  <form class="paper-form" @submit.prevent="search()">
    <label>{{t('研究关键词','Research keywords')}}<input v-model="query" :placeholder="t('例如：机器学习势','e.g. machine learning potentials')" maxlength="160" required/></label>
    <label>{{t('英文关键词（中文术语不足时补充）','English keywords (optional)')}}<input v-model="english" placeholder="machine learning interatomic potentials" maxlength="160"/></label>
    <label>{{t('首次提交日期 · UTC，从','First submission · UTC, from')}}<input v-model="from" type="date"/></label><label>{{t('至','To')}}<input v-model="to" type="date"/></label>
    <label class="check"><input v-model="external" type="checkbox"/>{{t('直接查询 arXiv 最新论文','Search arXiv directly for new papers')}}</label>
    <label class="check"><input v-model="publicTerms" type="checkbox"/>{{t('仅发送公开研究关键词，不含私有配方、路径或个人数据','Send public research keywords only; no private recipes, paths or personal data')}}</label>
    <div class="paper-actions"><button class="primary-button" :disabled="busy||!publicTerms||!query.trim()"><Search :size="15"/>{{busy?t('处理中…','Working…'):t('检索','Search')}}</button><button v-if="busy" type="button" class="secondary-button" @click="cancel">{{t('取消','Cancel')}}</button></div>
  </form>
  <p v-if="error" role="alert" class="paper-error">{{error}}</p>
  <div v-if="result" class="search-receipt"><span>{{result.provider}} · {{result.cacheAsOf?t('缓存','Cached'):t('来源回执','Source receipt')}} · {{result.fetchedAt}}</span><strong v-if="result.stale">{{t('离线缓存，非实时结果','Offline cache, not live results')}}</strong><p>{{result.queryExecuted}}</p><p v-if="result.limitation">{{result.limitation}}</p><p v-if="result.localSources.length">{{t('找到本地材料记录，请在“材料数据”中选择并阅读。','Local records found; select and read them in the Materials data tab.')}}</p></div>
  <div v-if="papers.length" class="paper-actions"><span>{{t('已选','Selected')}} {{selected.length}}</span><button v-for="format in (['bibtex','json','csv','markdown'] as const)" :key="format" class="secondary-button" :disabled="busy||!selected.length" @click="exportSelected(format)"><FileOutput :size="14"/>{{format}}</button></div>
  <p v-if="exportPath" class="path">{{t('已保存：','Saved: ')}}{{exportPath}}</p>
  <div class="paper-grid"><article v-for="r in records" :key="r.paper.paperId" class="paper-card"><div class="card-top"><label class="check"><input v-model="selected" type="checkbox" :value="r.paper.paperId"/>arXiv {{r.paper.arxivId}}</label><span>{{state(r.status)}}</span></div><h3>{{r.paper.titleOriginal}}</h3><p>{{r.paper.authors.slice(0,5).join(', ')}}{{r.paper.authors.length>5?'…':''}}</p><p class="abstract">{{r.paper.abstractOriginal}}</p><small>{{r.paper.publishedAt.slice(0,10)}} · {{r.paper.categories.join(', ')}}</small><div class="paper-actions"><button class="secondary-button" @click="open(r)"><BookOpen :size="14"/>{{t('详情与阅读','Details & reading')}}</button><button v-if="!r.file" class="secondary-button" :disabled="busy" @click="download(r)"><Download :size="14"/>{{t('下载 PDF','Download PDF')}}</button></div></article></div>
  <p v-if="!records.length" class="paper-empty">{{t('还没有论文结果。可先试试“机器学习势”。','No paper results yet. Try “machine learning potentials”.')}}</p>
  <button v-if="result?.nextPage!==null&&result?.nextPage!==undefined" class="secondary-button" :disabled="busy" @click="search(result.nextPage)">{{t('下一页','Next page')}}</button>
  <button class="secondary-button" @click="emit('example',t('查找最近一年机器学习势相关的 arXiv 论文，先检查项目和 MOOS，再补充公开来源。保留固定版本，下载并读取一篇最相关论文的前 5 页，导出文献 JSON 和 BibTeX。','Find arXiv papers on machine learning interatomic potentials from the last year. Check project and MOOS first, then public sources. Pin a version, download and read the first five pages of one relevant paper, and export JSON and BibTeX.'))">{{t('使用检索示例','Use search example')}}</button>
  <ElDrawer class="paper-reading-drawer" v-model="drawer" :title="t('论文详情','Paper details')" size="min(760px, 94vw)"><div v-if="detail" class="paper-detail"><h2>{{detail.paper.titleOriginal}}</h2><p>{{detail.paper.authors.join(', ')}}</p><p>{{detail.paper.abstractOriginal}}</p><p>{{state(detail.status)}} · {{t('预印本，未核实同行评审','Preprint; peer review not verified')}}</p><a :href="detail.paper.abstractUrl" target="_blank" rel="noopener noreferrer">{{t('arXiv 原始页面','Original arXiv page')}}</a><p class="path">{{detail.paper.arxivId}} · SHA {{detail.file?.sha256??detail.paper.metadataSha256}}</p><div class="paper-actions"><button v-if="!detail.file" class="primary-button" :disabled="busy" @click="download(detail)">{{t('下载 PDF','Download PDF')}}</button><template v-else><label>{{t('页码','Pages')}}<input v-model.number="firstPage" type="number" min="1"/></label><label>—<input v-model.number="lastPage" type="number" min="1" :placeholder="t('自动','Auto')"/></label><button class="primary-button" :disabled="busy" @click="read">{{t('读取页面','Read pages')}}</button></template></div><template v-if="reading"><p>{{t('已读文字页面','Text pages read')}} {{reading.readPages.length}} / {{reading.totalPages}} · {{t('图片尚未审阅','Images not reviewed')}}</p><p v-if="reading.missingPages.length">{{t('缺失文字的页面','Pages with missing text')}}: {{reading.missingPages.join(', ')}}</p><article v-for="page in reading.pages" :key="page.page"><h3>{{t('第','Page ')}}{{page.page}}{{t('页','')}}</h3><pre>{{page.text}}</pre></article></template></div></ElDrawer>
</section>
</template>
<style scoped>
:global(.paper-reading-drawer.el-drawer){background:var(--panel);color:var(--text);border-left:1px solid var(--line)}:global(.paper-reading-drawer .el-drawer__header),:global(.paper-reading-drawer .el-drawer__close-btn){color:var(--text)}:global(.paper-reading-drawer .el-drawer__body){background:var(--panel)}

.paper-library{min-width:0;border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:22px;display:grid;gap:16px;color:var(--text);box-sizing:border-box;max-width:100%}.paper-library header,.card-top{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.paper-library h2{font-size:18px;margin:0}.paper-library p{color:var(--muted);font-size:13px;line-height:1.7;margin:8px 0}.paper-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.paper-form label,.paper-detail label{display:grid;gap:6px;font-size:13px}.paper-form .check{grid-column:1/-1}.check{display:flex!important;align-items:center;gap:8px;font-size:12px}.check input{width:auto}.paper-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.paper-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,330px),1fr));gap:14px}.paper-card{min-width:0;background:var(--panel-2);border:1px solid var(--line);border-radius:12px;padding:18px;display:flex;flex-direction:column;gap:10px;overflow-wrap:anywhere}.paper-card h3{font-size:15px;line-height:1.6;margin:0}.paper-card .paper-actions{margin-top:auto}.abstract{display:-webkit-box;-webkit-line-clamp:4;-webkit-box-orient:vertical;overflow:hidden}.paper-card small,.card-top span{color:var(--muted);font-size:12px}.search-receipt{padding:12px;border:1px solid var(--line);border-radius:8px;font-size:12px;overflow-wrap:anywhere}.paper-error{color:var(--danger)!important;overflow-wrap:anywhere}.paper-empty{padding:20px;text-align:center}.path{overflow-wrap:anywhere;font-size:12px}.paper-detail{color:var(--text);overflow-wrap:anywhere}.paper-detail pre{background:var(--panel-2);color:var(--text);white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.8;font-size:13px;padding:14px;border:1px solid var(--line);border-radius:8px}.paper-detail .paper-actions input{max-width:90px}input{width:100%;box-sizing:border-box;min-width:0;border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:8px;padding:9px;font:inherit}@media(max-width:780px){.paper-form{grid-template-columns:1fr}.paper-library{padding:16px}}
</style>
