<script setup lang="ts">
import ExamplePrompts from './ExamplePrompts.vue';
import {ref,computed,onMounted,onUnmounted,watch} from 'vue';
import {ElDrawer} from 'element-plus';
import {Radar,ArrowRight,ChevronDown,RefreshCw} from '@lucide/vue';
import type {DiscoveryRecord} from '../../../../../packages/contracts/src/potential-discovery.js';
const props=defineProps<{locale:'zh'|'en'}>();const emit=defineEmits<{'use-example':[prompt:string]}>();
const api=window.materialsx,t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
const expanded=ref(false),busy=ref(false),error=ref(''),query=ref(''),filter=ref<'all'|'pending'|'approved'|'rejected'|'withdrawn'|'paper_only'>('all'),page=ref(0),total=ref(0),mode=ref('records');
const records=ref<DiscoveryRecord[]>([]),selected=ref<DiscoveryRecord|null>(null),evidence=ref<Awaited<ReturnType<typeof api.readPotentialEvidence>>|null>(null);
const discovery=ref<Awaited<ReturnType<typeof api.getPotentialDiscovery>>|null>(null),updates=ref<Awaited<ReturnType<typeof api.getPotentialUpdates>>|null>(null);
const visible=computed({get:()=>!!selected.value,set:(v:boolean)=>{if(!v)selected.value=null;}});
async function load(){try{const [d,u,r]=await Promise.all([api.getPotentialDiscovery(),api.getPotentialUpdates(),api.searchPotentialDiscovery({query:query.value,status:filter.value,offset:page.value*24,limit:24})]);discovery.value=d;updates.value=u;records.value=r.records;total.value=r.total;}catch(e){error.value=e instanceof Error?e.message:String(e);}}
async function action(fn:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';try{await fn();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{busy.value=false;await load();}}
async function open(r:DiscoveryRecord){selected.value=r;evidence.value=null;await action(async()=>{evidence.value=await api.readPotentialEvidence(r.id);});}
function example(prompt:string){selected.value=null;emit('use-example',prompt);}
const status=(r:DiscoveryRecord)=>r.observation.status==='withdrawn'?t('来源已撤回','Source withdrawn'):r.review.status==='approved'?t('资料已审核','Details reviewed'):r.review.status==='rejected'?t('未通过审核','Review rejected'):r.observation.kind==='paper'?t('论文线索 · 暂无可用模型','Paper · no runnable model'):t('待审核','Pending review');
let remove:(()=>void)|undefined,removeDiscovery:(()=>void)|undefined,debounce:ReturnType<typeof setTimeout>|undefined;
onMounted(()=>{remove=api.onPotentialCatalogChanged(()=>{if(expanded.value)void load();});removeDiscovery=api.onPotentialDiscoveryChanged(()=>{if(expanded.value)void load();});});onUnmounted(()=>{remove?.();removeDiscovery?.();if(debounce)clearTimeout(debounce);});
watch(expanded,v=>{if(v)void load();});
watch([query,filter],()=>{page.value=0;if(debounce)clearTimeout(debounce);debounce=setTimeout(()=>{if(expanded.value)void load();},200);});watch(page,()=>{if(expanded.value)void load();});
</script>
<template>
 <section class="potential-updates model-tools-panel" data-testid="potential-updates">
  <button class="model-tools-toggle" data-testid="updates-toggle" :aria-expanded="expanded" aria-controls="updates-content" @click="expanded=!expanded"><span class="model-tools-icon"><Radar :size="20"/></span><span class="model-tools-heading"><strong>{{t('新模型与目录更新','New models & catalog updates')}}</strong><span>{{t('浏览公开来源的新模型，检查目录更新。','Browse new models from public sources and check catalog updates.')}}</span></span><ChevronDown :size="18" class="model-tools-chevron" :class="{expanded}"/></button>
  <div v-if="expanded" id="updates-content" class="model-tools-body" data-testid="updates-content">
   <div class="discovery-overview"><div class="discovery-metrics"><div><strong>{{discovery?.total??'—'}}</strong><span>{{t('发现记录','Discoveries')}}</span></div><div><strong>{{discovery?.pending??'—'}}</strong><span>{{t('待审核','Pending review')}}</span></div><div><strong>{{discovery?.sources.length??'—'}}</strong><span>{{t('公开来源','Public sources')}}</span></div></div><button class="secondary-button" :disabled="busy||discovery?.busy" data-testid="discovery-sync" @click="action(()=>api.syncPotentialDiscovery({}))"><RefreshCw :size="14"/>{{t('检查新模型','Check for new models')}}</button><button v-if="discovery?.busy" class="secondary-button" @click="api.cancelPotentialDiscovery()">{{t('停止检查','Stop checking')}}</button></div>
   <p class="model-tools-note">{{t('新发现的模型将在审核并适配后开放安装。这里只检查公开资料，不会上传项目文件。','New discoveries become installable after review and integration. Checks use public sources; project files are not uploaded.')}}</p>
   <div class="discovery-toolbar"><div class="discovery-tabs" role="group" :aria-label="t('发现视图','Discovery views')"><button :aria-pressed="mode==='records'" :class="{active:mode==='records'}" @click="mode='records'">{{t('发现记录','Discoveries')}}</button><button data-testid="discovery-sources-tab" :aria-pressed="mode==='sources'" :class="{active:mode==='sources'}" @click="mode='sources'">{{t('数据来源','Sources')}}</button></div><div class="discovery-actions"><button class="secondary-button" :disabled="busy||updates?.busy" @click="action(()=>api.refreshPotentialUpdates())">{{t('更新模型目录','Update catalog')}}</button><button class="secondary-button" :disabled="busy" data-testid="catalog-import" @click="action(()=>api.importPotentialCatalog())">{{t('导入目录','Import catalog')}}</button></div></div>
   <p class="skill-detail-description" role="status">{{updates?.feedConfigured?t('已启用在线更新，最多每天自动检查一次，也可手动更新。','Online updates are enabled, with automatic checks at most once a day. You can also update manually.'):t('在线目录更新尚未开通。当前目录可正常使用，也可导入签名目录文件。','Online catalog updates are not yet available. Use the current catalog or import a signed catalog file.')}} {{updates?.expired?t('当前目录已过期，请更新目录。已有内容仍可离线查看。','The catalog has expired. Update it when available; cached entries remain readable offline.'):''}}</p>
   <p v-if="discovery?.cacheError" class="model-directory-notice" role="alert">{{t('发现缓存损坏，已隔离保存；可重新采集公开来源。可信目录不受影响。','Discovery cache was corrupt and has been quarantined; public sources can be collected again. The trusted catalog is unaffected.')}}</p>
   <p v-if="error||updates?.error" class="model-directory-notice" role="alert">{{error||updates?.error}}</p>
   <template v-if="mode==='records'">
    <div class="hub-controls"><label>{{t('搜索发现记录','Search discoveries')}}<input v-model="query" data-testid="discovery-query" :placeholder="t('名称、家族、DOI、论文','Name, family, DOI, paper')"/></label><label>{{t('审核状态','Review status')}}<select v-model="filter" data-testid="discovery-filter"><option value="all">{{t('全部','All')}}</option><option value="pending">{{t('待审核','Pending')}}</option><option value="approved">{{t('已审核','Reviewed')}}</option><option value="rejected">{{t('未通过','Rejected')}}</option><option value="withdrawn">{{t('来源撤回','Source withdrawn')}}</option><option value="paper_only">{{t('仅论文','Paper only')}}</option></select></label></div>
    <div class="catalog-grid" data-testid="discovery-grid"><button v-for="r in records" :key="r.id" :data-discovery-id="r.id" class="catalog-card" @click="open(r)"><div class="catalog-icon"><Radar :size="18"/></div><div class="catalog-content"><strong>{{r.observation.title}}</strong><p :lang="locale==='zh'?'zh-CN':'en'">{{r.description[locale]}}</p><span>{{r.sourceIds.join(', ')}} · {{r.observation.revision}}</span></div><ArrowRight class="catalog-open-icon" :size="15"/><div class="model-catalog-status">{{status(r)}}</div></button></div>
    <div v-if="!records.length" class="empty-list">{{query||filter!=='all'?t('没有匹配的记录，请调整搜索条件。','No matches. Try different search terms or filters.'):t('暂无发现记录。点击“检查新模型”获取公开更新。','No discoveries yet. Select “Check for new models” to fetch public updates.')}}</div>
    <div class="hub-pagination"><button class="secondary-button" :disabled="!page" @click="page--">{{t('上一页','Previous')}}</button><span>{{total}} · {{page+1}} / {{Math.max(1,Math.ceil(total/24))}}</span><button class="secondary-button" :disabled="(page+1)*24>=total" @click="page++">{{t('下一页','Next')}}</button></div>
   </template>
   <div v-else class="catalog-grid" data-testid="discovery-sources"><article v-for="s in discovery?.sources" :key="s.id" class="catalog-card"><div class="catalog-icon"><Radar :size="18"/></div><div class="catalog-content"><strong>{{s.label[locale]}}</strong><p>{{s.error??(s.lastSuccess?t('最近采集成功','Last collection succeeded'):t('尚未采集','Not collected'))}}</p><span>{{s.count??0}} · {{s.intervalHours}} h · {{s.lastSuccess?.slice(0,19)??'—'}}</span><p class="hub-url">{{s.url}}</p></div></article></div>
   <details class="catalog-update-details"><summary>{{t('目录版本信息','Catalog version details')}}</summary><p>{{t('目录序号','Catalog sequence')}} {{updates?.sequence??0}} · {{t('签名密钥','Signing key')}} {{updates?.keyId??'—'}} · {{updates?.withdrawals.length??0}} {{t('条撤回记录','withdrawals')}}</p></details>
   <p v-for="w in updates?.withdrawals" :key="w.id" class="model-directory-notice">{{w.id}} · {{w.reason[locale]}}</p>
  </div>
  <el-drawer v-model="visible" direction="rtl" size="min(560px, 100vw)" :with-header="false" class="model-details-drawer"><div v-if="selected" data-testid="discovery-details">
   <div class="skill-detail-heading"><div class="skill-detail-title"><span class="skill-detail-icon"><Radar :size="21"/></span><div><span class="eyebrow">{{status(selected)}}</span><h2>{{selected.observation.title}}</h2></div></div><button class="icon-button" :aria-label="t('关闭发现详情','Close discovery details')" @click="selected=null">×</button></div>
   <section class="skill-detail-section"><p class="skill-detail-description">{{selected.description[locale]}}</p></section>
   <section class="skill-detail-section skill-detail-meta potential-meta"><div><span>ID / {{t('关联方式','Relation')}}</span><strong>{{selected.id}} / {{selected.relation}}</strong></div><div><span>{{t('权重身份','Weight identity')}}</span><strong>{{selected.observation.asset?.sha256??t('待核实/无权重','Unverified / no weights')}} · {{selected.observation.asset?.bytes??'—'}} bytes</strong></div><div><span>{{t('审核快照摘要','Reviewed content digest')}}</span><strong>{{selected.contentSha256}}</strong></div><div><span>{{t('来源快照摘要','Source snapshot digest')}}</span><strong>{{selected.observation.snapshotSha256}}</strong></div><div><span>{{t('关联已有条目','Related catalog entries')}}</span><strong>{{selected.relatedCatalogIds.join(', ')||'—'}}</strong></div></section>
   <section class="skill-detail-section"><strong>{{t('来源资料','Source material')}}</strong><p class="skill-detail-description hub-url">{{selected.observation.url}}</p><p class="skill-detail-description">{{evidence?.excerpt??''}}</p><button class="skill-example-copy" @click="action(()=>api.openPotentialDiscoverySource(selected!.id))">{{t('打开官方来源','Open official source')}}</button></section>
   <section class="skill-detail-section"><strong>{{t('使用例子','Usage examples')}}</strong><ExamplePrompts :examples="selected.examples" :locale="locale" @use="example"/></section>
   <section class="skill-detail-section"><strong>{{t('变更记录','Change history')}}</strong><p class="skill-detail-description">{{selected.change}} · {{selected.lastChanged}}</p><p v-for="(h,i) in selected.history.slice(-10)" :key="i" class="skill-detail-description">{{h.change}} · {{h.at}}</p></section>
  </div></el-drawer>
 </section>
</template>
<style scoped>
.potential-updates{color:var(--text)}
.discovery-overview{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin:0 0 16px}.discovery-metrics{display:flex;flex:1;gap:36px}.discovery-metrics>div{display:grid;gap:5px}.discovery-metrics strong{font-size:24px;font-weight:600}.discovery-metrics span{font-size:12px;color:var(--muted)}.discovery-toolbar{display:flex;gap:12px;justify-content:space-between;align-items:center;flex-wrap:wrap;margin:22px 0 14px}.discovery-tabs{display:flex;gap:4px;padding:3px;border:1px solid var(--line);border-radius:8px}.discovery-tabs button{border:0;border-radius:5px;background:transparent;color:var(--muted);font-size:12px;padding:7px 12px;cursor:pointer}.discovery-tabs button.active{background:var(--accent-bg);color:var(--accent)}.discovery-actions{display:flex;gap:8px;flex-wrap:wrap}.catalog-update-details{font-size:11px;color:var(--dim);margin-top:16px;line-height:1.7;overflow-wrap:anywhere}.catalog-update-details summary{cursor:pointer}.hub-controls{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}.hub-controls label{flex:1;min-width:160px;display:grid;gap:6px;font-size:12px;color:var(--muted)}.hub-controls select{min-width:0;padding:8px;border:1px solid var(--line);border-radius:8px;background:var(--panel);color:var(--text)}.hub-pagination{display:flex;gap:12px;justify-content:center;align-items:center;margin:16px 0;font-size:12px;color:var(--muted)}.hub-controls input{min-width:0;max-width:100%;background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:8px;padding:8px}.potential-updates .catalog-filters{flex-wrap:wrap}.hub-url{overflow-wrap:anywhere}.potential-updates .catalog-content{min-width:0}.potential-updates .catalog-content strong{overflow-wrap:anywhere}
.potential-meta strong{overflow-wrap:anywhere;min-width:0;font-size:12px}.potential-meta div{min-width:0}.skill-detail-title h2{white-space:normal;overflow-wrap:anywhere}
@media(max-width:1100px){.potential-updates .catalog-grid{grid-template-columns:minmax(0,1fr)}}
@media(max-width:760px){.potential-meta div{flex-wrap:wrap}.potential-meta strong{max-width:100%;text-align:left}}
</style>
