<script setup lang="ts">
import {Download, ChevronDown} from '@lucide/vue';
import type {PotentialCatalog} from '../../../../../packages/contracts/src/potential-hub.js';
import {ref,onMounted,onUnmounted,watch,nextTick} from 'vue';
import type {AtomicStructure} from '../../../../../packages/contracts/src/atomistic.js';
import type {MountedPackageStatus,SelectionAssessment} from '../../../../../packages/contracts/src/potential-packages.js';
import type {PotentialWorkflow} from '../../../../../packages/contracts/src/potential-workflow.js';
import type {ScientificSnapshot} from '../../../../../packages/contracts/src/atomistic-dynamics.js';
import AtomicArtifactCard from './AtomicArtifactCard.vue';
const api=window.materialsx;
const props=defineProps<{projectId:string|null;conversationId:string|null;locale:'zh'|'en';catalog:PotentialCatalog|null;preparingDemo?:boolean}>();
const emit=defineEmits<{'use-example':[prompt:string];'try-silicon':[]}>();
const t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
const modelName=(id:string)=>props.catalog?.entries.find(e=>e.id===id)?.name??id;
const packages=ref<MountedPackageStatus[]>([]),structures=ref<AtomicStructure[]>([]),structureId=ref(''),workflows=ref<PotentialWorkflow[]>([]),results=ref<Record<string,ScientificSnapshot>>({});
const interaction=ref<'short-range'|'long-range-required'|'dispersion-required'|'spin-required'|'field-required'|'delta-required'|'multi-head-required'>('short-range');
const prompt=ref(''),task=ref<'relaxation'|'singlepoint'>('relaxation'),domain=ref<'inorganic-crystals'|'molecules'|'polymers'>('inorganic-crystals'),steps=ref(100),downloadMiB=ref(200),fmax=ref(.05),assessment=ref<SelectionAssessment|null>(null),selected=ref(''),error=ref(''),busy=ref(false),expanded=ref(false);
const stateLabels:Record<string,[string,string]>={absent:['未安装','Not installed'],installed:['已安装','Installed'],downloading:['下载中','Downloading'],paused:['已暂停 · 可续传','Paused · resumable'],disabled:['已停用','Disabled'],failed:['失败','Failed'],awaiting_approval:['等待计划确认','Awaiting plan approval'],checking:['复核中','Checking'],queued:['计算排队','Queued'],running:['计算中','Running'],completed:['已完成 · 需科学复核','Completed · needs review'],cancelled:['已取消','Cancelled'],interrupted:['已中断 · 可恢复','Interrupted · recoverable']};
const packageError=(code:string)=>code==='PACKAGE_PART_IDENTITY_MISMATCH'?t('下载缓存校验失败，请清理后重试。','Download cache validation failed. Clear it and retry.'):code==='PACKAGE_IDENTITY_MISMATCH'?t('模型文件校验失败，请重新下载或导入。','Model validation failed. Download or import it again.'):code==='POTENTIAL_WITHDRAWN'?t('此模型已撤回，暂不可使用。','This model was withdrawn and is unavailable.'):t('模型状态异常，请查看详情。','Model status is unavailable. See details.');
const label=(state:string)=>stateLabels[state]?.[props.locale==='zh'?0:1]??state;
async function refresh(){const before=packages.value.map(p=>p.potentialId+":"+p.state).join(";");packages.value=await api.getPotentialPackages();if(before!==packages.value.map(p=>p.potentialId+":"+p.state).join(";"))window.dispatchEvent(new Event("materialsx:packages-changed"));if(props.projectId){structures.value=await api.listAtomicStructures(props.projectId);if(!structures.value.some(s=>s.id===structureId.value))structureId.value=structures.value[0]?.id??'';workflows.value=await api.listPotentialWorkflows(props.projectId);for(const w of workflows.value)if(w.runId)results.value[w.id]=await api.getAtomisticRun(props.projectId,w.runId);}else{structures.value=[];workflows.value=[];}}
async function act(f:()=>Promise<unknown>){error.value='';busy.value=true;try{await f();await refresh();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{busy.value=false;}}
async function importStructure(){if(!props.projectId)return;const s=await api.chooseAtomicStructure(props.projectId);if(s)structureId.value=s.id;await refresh();}
const options=()=>({optimizer:'FIRE' as const,cellMode:'fixed' as const,cellConstraint:'none' as const,externalPressureGPa:null,maxSteps:steps.value,fmaxEvPerAngstrom:fmax.value});
async function assess(){if(!props.projectId)return;assessment.value=await api.assessPotentialAnalysis({projectId:props.projectId,structureId:structureId.value,prompt:prompt.value||t('选择合适的势分析已导入晶体','Select an eligible potential for the imported crystal'),locale:props.locale,domain:domain.value,mode:'exploratory',interaction:interaction.value,task:task.value,...(task.value==='relaxation'?{options:options()}:{}),budget:{maxAtoms:256,maxSteps:task.value==='relaxation'?steps.value:1,maxWallSeconds:600,maxMemoryMiB:4096,maxOutputMiB:64,threads:4},maxDownloadBytes:Math.round(downloadMiB.value*1048576)});const list=assessment.value.selection.candidates;const speed=/小|快速|速度|small|fast|speed/i.test(prompt.value);selected.value=speed&&list.some(c=>c.potentialId==='mace-mp-0b2-small')?'mace-mp-0b2-small':list.find(c=>packages.value.find(p=>p.potentialId===c.potentialId)?.state==='installed')?.potentialId??list[0]?.potentialId??'';}
async function freeze(){if(!props.projectId||!assessment.value)return;const c=assessment.value.selection.candidates.find(c=>c.potentialId===selected.value);if(!c)throw Error('POTENTIAL_EXCLUDED');await api.freezePotentialAnalysis(props.projectId,{assessmentId:assessment.value.id,potentialId:c.potentialId,evidenceIds:[...c.evidenceIds],reason:t('用户审阅合格候选后选择；按来源、适用范围与资源约束，不表示精度排名。','User selection after eligibility review; based on sources, domain and resources, not an accuracy rank.')});assessment.value=null;}
async function authorizeAgent(){if(!props.projectId||!props.conversationId)return;await api.setScientificScope({projectId:props.projectId,conversationId:props.conversationId,structureId:structureId.value,domain:domain.value,mode:'exploratory',interaction:interaction.value,permission:task.value,...(task.value==='relaxation'?{options:options()}: {})});await api.setPotentialAnalysisScope({projectId:props.projectId,conversationId:props.conversationId,structureId:structureId.value,maxDownloadBytes:Math.round(downloadMiB.value*1048576),maxSteps:task.value==='relaxation'?steps.value:1,permission:task.value});emit('use-example',t(`请根据目录证据为结构 ${structureId.value} 选择合适机器学习势，${task.value==='relaxation'?'固定晶胞弛豫':'单点计算'}。使用 materials_science auto_plan、auto_run、auto_get，必要时在已授权下载范围内安装。${prompt.value} 输出真实报告与 3D 产物，标明需科学复核。`,`Choose an eligible potential using catalog evidence for structure ${structureId.value}; ${task.value==='relaxation'?'relax at fixed cell':'run a single point'}. Use materials_science auto_plan, auto_run and auto_get; install only within the approved download scope if needed. ${prompt.value} Report real artifacts and 3D results with needs_review status.`));}
watch(()=>props.projectId,()=>{assessment.value=null;void act(refresh);});watch([structureId,task,domain,interaction,steps,downloadMiB,fmax,prompt],()=>assessment.value=null);
async function open(id?:string){expanded.value=true;await act(refresh);await nextTick();const el=id?document.querySelector(`[data-package="${id}"]`):document.querySelector('[data-testid="potential-automation"]');el?.scrollIntoView({block:'start',behavior:'smooth'});}
defineExpose({open});
let timer:ReturnType<typeof setInterval>;onMounted(()=>{void act(refresh);timer=setInterval(()=>{if(expanded.value)void refresh().catch(()=>{});},1500);});onUnmounted(()=>clearInterval(timer));
</script>
<template>
 <section class="automation-panel model-tools-panel" data-testid="potential-automation"><button class="model-tools-toggle" :aria-expanded="expanded" aria-controls="automation-content" @click="expanded=!expanded;expanded&&act(refresh)"><span class="model-tools-icon"><Download :size="20"/></span><span class="model-tools-heading"><strong>{{t('模型下载与自动分析','Downloads & automatic analysis')}}</strong><span>{{t('管理本地模型，根据结构和分析需求选择计算方案。','Manage local models and choose calculations for your structure.')}}</span></span><ChevronDown :size="18" class="model-tools-chevron" :class="{expanded}"/></button>
 <div v-if="expanded" class="automation-body model-tools-body" id="automation-content" :aria-busy="busy">
  <p class="model-tools-note">{{t('选择结构并填写分析需求，系统会筛选可用模型。确认计算计划后开始下载与运行。结果用于探索分析，正式研究需结合独立参考数据验证。','Choose a structure and describe your task to find eligible models. Review the plan before downloading and running. Results are exploratory and need independent reference validation for research use.')}}</p>
  <div class="analysis-demo"><div><strong>{{t('试用：硅晶体自动分析','Try automatic analysis of silicon')}}</strong><p>{{t('导入内置 8 原子结构，让对话助手选势并进行最多 3 步固定晶胞弛豫，返回能量、原子受力、报告和 3D 结构。','Import the bundled 8-atom structure. The assistant selects a potential and relaxes it for up to 3 fixed-cell steps, returning energy, forces, reports and a 3D structure.')}}</p><small>{{t('此按钮会授权当前任务最多下载 200 MiB 模型，填入输入框后由你发送。','This enables up to 200 MiB of model downloads for this task and fills the chat prompt for you to send.')}}</small><small v-if="!projectId">{{t('请先打开或创建一个项目。','Open or create a project first.')}}</small></div><button class="secondary-button" :disabled="busy||preparingDemo||!projectId" data-testid="analysis-try-silicon" @click="emit('try-silicon')">{{preparingDemo?t('正在准备结构…','Preparing structure…'):t('在对话中试用','Try in chat')}}</button></div>
  <div class="catalog-grid"><article v-for="p in packages" :key="p.potentialId" class="catalog-card package-card" :data-package="p.potentialId"><div class="catalog-content"><strong>{{modelName(p.potentialId)}}</strong><p>{{label(p.state)}} · {{(p.bytes/1048576).toFixed(1)}} / {{(p.totalBytes/1048576).toFixed(1)}} MiB</p><progress v-if="p.state==='downloading'||p.state==='paused'" :value="p.bytes" :max="p.totalBytes"/><p>{{p.runtimeReady?t('计算环境就绪','Compute environment ready'):t('计算环境未就绪','Compute environment not ready')}}</p><p v-if="p.error" role="alert">{{packageError(p.error)}}</p><details><summary>{{t('模型与环境信息','Model & environment details')}}</summary><p>{{p.potentialId}}</p><p v-if="p.error">{{p.error}}</p><p>{{p.potentialId==='mace-mp-0b3-medium-d3-bj-pbe-si'?t('共享 MACE 基线 + 原生 D3','Shared MACE baseline + native D3'):p.potentialId==='nep-si-2022-nep4-3body'?t('原生引擎 + Python 环境','Native engine + Python environment'):['sevennet-0-11jul2024','ani-2x-ensemble'].includes(p.potentialId)?t('独立计算环境','Dedicated compute environment'):t('共享计算环境','Shared compute environment')}} · {{p.environmentProfileId}}</p><p v-if="p.potentialId==='sevennet-0-11jul2024'&&!p.runtimeReady">{{t('开发版可执行 npm run m610:runtime:dev 准备环境。安装版由发行包提供；暂不支持 Windows 与 GPU。','Development: run npm run m610:runtime:dev to prepare the environment. Installers supply it; Windows and GPU are not yet supported.')}}</p><code>SHA-256: {{p.sha256}}</code></details></div><div class="package-actions"><button v-if="p.state!=='installed'&&p.state!=='disabled'" class="skill-example-copy" :disabled="busy||p.error==='POTENTIAL_WITHDRAWN'" @click="act(()=>api.downloadPotentialPackage(p.potentialId))">{{p.state==='paused'?t('继续下载','Resume download'):t('下载模型','Download model')}}</button><button v-if="p.state==='downloading'" class="skill-example-copy" @click="api.cancelPotentialDownload(p.potentialId)">{{t('取消下载','Cancel download')}}</button><button class="skill-example-copy" :disabled="busy||p.error==='POTENTIAL_WITHDRAWN'" @click="act(()=>api.importPotentialPackage(p.potentialId))">{{t('导入本地权重','Import local checkpoint')}}</button><button v-if="p.state==='installed'||p.state==='disabled'" class="skill-example-copy" :disabled="busy" @click="act(()=>api.disablePotentialPackage(p.potentialId,p.state==='installed'))">{{p.state==='disabled'?t('启用','Enable'):t('停用','Disable')}}</button><button v-if="p.cacheOwned||p.state==='paused'" class="skill-example-copy" :disabled="busy" @click="act(()=>api.uninstallPotentialPackage(p.potentialId))">{{t('移除模型文件','Remove model files')}}</button></div></article></div>
  <div class="analysis-form"><label>{{t('物理需求','Interaction requirement')}}<select v-model="interaction" data-testid="analysis-interaction"><option value="short-range">{{t('短程探索','Short-range screening')}}</option><option value="dispersion-required">{{t('显式 D3 色散（纯硅探索）','Explicit D3 dispersion (Si screening)')}}</option><option value="spin-required">{{t('自旋物理（尚未验证）','Spin physics (unverified)')}}</option><option value="field-required">{{t('外场（尚未验证）','External fields (unverified)')}}</option><option value="delta-required">{{t('Δ-learning（尚未验证）','Delta learning (unverified)')}}</option><option value="multi-head-required">{{t('多头任务（尚未验证）','Multi-head task (unverified)')}}</option><option value="long-range-required">{{t('必须显式长程静电','Explicit long-range electrostatics required')}}</option></select></label><label>{{t('已导入结构','Imported structure')}}<select v-model="structureId" data-testid="analysis-structure"><option value="">{{t('请选择','Choose')}}</option><option v-for="s in structures" :value="s.id" :key="s.id">{{s.atoms.length}} {{t('原子','atoms')}} · {{s.id.slice(0,12)}}</option></select></label><button class="secondary-button" :disabled="busy||!projectId" @click="act(importStructure)">{{t('选择本地结构','Import local structure')}}</button><label>{{t('任务','Task')}}<select v-model="task"><option value="relaxation">{{t('固定晶胞弛豫','Fixed-cell relaxation')}}</option><option value="singlepoint">{{t('单点计算','Single point')}}</option></select></label><label>{{t('材料类型','Material type')}}<select v-model="domain"><option value="inorganic-crystals">{{t('无机周期晶体','Inorganic bulk')}}</option><option value="molecules">{{t('孤立分子（ANI-2x）','Isolated molecules (ANI-2x)')}}</option><option value="polymers">{{t('高分子（暂不支持）','Polymers (not yet supported)')}}</option></select></label><label>{{t('下载上限（MiB）','Download limit (MiB)')}}<input v-model.number="downloadMiB" type="number" min="0" max="512"/></label><label v-if="task==='relaxation'">{{t('最多步数','Maximum steps')}}<input v-model.number="steps" type="number" min="1" max="500"/></label><label v-if="task==='relaxation'">Fmax (eV/Å)<input v-model.number="fmax" type="number" min="0.001" max="0.2" step="0.005"/></label><label class="wide">{{t('分析需求（中文 / English）','Analysis request (中文 / English)')}}<textarea v-model="prompt" data-testid="analysis-prompt" :placeholder="t('例如：优先快速小模型，检查这个晶体的局部结构','For example: prefer a small fast model and inspect local crystal geometry')"/></label></div>
  <p>{{t('任务上限：256 原子、10 分钟、4 GiB 内存、64 MiB 输出。部分模型限制更低，具体以计算计划为准。','Task limits: 256 atoms, 10 minutes, 4 GiB memory and 64 MiB output. Some models have lower limits; review the calculation plan.')}}</p><div class="package-actions"><button class="primary-button" :disabled="busy||!structureId" data-testid="analysis-assess" @click="act(assess)">{{t('选择计算模型','Find eligible models')}}</button><button class="secondary-button" :disabled="busy||!structureId||!conversationId" data-testid="analysis-authorize-agent" @click="act(authorizeAgent)">{{t('授权对话助手分析','Authorize chat analysis')}}</button><button class="secondary-button" @click="act(refresh)">{{t('刷新','Refresh')}}</button></div>
  <div v-if="assessment" class="skill-detail-section" data-testid="analysis-candidates"><strong>{{t('可用模型','Eligible models')}}</strong><details><summary>{{t('筛选依据','Selection criteria')}}</summary><p>{{assessment.rankingBasis}}</p></details><select v-if="assessment.selection.candidates.length" v-model="selected"><option v-for="c in assessment.selection.candidates" :key="c.potentialId" :value="c.potentialId">{{modelName(c.potentialId)}}</option></select><p v-else>{{t('暂无适用模型，请查看原因或调整分析需求。','No eligible models. Review the reasons or adjust your task.')}}</p><details><summary>{{t('排除原因','Exclusions')}}</summary><p v-for="c in assessment.selection.exclusions" :key="c.potentialId">{{c.potentialId}}: {{c.reasonCodes.join(', ')}}</p></details><button v-if="selected" class="secondary-button" data-testid="analysis-freeze" @click="act(freeze)">{{t('查看计算计划','Review calculation plan')}}</button></div>
  <article v-for="w in workflows" :key="w.id" class="workflow-card" :data-workflow="w.id"><strong>{{modelName(w.plan.potentialId)}} · {{label(w.state)}}</strong><p>{{w.plan.request.prompt}}</p><p>{{t('待下载','To download')}} {{(w.plan.downloadBytes/1048576).toFixed(1)}} MiB · {{w.plan.request.task==='relaxation'?t('固定晶胞优化','Fixed-cell relaxation'):t('单点计算','Single point')}} · {{w.plan.request.options?.maxSteps??1}} {{t('最多步','maximum steps')}} </p><details><summary>{{t('计算计划与过程','Calculation plan & progress')}}</summary><p>{{w.plan.reason}}</p><code>{{w.plan.planSha256}}</code><p>{{w.plan.evidenceIds.join(', ')}}</p><p v-for="(e,i) in w.events" :key="i">{{e.at.slice(11,19)}} · {{label(e.state)}} · {{e.detail}}</p></details><p v-if="w.error" role="alert">{{w.error}}</p><button v-if="['awaiting_approval','failed','cancelled','interrupted'].includes(w.state)" class="primary-button" :disabled="busy" data-testid="analysis-approve" @click="act(()=>api.approvePotentialAnalysis(w.plan.request.projectId,w.id,w.plan.planSha256))">{{w.state==='awaiting_approval'?t('确认并开始','Confirm & run'):t('按原计划恢复','Resume frozen plan')}}</button><button v-if="['checking','downloading','queued','running'].includes(w.state)" class="secondary-button" @click="act(()=>api.cancelPotentialAnalysis(w.plan.request.projectId,w.id))">{{t('取消任务','Cancel workflow')}}</button><AtomicArtifactCard v-if="results[w.id]" :run="results[w.id]!" :locale="locale"/></article>
  <p v-if="error" class="model-directory-notice" role="alert">{{error}}</p>
 </div></section>
</template>
<style scoped>
.analysis-demo{display:flex;gap:18px;align-items:center;justify-content:space-between;flex-wrap:wrap;border:1px solid var(--line);border-radius:10px;padding:16px;margin:14px 0;background:var(--catalog-surface)}.analysis-demo>div{flex:1;min-width:200px}.analysis-demo strong{font-size:13px}.analysis-demo p,.analysis-demo small{font-size:12px;line-height:1.7;color:var(--muted)}.analysis-demo small{display:block;margin-top:4px}.automation-panel{max-width:1120px;margin:18px auto;color:var(--text)}.automation-body{margin-top:0}.package-card{cursor:default;display:block}.package-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.package-actions button{font-size:12px}.package-card progress{width:100%;accent-color:var(--accent)}.package-card code,.workflow-card code{overflow-wrap:anywhere;font-size:11px}.analysis-form{display:flex;flex-wrap:wrap;align-items:end;gap:12px;margin:20px 0}.analysis-form label{display:grid;gap:6px;font-size:12px;flex:1;min-width:150px}.analysis-form .wide{flex-basis:100%}.analysis-form input,.analysis-form select,.analysis-form textarea,select{border:1px solid var(--line);border-radius:7px;background:var(--catalog-surface);color:var(--text);padding:9px;max-width:100%;min-width:0}.analysis-form textarea{min-height:80px;resize:vertical}.workflow-card{border:1px solid var(--line);border-radius:10px;background:var(--catalog-surface);padding:16px;margin:14px 0}.workflow-card p,.automation-body>p,details,.skill-detail-section p{font-size:12px;color:var(--muted);line-height:1.7;overflow-wrap:anywhere}.workflow-card details{margin:12px 0}
</style>
