<script setup lang="ts">
import TeamResearchPanel from './TeamResearchPanel.vue';
import AgentWorkspacePanel from './AgentWorkspacePanel.vue';
import CampaignPanel from './CampaignPanel.vue';
import MethodPackagesPanel from './MethodPackagesPanel.vue';
import PaperLibraryPanel from './PaperLibraryPanel.vue';
import ScientificQualityPanel from './ScientificQualityPanel.vue';
import NextExperimentPanel from './NextExperimentPanel.vue';
import ExperimentAnalysisPanel from './ExperimentAnalysisPanel.vue';
import {computed,ref,watch} from 'vue';
import {storeToRefs} from 'pinia';
import {ElDrawer} from 'element-plus';
import {Database,RefreshCw,Search,FileChartColumn} from '@lucide/vue';
import {useWorkspaceStore} from '../stores/workspace';
import MarkdownContent from './MarkdownContent.vue';
import ExecutionIdentity from './ExecutionIdentity.vue';
import ResearchPlanDrawer from './ResearchPlanDrawer.vue';
import type {ResearchOverview,ResearchSnapshot,DeliveryRecord,MoosRef,DeliveryContract} from '../../../../../packages/contracts/src/research-project.js';
import type {ResearchGoalPlan} from '../../../../../packages/contracts/src/research-goal.js';
const emit=defineEmits<{example:[text:string]}>();
const workspace=useWorkspaceStore(),{activeProject}=storeToRefs(workspace);
const tab=ref<'materials'|'papers'|'quality'|'experiments'|'next'|'methods'|'campaigns'|'workspace'|'team'>('materials');
const locale=ref<'zh'|'en'>('zh'),state=ref<ResearchOverview|null>(null),query=ref(''),review=ref<'verified'|'include-unreviewed'>('verified');
const found=ref<any>(null),busy=ref(false),error=ref(''),editor=ref(false),detail=ref<ResearchSnapshot|null>(null),preview=ref(''),previewKind=ref(''),image=ref(''),imageRights=ref('');
const plan=ref<ResearchGoalPlan|null>(null),planOpen=ref(false),session=ref<any>(null);
const sampleLinks=ref<Record<string,string|null>>({});
const material=ref(''),conditions=ref(''),samples=ref(''),kind=ref<DeliveryContract['kind']>('comparison'),requiredImage=ref(false),requireReviewed=ref(false),checks=ref('[]');
const t=(zh:string,en:string)=>locale.value==='zh'?zh:en;
const selected=computed(()=>state.value?.snapshots.filter(s=>state.value!.project.selected.includes(s.id))??[]);
const lastPlans=computed(()=>state.value?.bindings.map(b=>state.value!.planHistory.filter(p=>p.task.taskId===b.taskId).at(-1)).filter((p):p is ResearchGoalPlan=>!!p)??[]);
async function perform(fn:()=>Promise<unknown>){busy.value=true;error.value='';try{await fn();}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function load(){const id=activeProject.value?.id;if(!id){state.value=null;return;}const data=await window.materialsx.getResearchProject(id);if(activeProject.value?.id===id)state.value=data;}
watch(()=>activeProject.value?.id,()=>{found.value=null;detail.value=null;preview.value='';void perform(load);},{immediate:true});
function edit(){const p=state.value!.project;material.value=p.materialSystem;conditions.value=p.conditions.join('\n');samples.value=p.samples.map(s=>s.label).join('\n');sampleLinks.value=Object.fromEntries(p.samples.map((s,i)=>[String(i),s.snapshotId]));kind.value=p.delivery.kind;requiredImage.value=p.delivery.required.includes('image');requireReviewed.value=p.delivery.requireReviewed;checks.value=JSON.stringify(p.delivery.checks,null,2);editor.value=true;}
async function save(){await perform(async()=>{const p=state.value!.project;await window.materialsx.saveResearchProject({...p,revision:p.revision+1,materialSystem:material.value,
 conditions:conditions.value.split('\n').map(s=>s.trim()).filter(Boolean),samples:samples.value.split('\n').map(s=>s.trim()).filter(Boolean).map((label,i)=>({id:p.samples[i]?.id??'sample-'+(i+1),label,snapshotId:sampleLinks.value[String(i)]??null})),
 delivery:{...p.delivery,kind:kind.value,required:requiredImage.value?['table','chart','report','image']:['table','chart','report'],optional:requiredImage.value?[]:['image'],requireReviewed:requireReviewed.value,checks:JSON.parse(checks.value)}},p.revision);editor.value=false;await load();});}
async function search(cursor?:string){await perform(async()=>{const id=activeProject.value!.id,result=await window.materialsx.searchResearchData(id,query.value,review.value,cursor);if(activeProject.value?.id===id)found.value=result;});}
async function select(ref:MoosRef){await perform(async()=>{await window.materialsx.selectResearchData(activeProject.value!.id,ref);await load();});}
async function toggle(s:ResearchSnapshot,withdraw=false){await perform(async()=>{const p=state.value!.project,exists=p.selected.includes(s.id);await window.materialsx.saveResearchProject({...p,revision:p.revision+1,
 selected:withdraw||exists?p.selected.filter(id=>id!==s.id):[...p.selected,s.id],withdrawn:withdraw?[...new Set([...p.withdrawn,s.id])]:p.withdrawn.filter(id=>id!==s.id),decisions:[...p.decisions,{at:new Date().toISOString(),origin:'user',text:(withdraw?'Withdraw / 撤回 ':exists?'Deselect / 取消选择 ':'Select / 选择 ')+s.title}]},p.revision);await load();});}
async function importInput(){await perform(async()=>{await window.materialsx.importResearchData(activeProject.value!.id);await load();});}
async function refresh(s:ResearchSnapshot){await perform(async()=>{await window.materialsx.refreshResearchSource(activeProject.value!.id,s.id);await load();});}
async function showImage(s:ResearchSnapshot,id:string){await perform(async()=>{const r=await window.materialsx.readResearchImage(activeProject.value!.id,s.id,id);image.value=r.dataUrl;imageRights.value=r.rightsBasis;});}
async function showArtifact(d:DeliveryRecord,kind:'table'|'chart'|'report'){await perform(async()=>{const id=activeProject.value!.id,text=await window.materialsx.previewResearchArtifact(id,d.id,kind);if(activeProject.value?.id!==id)return;preview.value=text;previewKind.value=kind;});}
async function showPlan(p:ResearchGoalPlan){plan.value=p;session.value=await window.materialsx.getEngineSession(p.task.taskId);planOpen.value=true;}
function useExample(simulation=false){workspace.showView('chat');emit('example',simulation?t('@materials-research-workbench 整理选定记录报告的模拟方法与缺项，不执行模拟。','@materials-research-workbench Document reported simulation methods and missing inputs for selected records. Do not execute simulation.'):t('@materials-research-workbench 比较选定 MOOS 记录的太阳反射率，保留原单位、测试条件与证据，生成真实表格、概览图和报告。','@materials-research-workbench Compare the selected MOOS solar-reflectance observations, preserve original units, test conditions and evidence; generate a real table, overview and report.'));}
const svgUrl=computed(()=>previewKind.value==='chart'?'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(preview.value))):'');
</script>
<template>
<section class="catalog-view research-workspace" data-testid="research-workspace">
  <div class="page-heading"><div><span class="eyebrow">RESEARCH WORKSPACE</span><h1>{{t('研究数据与交付','Research data & delivery')}}</h1><p>{{t('选定数据、记录条件、查看研究产物和证据。','Select inputs, record conditions, and inspect deliverables and evidence.')}}</p></div><div class="actions"><button class="secondary-button" @click="locale=locale==='zh'?'en':'zh'">{{locale==='zh'?'English':'中文'}}</button><button class="secondary-button" :disabled="busy" @click="perform(load)"><RefreshCw :size="15"/>{{t('刷新','Refresh')}}</button></div></div>
  <div v-if="activeProject" class="actions research-tabs"><button :class="tab==='materials'?'primary-button':'secondary-button'" @click="tab='materials'">{{t('材料数据','Materials data')}}</button><button data-testid="paper-tab" :class="tab==='papers'?'primary-button':'secondary-button'" @click="tab='papers'">{{t('论文库','Paper library')}}</button><button data-testid="quality-tab" :class="tab==='quality'?'primary-button':'secondary-button'" @click="tab='quality'">{{t('科学检查与方法','Scientific checks & methods')}}</button><button data-testid="experiment-tab" :class="tab==='experiments'?'primary-button':'secondary-button'" @click="tab='experiments'">{{t('原始实验分析','Experimental analysis')}}</button><button data-testid="next-experiment-tab" :class="tab==='next'?'primary-button':'secondary-button'" @click="tab='next'">{{t('下一轮实验','Next experiments')}}</button><button data-testid="method-packages-tab" :class="tab==='methods'?'primary-button':'secondary-button'" @click="tab='methods'">{{t('方法包','Method packages')}}</button><button data-testid="campaign-tab" :class="tab==='campaigns'?'primary-button':'secondary-button'" @click="tab='campaigns'">{{t('长期计算','Long-running jobs')}}</button><button data-testid="agent-workspace-tab" :class="tab==='workspace'?'primary-button':'secondary-button'" @click="tab='workspace'">{{t('研究分工与浏览器','Subtasks & browser')}}</button><button data-testid="team-tab" :class="tab==='team'?'primary-button':'secondary-button'" @click="tab='team'">{{t('团队研究','Team research')}}</button></div>
  <p v-if="error" role="alert" class="research-error">{{error}}</p>
  <div v-if="!activeProject" class="empty-list"><Database :size="26"/><strong>{{t('先选择一个项目','Select a project first')}}</strong></div>
  <div v-else-if="state" v-show="tab==='materials'" class="catalog-page-body research-body">
    <article class="research-card"><header><div><h2>{{state.project.materialSystem||activeProject.name}}</h2><p>{{t('输入版本','Input revision')}} {{state.project.revision}} · {{selected.length}} {{t('个选定来源','selected sources')}}</p></div><button class="secondary-button" :disabled="busy" @click="edit">{{t('设置研究条件','Set research conditions')}}</button></header><div class="condition-tags"><span v-for="c in state.project.conditions" :key="c">{{c}}</span><span>{{state.project.delivery.kind}}</span></div><p class="field-help">{{t('交付要求在任务开始前固定。来源审核与科学复现分开显示；本地数据不会自动发送到云模型。','Delivery criteria are fixed before each task. Extraction review and scientific reproduction remain separate. Local data is not automatically sent to cloud models.')}}</p><div class="actions"><button class="secondary-button" @click="useExample()">{{t('使用条件比较示例','Use comparison example')}}</button><button class="secondary-button" @click="useExample(true)">{{t('使用模拟缺项示例','Use simulation-gap example')}}</button></div></article>
    <article class="research-card"><header><div><h2>{{t('项目输入与 MOOS','Project inputs & MOOS')}}</h2><p>{{t('优先搜索已选择的项目数据，无匹配时查询 MOOS。','Search selected project inputs first; query MOOS when no inputs match.')}}</p></div><button class="secondary-button" :disabled="busy" @click="importInput">{{t('导入项目 JSON','Import project JSON')}}</button></header><div class="search-row"><Search :size="18"/><input v-model="query" :placeholder="t('材料、论文、专利或性能关键词','Material, paper, patent or property')" @keyup.enter="search()"/><button class="primary-button" :disabled="busy" @click="search()">{{t('搜索','Search')}}</button></div><label class="check-label"><input type="checkbox" :checked="review==='include-unreviewed'" @change="review=($event.target as HTMLInputElement).checked?'include-unreviewed':'verified'"/>{{t('包含待审核来源（仍需科研复核）','Include unreviewed sources (requires review)')}}</label>
      <div v-if="found" class="search-results"><p>{{found.origin}} · {{found.outcome}} · {{found.items?.length??0}}</p><article v-for="(r,i) in found.items" :key="i" class="source-row"><div><strong>{{r.title||r.label||r.ref?.experimentId}}</strong><small>{{r.reviewStatus}} · {{r.ref?.generation??r.sha256?.slice(0,12)}}</small></div><button v-if="r.ref" class="secondary-button" :disabled="busy" @click="select(r.ref)">{{t('选择版本','Select version')}}</button></article><button v-if="found.nextCursor" class="secondary-button" @click="search(found.nextCursor)">{{t('下一页','Next page')}}</button><p v-if="!found.items?.length" class="field-help">{{t('当前页无匹配；待审核记录需主动勾选。服务失败不会伪装成无数据。','No matches on this page. Unreviewed records require opt-in. Service failures are reported separately.')}}</p></div>
      <div class="source-list"><article v-for="s in state.snapshots" :key="s.id" class="source-row"><div><strong>{{s.title}}</strong><small>{{s.origin}} · {{s.version.slice(0,18)}} · {{s.evidence.length}} {{t('条证据','evidence receipts')}}</small><span v-if="state.project.withdrawn.includes(s.id)" class="field-help">{{t('来源已撤回，相关产物失效','Source withdrawn; dependent artifacts are stale')}}</span></div><div class="actions"><button class="secondary-button" @click="detail=s;image=''">{{t('详情','Details')}}</button><button class="secondary-button" :disabled="busy" @click="toggle(s)">{{state.project.selected.includes(s.id)?t('取消选择','Deselect'):t('加入输入','Select')}}</button><button v-if="s.ref" class="secondary-button" :disabled="busy" @click="refresh(s)">{{t('检查来源版本','Check source version')}}</button><button class="secondary-button" :disabled="busy||state.project.withdrawn.includes(s.id)" @click="toggle(s,true)">{{t('撤回','Withdraw')}}</button></div></article></div>
    </article>
    <article class="research-card"><header><div><h2>{{t('研究任务','Research tasks')}}</h2><p>{{t('目标、缺项、实际步骤与模型 / 引擎身份来自同一任务记录。','Goals, gaps, steps and model / engine identity use the same task journal.')}}</p></div></header><p v-if="!lastPlans.length" class="field-help">{{t('发送研究任务后，计划会显示在这里。','Plans appear after a research task is sent.')}}</p><article v-for="p in lastPlans" :key="p.task.taskId" class="source-row"><div><strong>{{p.goal.problemType}}</strong><small>{{t('目标 / 计划版本','Goal / plan revision')}} {{p.goalRevision}} / {{p.planRevision}} · {{p.cognition.missing.length}} {{t('项待补充','missing conditions')}}</small><small>{{p.revisionReason}}</small><ExecutionIdentity :task-id="p.task.taskId" :project-id="activeProject.id" :locale="locale"/></div><button class="secondary-button" @click="showPlan(p)">{{t('计划与执行','Plan & execution')}}</button></article></article>
    <article class="research-card"><header><div><h2>{{t('交付与复核','Deliverables & review')}}</h2><p>{{t('核对真实文件、来源回链和逐项检查；不会把模型回答当作验收证据。','Verify real files, source links and itemized checks. Model statements are not acceptance evidence.')}}</p></div><FileChartColumn :size="22"/></header><p v-if="!state.deliveries.length" class="field-help">{{t('尚无研究产物。','No research deliverables yet.')}}</p><article v-for="d in state.deliveries" :key="d.id" class="delivery"><strong>{{d.status}} · {{t('科学结论待复核','Scientific conclusions need review')}}</strong><small>{{d.taskId}} · {{t('计划版本','Plan revision')}} {{d.planRevision}}</small><div class="actions"><button v-for="a in d.artifacts" :key="a.path" class="secondary-button" @click="a.kind==='image'?undefined:showArtifact(d,a.kind)">{{a.kind}} · {{a.bytes}} B</button></div><details><summary>{{t('查看逐项检查与限制','Itemized checks & limitations')}}</summary><p v-for="c in d.checks" :key="c.id">{{c.status}} · {{c.id}} · {{c.detail}}</p><p>{{d.limitations.join(' · ')}}</p></details></article></article>
    <details class="research-card"><summary>{{t('数据获取记录与修订历史','Source receipts & revision history')}}</summary><p v-for="r in state.receipts.slice(0,20)" :key="r.id">{{r.at}} · {{r.origin}} · {{r.tool}} · {{r.outcome}} {{r.detail}}</p><p v-for="r in state.projectHistory" :key="r.revision">{{t('输入版本','Input revision')}} {{r.revision}} · {{r.materialSystem}} · {{r.conditions.join('; ')}} · {{r.selected.length}} {{t('个来源','sources')}}</p><p v-for="decision in state.project.decisions" :key="decision.at">{{decision.at}} · {{decision.text}}</p><p v-for="p in state.planHistory" :key="p.task.taskId+':'+p.planRevision">{{p.task.taskId.slice(0,8)}} · v{{p.planRevision}} · {{p.revisionReason}} · {{p.goal.problemType}}</p></details>
  </div>
  <ElDrawer v-model="editor" :title="t('研究条件与交付要求','Research conditions & delivery criteria')" size="min(760px,96vw)"><div class="form"><label>{{t('材料体系','Material system')}}<input v-model="material"/></label><label>{{t('条件（每行一条）','Conditions (one per line)')}}<textarea v-model="conditions" rows="4"/></label><label>{{t('样品（每行一个）','Samples (one per line)')}}<textarea v-model="samples" rows="3"/></label><label v-for="(sample,i) in samples.split('\n').filter(Boolean)" :key="i">{{sample}} · {{t('关联数据','Linked source')}}<select v-model="sampleLinks[String(i)]"><option :value="null">{{t('未关联','Not linked')}}</option><option v-for="s in state?.snapshots" :key="s.id" :value="s.id">{{s.title}}</option></select></label><label>{{t('交付类型','Delivery kind')}}<select v-model="kind"><option value="comparison">{{t('条件比较','Condition comparison')}}</option><option value="recipe-process">{{t('配方与工艺','Recipe & process')}}</option><option value="simulation-gaps">{{t('模拟缺项','Simulation gaps')}}</option></select></label><label class="check-label"><input v-model="requiredImage" type="checkbox"/>{{t('必须包含合法图片','Require an authorized image')}}</label><label class="check-label"><input v-model="requireReviewed" type="checkbox"/>{{t('必须使用已审核数据','Require reviewed extraction')}}</label><label>{{t('数值验收条件（JSON 数组，可留空）','Value criteria (JSON array, may be empty)')}}<textarea v-model="checks" rows="5"/></label><p class="field-help">property、unit、condition、expected、tolerance；condition 为来源条件对象的原始 JSON。没有自动单位换算。保存影响后续任务，历史任务保留原要求。</p><button class="primary-button" :disabled="busy" @click="save">{{t('保存','Save')}}</button></div></ElDrawer>
  <ElDrawer :model-value="!!detail" :title="detail?.title??''" size="min(1080px,96vw)" @update:model-value="detail=null"><div v-if="detail" class="detail"><p>{{detail.sha256}} · {{detail.reviewStatus}}</p><h3>{{t('数据与条件','Data & conditions')}}</h3><div v-for="section in ['observations','recipes','ingredients','processes','nodes']" :key="section"><h4>{{section}}</h4><pre v-for="(r,i) in (detail.data[section] as any[]??[])" :key="i">{{JSON.stringify(r,null,2)}}</pre></div><h3>{{t('证据原文','Evidence text')}}</h3><pre v-for="(r,i) in (detail.data.readEvidence as any[]??[])" :key="i">{{JSON.stringify(r,null,2)}}</pre><h3>{{t('来源图片','Source images')}}</h3><button v-for="(m,i) in (detail.data.media_metadata as any[]??[])" :key="i" class="secondary-button" :disabled="busy" @click="showImage(detail,String(m.id))">{{String(m.id)}}</button><img v-if="image" :src="image" :alt="t('已授权研究预览','Authorized research preview')"/><p>{{imageRights}}</p></div></ElDrawer>
  <ElDrawer :model-value="!!preview" :title="t('产物预览','Artifact preview')" size="min(1080px,96vw)" @update:model-value="preview=''"><MarkdownContent v-if="previewKind==='report'" :content="preview"/><img v-else-if="previewKind==='chart'" class="preview-image" :src="svgUrl" alt="Source overview"/><pre v-else class="artifact-pre">{{preview}}</pre></ElDrawer>
  <TeamResearchPanel v-if="activeProject" v-show="tab==='team'" :active="tab==='team'" :project-id="activeProject.id" :locale="locale" :snapshots="state?.snapshots??[]" :selected="state?.project.selected??[]" @changed="perform(load)"/>
  <AgentWorkspacePanel v-if="activeProject" v-show="tab==='workspace'" :active="tab==='workspace'" :project-id="activeProject.id" :locale="locale" @example="workspace.showView('chat');emit('example',$event)"/>
  <CampaignPanel v-if="activeProject" v-show="tab==='campaigns'" :active="tab==='campaigns'" :project-id="activeProject.id" :locale="locale" @example="workspace.showView('chat');emit('example',$event)"/>
  <MethodPackagesPanel v-if="activeProject" v-show="tab==='methods'" :active="tab==='methods'" :locale="locale" @example="workspace.showView('chat');emit('example',$event)"/>
  <PaperLibraryPanel v-if="activeProject" v-show="tab==='papers'" :project-id="activeProject.id" :locale="locale" @example="emit('example',$event)"/>
  <ScientificQualityPanel v-if="activeProject&&state" v-show="tab==='quality'" :project-id="activeProject.id" :locale="locale" :snapshots="state.snapshots" :selected="state.project.selected" @example="workspace.showView('chat');emit('example',$event)" @changed="perform(load)"/>
  <ExperimentAnalysisPanel v-if="activeProject&&state" v-show="tab==='experiments'" :project-id="activeProject.id" :project-path="activeProject.path" :locale="locale" @example="workspace.showView('chat');emit('example',$event)" @changed="perform(load)"/>
  <NextExperimentPanel :active="tab==='next'" v-if="activeProject&&state" v-show="tab==='next'" :project-id="activeProject.id" :project-path="activeProject.path" :locale="locale" @example="workspace.showView('chat');emit('example',$event)" @changed="perform(load)"/>
  <ResearchPlanDrawer v-model="planOpen" :plan="plan" :engine-session="session" :locale="locale" @revised="plan=$event;perform(load)"/>
</section>
</template>
<style scoped>
.research-workspace,.research-body{min-width:0;max-width:100%;box-sizing:border-box}
.research-tabs{margin:0 0 18px}.research-body{display:grid;gap:18px}
.research-card{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:22px;min-width:0;overflow-wrap:anywhere}
.research-card header{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.research-card h2{margin:0;font-size:17px}.research-card p{font-size:13px;line-height:1.7;color:var(--muted)}
.actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.condition-tags{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.condition-tags span{padding:5px 9px;background:var(--panel-2);border:1px solid var(--line);border-radius:6px;font-size:12px}
.search-row{display:flex;align-items:center;gap:10px;margin:16px 0}.search-row input{flex:1;min-width:0}.check-label{display:flex!important;align-items:center;gap:8px;font-size:13px}.check-label input{width:auto!important}
.source-row{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:15px 0;border-top:1px solid var(--line)}.source-row>div:first-child{min-width:0;flex:1}.source-row strong{font-size:13px}.source-row small,.delivery small{display:block;color:var(--muted);font-size:12px;margin:6px 0;overflow-wrap:anywhere}
.delivery{display:grid;gap:10px;margin:14px 0;padding:16px;border:1px solid var(--line);border-radius:10px}.delivery strong{font-size:14px}
.form{display:grid;gap:16px;color:var(--text)}.form label{display:grid;gap:7px;font-size:13px}
input,textarea,select{box-sizing:border-box;width:100%;min-width:0;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:10px;border-radius:8px;font:inherit}
.detail{color:var(--text);min-width:0;overflow-wrap:anywhere}.detail pre,.artifact-pre{font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere;padding:12px;background:var(--panel);border:1px solid var(--line);border-radius:8px;max-width:100%;box-sizing:border-box}
.detail img,.preview-image{max-width:100%;height:auto;border-radius:8px;margin:12px 0}.research-error{background:var(--panel);border:1px solid var(--line);padding:12px;border-radius:8px;overflow-wrap:anywhere;color:var(--danger)}
@media(max-width:780px){.research-card header,.source-row{flex-direction:column;align-items:stretch}.research-card{padding:16px}.search-row{flex-wrap:wrap}.page-heading{flex-wrap:wrap}.search-row input{flex-basis:60%}}
</style>
