<script setup lang="ts">
import {computed,ref,watch} from 'vue';
import {ElDrawer} from 'element-plus';
import {ShieldCheck,RefreshCw,FlaskConical} from '@lucide/vue';
import MarkdownContent from './MarkdownContent.vue';
import type {ResearchSnapshot} from '../../../../../packages/contracts/src/research-project.js';
import type {ScientificOverview} from '../../../../../packages/contracts/src/scientific-quality.js';
import type {MethodAssessment,MethodRequest} from '../../../../../packages/contracts/src/research-methods.js';
const props=defineProps<{projectId:string;locale:'zh'|'en';snapshots:ResearchSnapshot[];selected:string[]}>();
const emit=defineEmits<{example:[text:string];changed:[]}>();
const t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
const state=ref<ScientificOverview|null>(null),busy=ref(false),error=ref(''),preview=ref('');
const task=ref<'summarize'|'fit'|'validate'>('summarize'),question=ref(''),assessment=ref<MethodAssessment|null>(null),reason=ref('');
const samples=ref<Array<{id:string;y:string;x:string;split:'train'|'validation'|'test'}>>([]);
const noticeSource=ref(''),noticeKind=ref<'updated'|'corrected'|'retracted'|'access-denied'>('retracted'),noticeReason=ref(''),replacement=ref('');
const sources=computed(()=>props.snapshots.filter(s=>props.selected.includes(s.id)));
const options=computed(()=>sources.value.flatMap(s=>Array.isArray(s.data.observations)?s.data.observations.flatMap((r:any)=>
  typeof r.id==='string'?[{key:s.id+'|'+r.id,snapshotId:s.id,observationId:r.id,label:s.title+' · '+r.property+' = '+r.value+' '+(r.unit??'')}]:[]):[]));
const statusLabel=(status:string)=>({pass:t('已核对','Checked'),warning:t('待复核','Review needed'),blocked:t('不可用于结论','Blocked'),stale:t('来源已失效','Source changed'),
  'usable-with-limitations':t('保留限制，可继续研究','Usable with limitations'),completed:t('计算已完成，结论待复核','Calculation complete; review needed')}[status]??status);
async function load(){const id=props.projectId,value=await window.materialsx.getScientificOverview(id);if(props.projectId===id)state.value=value;}
async function perform(fn:()=>Promise<void>){busy.value=true;error.value='';try{await fn();}catch(e){error.value=String(e);}finally{busy.value=false;}}
watch(()=>props.projectId,()=>{state.value=null;assessment.value=null;samples.value=[];preview.value='';void perform(load);},{immediate:true});
watch(()=>[props.selected.join(','),task.value],()=>{assessment.value=null;});
async function audit(){await perform(async()=>{await window.materialsx.auditScientificData(props.projectId,{snapshotIds:sources.value.map(s=>s.id)});await load();});}
function addRow(){samples.value.push({id:'sample-'+crypto.randomUUID().slice(0,8),y:options.value[0]?.key??'',x:'',split:'train'});assessment.value=null;}
function reference(key:string){const o=options.value.find(o=>o.key===key);if(!o)throw Error(t('请选择来源观测','Select a source observation'));return {snapshotId:o.snapshotId,observationId:o.observationId};}
async function assess(){await perform(async()=>{
  const input:MethodRequest={question:question.value||t('分析选定来源观测','Analyze selected source observations'),task:task.value,
    samples:samples.value.map(s=>({id:s.id,y:reference(s.y),...(task.value==='summarize'?{}:{x:reference(s.x)}),...(task.value==='validate'?{split:s.split}:{})}))};
  assessment.value=await window.materialsx.assessResearchMethods(props.projectId,input);await load();
});}
async function run(methodId:MethodAssessment['candidates'][number]['methodId']){await perform(async()=>{await window.materialsx.runResearchMethod(props.projectId,{assessmentId:assessment.value!.id,methodId,reason:reason.value.trim()});await load();});}
async function show(record:{id:string;artifacts:Array<{path:string}>},path:string){await perform(async()=>{preview.value=await window.materialsx.previewScientificArtifact(props.projectId,record.id,path);});}
async function saveNotice(){await perform(async()=>{await window.materialsx.recordSourceNotice(props.projectId,{snapshotId:noticeSource.value,kind:noticeKind.value,reason:noticeReason.value.trim(),replacementSnapshotId:replacement.value||null});noticeReason.value='';await load();emit('changed');});}
function example(){emit('example',t('先用 research_quality 检查选定来源的证据、原单位、条件及重复数据，再用 research_methods 筛选可用方法。单位或条件不一致时保留原值和限制；不要自动排名、合并或声称科学验证。','Use research_quality to check selected evidence, original units, conditions and duplicate reports. Then assess eligible methods with research_methods. Preserve incompatible original values and limitations; do not rank, pool or claim scientific validation.'));}
</script>
<template>
<section class="scientific-panel" data-testid="scientific-quality">
  <article class="quality-card"><header><div><span class="eyebrow">{{t('证据与方法','EVIDENCE & METHODS')}}</span><h2>{{t('先核对数据，再选择方法','Check the data, then select a method')}}</h2><p>{{t('来源、单位和测试条件决定哪些分析可以开展。文件生成与科学结论分别验收。','Sources, units and test conditions determine eligible analyses. Files and scientific conclusions are checked separately.')}}</p></div><ShieldCheck :size="24"/></header>
    <div class="actions"><button class="primary-button" :disabled="busy||!sources.length" @click="audit">{{t('检查选定数据','Check selected data')}}</button><button class="secondary-button" :disabled="busy" @click="perform(load)"><RefreshCw :size="15"/>{{t('刷新','Refresh')}}</button><button class="secondary-button" @click="example">{{t('将示例填入对话','Use example in chat')}}</button></div>
    <p v-if="!sources.length" class="hint">{{t('先在“材料数据”中选择研究来源。','Select research sources in Materials data first.')}}</p>
    <p v-if="error" role="alert" class="error">{{error}}</p>
  </article>
  <div v-if="state" class="method-grid"><article v-for="m in state.methods" :key="m.id" class="quality-card method-card"><FlaskConical :size="18"/><h3>{{m.name[locale]}}</h3><p>{{m.description[locale]}}</p><details><summary>{{t('所需输入与范围','Required inputs & scope')}}</summary><p>{{m.requiredInputs.join(' · ')}}</p><p>{{m.scope.join(' · ')}}</p></details></article></div>
  <article class="quality-card"><h3>{{t('用来源观测进行分析','Analyze source observations')}}</h3><p>{{t('支持原值统计、线性拟合和分组留出验证。原子结构计算仍在模型目录或对话中执行。','Use summaries, linear fits and grouped holdout validation. Atomic calculations remain in the model directory or chat.')}}</p>
    <div class="form-row"><label>{{t('研究问题','Research question')}}<input v-model="question" :disabled="busy"/></label><label>{{t('分析类型','Analysis type')}}<select v-model="task" :disabled="busy"><option value="summarize">{{t('原值描述统计','Descriptive summary')}}</option><option value="fit">{{t('线性拟合','Linear fit')}}</option><option value="validate">{{t('分组验证与基线','Grouped validation & baseline')}}</option></select></label></div>
    <div class="observation-list"><div v-for="(s,i) in samples" :key="s.id" class="observation-row"><span>{{i+1}}</span><label>{{t('目标值 Y','Target Y')}}<select v-model="s.y" :disabled="busy" @change="assessment=null"><option v-for="o in options" :key="o.key" :value="o.key">{{o.label}}</option></select></label><label v-if="task!=='summarize'">{{t('输入值 X','Predictor X')}}<select v-model="s.x" :disabled="busy" @change="assessment=null"><option value="">{{t('请选择','Select')}}</option><option v-for="o in options" :key="o.key" :value="o.key">{{o.label}}</option></select></label><label v-if="task==='validate'">{{t('冻结分组','Frozen split')}}<select v-model="s.split" :disabled="busy" @change="assessment=null"><option value="train">{{t('训练','Train')}}</option><option value="validation">{{t('验证','Validation')}}</option><option value="test">{{t('测试','Test')}}</option></select></label><button class="secondary-button" :disabled="busy" @click="samples.splice(i,1);assessment=null">{{t('移除','Remove')}}</button></div></div>
    <div class="actions"><button class="secondary-button" :disabled="busy||!options.length||samples.length>=300" @click="addRow">{{t('添加观测','Add observation')}}</button><button class="primary-button" :disabled="busy||!samples.length" @click="assess">{{t('检查方法可用性','Check eligibility')}}</button></div>
    <div v-if="assessment" class="assessment"><p v-if="!assessment.candidates.length">{{t('当前输入没有可用方法。请根据下方原因补充数据或调整任务。','No method is eligible. Address the exclusions below before continuing.')}}</p><template v-else><label>{{t('选择理由','Reason for selection')}}<input v-model="reason" :placeholder="t('说明此方法如何回答研究问题','Explain how this method addresses your question')"/></label><div class="actions"><button v-for="c in assessment.candidates" :key="c.methodId" class="primary-button" :disabled="busy||!reason.trim()" @click="run(c.methodId)">{{t('运行','Run')}} · {{state?.methods.find(m=>m.id===c.methodId)?.name[locale]}}</button></div></template><details><summary>{{t('查看筛选依据','Eligibility details')}}</summary><p v-for="e in assessment.exclusions" :key="e.methodId">{{e.methodId}} · {{e.reasons.join(' · ')}}</p></details></div>
  </article>
  <article class="quality-card"><h3>{{t('检查与分析记录','Checks & analyses')}}</h3><p v-if="!state?.audits.length&&!state?.analyses.length">{{t('检查或运行分析后，结果会保存在这里。','Checks and analyses are saved here after execution.')}}</p>
    <div v-for="a in state?.audits" :key="a.id" class="record"><strong>{{statusLabel(a.decision)}}</strong><small>{{a.createdAt}} · {{a.inputs.length}} {{t('个来源','sources')}}</small><div class="actions"><button v-for="f in a.artifacts" :key="f.path" class="secondary-button" @click="show(a,f.path)">{{f.path.endsWith('.md')?t('检查报告','Check report'):t('来源与回执 JSON','Sources & receipts JSON')}}</button></div><details><summary>{{t('逐项检查','Itemized checks')}}</summary><p v-for="(c,i) in a.checks" :key="i"><span :class="c.status">{{statusLabel(c.status)}}</span> · {{c.code}} · {{c.detail}}<small>{{c.refs.join(' · ')}}</small></p></details></div>
    <div v-for="a in state?.analyses" :key="a.id" class="record"><strong>{{state?.methods.find(m=>m.id===a.methodId)?.name[locale]}} · {{statusLabel(a.status)}}</strong><small>{{a.createdAt}}</small><div class="actions"><button v-for="f in a.artifacts" :key="f.path" class="secondary-button" @click="show(a,f.path)">{{f.path.endsWith('.md')?t('分析报告','Analysis report'):t('数值与输入 JSON','Numbers & inputs JSON')}}</button></div><details><summary>{{t('适用范围与限制','Scope & limitations')}}</summary><p v-for="l in a.limitations" :key="l">{{l}}</p></details></div>
  </article>
  <article class="quality-card"><h3>{{t('来源更新与撤回','Source changes & withdrawal')}}</h3><p>{{t('记录已核实的更正或撤回。历史数据保留，依赖该版本的结论和分析会标为失效；任务运行期间不能修改。','Record confirmed corrections or withdrawals. Keep history and mark dependent conclusions and analyses stale. Stop active tasks before changing source status.')}}</p>
    <div class="form-row"><label>{{t('来源版本','Source version')}}<select v-model="noticeSource"><option value="">{{t('请选择','Select')}}</option><option v-for="s in snapshots" :key="s.id" :value="s.id">{{s.title}} · {{s.version.slice(0,16)}}</option></select></label><label>{{t('变更类型','Change type')}}<select v-model="noticeKind"><option value="updated">{{t('版本更新','Version updated')}}</option><option value="corrected">{{t('内容更正','Corrected')}}</option><option value="retracted">{{t('来源撤回','Retracted')}}</option><option value="access-denied">{{t('访问权限撤销','Access revoked')}}</option></select></label><label>{{t('替代版本（可选）','Replacement (optional)')}}<select v-model="replacement"><option value="">{{t('未选择','None')}}</option><option v-for="s in snapshots.filter(s=>s.id!==noticeSource)" :key="s.id" :value="s.id">{{s.title}} · {{s.version.slice(0,16)}}</option></select></label></div>
    <label>{{t('依据与原因','Evidence & reason')}}<textarea v-model="noticeReason" rows="2" :placeholder="t('例如：出版方更正通知及涉及字段','For example: publisher correction and affected fields')"/></label><button class="secondary-button" :disabled="busy||!noticeSource||!noticeReason.trim()" @click="saveNotice">{{t('记录变更并检查影响','Record change & check impact')}}</button>
    <div v-if="state?.impact.snapshotIds.length" class="impact"><strong>{{t('需要重新核对','Recheck required')}}</strong><p>{{state.impact.deliveryIds.length}} {{t('份交付','deliveries')}} · {{state.impact.analysisIds.length}} {{t('项分析','analyses')}} · {{state.impact.tasks.length}} {{t('个任务','tasks')}}</p><p v-for="task in state.impact.tasks" :key="task.taskId">{{task.taskId.slice(0,8)}} · {{t('受影响步骤','Affected steps')}}: {{task.stepIds.join(', ')}}</p></div>
    <details v-if="state?.notices.length"><summary>{{t('变更历史','Change history')}}</summary><p v-for="n in state.notices" :key="n.id">{{n.at}} · {{n.kind}} · {{n.reason}}</p></details>
  </article>
  <ElDrawer :model-value="!!preview" class="scientific-preview-drawer" :title="t('科学检查与分析','Scientific checks & analysis')" size="min(1080px,96vw)" @update:model-value="preview=''"><MarkdownContent v-if="preview.startsWith('#')" :content="preview"/><pre v-else class="result-json">{{preview}}</pre></ElDrawer>
</section>
</template>
<style scoped>
.scientific-panel{display:grid;gap:18px;min-width:0;max-width:100%;box-sizing:border-box}.quality-card{min-width:0;padding:22px;border:1px solid var(--line);border-radius:14px;background:var(--panel);overflow-wrap:anywhere}.quality-card header{display:flex;justify-content:space-between;gap:14px}.quality-card h2{font-size:18px;margin:10px 0}.quality-card h3{font-size:15px;margin:0 0 10px}.quality-card p,.quality-card summary,.hint{font-size:13px;line-height:1.7;color:var(--muted)}.actions{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.method-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.method-card>svg{color:var(--accent);margin-bottom:12px}.form-row{display:flex;flex-wrap:wrap;gap:12px;margin:14px 0}.form-row>label{flex:1;min-width:180px}label{display:grid;gap:7px;font-size:13px;min-width:0}input,select,textarea{box-sizing:border-box;width:100%;min-width:0;max-width:100%;background:var(--panel-2);color:var(--text);border:1px solid var(--line);padding:10px;border-radius:8px;font:inherit}.observation-row{display:flex;align-items:end;gap:10px;margin:12px 0}.observation-row>label{flex:1;min-width:0}.observation-row>span{padding-bottom:12px}.observation-row>button{flex-shrink:0}.assessment,.record,.impact{border-top:1px solid var(--line);padding-top:16px;margin-top:16px}.record strong,.impact strong{font-size:14px}.record small{display:block;color:var(--muted);font-size:12px;margin-top:7px;overflow-wrap:anywhere}.error,.blocked{color:var(--danger)}.warning{color:var(--muted)}.pass{color:var(--accent)}.result-json{color:var(--text);white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.scientific-panel :global(.scientific-preview-drawer.el-drawer){background:var(--panel);color:var(--text)}.scientific-panel :global(.scientific-preview-drawer .el-drawer__header){color:var(--text)}
@media(max-width:780px){.method-grid{grid-template-columns:1fr}.quality-card{padding:16px}.observation-row{flex-wrap:wrap}.observation-row>label{flex-basis:80%;min-width:0}.form-row>label{min-width:0;flex-basis:100%}}
</style>
