<script setup lang="ts">
import { ref,onMounted,onUnmounted,watch } from 'vue';
import type { PackageStatus,QualityMatrix,EvaluationStatus } from '../../../../../packages/contracts/src/atomistic-validation.js';
import type { RunnablePotentialId } from '../../../../../packages/contracts/src/atomistic-runtime.js';
const api=window.materialsx;
const props=defineProps<{projectId:string|null;locale:'zh'|'en'}>();const emit=defineEmits<{changed:[]}>();
const packages=ref<PackageStatus[]>([]),matrix=ref<QualityMatrix|null>(null),datasets=ref<Awaited<ReturnType<typeof window.materialsx.listScientificDatasets>>>([]),jobs=ref<EvaluationStatus[]>([]);
const datasetId=ref(''),potentialId=ref<RunnablePotentialId>('chgnet-0.3.0'),error=ref(''),busy=ref(false);let timer:ReturnType<typeof setInterval>|undefined;let disposed=false;let generation=0;
const t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
const states:Record<string,string>={absent:'未安装',downloading:'下载中',paused:'已暂停，可续传',installed:'已安装',disabled:'已禁用（文件保留）',failed:'失败',completed:'完成',queued:'排队',running:'评测中',cancelled:'已取消',interrupted:'已中断',blocked:'待满足门槛','passed-screening':'筛查阈值通过','blocked-reference-data-missing':'独立参考待补'};
async function refresh(){const n=++generation;try{const p=await window.materialsx.getScientificPackages();if(disposed||n!==generation)return;packages.value=p;if(props.projectId){const id=props.projectId;const [m,d,j]=await Promise.all([window.materialsx.getScientificQualityMatrix(id),window.materialsx.listScientificDatasets(id),window.materialsx.listScientificEvaluations(id)]);if(disposed||n!==generation||props.projectId!==id)return;matrix.value=m;datasets.value=d;jobs.value=j;if(!datasetId.value&&d[0])datasetId.value=d[0].id;}else{matrix.value=null;datasets.value=[];jobs.value=[];}}catch(e){if(!disposed)error.value=String(e);}}
async function action(fn:()=>Promise<unknown>){busy.value=true;error.value='';try{await fn();await refresh();emit('changed');}catch(e){error.value=String(e);}finally{busy.value=false;}}
watch(()=>props.projectId,()=>{datasetId.value='';void refresh();});onMounted(()=>{void refresh();timer=setInterval(()=>{if(packages.value.some(p=>p.state==='downloading')||jobs.value.some(j=>['queued','running'].includes(j.status)))void refresh();},800);});onUnmounted(()=>{disposed=true;generation++;if(timer)clearInterval(timer);});
</script>
<template>
 <details class="science-validation" data-testid="science-validation">
  <summary>{{t('模型验证与参考数据','Model validation & reference data')}}</summary>
  <p class="hint">{{t('权重、运行与领域精度分开验收。外部参考数据需要许可、理论设置和训练重叠审查；几何样例及多势一致不能代替 DFT。所有报告保留“需复核”，不自动开放正式计算。','Checkpoint identity, runtime and domain accuracy are separate. References require licensing, matched theory and training-overlap review. Geometry fixtures or model agreement are not DFT. Reports never enable production automatically.')}}</p>
  <article v-for="p in packages" :key="p.potentialId" class="package-row" data-testid="extension-package" :data-state="p.state">
   <div><strong>CHGNet r2SCAN</strong><span>{{t(states[p.state]??p.state,p.state)}} · {{(p.totalBytes/1048576).toFixed(2)}} MiB · r2SCAN</span><small>{{p.sha256}}</small><p class="hint">{{t('复用 CHGNet 隔离环境；固定官方来源与哈希。PBE+U 参考不能用于 r2SCAN 精度验收。','Reuses the isolated CHGNet runtime; pinned official source/hash. PBE+U references cannot validate r2SCAN accuracy.')}}</p></div>
   <div class="actions"><button class="secondary-button" data-testid="import-extension" :disabled="busy||p.state==='downloading'" @click="action(()=>api.chooseScientificPackage({potentialId:p.potentialId}))">{{t('导入离线权重','Import offline checkpoint')}}</button><button v-if="!['installed','disabled'].includes(p.state)" class="secondary-button" :disabled="busy||p.state==='downloading'" @click="action(()=>api.downloadScientificPackage({potentialId:p.potentialId}))">{{t(p.state==='paused'?'继续下载':'下载扩展包',p.state==='paused'?'Resume download':'Download extension')}}</button><button v-if="p.state==='downloading'" class="secondary-button" @click="api.cancelScientificPackage()">{{t('暂停下载','Pause download')}}</button><button v-if="['installed','disabled'].includes(p.state)" class="secondary-button" data-testid="disable-extension" :disabled="busy" @click="action(()=>api.disableScientificPackage({potentialId:p.potentialId},p.state!=='disabled'))">{{t(p.state==='disabled'?'重新启用':'禁用自动选势',p.state==='disabled'?'Enable again':'Disable selection')}}</button></div>
   <progress v-if="p.state==='downloading'" :value="p.bytes" :max="p.totalBytes"/><p v-if="p.error" class="error">{{p.error}}</p>
  </article>
  <div class="actions"><button class="secondary-button" data-testid="import-holdout" :disabled="!projectId||busy" @click="action(()=>api.chooseScientificDataset(projectId!))">{{t('导入科学保留集 JSON','Import scientific holdout JSON')}}</button><button class="secondary-button" :disabled="busy" @click="refresh">{{t('刷新质量矩阵','Refresh quality matrix')}}</button></div>
  <table v-if="matrix" class="quality-matrix" data-testid="quality-matrix"><thead><tr><th>{{t('模型 / 理论','Model / theory')}}</th><th>{{t('本机运行时','Local runtime')}}</th><th>{{t('领域筛查','Domain screening')}}</th><th>{{t('正式计算','Production')}}</th></tr></thead><tbody><tr v-for="r in matrix.rows" :key="r.potentialId"><td>{{r.potentialId}}<small>{{r.functional}}</small></td><td>{{r.installed?t('已安装，任务另验','Installed; job validation required'):t('缺失或禁用','Absent or disabled')}}<small>{{r.portable?t('可移植 CPU 环境','Portable CPU environment'):t('无可移植回执','No portable receipt')}} · GPU {{t('未验收','unverified')}}</small></td><td>{{t(states[r.domainStatus]??r.domainStatus,r.domainStatus)}}</td><td>{{t('阻断','Blocked')}}</td></tr></tbody></table>
  <div v-if="datasets.length" class="actions"><label>{{t('保留集','Holdout')}} <select v-model="datasetId" data-testid="holdout-select"><option v-for="d in datasets" :key="d.id" :value="d.id">{{d.title}} · {{d.samples}} · {{d.functional}} · {{d.kind}}</option></select></label><label>{{t('评测模型','Evaluation model')}} <select v-model="potentialId"><option v-for="r in matrix?.rows??[]" :key="r.potentialId" :value="r.potentialId" :disabled="!r.installed">{{r.potentialId}}</option></select></label><button class="primary-button" data-testid="start-evaluation" :disabled="busy||jobs.some(j=>['queued','running'].includes(j.status))" @click="action(()=>api.startScientificEvaluation({projectId:projectId!,datasetId,potentialId}))">{{t('运行真实单点评测','Run actual single-point evaluation')}}</button></div>
  <article v-for="j in jobs" :key="j.id" class="evaluation-row" data-testid="evaluation-job" :data-status="j.status"><strong>{{j.potentialId}}</strong> · {{t(states[j.status]??j.status,j.status)}} · {{j.completedSamples}}/{{j.totalSamples}}<button v-if="['running','queued'].includes(j.status)" class="secondary-button" @click="api.cancelScientificEvaluation(projectId!,j.id)">{{t('取消评测','Cancel evaluation')}}</button><p v-if="j.error" class="error">{{j.error}}</p><template v-if="j.report"><p>{{t(states[j.report.status]??j.report.status,j.report.status)}} · needs_review · {{t('不改变生产准入','No production approval')}}</p><p>{{j.report.reasonCodes.join(' · ')}}</p><table class="quality-matrix"><thead><tr><th>Domain</th><th>N/required</th><th>E MAE (eV/atom)</th><th>F RMSE (eV/Å)</th></tr></thead><tbody><tr v-for="d in j.report.domains" :key="d.domain"><td>{{d.domain}}</td><td>{{d.samples}}/{{d.required}}</td><td>{{d.energyMaeEvPerAtom?.toPrecision(5)??'—'}}</td><td>{{d.forceRmseEvPerAngstrom?.toPrecision(5)??'—'}}</td></tr></tbody></table><button class="secondary-button" @click="action(()=>api.exportScientificEvaluation(projectId!,j.id))">{{t('导出评测 JSON','Export evaluation JSON')}}</button></template></article>
  <p class="hint">{{t('发布待验：独立 DFT 数据、Windows 实机离线安装、签名/公证。开发版流程通过不能替代这些验收。','Release gates pending: independent DFT data, actual Windows offline installation, signing/notarization. Development acceptance does not replace these gates.')}}</p><p v-if="error" class="error">{{error}}</p>
 </details>
</template>
<style scoped>
.science-validation{margin:18px 0;border:1px solid var(--line);border-radius:12px;padding:16px;background:var(--surface)}summary{font-weight:600;cursor:pointer}.hint{color:var(--muted);font-size:12px;line-height:1.65}.package-row,.evaluation-row{padding:14px 0;border-top:1px solid var(--line)}.package-row span,.package-row small,td small{display:block;margin-top:5px;color:var(--muted)}small{font-size:11px;overflow-wrap:anywhere}.actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin:12px 0}.quality-matrix{width:100%;border-collapse:collapse;font-size:12px;color:var(--text)}th,td{padding:10px 7px;text-align:left;border-bottom:1px solid var(--line)}th{color:var(--muted);font-weight:500}select{max-width:290px;background:var(--surface);color:var(--text);border:1px solid var(--line);border-radius:6px;padding:6px}progress{width:100%}.error{color:var(--danger,#d35c63);font-size:12px;overflow-wrap:anywhere}
</style>
