<script setup lang="ts">
import {onMounted,ref} from 'vue';
import type {Ticket} from '../../../../../packages/contracts/src/lifecycle.js';
import {usePreferences} from '../../../../../packages/ui/src/preferences.js';
const {t}=usePreferences();
const tickets=ref<Ticket[]>([]),cursor=ref<string|null>(null),selected=ref<Ticket|null>(null),subject=ref(''),category=ref<'account'|'payment'|'usage'|'research'|'other'>('other'),body=ref(''),referenceId=ref(''),reply=ref(''),attachmentName=ref('diagnostic.txt'),attachmentText=ref(''),consent=ref(false),busy=ref(false),message=ref('');
const keys=new Map<string,string>();
async function mutate<T>(payload:unknown,fn:(key:string)=>Promise<T>){const hash=JSON.stringify(payload),key=keys.get(hash)??crypto.randomUUID();keys.set(hash,key);const out=await fn(key);keys.delete(hash);return out}
async function action(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;message.value='';try{await fn()}catch{message.value=t('操作未完成，请刷新核对。请勿粘贴密钥、密码或未经授权的文档。','Operation incomplete. Refresh to check. Do not paste keys, passwords or unauthorized documents.')}finally{busy.value=false}}
async function refresh(){const page=await window.materialsx.getSupportTickets();tickets.value=page.items;cursor.value=page.nextCursor;if(selected.value)selected.value=tickets.value.find(v=>v.id===selected.value?.id)??null}
async function more(){if(!cursor.value)return;const page=await window.materialsx.getSupportTickets(cursor.value);tickets.value.push(...page.items);cursor.value=page.nextCursor}
async function create(){const input={subject:subject.value.trim(),category:category.value,body:body.value.trim(),referenceId:referenceId.value.trim()};await action(async()=>{const v=await mutate(input,key=>window.materialsx.createSupportTicket(input,key));await refresh();selected.value=v;subject.value='';body.value='';referenceId.value=''})}
async function send(state:'open'|'closed'){const v=selected.value;if(!v||!reply.value.trim())return;const input={body:reply.value.trim(),state,expectedVersion:v.version};await action(async()=>{selected.value=await mutate([v.id,input],key=>window.materialsx.replySupportTicket(v.id,input,key));reply.value='';await refresh()})}
async function attach(){const v=selected.value;if(!v||!consent.value)return;const input={name:attachmentName.value,text:attachmentText.value,consentVersion:'support-text-v1' as const};await action(async()=>{await mutate([v.id,input],key=>window.materialsx.attachSupportText(v.id,input,key));attachmentText.value='';consent.value=false;await refresh()})}
onMounted(()=>action(refresh));
</script>
<template><article class="catalog-panel support-panel"><div class="catalog-panel-heading"><div><h2>{{t('帮助与工单','Help and support')}}</h2><p>{{t('提交问题，查看处理记录。附件由您主动授权。','Submit an issue and view replies. Attachments require your explicit consent.')}}</p></div><button class="secondary-button" :disabled="busy" @click="action(refresh)">{{t('刷新','Refresh')}}</button></div><p v-if="message" role="status">{{message}}</p>
<details><summary>{{t('新建工单','Create a ticket')}}</summary><form @submit.prevent="create"><label>{{t('标题','Subject')}}<input v-model="subject" maxlength="160" required /></label><label>{{t('类别','Category')}}<select v-model="category"><option value="account">{{t('账户','Account')}}</option><option value="payment">{{t('支付与退款','Payment and refunds')}}</option><option value="usage">{{t('积分与用量','Credits and usage')}}</option><option value="research">{{t('科研结果','Research results')}}</option><option value="other">{{t('其他','Other')}}</option></select></label><label>{{t('订单或请求 ID（可选）','Order or request ID (optional)')}}<input v-model="referenceId" maxlength="128" /></label><label>{{t('问题描述','Description')}}<textarea v-model="body" rows="4" maxlength="8000" required /></label><button class="primary-button" :disabled="busy">{{t('提交','Submit')}}</button></form></details>
<div class="support-list"><button v-for="v in tickets" :key="v.id" class="secondary-button" @click="selected=v">{{v.subject}} · {{v.state}}</button><p v-if="!tickets.length">{{t('暂无工单','No tickets yet')}}</p><button v-if="cursor" class="secondary-button" :disabled="busy" @click="action(more)">{{t('更多','More')}}</button></div>
<section v-if="selected"><h3>{{selected.subject}}</h3><small>{{selected.id}} · {{selected.state}}</small><div v-for="event in selected.events" :key="event.id" class="support-event"><small>{{new Date(event.createdAt).toLocaleString()}} · {{event.state}}</small><p>{{event.body}}</p></div><form v-if="selected.state!=='closed'" @submit.prevent="send('open')"><label>{{t('补充说明','Reply')}}<textarea v-model="reply" rows="3" maxlength="8000" required /></label><div class="actions"><button class="primary-button" :disabled="busy">{{t('发送并继续处理','Send and reopen')}}</button><button type="button" class="secondary-button" :disabled="busy||!reply.trim()" @click="send('closed')">{{t('关闭工单','Close ticket')}}</button></div></form>
<details v-if="selected.state!=='closed'"><summary>{{t('授权附加脱敏文本','Share redacted diagnostic text')}}</summary><p>{{t('最多 32 KiB，仅上传下方粘贴的内容；不会自动读取日志或项目文件。请先删除敏感信息。','Up to 32 KiB. Only the text pasted below is uploaded; logs and project files are never read automatically. Remove sensitive information first.')}}</p><form @submit.prevent="attach"><input v-model="attachmentName" maxlength="80" required :aria-label="t('附件名','Attachment name')" /><textarea v-model="attachmentText" rows="4" maxlength="32768" required /><label class="consent"><input v-model="consent" type="checkbox" />{{t('我授权管理员查看上述文本（support-text-v1）','I authorize administrators to view this text (support-text-v1)')}}</label><button class="secondary-button" :disabled="busy||!consent">{{t('授权并上传','Authorize and upload')}}</button></form></details><p v-for="a in selected.attachments" :key="a.id">{{a.name}} · SHA-256 {{a.sha256.slice(0,12)}}…</p></section></article></template>
<style scoped>
.support-panel{margin-top:16px}.support-panel p{font-size:11px;color:var(--muted);line-height:1.65}.support-panel h2{font-size:14px;margin:0}.support-panel h3{font-size:13px}.support-panel label{display:grid;gap:6px;font-size:11px}.support-panel form{display:grid;gap:12px;margin:14px 0}.support-panel input:not([type=checkbox]),.support-panel select,.support-panel textarea{width:100%;box-sizing:border-box;border:1px solid var(--line);border-radius:7px;background:var(--catalog-surface);color:var(--text);padding:9px;font:inherit;font-size:11px}.support-panel summary{cursor:pointer;font-size:12px}.support-list{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.support-event{border-top:1px solid var(--line);padding:10px 0}.support-event p{white-space:pre-wrap;color:var(--text)}.support-panel small{font-size:9px;color:var(--muted);overflow-wrap:anywhere}.support-panel .consent{display:flex;align-items:center}.support-panel .actions{display:flex;gap:8px}
</style>
