<script setup lang="ts">
import {ref,onMounted,onUnmounted,watch} from 'vue';
import type {UserSkillRecord} from '../../../../../packages/atomistic/src/user-skills.js';
import type {userSkillDraftSchema} from '../../../../../packages/contracts/src/potential-hub.js';
import type {z} from 'zod';
const api=window.materialsx;
const props=defineProps<{locale:'zh'|'en';incomingDraft?:z.infer<typeof userSkillDraftSchema>|null}>();const emit=defineEmits<{'changed':[]}>();
const t=(zh:string,en:string)=>props.locale==='zh'?zh:en;
type Draft=z.infer<typeof userSkillDraftSchema>;
const initial=():Draft=>({schemaVersion:'m6.7-v1',name:'my-crystal-analysis',description:{zh:'检查无机晶体并生成探索分析报告。',en:'Inspect an inorganic crystal and generate an exploratory analysis report.'},instructions:{zh:'先使用 potential_search 与 materials_science 检查适用范围。仅对用户授权的已导入结构进行计算，读取真实终态与文件，报告单位、收敛条件及 needs_review。',en:'Use potential_search and materials_science to check eligibility. Calculate only for the imported structure in user-approved scope. Read actual terminal status and artifacts; report units, convergence and needs_review.'},examples:[{zh:'@my-crystal-analysis 分析已导入无机晶体，先让我审阅计算计划。',en:'@my-crystal-analysis Analyze my imported inorganic crystal; show the plan for review.'}],potentialIds:[],requiredTools:['potential_search','materials_science']});
const records=ref<UserSkillRecord[]>([]),draft=ref<Draft>(initial()),revision=ref<number|null>(null),preview=ref(''),error=ref(''),busy=ref(false),expanded=ref(false);
watch(draft,()=>preview.value='',{deep:true});
watch(()=>draft.value.name,(name,previous)=>{if(previous&&revision.value===null)for(const e of draft.value.examples){e.zh=e.zh.replaceAll('@'+previous,'@'+name);e.en=e.en.replaceAll('@'+previous,'@'+name);}});
async function refresh(){records.value=await api.listUserSkills();}
async function act(f:()=>Promise<unknown>){busy.value=true;error.value='';try{await f();await refresh();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{busy.value=false;}}
function edit(r:UserSkillRecord){draft.value=JSON.parse(JSON.stringify(r.draft));revision.value=r.revision;preview.value='';expanded.value=true;}
function reset(){draft.value=initial();revision.value=null;preview.value='';expanded.value=true;}
async function validate(){preview.value=(await api.previewUserSkill(JSON.parse(JSON.stringify(draft.value)))).text;}
async function importDraft(){const r=await api.importUserSkill();if(!r)return;draft.value=r.draft;revision.value=null;expanded.value=true;preview.value='';await validate();}
async function save(){const r=await api.saveUserSkill(JSON.parse(JSON.stringify(draft.value)),revision.value);revision.value=r.revision;emit('changed');}
watch(()=>props.incomingDraft,async d=>{if(d){await refresh();draft.value=JSON.parse(JSON.stringify(d));revision.value=records.value.find(r=>r.draft.name===d.name)?.revision??null;expanded.value=true;await act(validate);}},{immediate:true});
let remove:()=>void;onMounted(()=>{void act(refresh);remove=api.onUserSkillDraft(d=>{draft.value=d;revision.value=records.value.find(r=>r.draft.name===d.name)?.revision??null;expanded.value=true;preview.value='';void act(validate);});});onUnmounted(()=>remove?.());
</script>
<template><section class="user-skills-panel" data-testid="user-skills"><div class="user-heading"><strong>{{t('我的 Skills','My Skills')}} · {{records.length}}</strong><button class="secondary-button" :disabled="busy" @click="act(importDraft)">{{t('导入 Skill JSON','Import Skill JSON')}}</button><button class="secondary-button" @click="reset">{{t('创建 Skill','Create Skill')}}</button><button class="secondary-button" @click="expanded=!expanded">{{t('编辑器','Editor')}}</button></div><p>{{t('用户 Skill 保存在本机，支持中英文与使用例子。先预览后保存；不会覆盖内置 Skill，也不会自动执行脚本。保存后即可通过 @ 调用。导入仅接收双语 JSON 指令草稿；先核对来源权利、步骤和工具依赖，不安装脚本或依赖。','User Skills are local, bilingual and include examples. Preview before saving; builtin Skills cannot be overwritten and scripts are not auto-executed. Saved enabled Skills are available through @. Import accepts bilingual JSON instructions only; review rights and dependencies before saving. Scripts and packages are not installed.')}}</p><div v-if="records.length" class="catalog-grid"><article v-for="r in records" :key="r.draft.name" class="catalog-card"><div class="catalog-content"><strong>{{r.draft.name}} · v{{r.revision}}</strong><p>{{r.draft.description[locale]}}</p><span>{{r.enabled?t('已启用','Enabled'):t('已停用','Disabled')}}</span><div class="user-actions"><button class="skill-example-copy" @click="edit(r)">{{t('编辑与预览','Edit & preview')}}</button><button class="skill-example-copy" :disabled="busy" @click="act(async()=>{await api.enableUserSkill(r.draft.name,!r.enabled);emit('changed')})">{{r.enabled?t('停用','Disable'):t('启用','Enable')}}</button><button class="skill-example-copy" :disabled="busy" @click="act(async()=>{await api.deleteUserSkill(r.draft.name,r.revision);emit('changed');if(draft.name===r.draft.name)reset()})">{{t('删除','Delete')}}</button></div></div></article></div>
<div v-if="expanded" class="user-editor" data-testid="user-skill-editor"><label>{{t('名称（英文小写与连字符）','Name (lowercase, hyphenated)')}}<input v-model="draft.name" :disabled="revision!==null" data-testid="user-skill-name"/></label><label v-for="lang in ['zh','en'] as const" :key="'description-'+lang">{{lang==='zh'?'中文简介':'English description'}}<input v-model="draft.description[lang]"/></label><label v-for="lang in ['zh','en'] as const" :key="'instructions-'+lang">{{lang==='zh'?'中文步骤与限制':'English workflow & limitations'}}<textarea v-model="draft.instructions[lang]"/></label><div v-for="(e,i) in draft.examples" :key="i" class="user-examples"><label>中文例子 {{i+1}}<textarea v-model="e.zh"/></label><label>English example {{i+1}}<textarea v-model="e.en"/></label></div><button v-if="draft.examples.length<2" class="skill-example-copy" @click="draft.examples.push({zh:'',en:''})">{{t('增加一个例子','Add one example')}}</button><details><summary>{{t('目录与工具依赖（受控 ID）','Catalog & tool dependencies (controlled IDs)')}}</summary><p>{{draft.potentialIds.join(', ')||'—'}} · {{draft.requiredTools.join(', ')}}</p><small>{{t('可由内置 materials-skill-creator 使用目录搜索生成草稿，并自动显示在此编辑器。','The builtin materials-skill-creator can search the catalog and send a draft to this editor.')}}</small></details><div class="user-actions"><button class="secondary-button" :disabled="busy" data-testid="user-skill-preview" @click="act(validate)">{{t('校验并预览','Validate & preview')}}</button><button class="primary-button" :disabled="busy||!preview" data-testid="user-skill-save" @click="act(save)">{{t('保存当前版本','Save current version')}}</button></div><pre v-if="preview" data-testid="user-skill-preview-text">{{preview}}</pre></div><p v-if="error" role="alert">{{error}}</p></section></template>
<style scoped>.user-skills-panel{max-width:1120px;margin:16px auto;border:1px solid var(--line);border-radius:9px;padding:16px;background:var(--catalog-surface);color:var(--text)}.user-heading,.user-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.user-heading strong{flex:1}.user-skills-panel p,small,details{font-size:12px;line-height:1.7;color:var(--muted)}.user-editor{display:grid;gap:12px;margin-top:16px}.user-editor label{display:grid;gap:6px;font-size:12px}.user-editor input,.user-editor textarea{border:1px solid var(--line);border-radius:7px;background:var(--catalog-surface);color:var(--text);padding:9px;min-width:0}.user-editor textarea{min-height:70px;resize:vertical}.user-examples{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:340px;overflow:auto;background:var(--panel-2);border:1px solid var(--line);border-radius:7px;padding:14px;font-size:12px}.catalog-card{cursor:default}@media(max-width:760px){.user-examples{grid-template-columns:minmax(0,1fr)}}</style>
