/** Bilingual annotations of existing names. Schemas, permissions and readiness come from the live registry. */
const rows:readonly (readonly [string,string,string,string,string,string])[]=[
 ['paper_search','查找论文','Search papers','论文 文献 arxiv search literature publications','公开检索词 / Public query','论文元数据与来源 / Metadata and sources'],
 ['paper_get','核对论文信息','Read paper metadata','论文 元数据 DOI paper metadata','已注册论文 ID / Registered paper ID','标题摘要与来源 / Title, abstract, source'],
 ['paper_fetch','下载论文','Download a paper','论文 PDF download fetch','论文 ID 与研究授权 / Paper ID and research grant','本机 PDF 及哈希 / Local PDF and hash'],
 ['paper_read','按页阅读论文','Read paper pages','论文 PDF 阅读 evidence read pages','已下载论文与页码 / Downloaded paper and pages','页面文本、范围及遗漏 / Text, range and missing pages'],
 ['paper_export','导出参考文献','Export references','论文 bibtex bibliography citations export','论文 ID 与格式 / Paper IDs and format','JSON/BibTeX/CSV/Markdown'],
 ['research_data','读取材料来源数据','Find materials source data','MOOS 水性涂料 配方 工艺 性能 recipe formulation coating process data search','检索词或真实记录 ID / Query or actual record ID','组分用量、步骤、来源证据 / Amounts, process, evidence'],
 ['recipe_proposal','提出配方工艺建议','Propose recipe changes','配方 工艺 recipe formulation propose suggestion','已读取来源与修改方案 / Read sources and changes','待验证建议，不是实验 / Unverified proposal, not an experiment'],
 ['research_delivery','导出研究资料','Export research sources','对比 表格 comparison report source delivery','真实来源和交付要求 / Sources and delivery contract','带来源的表格、图表、报告 / Evidence-linked deliverables'],
 ['materials_science','分析原子与分子结构','Analyze atomic or molecular structures','结构 能量 单点 受力 晶体 分子 势 弛豫 分子动力学 structure energy forces crystal molecule potential relaxation dynamics','已批准结构与实际选势 ID / Approved structure and actual selection ID','能量受力、任务状态、报告、3D / Results, status, report, 3D'],
 ['potential_search','查找机器学习势','Find machine learning potentials','机器学习势 potential mlip 晶体 分子 catalog models','用途、元素、周期性 / Task, elements, periodicity','目录候选，不授予计算权限 / Catalog candidates, no run permission'],
 ['potential_discover','发现新的势与论文线索','Discover potential resources','新势 发布 论文 release discovery potential','公开关键词与固定来源 / Public query and fixed sources','待审核来源线索 / Leads pending review'],
 ['skill_search','查找研究 Skill','Find research Skills','技能 skill 方法 工作流 workflows','中英文用途 / Chinese or English purpose','说明概览与安装状态 / Overview and installation status'],
 ['read_skill','阅读指定 Skill','Read a selected Skill','技能 skill instructions read','已安装名称与行范围 / Installed name and line range','固定版本说明与读取范围 / Pinned instructions and range'],
 ['skill_resource','读取 Skill 附带资源','Read Skill resources','skill resources script reference 模板 附带脚本','Skill 名称及资源路径 / Skill name and resource path','受权资源 / Scoped resource'],
 ['skill_capabilities','检查 Skill 能力','Check Skill capabilities','skill installed available readiness 技能 状态','Skill 名称 / Skill name','安装、配置与运行限制 / Installation and runtime limits'],
 ['materials_rpsme_extract','提取论文材料实验','Extract paper experiments','论文 PDF 提取 配方 实验 rpsme extract experiments','批准 PDF / Approved PDF','RPSME JSON、中文摘要、校验 / Evidence-linked extraction'],
 ['research_methods','评估数据分析方法','Assess data analysis methods','统计 平均 拟合 statistics mean average fit regression 方法','已批准数据与问题 / Approved data and question','适用候选与排除原因 / Eligible methods and exclusions'],
 ['research_method_run','执行数据分析','Run data analysis','统计 平均 拟合 statistics mean average fit regression calculate','真实方法评估 ID / Actual method assessment ID','分析 JSON 与报告 / Analysis JSON and report'],
 ['research_quality','核验科学数据质量','Check scientific data quality','统计 平均 拟合 质量 数据 单位 statistics mean average fit quality data units validation','真实来源 / Actual sources','质量 JSON 与报告 / Quality JSON and report'],
 ['experiment_data','读取拉伸实验数据','Read tensile experiment data','拉伸 应力应变 tensile stress-strain data','已导入实验 ID / Imported experiment ID','冻结样本与设置 / Frozen samples and settings'],
 ['experiment_analyze','分析拉伸实验','Analyze tensile experiments','拉伸 应力应变 tensile stress-strain analysis','已确认实验设置 / Confirmed experimental settings','结果、图表、报告 / Results, charts, report'],
 ['next_experiment_data','读取实验设计设置','Read experiment design settings','下一轮实验 实验设计 DOE active learning bayesian','已保存研究 ID / Saved study ID','数据与缺项 / Data and missing conditions'],
 ['next_experiment_design','设计下一轮实验','Design the next experiment','下一轮实验 实验设计 DOE active learning bayesian','已确认设置与预算 / Confirmed settings and budget','候选、实验顺序与报告 / Candidates, order, report'],
 ['method_package_search','查找方法包','Find method packages','方法包 method package catalog','方法用途 / Method purpose','方法合同与资格 / Contracts and qualification'],
 ['campaign_job','管理后台计算','Manage background computations','后台 长期 计算 campaign background long-running jobs','已批准管线或原任务 ID / Approved pipeline or original job ID','真实任务状态与产物 / Actual state and artifacts'],
 ['research_subtask','执行独立研究子任务','Run an independent research subtask','子任务 分工 delegate subtask','显式授权与独立目标 / Explicit grant and independent objective','实际子任务回执 / Actual subtask receipts'],
 ['research_browser','读取网页与图片','Read web pages and images','浏览器 网页 图像 browser web image screenshot','允许来源与读取范围 / Allowed source and range','真实页面或图片证据 / Actual page or image evidence'],
 ['environment_check','检查运行环境','Check the managed environment','环境 依赖 Python environment dependencies check','受管环境 / Managed environment','实际状态与依赖版本 / Actual status and versions'],
 ['environment_repair','修复受管依赖','Repair managed dependencies','环境 依赖 environment dependencies repair','受权锁定环境 / Authorized locked environment','修复或回滚回执 / Repair or rollback receipt'],
 ['official_document','查询官方文档','Read official documentation','官方 文档 docs documentation python arxiv','受支持来源 / Supported source','有来源的文档片段 / Source-linked excerpts'],
 ['exec_command','运行项目命令','Run a project command','修 Python 调试 脚本 code script repair fix debug terminal command','项目内命令 / Scoped project command','实际退出码或会话 ID / Actual exit or session ID'],
 ['bash','运行项目命令','Run a project command','修 Python 调试 脚本 code script repair fix debug terminal command','项目内命令 / Scoped project command','实际输出与退出状态 / Actual output and exit'],
 ['apply_patch','修改项目代码','Patch project code','修 Python 修复 代码 code script repair fix debug patch','真实补丁 / Actual patch','文件修改回执 / File change receipt'],
 ['edit','编辑项目文件','Edit project files','修 Python 代码 code script repair fix edit','受权路径与替换内容 / Approved path and replacement','编辑回执 / Edit receipt'],
 ['write','写入项目文件','Write project files','文件 报告 file report write','受权路径与内容 / Approved path and content','文件回执 / File receipt'],
 ['read','读取项目文件','Read project files','修 Python 源码 文件 code source script file read','受权路径与行范围 / Approved path and range','实际内容与截断信息 / Actual content and truncation'],
 ['ls','查看项目目录','List project files','目录 文件 directory file list','受权目录 / Approved directory','真实目录项 / Actual entries'],
 ['find','查找项目文件','Find project files','文件 搜索 路径 file search path find','受权目录及模式 / Approved directory and pattern','真实路径 / Actual paths'],
 ['grep','查找项目文本','Search project text','代码 搜索 文本 code text search grep','受权范围及模式 / Approved scope and pattern','文本匹配与位置 / Matches and locations'],
 ['write_stdin','查询或交互终端会话','Poll or interact with a terminal session','终端 进程 等待 session terminal process poll','当前步骤拥有的会话 ID / Session ID owned by this step','输出与实际终态 / Output and actual terminal status'],
 ['read_material_file','读取已选文件快照','Read a selected file snapshot','附件 文件 snapshot attached file read','批准的文件 ID / Approved file ID','固定字节与版本 / Frozen bytes and version'],
];
const examples:Record<string,{zh:string;en:string}>={
 paper_search:{zh:'查找近两年水性辐射制冷涂料论文，保留原始检索词和来源。',en:'Search recent papers about waterborne radiative cooling coatings and keep sources.'},
 research_data:{zh:'找本项目已授权的水性涂料配方，列出组分、原始用量和证据。',en:'Find approved coating recipes and report original amounts and evidence.'},
 materials_science:{zh:'对已授权的硅结构计算单点能量与原子受力，先检查势的适用范围。',en:'Calculate energy and forces for approved silicon using an eligible potential.'},
 exec_command:{zh:'读取项目中失败的 Python 脚本，定位错误后运行必要检查。',en:'Inspect the failing project Python script and run the relevant checks.'},
};
export function toolMetadata(name:string){
 const row=rows.find(r=>r[0]===name);if(!row)return null;
 return {purpose:{zh:row[1],en:row[2]},aliases:row[3],input:row[4],output:row[5],
  examples:examples[name]??{zh:row[1]+'：'+row[4].split(' / ')[0]+' → '+row[5].split(' / ')[0],en:row[2]+': '+(row[4].split(' / ')[1]??row[4])+' → '+(row[5].split(' / ')[1]??row[5])}};
}
