import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm,readdir,symlink,lstat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {CatalogWeightManager} from './catalog-weights.js';
import {PotentialDistributionService} from './potential-distribution.js';
import {PotentialPackageManager} from './package-manager.js';
import type {HubEntry,PotentialCatalog} from '../../contracts/src/potential-hub.js';
const bytes=Buffer.from('verified checkpoint fixture — not executable');
const hash=(v:Uint8Array)=>createHash('sha256').update(v).digest('hex');
const makeEntry=(known=true)=>({id:'fixture-model',name:'Fixture',entityType:'checkpoint',access:'public',asset:{url:'https://github.com/example/model/releases/download/v1/fixture.bin',revision:'v1',sha256:known?hash(bytes):null,bytes:known?bytes.length:null}} as HubEntry);
async function fixture(t:any,entry=makeEntry(),network:typeof fetch=(async()=>new Response(bytes,{headers:{'Content-Length':String(bytes.length)}})) as typeof fetch){const root=await mkdtemp(join(tmpdir(),'mx-catalog-weight-'));t.after(()=>rm(root,{recursive:true,force:true}));const catalog={entries:[entry]} as PotentialCatalog;const manager=new CatalogWeightManager(root,()=>catalog,()=>{},network);return{root,catalog,manager};}
test('download commits actual bytes and fingerprint, remains outside executable package cache',async t=>{const{root,manager}=await fixture(t);await manager.download('fixture-model');const status=await manager.status('fixture-model');assert.equal(status.state,'downloaded');assert.equal(status.verifiedAgainstCatalog,true);assert.equal(status.observedSha256,hash(bytes));assert.deepEqual(await readFile(await manager.cachedFile('fixture-model')),bytes);await assert.rejects(lstat(join(root,'scientific-packages')),{code:'ENOENT'});const items=await manager.storageItems();assert.equal(items.length,1);assert.equal(items[0]!.kind,'catalog');await manager.removeStorage(items[0]!.id.slice(8));assert.equal((await manager.status('fixture-model')).state,'absent');});
test('unverified source records a local fingerprint without claiming catalog verification; reveal rehashes',async t=>{const{manager}=await fixture(t,makeEntry(false));await manager.download('fixture-model');const s=await manager.status('fixture-model');assert.equal(s.verifiedAgainstCatalog,false);assert.equal(s.observedSha256,hash(bytes));const file=await manager.cachedFile('fixture-model');await writeFile(file,Buffer.alloc(bytes.length));await assert.rejects(manager.cachedFile('fixture-model'),/ARTIFACT_CHANGED/);});
test('bad checksum, truncated response, HTML response never become a downloaded model',async t=>{for(const response of [()=>new Response(Buffer.alloc(bytes.length)),()=>new Response(bytes.subarray(0,4)),()=>new Response('<html>login</html>',{headers:{'Content-Type':'text/html'}})]){const{manager}=await fixture(t,makeEntry(),(async()=>response()) as typeof fetch);await assert.rejects(manager.download('fixture-model'));assert.equal((await manager.status('fixture-model')).state,'failed');await assert.rejects(manager.cachedFile('fixture-model'),/NOT_DOWNLOADED/);}});
test('pause and resume a pinned source checks Range and validates final digest',async t=>{let calls=0;const network=(async(_url:any,init:any)=>{calls++;if(calls===1){return new Response(new ReadableStream({start(c){c.enqueue(bytes.subarray(0,8));init.signal.addEventListener('abort',()=>c.error(init.signal.reason),{once:true});}}),{headers:{'Content-Length':String(bytes.length)}});}assert.equal(new Headers(init.headers).get('Range'),'bytes=8-');return new Response(bytes.subarray(8),{status:206,headers:{'Content-Length':String(bytes.length-8),'Content-Range':`bytes 8-${bytes.length-1}/${bytes.length}`}});}) as typeof fetch;const{manager}=await fixture(t,makeEntry(),network);const pending=manager.download('fixture-model');const rejected=assert.rejects(pending);for(let n=0;n<100;n++){if((await manager.status('fixture-model')).bytes===8)break;await new Promise(r=>setTimeout(r,10));}assert(manager.busy());assert.equal((await manager.storageItems())[0]!.removable,false);assert(manager.cancel('fixture-model'));await rejected;assert.equal((await manager.status('fixture-model')).state,'paused');await manager.download('fixture-model');assert.equal(calls,2);assert.equal((await manager.status('fixture-model')).state,'downloaded');});
test('untrusted redirect and gated source fail without crossing approved host boundary',async t=>{let calls=0;const{manager}=await fixture(t,makeEntry(),(async()=>{calls++;return new Response(null,{status:302,headers:{Location:'http://127.0.0.1:1234/private'}});}) as typeof fetch);await assert.rejects(manager.download('fixture-model'),/SOURCE_UNSUPPORTED/);assert.equal(calls,1);const gated=await fixture(t,makeEntry(),(async()=>new Response(null,{status:403})) as typeof fetch);await assert.rejects(gated.manager.download('fixture-model'),/ACCESS_REQUIRED/);});
test('unknown digest cannot import; matching known local file can import',async t=>{const known=await fixture(t),file=join(known.root,'local.bin');await writeFile(file,bytes);await known.manager.importFile('fixture-model',file);assert.equal((await known.manager.status('fixture-model')).state,'downloaded');const unknown=await fixture(t,makeEntry(false));await assert.rejects(unknown.manager.importFile('fixture-model',file),/EXPECTED_HASH_REQUIRED/);});
test('cache symlinks and traversal IDs are rejected; withdrawn/orphan files remain clearable',async t=>{const{root,manager,catalog}=await fixture(t);await assert.rejects(manager.download('../outside'));await manager.download('fixture-model');const item=(await manager.storageItems())[0]!;catalog.entries=[];assert.equal((await manager.storageItems())[0]!.id,item.id);await manager.removeStorage(item.id.slice(8));assert.equal((await manager.storageItems()).length,0);await rm(join(root,'catalog-weights'),{recursive:true});const outside=join(root,'outside');await mkdir(outside);await symlink(outside,join(root,'catalog-weights'));catalog.entries=[makeEntry()];await assert.rejects(manager.download('fixture-model'),/CACHE_UNSAFE/);assert.deepEqual(await readdir(outside),[]);});
test('source change or withdrawal during stream prevents commit',async t=>{const entry=makeEntry();let allowed=true;const root=await mkdtemp(join(tmpdir(),'mx-withdrawn-'));t.after(()=>rm(root,{recursive:true,force:true}));const manager=new CatalogWeightManager(root,()=>({entries:[entry]} as PotentialCatalog),()=>{if(!allowed)throw Error('POTENTIAL_WITHDRAWN');},(async()=>{allowed=false;return new Response(bytes);}) as typeof fetch);await assert.rejects(manager.download(entry.id),/WITHDRAWN/);assert.equal((await manager.storageItems()).length,1);await manager.removeStorage((await manager.storageItems())[0]!.id.slice(8));});
test('storage preview includes directory downloads and prevents stale cleanup',async t=>{const{root,manager}=await fixture(t);await manager.download('fixture-model');const distribution=new PotentialDistributionService(process.cwd(),root,new PotentialPackageManager(process.cwd(),root),()=>false,()=>{},manager);const inventory=await distribution.inventory(),item=inventory.items.find(i=>i.kind==='catalog')!;assert(item.removable);assert(inventory.reclaimableBytes>=bytes.length);await assert.rejects(distribution.cleanup({ids:[item.id],inventorySha256:'0'.repeat(64)}),/PREVIEW_STALE/);const result=await distribution.cleanup({ids:[item.id],inventorySha256:inventory.inventorySha256});assert.deepEqual(result.removed,[item.id]);assert.equal((await manager.status('fixture-model')).state,'absent');});

test('a fully received pinned partial commits without another network call',async t=>{let calls=0;const{root,manager}=await fixture(t,makeEntry(),(async()=>{calls++;return new Response(bytes);}) as typeof fetch);await manager.status('fixture-model');const parent=join(root,'catalog-weights','fixture-model'),key=(await readdir(parent))[0]!;await writeFile(join(parent,key,'checkpoint.part'),bytes);await manager.download('fixture-model');assert.equal(calls,0);assert.equal((await manager.status('fixture-model')).state,'downloaded');});

test('concurrent requests cannot race the initial directory creation',async t=>{const{manager}=await fixture(t);const first=manager.download('fixture-model');await assert.rejects(manager.download('fixture-model'),/DOWNLOAD_BUSY/);await first;assert.equal((await manager.status('fixture-model')).state,'downloaded');});
