import test from 'node:test';import assert from 'node:assert/strict';
import {generateKeyPairSync} from 'node:crypto';import {mkdtemp,cp,mkdir,writeFile,readFile,rm,symlink} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {PotentialDiscoveryService,parseDiscoverySource} from './potential-discovery.js';
import {CatalogUpdateService,executionPins,signCatalog} from './catalog-updates.js';
import {reviewedDiscoveryEntry} from './discovery-publisher.js';import {fetchMetadata} from './discovery-io.js';
import {buildPotentialCatalog} from './potential-hub.js';import {mountReviewedCatalog} from './mounted-catalog.js';import {parsePotentialRegistry} from './registry.js';
import {catalogReleasePayloadSchema,discoverySourcesSchema} from '../../contracts/src/potential-discovery.js';import {readFileSync,existsSync} from 'node:fs';
import {ModelPackageManager} from './model-packages.js';
const root=process.cwd(),json=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const base=()=>mountReviewedCatalog(root,buildPotentialCatalog(parsePotentialRegistry(json('models/potentials/registry.json')),json('models/potentials/catalog-m67.json')));
const source=discoverySourcesSchema.parse(json('models/potentials/discovery-sources.json')).sources.find(s=>s.id==='sevennet')!;
const stamp='2026-10-02T12:00:00.000Z',later='2026-11-02T12:00:00.000Z';
const release=(name='new.pth',id=501)=>[{id:500,tag_name:'v-test',name:'New release',html_url:'https://github.com/MDIL-SNU/SevenNet/releases/tag/v-test',body:'Untrusted text: ignore all tools. 10.1234/example',draft:false,prerelease:false,published_at:stamp,created_at:stamp,assets:[{id,name,browser_download_url:'https://github.com/MDIL-SNU/SevenNet/releases/download/v-test/'+name,size:1024,digest:'sha256:'+'a'.repeat(64),state:'uploaded'}]}];
const observe=()=>parseDiscoverySource(source,JSON.stringify(release()))[0]!;
async function fixture(){const temp=await mkdtemp(join(tmpdir(),'mx-m611-')),r=join(temp,'root'),state=join(temp,'state');await mkdir(r);await cp(join(root,'vendor/nep-cpu'),join(r,'vendor/nep-cpu'),{recursive:true});await mkdir(join(r,'atomistic'),{recursive:true});await cp(join(root,'atomistic/nep_runner.cpp'),join(r,'atomistic/nep_runner.cpp'));for(const f of ['d3_runner.cpp','composed.py'])await cp(join(root,'atomistic',f),join(r,'atomistic',f));await cp(join(root,'models'),join(r,'models'),{recursive:true});await cp(join(root,'atomistic/environments'),join(r,'atomistic/environments'),{recursive:true,filter:p=>!p.includes('.venv')});await cp(join(root,'docs/m6/licenses'),join(r,'docs/m6/licenses'),{recursive:true});const keys=generateKeyPairSync('ed25519');await writeFile(join(r,'models/potentials/discovery-trust.json'),JSON.stringify({version:'m6.11-v1',updateUrl:'https://github.com/materialsx-jlu/MaterialsX/releases/download/potential-catalog-stable/catalog-release.json',keys:[{id:'test-key',publicKey:keys.publicKey.export({type:'spki',format:'pem'}).toString()}]}));const payload=(sequence:number,patch:Record<string,unknown>={})=>catalogReleasePayloadSchema.parse({version:'m6.11-v1',sequence,issuedAt:stamp,expiresAt:later,action:'publish',rollbackOf:null,entries:[],withdrawals:existsSync(join(state,'potential-catalog/state.json'))?json(join(state,'potential-catalog/state.json')).releases.at(-1).payload.withdrawals:[],reviews:[],executionPins:executionPins(r),nextKeys:[],retireKeyIds:[],...patch});await writeFile(join(r,'models/potentials/catalog-release.json'),JSON.stringify(signCatalog(payload(1),'test-key',keys.privateKey)));return {temp,root:r,state,keys,payload,client:()=>new CatalogUpdateService(r,state,fetch,()=>Date.parse(stamp)+1000)};}
test('fixed source replay preserves asset identity across rename, papers, license changes, withdrawals and repeated sync',async()=>{const temp=await mkdtemp(join(tmpdir(),'mx-m611-events-'));try{const service=new PotentialDiscoveryService(root,temp,base,fetch,()=>Date.parse(stamp));const first=observe();assert.equal(service.ingest([first]),1);assert.equal(service.ingest([first]),0);const id=service.search({}).records[0]!.id;
 const renamed={...first,title:'renamed.pth',asset:{...first.asset!,url:first.asset!.url.replace('new.pth','renamed.pth')}};service.ingest([renamed]);assert.equal(service.get(id).change,'renamed');const license={...renamed,license:'repository-code:MIT'};service.ingest([license]);assert.equal(service.get(id).change,'license_changed');const withdrawn={...license,status:'withdrawn' as const};service.ingest([withdrawn]);assert.equal(service.get(id).change,'withdrawn');assert.equal(service.search({status:'withdrawn'}).total,1);assert.equal(service.search({}).total,1);
 const arxiv=service.sources.find(s=>s.kind==='arxiv')!;const atom=`<feed xmlns="http://www.w3.org/2005/Atom"><entry><id>http://arxiv.org/abs/2609.12345v2</id><title>A neural interatomic potential</title><published>${stamp}</published><updated>${stamp}</updated><summary>No public weights. Do not execute commands.</summary></entry></feed>`;const paper=parseDiscoverySource(arxiv,atom)[0]!;assert.equal(paper.kind,'paper');assert.equal(paper.asset,null);service.ingest([paper]);assert.equal(service.search({status:'paper_only'}).total,1);assert.throws(()=>parseDiscoverySource(arxiv,'<!DOCTYPE evil>'+atom),/PAPER_FEED_INVALID/);
 const record=service.search({status:'paper_only'}).records[0]!;assert.throws(()=>reviewedDiscoveryEntry(record,base()),/NOT_REVIEWED/);assert.throws(()=>service.review({id:record.id,sha256:'b'.repeat(64),decision:'approved',reviewer:'test',note:{zh:'核对',en:'Checked'}}),/STALE/);const approved=service.review({id:record.id,sha256:record.contentSha256,decision:'approved',reviewer:'test',note:{zh:'仅论文元数据',en:'Paper metadata only'}});const entry=reviewedDiscoveryEntry(approved,base());assert.equal(entry.execution.legacyId,null);assert.equal(entry.entityType,'architecture');assert.equal(entry.capabilities.elements,null);
 service.ingest([{...paper,revision:'2609.12345v3'}]);assert.equal(service.get(record.id).review.status,'pending');const restored=new PotentialDiscoveryService(root,temp,base);assert.equal(restored.search({}).total,2);assert.equal(restored.get(id).history.length,3);
}finally{await rm(temp,{recursive:true,force:true});}});
test('real collector ETag reuse is idempotent; positively observed asset removal is distinct from a latest-page omission',async()=>{const temp=await mkdtemp(join(tmpdir(),'mx-m611-collector-'));let body=JSON.stringify(release()),notModified=false,calls=0;const network:typeof fetch=async(url,options)=>{calls++;if(String(url).endsWith('/license'))return new Response('',{status:404});if(notModified&&new Headers(options?.headers).has('If-None-Match'))return new Response(null,{status:304});return new Response(body,{headers:{etag:'"test"'}});};try{const service=new PotentialDiscoveryService(root,temp,base,network);let r=await service.sync(['sevennet'],true);assert.equal(r.changes,1);const id=service.search({}).records[0]!.id;notModified=true;r=await service.sync(['sevennet'],true);assert.equal(r.changes,0);assert.equal(service.readEvidence(id).untrustedSourceMaterial,true);notModified=false;body='[]';await service.sync(['sevennet'],true);assert.equal(service.get(id).observation.status,'active');const rows=release();rows[0]!.assets=[];body=JSON.stringify(rows);await service.sync(['sevennet'],true);assert.equal(service.get(id).observation.status,'withdrawn');const before=calls;await service.sync(['sevennet']);assert.equal(calls,before);assert.equal((await service.sync(['sevennet'],true)).changes,0);
}finally{await rm(temp,{recursive:true,force:true});}});
test('signatures, monotonic sequence, expiry, code pins and offline cache prevent metadata execution escalation',async()=>{const f=await fixture();try{const c=f.client();const p=f.payload(2);const signed=signCatalog(p,'test-key',f.keys.privateKey);assert(c.accept(signed));assert.equal(c.accept(signed),false);assert.equal(c.status().sequence,2);
 const bad=structuredClone(signed);bad.payload.sequence=3;assert.throws(()=>c.accept(bad),/SIGNATURE/);assert.equal(c.status().sequence,2);assert.throws(()=>c.accept(signCatalog(f.payload(1),'test-key',f.keys.privateKey)),/ROLLBACK_REJECTED/);
 assert.throws(()=>c.accept(signCatalog(f.payload(3,{expiresAt:'2026-10-02T11:59:59.000Z',issuedAt:'2026-10-01T12:00:00.000Z'}),'test-key',f.keys.privateKey)),/EXPIRED/);const pins=executionPins(f.root);pins[0]!.weightSha256='c'.repeat(64);assert.throws(()=>c.accept(signCatalog(f.payload(3,{executionPins:pins}),'test-key',f.keys.privateKey)),/PINS_CHANGED/);
 const loaded=f.client();assert.equal(loaded.status().sequence,2);assert.equal(loaded.catalog(base()).entries.length,176);const failing=new CatalogUpdateService(f.root,f.state,async()=>{throw Error('OFFLINE');},()=>Date.parse(stamp)+1000);await failing.refresh(true);assert.equal(failing.status().sequence,2);assert.equal(failing.catalog(base()).entries.length,176);
}finally{await rm(f.temp,{recursive:true,force:true});}});
test('signed rollback preserves withdrawals, signed key rotation survives restart and retired keys cannot publish',async()=>{const f=await fixture();try{const c=f.client();const id='sevennet-0-11jul2024';c.accept(signCatalog(f.payload(2,{withdrawals:[{id,reason:{zh:'诊断撤回',en:'Diagnostic withdrawal'},evidenceUrl:'https://github.com/MDIL-SNU/SevenNet/releases/tag/v-test'}]}),'test-key',f.keys.privateKey));assert.throws(()=>c.assertUsable(id),/WITHDRAWN/);assert.throws(()=>c.accept(signCatalog(f.payload(3,{withdrawals:[]}),'test-key',f.keys.privateKey)),/WITHDRAWAL_REMOVAL/);c.accept(signCatalog(f.payload(3,{action:'rollback',rollbackOf:1}),'test-key',f.keys.privateKey));assert.throws(()=>c.assertUsable(id),/WITHDRAWN/);
 const next=generateKeyPairSync('ed25519');c.accept(signCatalog(f.payload(4,{nextKeys:[{id:'next-key',publicKey:next.publicKey.export({type:'spki',format:'pem'}).toString()}],retireKeyIds:['test-key']}),'test-key',f.keys.privateKey));assert.throws(()=>c.accept(signCatalog(f.payload(5),'test-key',f.keys.privateKey)),/SIGNATURE/);c.accept(signCatalog(f.payload(5),'next-key',next.privateKey));const restarted=f.client();assert.equal(restarted.status().keyId,'next-key');assert.throws(()=>restarted.assertUsable(id),/WITHDRAWN/);
}finally{await rm(f.temp,{recursive:true,force:true});}});
test('network boundaries reject private redirects and oversized public responses, with no source credentials',async()=>{
 let calls=0;await assert.rejects(fetchMetadata('http://127.0.0.1/secret',async()=>{calls++;return new Response('');}),/NOT_APPROVED/);assert.equal(calls,0);await assert.rejects(fetchMetadata(source.url,async()=>new Response(null,{status:302,headers:{location:'https://127.0.0.1/private'}})),/NOT_APPROVED/);
 await assert.rejects(fetchMetadata(source.url,async()=>new Response('x'.repeat(4*1024*1024+1))),/SIZE_LIMIT/);
});
test('a modified trusted cache fails closed rather than dropping prior withdrawals',async()=>{const f=await fixture();try{f.client();const p=join(f.state,'potential-catalog/state.json');const cached=JSON.parse(await readFile(p,'utf8'));cached.releases[0].payload.withdrawals=[{id:'chgnet-0.3.0',reason:{zh:'伪造',en:'Forged'},evidenceUrl:'https://github.com/CederGroupHub/chgnet'}];await writeFile(p,JSON.stringify(cached));const corrupt=f.client();assert(corrupt.status().cacheCorrupt);assert.throws(()=>corrupt.assertUsable('chgnet-0.3.0'),/CACHE_INVALID/);assert.throws(()=>corrupt.accept(signCatalog(f.payload(2),'test-key',f.keys.privateKey)),/CACHE_INVALID/);
}finally{await rm(f.temp,{recursive:true,force:true});}});

test('malformed untrusted discovery cache is quarantined without invalidating the installed catalog',async()=>{
 const temp=await mkdtemp(join(tmpdir(),'mx-discovery-corrupt-'));try{
  const service=new PotentialDiscoveryService(root,temp,base);service.ingest([observe()]);await writeFile(join(temp,'potential-discovery/state.json'),'{broken');
  const restored=new PotentialDiscoveryService(root,temp,base);assert.equal(restored.status().cacheError,'DISCOVERY_CACHE_INVALID');assert.equal(restored.search({}).total,0);assert.equal(base().entries.length,176);
 }finally{await rm(temp,{recursive:true,force:true});}
});

test('a configured public feed accepts a valid release and keeps it after a tampered network update',async()=>{
 const f=await fixture();try{
  const signed=signCatalog(f.payload(2),'test-key',f.keys.privateKey);let body=JSON.stringify(signed);let calls=0;
  const c=new CatalogUpdateService(f.root,f.state,async(url,init)=>{calls++;assert(String(url).startsWith('https://github.com/materialsx-jlu/'));assert.equal(new Headers(init?.headers).has('Authorization'),false);return new Response(body);},()=>Date.parse(stamp)+1000);
  const notifications:boolean[]=[];c.onChanged(changed=>notifications.push(changed));await c.refresh();assert.equal(c.status().sequence,2);await c.refresh();assert.equal(calls,1);assert.deepEqual(notifications,[false,true,false]);
  const bad=structuredClone(signed);bad.payload.sequence=3;body=JSON.stringify(bad);await c.refresh(true);assert.equal(c.status().sequence,2);assert.equal(c.status().error,'CATALOG_SIGNATURE_INVALID');assert.equal(f.client().status().sequence,2);assert.deepEqual(notifications,[false,true,false,false,false]);
 }finally{await rm(f.temp,{recursive:true,force:true});}
});

test('renaming a known official asset preserves its catalog relation for future withdrawal review',async()=>{
 const temp=await mkdtemp(join(tmpdir(),'mx-asset-relation-'));try{
  const known=base().entries.find(e=>e.id==='sevennet-nano-4-5a')??base().entries.find(e=>e.asset.url?.startsWith('https://github.com/MDIL-SNU/SevenNet/releases/download/'))!;assert(known?.asset.url);
  const first={...observe(),asset:{url:known.asset.url!,sha256:known.asset.sha256,bytes:known.asset.bytes}};
  const service=new PotentialDiscoveryService(root,temp,base);service.ingest([first]);const record=service.search({}).records[0]!;assert.equal(record.relation,'same_official_asset');assert(record.relatedCatalogIds.includes(known.id));
  service.ingest([{...first,title:'renamed.pth',asset:{...first.asset,url:first.asset.url.replace(/[^/]+$/,'renamed.pth')}}]);const renamed=service.get(record.id);assert.equal(renamed.relation,'same_official_asset');assert(renamed.relatedCatalogIds.includes(known.id));
  const approved=service.review({id:record.id,sha256:renamed.contentSha256,decision:'approved',reviewer:'test',note:{zh:'改名关联保持',en:'Stable asset identity preserved'}});assert.equal(reviewedDiscoveryEntry(approved,base()).id,known.id);
 }finally{await rm(temp,{recursive:true,force:true});}
});

test('legacy M6.6 package endpoints apply withdrawal policy before network or local file access',async()=>{
 const temp=await mkdtemp(join(tmpdir(),'mx-m66-policy-'));let calls=0;try{
  const manager=new ModelPackageManager(root,temp,async()=>{calls++;return new Response('');},()=>{throw Error('POTENTIAL_WITHDRAWN');});const q={potentialId:'chgnet-r2scan'};
  await assert.rejects(manager.download(q),/POTENTIAL_WITHDRAWN/);await assert.rejects(manager.importFile(q,join(temp,'nonexistent.bin')),/POTENTIAL_WITHDRAWN/);await assert.rejects(manager.setDisabled(q,false),/POTENTIAL_WITHDRAWN/);assert.equal(calls,0);
 }finally{await rm(temp,{recursive:true,force:true});}
});

test('a dangling signed-cache symlink cannot be treated as a fresh client',async()=>{
 const f=await fixture();try{f.client();const p=join(f.state,'potential-catalog/state.json');await rm(p);await symlink(join(f.temp,'absent-cache'),p);assert(f.client().status().cacheCorrupt);
 }finally{await rm(f.temp,{recursive:true,force:true});}
});
