import {hubEntrySchema,type HubEntry,type PotentialCatalog} from '../../contracts/src/potential-hub.js';
import type {DiscoveryRecord} from '../../contracts/src/potential-discovery.js';
/** Creates metadata only. Code families still need an application release and actual adapter checks. */
export function reviewedDiscoveryEntry(r:DiscoveryRecord,catalog:PotentialCatalog):HubEntry{
 if(r.review.status!=='approved'||r.review.sha256!==r.contentSha256||r.observation.status==='withdrawn')throw Error('DISCOVERY_NOT_REVIEWED');
 const o=r.observation,sourceId='discovered-source';const existing=r.relation==='same_official_asset'?catalog.entries.find(e=>r.relatedCatalogIds.includes(e.id)):null;
 if(existing?.execution.legacyId)throw Error('CATALOG_EXECUTABLE_OVERRIDE_REJECTED');
 const sources=[{id:sourceId,url:o.url,revision:o.revision,sha256:o.snapshotSha256,status:'documented' as const,note:{zh:'官方元数据快照已核对；权重身份声明尚不构成加载或精度验收。',en:'Reviewed official metadata snapshot; asset identity is not a loading or accuracy validation.'}}];
 const common={id:existing?.id??r.id,name:existing?.name??o.title,aliases:existing?.aliases??[],entityType:o.kind==='checkpoint'?'checkpoint' as const:o.kind==='paper'?'architecture' as const:o.kind==='code'?'training_framework' as const:o.kind==='classical_forcefield'?'classical_forcefield' as const:'repository' as const,family:existing?.family??r.sourceIds[0]!,category:existing?.category??(o.kind==='checkpoint'?'materials' as const:'resources' as const),description:r.description,examples:r.examples,limitations:[{zh:'本条目仅发布已审核元数据，能力、依赖、许可与科学域仍需专门验收，不可执行。',en:'Reviewed metadata only; capabilities, dependencies, licenses and scientific domains still need dedicated validation. Not executable.'}],sources,fieldEvidence:o.asset?{asset:[sourceId]}:{},capabilities:{energy:'unknown' as const,forces:'unknown' as const,stress:'unknown' as const,forceRelation:'unknown' as const,elements:null,periodicity:[],domains:[],heads:[],headPolicy:'unknown' as const,charge:'unknown' as const,spin:{input:'unknown' as const,semantics:'unknown' as const},electricField:'unknown' as const,particleSemantics:'unknown' as const,cutoffAngstrom:null,longRange:[],compositionRole:'unknown' as const,requiredComponents:[],functional:null,dataset:null,units:{energy:null,forces:null,stress:null},temperatureK:null,pressureGPa:null,tasks:[]},asset:o.asset?{...o.asset,revision:o.revision}:{url:null,revision:null,sha256:null,bytes:null},licenses:{code:null,weights:null,trainingData:null,redistribution:'review-required' as const},execution:{legacyId:null,adapter:null,profileId:null,diskEstimateMiB:null,memoryEstimateMiB:null,platforms:[],state:o.kind==='checkpoint'?'awaiting_adapter' as const:'not_a_potential' as const,blockers:['METADATA_ONLY','ADAPTER_AND_LICENSE_REVIEW_REQUIRED'],runtimeEvidenceIds:[],taskEvidenceIds:[]},maintenance:'unknown' as const,access:o.access,reviewedAt:r.lastChanged,nextStage:'M6.11' as const,relatedIds:r.relatedCatalogIds};
 return hubEntrySchema.parse(common);
}
