import test from 'node:test';import assert from 'node:assert/strict';
import {generateKeyPairSync} from 'node:crypto';import {mkdtemp,cp,mkdir,writeFile,readFile,rm,symlink,readdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {CatalogUpdateService,executionPins,signCatalog} from './catalog-updates.js';import {PotentialPackageManager} from './package-manager.js';import {PotentialDistributionService} from './potential-distribution.js';import {hash,canonical} from './discovery-io.js';import {catalogReleasePayloadSchema} from '../../contracts/src/potential-discovery.js';
const root=process.cwd(),stamp='2026-10-02T12:00:00.000Z',later='2026-11-02T12:00:00.000Z';
async function fixture(){const temp=await mkdtemp(join(tmpdir(),'mx-m612-')),r=join(temp,'root'),state=join(temp,'state');await mkdir(r);await mkdir(state);await cp(join(root,'vendor/nep-cpu'),join(r,'vendor/nep-cpu'),{recursive:true});await mkdir(join(r,'atomistic'),{recursive:true});await cp(join(root,'atomistic/nep_runner.cpp'),join(r,'atomistic/nep_runner.cpp'));for(const f of ['d3_runner.cpp','composed.py'])await cp(join(root,'atomistic',f),join(r,'atomistic',f));await cp(join(root,'models'),join(r,'models'),{recursive:true});await cp(join(root,'atomistic/environments'),join(r,'atomistic/environments'),{recursive:true,filter:p=>!p.includes('.venv')});await cp(join(root,'docs/m6/licenses'),join(r,'docs/m6/licenses'),{recursive:true});const keys=generateKeyPairSync('ed25519');await writeFile(join(r,'models/potentials/discovery-trust.json'),JSON.stringify({version:'m6.11-v1',updateUrl:null,keys:[{id:'old-key',publicKey:keys.publicKey.export({type:'spki',format:'pem'}).toString()}]}));const payload=(sequence:number,patch:Record<string,unknown>={})=>catalogReleasePayloadSchema.parse({version:'m6.11-v1',sequence,issuedAt:stamp,expiresAt:later,action:'publish',rollbackOf:null,entries:[],withdrawals:[],reviews:[],executionPins:executionPins(r),nextKeys:[],retireKeyIds:[],...patch});await writeFile(join(r,'models/potentials/catalog-release.json'),JSON.stringify(signCatalog(payload(1),'old-key',keys.privateKey)));return {temp,root:r,state,keys,payload,client:(s=state)=>new CatalogUpdateService(r,s,fetch,()=>Date.parse(stamp)+1000)};}

test('offline catalog bundles catch up across retired signing keys, accept expired intermediate proofs, and restart',async()=>{const f=await fixture();try{
 const publisher=f.client(),next=generateKeyPairSync('ed25519'),withdrawals=[{id:'sevennet-0-11jul2024',reason:{zh:'撤回测试',en:'Withdrawal test'},evidenceUrl:'https://github.com/MDIL-SNU/SevenNet'}];
 publisher.accept(signCatalog(f.payload(2,{withdrawals,nextKeys:[{id:'new-key',publicKey:next.publicKey.export({type:'spki',format:'pem'}).toString()}],retireKeyIds:['old-key']}),'old-key',f.keys.privateKey));publisher.accept(signCatalog(f.payload(3,{withdrawals}),'new-key',next.privateKey));const path=join(f.temp,'fresh'),client=f.client(path);assert.throws(()=>client.accept(publisher.release(3)),/SIGNATURE/);assert(client.accept(publisher.bundle()));assert.equal(client.accept(publisher.bundle()),false);assert.equal(f.client(path).status().keyId,'new-key');assert.throws(()=>f.client(path).assertUsable('sevennet-0-11jul2024'),/WITHDRAWN/);
 const old=signCatalog(f.payload(2,{issuedAt:'2026-09-01T00:00:00.000Z',expiresAt:'2026-09-02T00:00:00.000Z',nextKeys:[{id:'new-key',publicKey:next.publicKey.export({type:'spki',format:'pem'}).toString()}],retireKeyIds:['old-key']}),'old-key',f.keys.privateKey);const bundle={version:'m6.12-v1',baselineSha256:publisher.bundle().baselineSha256,releases:[publisher.release(1),old,signCatalog(f.payload(3),'new-key',next.privateKey)]};assert(f.client(join(f.temp,'expired-proof')).accept(bundle));
 }finally{await rm(f.temp,{recursive:true,force:true});}});
test('bad bundle is atomic and cannot remove, replace or rewind trusted history',async()=>{const f=await fixture();try{const c=f.client();c.accept(signCatalog(f.payload(2),'old-key',f.keys.privateKey));const before=await readFile(join(f.state,'potential-catalog/state.json'),'utf8');const good={...c.bundle(),releases:[...c.bundle().releases,signCatalog(f.payload(3),'old-key',f.keys.privateKey)]};const bad=structuredClone(good);bad.releases.at(-1)!.signature='A'.repeat(86)+'==';assert.throws(()=>c.accept(bad),/SIGNATURE/);assert.equal(c.status().sequence,2);assert.equal(await readFile(join(f.state,'potential-catalog/state.json'),'utf8'),before);
 assert.throws(()=>c.accept({...good,releases:good.releases.filter(r=>r.payload.sequence!==2)}),/HISTORY_REPLACED/);assert.throws(()=>c.accept({...good,baselineSha256:'f'.repeat(64)}),/BASELINE/);assert(c.accept(good));assert.throws(()=>c.accept({...good,releases:good.releases.slice(0,2)}),/ROLLBACK/);
 }finally{await rm(f.temp,{recursive:true,force:true});}});

async function tinyPackages(){const f=await fixture();const m=JSON.parse(await readFile(join(f.root,'models/potentials/packages-m68.json'),'utf8')),registry=JSON.parse(await readFile(join(f.root,'models/potentials/registry.json'),'utf8'));for(const [i,e] of m.entries.entries()){const data=Buffer.from('reviewed-weight-'+i);e.bytes=data.length;e.sha256=hash(data);registry.potentials.find((p:{id:string})=>p.id===e.potentialId).weights.sha256=e.sha256;const dir=join(f.root,'model-packages',e.potentialId,e.sha256);await mkdir(dir,{recursive:true});await writeFile(join(dir,'checkpoint.bin'),data);}await writeFile(join(f.root,'models/potentials/packages-m68.json'),JSON.stringify(m));await writeFile(join(f.root,'models/potentials/registry.json'),JSON.stringify(registry));return f;}
test('offline collections preserve notices and identity; corrupt final asset never mounts an earlier asset',async()=>{const f=await tinyPackages();try{const manager=new PotentialPackageManager(f.root,f.state);const service=new PotentialDistributionService(f.root,f.state,manager);const ids=manager.entries().filter(e=>e.family!=='sevennet').slice(0,2).map(e=>e.potentialId);const exported=await service.exportCollection(f.temp,ids);const manifest=JSON.parse(await readFile(join(exported.path,'collection.json'),'utf8'));assert.equal(manifest.entries.length,2);const last=join(exported.path,ids[1]!,'checkpoint.bin'),bytes=await readFile(last);await writeFile(last,'corrupt');await assert.rejects(service.importCollection(exported.path),/ARTIFACT|SIZE/);assert.equal((await service.inventory()).items.filter(i=>i.kind==='package').length,0);await writeFile(last,bytes);assert.deepEqual((await service.importCollection(exported.path)).imported,ids);const status=await manager.status();for(const id of ids)assert(status.find(s=>s.potentialId===id)?.cacheOwned);await rm(last);await symlink(join(f.root,'models/potentials/registry.json'),last);await assert.rejects(service.importCollection(exported.path),/SYMLINK/);
 }finally{await rm(f.temp,{recursive:true,force:true});}});
test('offline collections reject version/lock drift, traversal and undeclared executable files',async()=>{const f=await tinyPackages();try{const manager=new PotentialPackageManager(f.root,f.state),service=new PotentialDistributionService(f.root,f.state,manager);const id=manager.entries()[0]!.potentialId;const exported=await service.exportCollection(f.temp,[id]),path=join(exported.path,'collection.json'),original=await readFile(path,'utf8'),manifest=JSON.parse(original);manifest.entries[0].dependencyLockSha256='a'.repeat(64);await writeFile(path,JSON.stringify(manifest));await assert.rejects(service.importCollection(exported.path),/INCOMPATIBLE/);manifest.entries[0].potentialId='../outside';await writeFile(path,JSON.stringify(manifest));await assert.rejects(service.importCollection(exported.path));await writeFile(path,original);await writeFile(join(exported.path,id,'run.py'),'malicious');await assert.rejects(service.importCollection(exported.path),/UNDECLARED/);assert.equal((await service.inventory()).items.filter(i=>i.kind==='package').length,0);
 }finally{await rm(f.temp,{recursive:true,force:true});}});
test('storage preview detects stale state, blocks in-use removal, preserves bundled resources, evidence and project results',async()=>{const f=await tinyPackages();let busy=false;try{const manager=new PotentialPackageManager(f.root,f.state,()=>busy),service=new PotentialDistributionService(f.root,f.state,manager,()=>busy);const id=manager.entries()[0]!.potentialId;await manager.importFile(id,manager.weight(id));await mkdir(join(f.state,'potential-discovery'),{recursive:true});await writeFile(join(f.state,'potential-discovery/state.invalid-123.json'),'broken');await writeFile(join(f.state,'potential-discovery/state.json'),'important audit evidence');await mkdir(join(f.state,'materials-output'),{recursive:true});await writeFile(join(f.state,'materials-output/result.json'),'real result');const inventory=await service.inventory(),selection={ids:['package:'+id,'quarantine:state.invalid-123.json'],inventorySha256:inventory.inventorySha256};busy=true;await assert.rejects(service.cleanup(selection),/STALE/);busy=false;await writeFile(join(f.state,'potential-discovery/state.invalid-123.json'),'changed');await assert.rejects(service.cleanup(selection),/STALE/);const fresh=await service.inventory();await assert.rejects(service.cleanup({ids:['protected:catalog'],inventorySha256:fresh.inventorySha256}));assert.equal((await service.cleanup({...selection,inventorySha256:fresh.inventorySha256})).removed.length,2);assert.equal(await readFile(join(f.state,'materials-output/result.json'),'utf8'),'real result');assert.equal(await readFile(join(f.state,'potential-discovery/state.json'),'utf8'),'important audit evidence');assert.equal((await manager.status()).find(s=>s.potentialId===id)?.state,'installed');assert(!(await manager.status()).find(s=>s.potentialId===id)?.cacheOwned);
 }finally{await rm(f.temp,{recursive:true,force:true});}});
test('storage scope fails closed on symlinked owned package directories',async()=>{const f=await tinyPackages();try{await mkdir(join(f.state,'scientific-packages'));await symlink(f.root,join(f.state,'scientific-packages',new PotentialPackageManager(f.root,f.state).entries()[0]!.potentialId));await assert.rejects(new PotentialDistributionService(f.root,f.state,new PotentialPackageManager(f.root,f.state)).inventory(),/SYMLINK/);}finally{await rm(f.temp,{recursive:true,force:true});}});

test('read-only bundled symlinks are counted without following them; unknown user cache remains protected',async()=>{const f=await tinyPackages();try{await mkdir(join(f.root,'python-runtime'));await symlink(f.root,join(f.root,'python-runtime','readonly-link'));await mkdir(join(f.state,'scientific-packages/retained-legacy'),{recursive:true});await writeFile(join(f.state,'scientific-packages/retained-legacy','original.bin'),'preserve cross-version cache');const service=new PotentialDistributionService(f.root,f.state,new PotentialPackageManager(f.root,f.state)),inventory=await service.inventory();assert(inventory.items.some(i=>i.id==='protected:skill-python'&&i.bytes>0));assert(inventory.items.some(i=>i.id==='protected:other-scientific-cache'&&!i.removable&&i.bytes>0));assert.equal(await readFile(join(f.state,'scientific-packages/retained-legacy/original.bin'),'utf8'),'preserve cross-version cache');}finally{await rm(f.temp,{recursive:true,force:true});}});
