import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';import {effectiveRegistry} from './model-packages.js';import {molecularExpansion} from './molecular-expansion.js';import {assessPotentials,digest} from './selection.js';import {mountReviewedCatalog} from './mounted-catalog.js';import {buildPotentialCatalog} from './potential-hub.js';import {parsePotentialRegistry} from './registry.js';import {executionPins,CatalogUpdateService} from './catalog-updates.js';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
const root=process.cwd(),m=molecularExpansion(root)!,registry=effectiveRegistry(root),cap=[{potentialId:m.entry.potentialId,sha256:m.entry.sha256,dependencyLockSha256:m.entry.dependencyLockSha256,elements:m.entry.elements,loadedMemoryMiB:900,device:'cpu' as const,adapter:{}}];
const base=JSON.parse(readFileSync('samples/atomistic/water.structure.json','utf8'));const s={...base,charge:0,spinMultiplicity:1,cell:[[20,0,0],[0,20,0],[0,0,20]]};const request={projectId:'p',structureId:s.id,domain:'molecules' as const,mode:'exploratory' as const,task:'singlepoint' as const};
const assess=(structure=s,patch={})=>assessPotentials(registry,digest(JSON.stringify(registry)),structure,{...request,...patch},cap);
test('molecular selection gates explicit electronic state, parity, elements, boundaries, long range and tasks',()=>{assert.deepEqual(assess().selection.candidates.map(c=>c.potentialId),['ani-2x-ensemble']);for(const [structure,patch,reason] of [[{...s,charge:null},{},'ELECTRONIC_STATE_REQUIRED'],[{...s,charge:1},{},'NEUTRAL_SINGLET_REQUIRED'],[{...s,spinMultiplicity:3},{},'NEUTRAL_SINGLET_REQUIRED'],[{...s,pbc:[true,true,true]},{},'MOLECULE_REQUIRES_ISOLATED_BOUNDARY'],[s,{interaction:'long-range-required'},'LONG_RANGE_PHYSICS_UNAVAILABLE'],[s,{mode:'production'},'DOMAIN_NOT_VALIDATED'],[s,{task:'md'},'MOUNTED_MD_NOT_VERIFIED'],[{...s,atoms:[{...s.atoms[0],element:'H'}]},{},'ELECTRON_COUNT_PARITY_MISMATCH'],[{...s,atoms:[{...s.atoms[0],element:'Si'}]},{},'ELEMENT_NOT_SUPPORTED'],[{...s,cell:null},{task:'relaxation'},'EXPLICIT_DISPLAY_BOX_REQUIRED']] as const){const a=assess(structure as typeof s,patch);assert.equal(a.selection.candidates.length,0);assert(a.selection.exclusions.find(c=>c.potentialId===m.entry.potentialId)?.reasonCodes.includes(reason),reason);}});
test('reviewed ANI is visible in bilingual catalog without upgrading metadata candidates or breaking the signed baseline',()=>{const base=parsePotentialRegistry(JSON.parse(readFileSync('models/potentials/registry.json','utf8'))),catalog=mountReviewedCatalog(root,buildPotentialCatalog(base,JSON.parse(readFileSync('models/potentials/catalog-m67.json','utf8'))));const e=catalog.entries.find(e=>e.id===m.entry.potentialId)!;assert(e.examples.length===2&&e.description.zh&&e.description.en);assert.equal(e.capabilities.stress,'no');assert.equal(e.execution.legacyId,m.entry.potentialId);assert.equal(executionPins(root).length,6);const state=mkdtempSync(join(tmpdir(),'mx-m613-catalog-'));try{const updates=new CatalogUpdateService(root,state);assert.equal(updates.status().cacheCorrupt,false);assert(updates.catalog(catalog).entries.some(e=>e.id===m.entry.potentialId));assert.throws(()=>updates.accept({}),/INVALID/);}finally{rmSync(state,{recursive:true,force:true});}});

test('molecular download admits the official observed HF CDN and rejects unrelated redirects',async()=>{const {PotentialPackageManager}=await import('./package-manager.js');const temp=mkdtempSync(join(tmpdir(),'mx-m613-redirect-'));try{for(const [host,expected] of [['us.aws.cdn.hf.co','TEST_NETWORK_STOP'],['unreviewed.example','PACKAGE_REDIRECT_NOT_APPROVED']]){let calls=0;const manager=new PotentialPackageManager(root,temp,()=>false,(async()=>{if(calls++===0)return new Response(null,{status:302,headers:{location:'https://'+host+'/checkpoint'}});throw Error('TEST_NETWORK_STOP');}) as typeof fetch);await assert.rejects(manager.download(m.entry.potentialId),new RegExp(expected!));assert.equal(calls,host==='us.aws.cdn.hf.co'?2:1);}}finally{rmSync(temp,{recursive:true,force:true});}});
