import {currentPotentialCatalogSchema as potentialCatalogSchema} from '../../contracts/src/potential-physics.js';
import {physicsExpansion} from './physics-expansion.js';
import {nativeExpansion} from './native-expansion.js';
import {molecularExpansion} from './molecular-expansion.js';
import {type PotentialCatalog} from '../../contracts/src/potential-hub.js';
import {approvedPackages} from './approved-packages.js';
import {adapterExpansion} from './adapter-expansion.js';
/** Current audited overlays leave the historical catalog and M6.0 registry files untouched. */
export function mountReviewedCatalog(root:string,input:PotentialCatalog){const c=structuredClone(input);const expansion=adapterExpansion(root);
 const molecule=molecularExpansion(root);
 if(molecule){const p=molecule.potential,entry=structuredClone(c.entries.find(e=>e.id==='hub-ani-2x')!);entry.id=p.id;entry.name=p.name;entry.entityType='checkpoint';entry.aliases.push('ANI2x ensemble');entry.description=p.description;entry.examples=p.examples;entry.limitations=p.limitations;entry.asset={url:p.weights.url,revision:p.weights.revision,sha256:p.weights.sha256,bytes:p.weights.bytes};entry.capabilities={...entry.capabilities,energy:'yes',forces:'yes',stress:'no',forceRelation:'energy_gradient',elements:p.declared.elements,periodicity:['molecule'],domains:['molecules'],headPolicy:'single',heads:[],charge:'unsupported',spin:{input:'unsupported',semantics:'multiplicity'},longRange:[],tasks:['singlepoint','relaxation'],units:{energy:'eV',forces:'eV/angstrom',stress:'unknown'}};entry.sources=p.evidence.concat([p.source]).map(e=>({id:e.id,url:e.url,revision:e.revision,sha256:e.sha256,status:'documented' as const,note:{zh:'M6.13 已审核分子接口来源。',en:'M6.13 reviewed molecular adapter source.'}}));for(const field of Object.keys(entry.fieldEvidence))entry.fieldEvidence[field]=entry.sources.map(s=>s.id);for(const k of Object.keys(entry.capabilities))entry.fieldEvidence['capabilities.'+k]=entry.sources.map(s=>s.id);entry.fieldEvidence.asset=entry.sources.map(s=>s.id);entry.execution={...entry.execution,legacyId:p.id,adapter:p.environment.adapter,profileId:p.environment.profileId,platforms:p.environment.matrix,runtimeEvidenceIds:p.runtimeEvidenceIds,taskEvidenceIds:[],state:'legacy_candidate',blockers:['ACTUAL_PHASE_B_CHECK_REQUIRED','DOMAIN_NOT_VALIDATED']};entry.relatedIds=['hub-ani-2x'];entry.nextStage='M6.13';entry.licenses={code:'MIT',weights:'MIT',trainingData:'unknown',redistribution:'permitted-with-notices'};c.entries.push(entry);c.coverage.push({name:p.name,entryId:p.id,reason:{zh:'M6.13 审核的八成员运行配置。',en:'M6.13 reviewed eight-member execution configuration.'}});}
 const native=nativeExpansion(root);if(native){const p=native.potential,entry=structuredClone(c.entries.find(e=>e.id==='mace-mp-0b2-small')!);entry.id=p.id;entry.name=p.name;entry.family='NEP';entry.aliases=['Si NEP CPU','硅专用势','Si_2022_NEP4_3body'];entry.description=p.description;entry.examples=p.examples;entry.limitations=p.limitations;entry.asset={url:p.weights.url,revision:p.weights.revision,sha256:p.weights.sha256,bytes:p.weights.bytes};entry.relatedIds=['hub-nep'];entry.sources=[p.source,...p.evidence].map(s=>({id:s.id,url:s.url,revision:s.revision,sha256:s.sha256,status:'documented' as const,note:{zh:'固定原生引擎及权重仓库的独立许可证据。',en:'Separate pinned license evidence for the native engine and checkpoint repository.'}}));for(const k of Object.keys(entry.fieldEvidence))entry.fieldEvidence[k]=entry.sources.map(s=>s.id);entry.capabilities={...entry.capabilities,elements:['Si'],functional:p.energyReference.functional,dataset:p.energyReference.dataset,cutoffAngstrom:5,particleSemantics:'all_atom',compositionRole:'standalone',longRange:[],tasks:['singlepoint','relaxation']};entry.execution={...entry.execution,legacyId:p.id,adapter:'nep-cpu',profileId:p.environment.profileId,platforms:p.environment.matrix,state:'legacy_candidate',runtimeEvidenceIds:p.runtimeEvidenceIds,taskEvidenceIds:[],blockers:['ACTUAL_PHASE_B_CHECK_REQUIRED','DOMAIN_NOT_VALIDATED']};entry.licenses={code:'GPL-3.0-or-later',weights:'GPL-3.0-only',trainingData:'unknown',redistribution:'permitted-with-notices'};entry.nextStage='M6.14';c.entries.push(entry);c.coverage.push({name:p.name,entryId:p.id,reason:{zh:'M6.14 已审核的具体硅 NEP4 参数文件。',en:'M6.14 reviewed silicon NEP4 parameter file.'}});}
 const physics=physicsExpansion(root);if(physics){const p=physics.potential,e=structuredClone(c.entries.find(e=>e.id==='mace-mp-0b3-medium')!);e.id=p.id;e.name=p.name;e.category='physics';e.entityType='workflow';e.aliases=['MACE D3 BJ','MACE+D3','组合势','色散修正'];e.description=p.description;e.examples=p.examples;e.limitations=p.limitations;e.asset={url:p.weights.url,revision:p.weights.revision,sha256:p.weights.sha256,bytes:p.weights.bytes};e.relatedIds=[physics.profile.baseline.id];e.sources=[p.source,...p.evidence].map(s=>({id:s.id,url:s.url,revision:s.revision,sha256:s.sha256,status:'documented' as const,note:{zh:'固定基线及原生D3来源；组合配置并非新训练权重。',en:'Fixed baseline/native D3 provenance; composition is not a new trained checkpoint.'}}));for(const k of Object.keys(e.fieldEvidence))e.fieldEvidence[k]=e.sources.map(s=>s.id);e.capabilities={...e.capabilities,elements:['Si'],functional:p.energyReference.functional,dataset:p.energyReference.dataset,cutoffAngstrom:10,compositionRole:'composite',requiredComponents:[physics.profile.baseline.id,'NEP_CPU-PBE-D3(BJ)-two-body'],longRange:['dispersion'],tasks:['singlepoint','relaxation']};e.licenses={code:p.licenses.code.expression,weights:'MIT',trainingData:'unknown',redistribution:'permitted-with-notices'};e.execution={...e.execution,legacyId:p.id,adapter:'mace-ase',profileId:p.environment.profileId,platforms:p.environment.matrix,runtimeEvidenceIds:p.runtimeEvidenceIds,taskEvidenceIds:[],state:'legacy_candidate',blockers:['ACTUAL_PHASE_B_CHECK_REQUIRED','DOMAIN_NOT_VALIDATED']};e.nextStage='M6.15';c.entries.push(e);c.coverage.push({name:p.name,entryId:p.id,reason:{zh:'审核的组合配置；共享基线权重。',en:'Reviewed composition with shared baseline weights.'}});}
 for(const p of approvedPackages(root)){
  const e=c.entries.find(e=>e.id===p.potentialId);if(!e)throw Error('PACKAGE_NOT_IN_CATALOG');const id=`package-review:${p.potentialId}`;
  e.sources.push({id,url:p.url,revision:e.asset.revision,sha256:p.sha256,status:'documented',note:{zh:'MaterialsX 从此官方资源下载并校验权重，实际读取元素表；哈希与加载记录是本机工程验收，不是领域精度证明。',en:'MaterialsX downloaded and hashed this official checkpoint and inspected its element table. Identity and loading receipts are engineering checks, not domain accuracy evidence.'}});
  e.asset.sha256=p.sha256;e.asset.bytes=p.bytes;e.capabilities.elements=p.elements;e.fieldEvidence.asset=[id];e.fieldEvidence['capabilities.elements']=[id];e.execution.profileId=p.environmentProfileId;e.execution.diskEstimateMiB=p.bytes/1048576;e.execution.memoryEstimateMiB=p.loadedMemoryMiB;e.execution.blockers=['ACTUAL_PHASE_B_CHECK_REQUIRED','DOMAIN_NOT_VALIDATED'];e.licenses.redistribution='permitted-with-notices';
  e.limitations.push({zh:'权重按需下载；内存为小体系观测，不能作为大结构计算上限。',en:'Weights are on demand. Memory was observed on a small system and is not a bound for larger calculations.'});
  const reviewed=(physics?.entry.potentialId===p.potentialId?physics.potential:undefined)??expansion.potentials.find(v=>v.id===p.potentialId)??(molecule?.entry.potentialId===p.potentialId?molecule.potential:native?.entry.potentialId===p.potentialId?native.potential:undefined);
  if(reviewed){
   e.description=reviewed.description;e.examples=reviewed.examples;e.limitations=reviewed.limitations;
   e.capabilities.forceRelation='energy_gradient';e.capabilities.units={energy:reviewed.declared.nativeUnits.energy,forces:reviewed.declared.nativeUnits.forces,stress:reviewed.declared.nativeUnits.stress};e.capabilities.tasks=['singlepoint','relaxation'];
   for(const k of ['forceRelation','units','tasks'])e.fieldEvidence[`capabilities.${k}`]=[id];
   e.licenses.weights=reviewed.licenses.weights.expression;e.execution.platforms=reviewed.environment.matrix;e.execution.runtimeEvidenceIds=reviewed.runtimeEvidenceIds;e.execution.taskEvidenceIds=reviewed.taskEvidenceIds;e.execution.diskEstimateMiB=reviewed.environment.diskEstimateMiB;e.nextStage=p.potentialId===physics?.entry.potentialId?'M6.15':p.family==='nep'?'M6.14':p.family==='ani'?'M6.13':'M6.11';
  }
 }
 for(const e of expansion.candidates){const i=c.entries.findIndex(v=>v.id===e.id);if(i>=0)c.entries[i]=e;else {c.entries.push(e);c.coverage.push({name:e.name,entryId:e.id,reason:{zh:'M6.10 官方发布候选，未适配。',en:'M6.10 official release candidate; not adapted.'}});}}
 return potentialCatalogSchema.parse(c);
}
