import {COMPOSITE_ID} from '../../contracts/src/potential-physics.js';
import { constants,existsSync,lstatSync } from 'node:fs';
import { mkdir,lstat,open,rename,rm,readFile,statfs,copyFile } from 'node:fs/promises';
import { join } from 'node:path';
import { approvedPackages } from './approved-packages.js';
import { mountedPackageRequest,mountedPackageStatus,type ApprovedPackage,type MountedPackageStatus } from '../../contracts/src/potential-packages.js';
import { digestFile } from './selection.js';
const allowedHost=new Set(['github.com','release-assets.githubusercontent.com','objects.githubusercontent.com','raw.githubusercontent.com','huggingface.co','cdn-lfs.huggingface.co','cdn-lfs-us-1.hf.co','cas-bridge.xethub.hf.co','us.aws.cdn.hf.co']);
/** One bounded transfer at a time. Shared locked runtimes are never deleted with a checkpoint. */
export class PotentialPackageManager{
 private active:{id:string;controller:AbortController}|null=null;
 private live:MountedPackageStatus|null=null;
 constructor(private root:string,private userData:string,private inUse:(id:string)=>boolean=()=>false,private network:typeof fetch=fetch,private disk:(path:string)=>Promise<{bavail:number|bigint;bsize:number|bigint}>=statfs,private assertUsable:(id:string)=>void=()=>{}){}
 entries(){return approvedPackages(this.root);}
 entry(id:string){const e=this.entries().find(e=>e.potentialId===mountedPackageRequest.parse({potentialId:id}).potentialId);if(!e)throw Error('PACKAGE_NOT_APPROVED');return e;}
 private base(id:string){return join(this.userData,'scientific-packages',id);}
 weight(id:string){const e=this.entry(id);const safe=(base:string,parts:string[])=>{let path=base;for(const [i,c] of parts.entries()){path=join(path,c);try{const s=lstatSync(path);if(s.isSymbolicLink()||i<parts.length-1&&!s.isDirectory()||i===parts.length-1&&!s.isFile())throw Error('UNSAFE_PACKAGE_PATH');}catch(err){if((err as NodeJS.ErrnoException).code!=='ENOENT')throw err;}}return path;};const local=safe(this.userData,['scientific-packages',id,e.sha256,'checkpoint.bin']);if(id===COMPOSITE_ID){const parts=existsSync(join(this.root,'atomistic-runtime'))?['atomistic-runtime','mace','checkpoint.bin']:['runtime','atomistic',process.platform==='darwin'&&process.arch==='arm64'?'macos-arm64':'windows-x64','mace','checkpoint.bin'];return safe(this.root,parts);} return existsSync(local)?local:safe(this.root,['model-packages',id,e.sha256,'checkpoint.bin']);}
 disabled(id:string){this.entry(id);return existsSync(join(this.base(id),'disabled.json'));}
 private async directory(id:string){let path=this.userData;const root=await lstat(path);if(root.isSymbolicLink()||!root.isDirectory())throw Error('UNSAFE_PACKAGE_DIRECTORY');for(const c of ['scientific-packages',id]){path=join(path,c);await mkdir(path,{recursive:true});const s=await lstat(path);if(s.isSymbolicLink()||!s.isDirectory())throw Error('UNSAFE_PACKAGE_DIRECTORY');}return path;}
 private statusValue(e:ApprovedPackage,state:MountedPackageStatus['state'],bytes:number,error:string|null=null){return mountedPackageStatus.parse({potentialId:e.potentialId,state,bytes,totalBytes:e.bytes,sha256:e.sha256,error,runtimeReady:false,quality:'needs_review',environmentProfileId:e.environmentProfileId,cacheOwned:existsSync(join(this.base(e.potentialId),e.sha256,'checkpoint.bin'))});}
 async status(){const out:MountedPackageStatus[]=[];for(const e of this.entries()){
  if(this.active?.id===e.potentialId&&this.live){out.push(structuredClone(this.live));continue;}
  let state:MountedPackageStatus['state']='absent',bytes=0,error:string|null=null;
  let weight:string;try{weight=this.weight(e.potentialId);}catch{out.push(this.statusValue(e,'failed',0,'UNSAFE_PACKAGE_PATH'));continue;}const part=join(this.base(e.potentialId),'checkpoint.part');
  if(existsSync(weight)){try{await this.directory(e.potentialId);const dir=await lstat(join(weight,'..'));const s=await lstat(weight);if(dir.isSymbolicLink()||s.isSymbolicLink()||!s.isFile()||s.size!==e.bytes||await digestFile(weight,e.bytes)!==e.sha256)throw Error('PACKAGE_IDENTITY_MISMATCH');state=this.disabled(e.potentialId)?'disabled':'installed';bytes=e.bytes;}catch{state='failed';error='PACKAGE_IDENTITY_MISMATCH';}}
  else if(existsSync(part)){try{await this.directory(e.potentialId);const s=await lstat(part);if(s.isSymbolicLink()||!s.isFile()||s.size>e.bytes)throw Error();const meta=JSON.parse(await readFile(join(this.base(e.potentialId),'transfer.json'),'utf8'));if(meta.sha256!==e.sha256||meta.url!==e.url||meta.bytes!==e.bytes)throw Error();state='paused';bytes=s.size;}catch{state='failed';error='PACKAGE_PART_IDENTITY_MISMATCH';}}
  if(this.live?.potentialId===e.potentialId&&this.live.error&&state!=='installed'){state='failed';error=this.live.error;}
  out.push(this.statusValue(e,state,bytes,error));
 }return out;}
 operationBusy(id:string){return !!this.active||this.inUse(id);}
 async removePartial(id:string){this.entry(id);this.guard(id);const dir=await this.directory(id);for(const name of ['checkpoint.part','transfer.json']){const path=join(dir,name);try{const s=await lstat(path);if(s.isSymbolicLink()||!s.isFile())throw Error('UNSAFE_PACKAGE_PATH');await rm(path);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}}this.live=null;}
 private guard(id:string){if(this.active)throw Error('PACKAGE_OPERATION_BUSY');if(this.inUse(id))throw Error('PACKAGE_IN_USE');}
 async setDisabled(id:string,disabled:boolean){this.entry(id);this.guard(id);if(!disabled)this.assertUsable(id);const dir=await this.directory(id);if(disabled)await this.json(join(dir,'disabled.json'),{disabledAt:new Date().toISOString()});else await rm(join(dir,'disabled.json'),{force:true});}
 async uninstall(id:string){const e=this.entry(id);this.guard(id);const dir=await this.directory(id);await rm(join(dir,e.sha256),{recursive:true,force:true});await rm(join(dir,'checkpoint.part'),{force:true});await rm(join(dir,'transfer.json'),{force:true});this.live=null;}
 cancel(id?:string){if(!this.active||id&&this.active.id!==id)return false;this.active.controller.abort();return true;}
 private async json(path:string,value:unknown){const file=await open(path,constants.O_WRONLY|constants.O_CREAT|constants.O_TRUNC|constants.O_NOFOLLOW,0o600);try{await file.writeFile(JSON.stringify(value)+'\n');await file.sync();}finally{await file.close();}}
 private async checkDisk(dir:string,bytes:number){const s=await this.disk(dir);if(Number(s.bavail)*Number(s.bsize)<bytes+256*1048576)throw Error('PACKAGE_DISK_SPACE_LIMIT');}
 private async commit(e:ApprovedPackage,dir:string,part:string,signal:AbortSignal){signal.throwIfAborted();this.assertUsable(e.potentialId);if((await lstat(part)).size!==e.bytes||await digestFile(part,e.bytes)!==e.sha256)throw Error('PACKAGE_IDENTITY_MISMATCH');signal.throwIfAborted();const dest=join(dir,e.sha256);await mkdir(dest,{recursive:true});if((await lstat(dest)).isSymbolicLink())throw Error('UNSAFE_PACKAGE_DIRECTORY');for(const [i,n] of e.notices.entries()){const target=join(dest,`NOTICE-${i}.txt`);await this.json(join(dest,'identity.json'),e);const f=await open(target,constants.O_WRONLY|constants.O_CREAT|constants.O_TRUNC|constants.O_NOFOLLOW,0o600);try{await f.writeFile(await readFile(join(this.root,n.path)));}finally{await f.close();}}await rename(part,join(dest,'checkpoint.bin'));await rm(join(dir,'transfer.json'),{force:true});await rm(join(dir,'disabled.json'),{force:true});this.live=null;}
 async importFile(id:string,source:string){const e=this.entry(id);if(id===COMPOSITE_ID){this.guard(id);this.assertUsable(id);const st=await lstat(source);if(st.isSymbolicLink()||!st.isFile()||st.size!==e.bytes||await digestFile(source,e.bytes)!==e.sha256||await digestFile(this.weight(id),e.bytes)!==e.sha256)throw Error('COMPOSITION_BASELINE_CHANGED');return;} this.assertUsable(id);this.guard(id);const controller=new AbortController();this.active={id,controller};try{const s=await lstat(source);if(s.isSymbolicLink()||!s.isFile()||s.size!==e.bytes||await digestFile(source,e.bytes)!==e.sha256)throw Error('PACKAGE_IDENTITY_MISMATCH');const dir=await this.directory(id);await this.checkDisk(dir,e.bytes);const part=join(dir,'checkpoint.part');if(existsSync(part)&&(await lstat(part)).isSymbolicLink())throw Error('UNSAFE_PACKAGE_PART');await this.json(join(dir,'transfer.json'),{sha256:e.sha256,url:e.url,bytes:e.bytes});await copyFile(source,part);await this.commit(e,dir,part,controller.signal);}finally{this.active=null;}}
 private async request(url:string,offset:number,signal:AbortSignal){for(let redirects=0;redirects<5;redirects++){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||!allowedHost.has(u.hostname))throw Error('PACKAGE_REDIRECT_NOT_APPROVED');const r=await this.network(url,{redirect:'manual',headers:offset?{Range:`bytes=${offset}-`}:{},signal});if([301,302,303,307,308].includes(r.status)){const location=r.headers.get('location');await r.body?.cancel();if(!location)throw Error('PACKAGE_HTTP_FAILED');url=new URL(location,url).href;continue;}return r;}throw Error('PACKAGE_REDIRECT_LIMIT');}
 async download(id:string,signal?:AbortSignal){const e=this.entry(id);if(id===COMPOSITE_ID){this.guard(id);this.assertUsable(id);signal?.throwIfAborted();if(await digestFile(this.weight(id),e.bytes)!==e.sha256)throw Error('COMPOSITION_BASELINE_CHANGED');return;} this.assertUsable(id);this.guard(id);const controller=new AbortController();this.active={id,controller};const abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();let offset=0,part:string|undefined;
 try{controller.signal.throwIfAborted();const dir=await this.directory(id);part=join(dir,'checkpoint.part');if(existsSync(part)){const s=await lstat(part);if(s.isSymbolicLink()||!s.isFile()||s.size>e.bytes)throw Error('UNSAFE_PACKAGE_PART');let meta;try{meta=JSON.parse(await readFile(join(dir,'transfer.json'),'utf8'));}catch{}if(meta?.sha256!==e.sha256||meta.url!==e.url||meta.bytes!==e.bytes)throw Error('PACKAGE_PART_IDENTITY_MISMATCH');offset=s.size;}
 await this.checkDisk(dir,e.bytes-offset);await this.json(join(dir,'transfer.json'),{sha256:e.sha256,url:e.url,bytes:e.bytes});this.live=this.statusValue(e,'downloading',offset);
 if(offset!==e.bytes){const response=await this.request(e.url,offset,AbortSignal.any([controller.signal,AbortSignal.timeout(300000)]));if(!response.ok||!response.body)throw Error('PACKAGE_HTTP_FAILED');if(response.status===206){if(response.headers.get('content-range')!==`bytes ${offset}-${e.bytes-1}/${e.bytes}`)throw Error('PACKAGE_RANGE_MISMATCH');}else if(response.status===200)offset=0;else throw Error('PACKAGE_HTTP_FAILED');
 const f=await open(part,constants.O_WRONLY|constants.O_CREAT|constants.O_NOFOLLOW|(offset?constants.O_APPEND:constants.O_TRUNC),0o600);try{for await(const chunk of response.body){controller.signal.throwIfAborted();if(offset+chunk.length>e.bytes)throw Error('PACKAGE_SIZE_LIMIT');let written=0;while(written<chunk.length){const {bytesWritten}=await f.write(chunk,written,chunk.length-written);if(!bytesWritten)throw Error('PACKAGE_WRITE_FAILED');written+=bytesWritten;}offset+=chunk.length;this.live.bytes=offset;}await f.sync();}finally{await f.close();}if(offset!==e.bytes)throw Error('PACKAGE_TRUNCATED');}
 await this.commit(e,dir,part,controller.signal);
 }catch(err){const paused=controller.signal.aborted;const error=err instanceof Error?err.message.slice(0,200):'PACKAGE_FAILED';this.live=this.statusValue(e,paused?'paused':'failed',offset,paused?null:error);if(part&&!paused&&/IDENTITY|SIZE|RANGE/.test(error)){await rm(part,{force:true});await rm(join(this.base(id),'transfer.json'),{force:true});}throw paused?Error('PACKAGE_CANCELLED'):err;
 }finally{signal?.removeEventListener('abort',abort);this.active=null;}
 }
}
