import {requiredInteraction} from './interaction-requirements.js';
import { randomUUID } from 'node:crypto';
import { mkdirSync,readFileSync,writeFileSync,renameSync,lstatSync,readdirSync } from 'node:fs';
import { join } from 'node:path';
import { currentAnalysisRequestSchema as analysisRequestSchema,freezeAnalysisSchema,currentWorkflowSchema as workflowSchema,type AnalysisRequest,type PotentialWorkflow } from '../../contracts/src/potential-workflow.js';
import { type SelectionAssessment } from '../../contracts/src/potential-packages.js';
import { assessPotentials,digest,validateProposal } from './selection.js';
import { effectiveRegistry } from './model-packages.js';
import type { AtomisticRuntime } from './runtime.js';
const terminal=(s:string)=>['completed','failed','cancelled','interrupted'].includes(s);
/** Persisted plan + scoped ownership. Restart never silently restarts downloads or scientific jobs. */
export class PotentialAnalysisService{
 private assessments=new Map<string,{request:AnalysisRequest;assessment:SelectionAssessment}>();
 private records=new Map<string,PotentialWorkflow>();
 private controllers=new Map<string,AbortController>();
 private dir:string;
 constructor(private root:string,userData:string,private runtime:AtomisticRuntime){this.dir=join(userData,'potential-workflows');mkdirSync(this.dir,{recursive:true});if(lstatSync(this.dir).isSymbolicLink())throw Error('UNSAFE_WORKFLOW_DIRECTORY');}
 restore(){for(const name of readdirSync(this.dir)){if(!/^[a-f0-9-]+\.json$/.test(name))continue;try{const path=join(this.dir,name),s=lstatSync(path);if(s.isSymbolicLink()||s.size>2*1024**2)continue;const w=workflowSchema.parse(JSON.parse(readFileSync(path,'utf8')));if(w.id+'.json'!==name||w.id!==w.plan.id||this.planHash(w.plan)!==w.plan.planSha256)continue;this.runtime.inspect({projectId:w.plan.request.projectId,structureId:w.plan.request.structureId});if(!terminal(w.state)&&w.state!=='awaiting_approval'){w.state='interrupted';w.error='APP_RESTARTED';}this.records.set(w.id,w);this.save(w);}catch{}}}
 private planHash(plan:PotentialWorkflow['plan']){const {planSha256,...body}=plan;return digest(JSON.stringify(body));}
 private save(w:PotentialWorkflow){workflowSchema.parse(w);const path=join(this.dir,w.id+'.json');writeFileSync(path+'.tmp',JSON.stringify(w,null,2)+'\n',{mode:0o600});renameSync(path+'.tmp',path);}
 private update(w:PotentialWorkflow,state:PotentialWorkflow['state'],detail:string){w.state=state;w.updatedAt=new Date().toISOString();w.events.push({at:w.updatedAt,state,detail});w.events=w.events.slice(-200);this.save(w);}
 async assess(input:unknown){const request=analysisRequestSchema.parse(input);const interaction=requiredInteraction(request.prompt,request.interaction);if(interaction)request.interaction=interaction;const structure=this.runtime.inspect({projectId:request.projectId,structureId:request.structureId});await this.runtime.view({kind:'import',projectId:request.projectId,structureId:request.structureId});const registry=effectiveRegistry(this.root),packages=this.runtime.mountedPackages.entries();
 // Phase A uses reviewed checkpoint inspection receipts, explicitly not current-host runtime receipts.
 const capabilities=packages.filter(e=>this.runtime.isPotentialAllowed?.(e.potentialId)!==false&&!this.runtime.mountedPackages.disabled(e.potentialId)&&this.runtime.environmentReady(e.potentialId)).map(e=>({potentialId:e.potentialId,sha256:e.sha256,dependencyLockSha256:e.dependencyLockSha256,elements:e.elements,loadedMemoryMiB:e.loadedMemoryMiB,device:'cpu' as const,adapter:{phase:'reviewed-package-metadata-not-current-load'}}));
 const installed=await this.runtime.assess({projectId:request.projectId,structureId:request.structureId,domain:request.domain,mode:request.mode,interaction:request.interaction,task:request.task,budget:request.budget});for(const c of installed.capabilities){const i=capabilities.findIndex(x=>x.potentialId===c.potentialId);if(i>=0)capabilities.splice(i,1);capabilities.push(c as typeof capabilities[number]);}
 const a=assessPotentials(registry,digest(JSON.stringify(registry)),structure,{projectId:request.projectId,structureId:request.structureId,domain:request.domain,mode:request.mode,interaction:request.interaction,task:request.task,budget:request.budget},capabilities);if(request.options?.cellMode==='variable'){a.selection.candidates=a.selection.candidates.filter(c=>{if(['mace-mp-0b3-medium-d3-bj-pbe-si','nep-si-2022-nep4-3body','ani-2x-ensemble'].includes(c.potentialId)){a.selection.exclusions.push({potentialId:c.potentialId,reasonCodes:['FIXED_CELL_ONLY']});return false;}return true;});}
 a.rankingBasis='Phase A: audited metadata plus available actual runtime receipts; installed status does not prove scientific accuracy. Phase B must recheck the actual selected checkpoint after installation.';
 const statuses=await this.runtime.mountedPackages.status();for(const c of a.selection.candidates){const status=statuses.find(s=>s.potentialId===c.potentialId);if(status&&status.state!=='installed')c.reason={zh:'审核过的官方权重与已锁定环境在声明范围内匹配；本机尚未安装，需授权下载后进行阶段 B 真实加载检查。无独立精度证据。',en:'Reviewed official checkpoint and locked environment match the declared scope. Not installed locally: authorized download and Phase B actual loading checks are required. No independent accuracy evidence.'};}
 a.selection.candidates=a.selection.candidates.filter(c=>{const e=packages.find(e=>e.potentialId===c.potentialId);if(e&&statuses.find(s=>s.potentialId===e.potentialId)?.state!=='installed'&&e.bytes>request.maxDownloadBytes){a.selection.exclusions.push({potentialId:c.potentialId,reasonCodes:['DOWNLOAD_BUDGET_EXCEEDED']});return false;}return true;});
 this.assessments.set(a.id,{request,assessment:a});if(this.assessments.size>100)this.assessments.delete(this.assessments.keys().next().value!);return structuredClone(a);
 }
 async freeze(projectId:string,input:unknown){const q=freezeAnalysisSchema.parse(input),found=this.assessments.get(q.assessmentId);if(!found||found.request.projectId!==projectId)throw Error('ASSESSMENT_NOT_OWNED');validateProposal(found.assessment,{assessmentId:q.assessmentId,selectedPotentialId:q.potentialId,evidenceIds:q.evidenceIds});const p=effectiveRegistry(this.root).potentials.find(p=>p.id===q.potentialId)!;const e=this.runtime.mountedPackages.entries().find(e=>e.potentialId===p.id);const status=e?(await this.runtime.mountedPackages.status()).find(s=>s.potentialId===e.potentialId):null;const downloadBytes=e&&status?.state!=='installed'?e.bytes:0;if(downloadBytes>found.request.maxDownloadBytes)throw Error('DOWNLOAD_BUDGET_EXCEEDED');
 const id=randomUUID(),createdAt=new Date().toISOString();const body={version:'m6.9-v1' as const,id,createdAt,request:found.request,assessment:found.assessment,potentialId:p.id,potentialSha256:p.weights.sha256!,dependencyLockSha256:e?.dependencyLockSha256??this.runtime.status().find(s=>s.potentialId===p.id)!.dependencyLockSha256!,downloadBytes,evidenceIds:q.evidenceIds,reason:q.reason};const w=workflowSchema.parse({version:'m6.9-v1',id,plan:{...body,planSha256:digest(JSON.stringify(body))},state:'awaiting_approval',createdAt,updatedAt:createdAt,authorizedAt:null,runId:null,error:null,events:[]});this.records.set(id,w);this.update(w,'awaiting_approval','Frozen plan ready for scope authorization');return structuredClone(w);
 }
 get(projectId:string,id:string){const w=this.records.get(id);if(!w||w.plan.request.projectId!==projectId)throw Error('WORKFLOW_NOT_OWNED');return structuredClone(w);}
 list(projectId:string){return [...this.records.values()].filter(w=>w.plan.request.projectId===projectId).slice(-50).reverse().map(w=>structuredClone(w));}
 approve(projectId:string,id:string,planSha256:string){const w=this.records.get(this.get(projectId,id).id)!;if(w.plan.planSha256!==planSha256||this.planHash(w.plan)!==planSha256)throw Error('FROZEN_PLAN_CHANGED');if(this.controllers.has(id)||!['awaiting_approval','failed','cancelled','interrupted'].includes(w.state))throw Error('WORKFLOW_ALREADY_STARTED');w.authorizedAt=new Date().toISOString();w.error=null;const c=new AbortController();this.controllers.set(id,c);this.update(w,'checking','User authorized frozen plan; limits and structure cannot change');void this.execute(w,c).finally(()=>this.controllers.delete(id));return this.get(projectId,id);}
 private async execute(w:PotentialWorkflow,c:AbortController){const q=w.plan.request;try{
 c.signal.throwIfAborted();await this.runtime.view({kind:'import',projectId:q.projectId,structureId:q.structureId});const registry=effectiveRegistry(this.root),p=registry.potentials.find(p=>p.id===w.plan.potentialId);if(digest(JSON.stringify(registry))!==w.plan.assessment.registrySha256||!p||p.weights.sha256!==w.plan.potentialSha256||digest(JSON.stringify(this.runtime.inspect({projectId:q.projectId,structureId:q.structureId})))!==w.plan.assessment.structureSha256)throw Error('FROZEN_PLAN_STALE');
 if(w.runId){const existing=this.runtime.get({projectId:q.projectId,runId:w.runId});if(existing.job.status==='completed'){await this.validateResult(existing);this.update(w,'completed','Recovered verified scientific result; no duplicate calculation');return;}if(!terminal(existing.job.status))throw Error('PREVIOUS_JOB_STILL_ACTIVE');}
 const e=this.runtime.mountedPackages.entries().find(e=>e.potentialId===p.id);if(e){if(e.dependencyLockSha256!==w.plan.dependencyLockSha256)throw Error('FROZEN_ENVIRONMENT_CHANGED');if(this.runtime.mountedPackages.disabled(e.potentialId))throw Error('POTENTIAL_DISABLED');const s=(await this.runtime.mountedPackages.status()).find(s=>s.potentialId===e.potentialId)!;if(s.state!=='installed'){if(e.bytes>q.maxDownloadBytes||w.plan.downloadBytes<e.bytes)throw Error('DOWNLOAD_NOT_AUTHORIZED');this.update(w,'downloading','Downloading reviewed checkpoint with exact byte/hash checks');await this.runtime.mountedPackages.download(e.potentialId,c.signal);}}
 this.update(w,'checking','Phase B: verify actual bytes, locked environment, elements and structure');const fresh=await this.runtime.assess({projectId:q.projectId,structureId:q.structureId,domain:q.domain,mode:q.mode,interaction:q.interaction,task:q.task,budget:q.budget},c.signal);const candidate=fresh.selection.candidates.find(x=>x.potentialId===p.id);if(!candidate)throw Error('PHASE_B_POTENTIAL_EXCLUDED');const job=await this.runtime.startSelected({projectId:q.projectId,proposal:{assessmentId:fresh.id,selectedPotentialId:p.id,evidenceIds:candidate.evidenceIds},...(q.options?{options:q.options}:{})},c.signal);w.runId=job.job.id;this.update(w,'queued','Scientific worker queued with frozen calculation options');
 const abort=()=>this.runtime.cancel({projectId:q.projectId,runId:job.job.id});c.signal.addEventListener('abort',abort,{once:true});if(c.signal.aborted)abort();try{let last='';for(;;){c.signal.throwIfAborted();const s=this.runtime.get({projectId:q.projectId,runId:job.job.id});if(s.job.status==='completed'){await this.validateResult(s);this.update(w,'completed','Real result, structure, bilingual reports and artifact hashes verified');return;}if(terminal(s.job.status))throw Error(s.job.error??s.job.status);if(last!==s.job.status){last=s.job.status;this.update(w,s.job.status==='queued'?'queued':'running',s.job.status);}await new Promise(r=>setTimeout(r,250));}}finally{c.signal.removeEventListener('abort',abort);}
 }catch(err){w.error=err instanceof Error?err.message.slice(0,512):'ANALYSIS_FAILED';this.update(w,c.signal.aborted?'cancelled':'failed',w.error);}}
 private async validateResult(s:ReturnType<AtomisticRuntime['get']>){const a=s.artifacts.find(a=>a.relativePath.endsWith(s.relaxation?'/final.json':'/structure.json'));if(!a||!s.result)throw Error('REAL_RESULT_MISSING');await this.runtime.view({kind:'artifact',projectId:s.job.projectId,runId:s.job.id,artifactId:a.id});}
 cancel(projectId:string,id:string){const w=this.records.get(this.get(projectId,id).id)!;if(terminal(w.state))return false;const c=this.controllers.get(id);if(c)c.abort();else this.update(w,'cancelled','Cancelled before authorization');return true;}
 busy(id:string){return [...this.records.values()].some(w=>w.plan.potentialId===id&&this.controllers.has(w.id));}
 dispose(){for(const c of this.controllers.values())c.abort();}
}
