import test from 'node:test';import assert from 'node:assert/strict';import { readFileSync } from 'node:fs';
import { holdoutSchema,type Holdout,type Prediction } from '../../contracts/src/atomistic-validation.js';
import { evaluatePredictions,geometryHash } from './scientific-validation.js';import { digest } from './selection.js';
const structure=JSON.parse(readFileSync('samples/atomistic/si-diamond.structure.json','utf8')),policy=JSON.parse(readFileSync('models/potentials/quality-policy.json','utf8')),h='a'.repeat(64);
// Fabricated fixtures exercise the evaluator only; they are never DFT/scientific evidence.
export function holdoutFixture(kind:'synthetic-test'|'dft-heldout'='synthetic-test'):Holdout{return holdoutSchema.parse({version:'m6.6-v1',id:'synthetic-unit-only',title:'Synthetic evaluator fixture, NOT DFT',kind,units:{energy:'eV-total',forces:'eV/angstrom',positions:'angstrom'},source:{citation:'Fabricated test fixture',license:'AGPL-3.0-only',licenseConfirmed:true,labelProvenanceSha256:h},settings:{code:'fixture',version:'fixture',functional:'PBE+U',hubbardU:{},pseudopotentialSha256:[h],cutoffEv:500,kpointMesh:[4,4,4],spin:'fixture',charge:'fixture',energyReference:'fixture',corrections:'fixture',forceConvergenceEvPerAngstrom:.01,electronicConvergenceEv:1e-6},audits:[{potentialId:'chgnet-0.3.0',trainingOverlap:'independent-reviewed',reviewer:'test only',evidenceSha256:h,reviewedAt:'2026-10-02',matchedTheory:true,matchedEnergyReference:true}],samples:Array.from({length:50},(_,i)=>({id:`sample-${i}`,domain:i<20?'bulk':i<30?'multi-element':i<40?'defect':'surface',structure:{...structuredClone(structure),id:`fixture-${i}`,atoms:structure.atoms.map((a:any,j:number)=>({...a,position:[a.position[0]+(j===0?i*.001:0),a.position[1],a.position[2]]}))},energyEv:-40,forcesEvPerAngstrom:structure.atoms.map(()=>[0,0,0])}))});}
const predictions=(d:Holdout):Prediction[]=>d.samples.map(s=>({sampleId:s.id,runId:s.id,potentialId:'chgnet-0.3.0',potentialSha256:h,structureSha256:geometryHash(s.structure),energyEv:s.energyEv+.08,forcesEvPerAngstrom:s.forcesEvPerAngstrom.map(()=>[.1,.1,.1])}));
const evaluate=(d:Holdout,p=predictions(d))=>evaluatePredictions(d,digest(JSON.stringify(d)),'chgnet-0.3.0',h,'PBE+U',p,policy,h);
test('component-pooled force RMSE and per-structure per-atom energy MAE; no fitted offsets',()=>{const d=holdoutFixture('dft-heldout'),r=evaluate(d);assert.equal(r.status,'passed-screening');assert.equal(r.productionApproved,false);for(const row of r.domains){assert(Math.abs(row.energyMaeEvPerAtom!-.01)<1e-12);assert(Math.abs(row.forceRmseEvPerAngstrom!-.1)<1e-12);}const p=predictions(d).map(p=>({...p,energyEv:p.energyEv+8}));assert.equal(evaluate(d,p).status,'failed');});
test('synthetic labels, overlap, theory/reference/license and insufficient quotas never pass',()=>{const d=holdoutFixture();assert(evaluate(d).reasonCodes.includes('SYNTHETIC_NOT_DFT'));for(const change of [(d:Holdout)=>d.source.licenseConfirmed=false,(d:Holdout)=>d.audits[0]!.trainingOverlap='unknown',(d:Holdout)=>d.audits[0]!.matchedEnergyReference=false,(d:Holdout)=>d.settings.functional='r2SCAN',(d:Holdout)=>d.samples=d.samples.slice(0,20)]){const x=holdoutFixture('dft-heldout');change(x);assert.equal(evaluate(x).status,'blocked');}const x=holdoutFixture('dft-heldout');assert.equal(evaluate(x,predictions(x).slice(1)).status,'blocked');});
test('atom mapping, model bytes, duplicate predictions and geometry provenance are enforced',()=>{const d=holdoutFixture();for(const change of [(p:Prediction)=>p.structureSha256='b'.repeat(64),(p:Prediction)=>p.potentialSha256='b'.repeat(64),(p:Prediction)=>p.forcesEvPerAngstrom.pop(),(p:Prediction)=>p.sampleId='foreign']){const p=predictions(d);change(p[0]!);assert.throws(()=>evaluate(d,p),/PROVENANCE/);}const p=predictions(d);assert.throws(()=>evaluate(d,[...p,p[0]!]),/DUPLICATE/);});
test('holdout contract blocks duplicate structures, unknown units, NaN and label mismatch',()=>{const d=holdoutFixture();for(const change of [(d:any)=>d.samples[1].structure=d.samples[0].structure,(d:any)=>d.units.energy='eV/atom',(d:any)=>d.samples[0].energyEv=NaN,(d:any)=>d.samples[0].forcesEvPerAngstrom.pop(),(d:any)=>d.samples[0].structure.pbc=[true,true,false]]){const x=structuredClone(d);change(x);assert(!holdoutSchema.safeParse(x).success);}});
