import { randomUUID } from 'node:crypto';
import { lstat,mkdir,readFile,rename,readdir,rm,writeFile } from 'node:fs/promises';
import { join,dirname } from 'node:path';
import { readOwnedBytes } from './artifact-io.js';
import { realpath } from 'node:fs/promises';
import { holdoutSchema,evaluationRequestSchema,evaluationStatusSchema,evaluationReportSchema,predictionSchema,qualityMatrixSchema,type Holdout,type Prediction,type EvaluationStatus,type EvaluationReport } from '../../contracts/src/atomistic-validation.js';
import { type RunnablePotentialId } from '../../contracts/src/atomistic-runtime.js';
import type { AtomicStructure } from '../../contracts/src/atomistic.js';
import { digest } from './selection.js';
import { effectiveRegistry } from './model-packages.js';
import type { AtomisticRuntime } from './runtime.js';
export const geometryHash=(s:AtomicStructure)=>digest(JSON.stringify({cell:s.cell,pbc:s.pbc,atoms:s.atoms.map(a=>({element:a.element,position:a.position}))}));
type Policy={domainQuality:{minimumStructuresPerCore:number;minimumPerDomain:Record<string,number>;energyMaeMaxEvPerAtom:number;forceRmseMaxEvPerAngstrom:number}};
/** Metrics use supplied DFT labels, with no fitted energy offsets or cross-model averaging. */
export function evaluatePredictions(dataset:Holdout,datasetSha256:string,potentialId:RunnablePotentialId,potentialSha256:string,functional:string,predictions:Prediction[],policy:Policy,policySha256:string):EvaluationReport{
 const d=holdoutSchema.parse(dataset),preds=predictions.map(p=>predictionSchema.parse(p));const reasons:string[]=[];const audit=d.audits.find(a=>a.potentialId===potentialId);
 if(d.kind!=='dft-heldout')reasons.push('SYNTHETIC_NOT_DFT');if(!d.source.licenseConfirmed)reasons.push('DATA_LICENSE_UNCONFIRMED');
 if(!audit||audit.trainingOverlap!=='independent-reviewed')reasons.push('TRAINING_OVERLAP_UNVERIFIED');if(!audit?.matchedTheory||d.settings.functional!==functional)reasons.push('THEORY_MISMATCH');if(!audit?.matchedEnergyReference)reasons.push('ENERGY_REFERENCE_UNVERIFIED');
 if(d.samples.length<policy.domainQuality.minimumStructuresPerCore)reasons.push('INSUFFICIENT_TOTAL_SAMPLES');
 if(new Set(preds.map(p=>p.sampleId)).size!==preds.length)throw Error('DUPLICATE_PREDICTION');
 for(const p of preds){const s=d.samples.find(s=>s.id===p.sampleId);if(!s||p.potentialId!==potentialId||p.potentialSha256!==potentialSha256||p.structureSha256!==geometryHash(s.structure)||p.forcesEvPerAngstrom.length!==s.structure.atoms.length)throw Error('PREDICTION_PROVENANCE_MISMATCH');}
 if(preds.length!==d.samples.length)reasons.push('INCOMPLETE_PREDICTIONS');
 const domains=(['bulk','multi-element','defect','surface'] as const).map(domain=>{const samples=d.samples.filter(s=>s.domain===domain),pairs=samples.flatMap(s=>{const p=preds.find(p=>p.sampleId===s.id);return p?[{s,p}]:[];});const required=policy.domainQuality.minimumPerDomain[domain]!;
  let energy=0,squared=0,components=0;for(const {s,p}of pairs){energy+=Math.abs(p.energyEv-s.energyEv)/s.structure.atoms.length;for(let i=0;i<s.forcesEvPerAngstrom.length;i++)for(let j=0;j<3;j++){squared+=(p.forcesEvPerAngstrom[i]![j]!-s.forcesEvPerAngstrom[i]![j]!)**2;components++;}}
  const mae=pairs.length?energy/pairs.length:null,rmse=components?Math.sqrt(squared/components):null;
  return {domain,samples:pairs.length,required,energyMaeEvPerAtom:mae,forceRmseEvPerAngstrom:rmse,passed:reasons.length===0&&pairs.length>=required&&pairs.length===samples.length&&mae!==null&&mae<=policy.domainQuality.energyMaeMaxEvPerAtom&&rmse!==null&&rmse<=policy.domainQuality.forceRmseMaxEvPerAngstrom};
 });
 if(domains.some(d=>d.samples<d.required))reasons.push('INSUFFICIENT_DOMAIN_SAMPLES');
 const metricFailure=domains.some(d=>d.energyMaeEvPerAtom!==null&&d.energyMaeEvPerAtom>policy.domainQuality.energyMaeMaxEvPerAtom||d.forceRmseEvPerAngstrom!==null&&d.forceRmseEvPerAngstrom>policy.domainQuality.forceRmseMaxEvPerAngstrom);
 if(metricFailure)reasons.push('ERROR_THRESHOLD_EXCEEDED');
 return evaluationReportSchema.parse({version:'m6.6-v1',id:randomUUID(),datasetId:d.id,datasetSha256,policySha256,potentialId,potentialSha256,createdAt:new Date().toISOString(),status:reasons.some(r=>r!=='ERROR_THRESHOLD_EXCEEDED')?'blocked':metricFailure?'failed':'passed-screening',productionApproved:false,quality:'needs_review',reasonCodes:[...new Set(reasons)],totalSamples:d.samples.length,completedSamples:preds.length,domains,predictions:preds,limitations:['User-supplied reference settings, provenance and overlap attestations require independent review. This report never changes production eligibility.','Frozen per-domain energy/force screening only; no fitted energy offset. It does not validate stress, target properties, relaxation, molecular dynamics, molecules or polymers.']});
}
type DatasetRecord={projectId:string;sha256:string;dataset:Holdout};
export class ScientificValidationService {
 private datasets=new Map<string,DatasetRecord>();private jobs=new Map<string,EvaluationStatus>();private published=new Map<string,EvaluationStatus>();private controller:AbortController|null=null;private directory:string;
  constructor(private root:string,userData:string,private runtime:AtomisticRuntime,private projectPath:(id:string)=>string|null){this.directory=join(userData,'scientific-validation');}
 private project(id:string){const p=this.projectPath(id);if(!p)throw Error('UNKNOWN_PROJECT');return p;}
 async restore(){await mkdir(this.directory,{recursive:true});for(const name of (await readdir(this.directory)).sort()){try{const path=join(this.directory,name),s=await lstat(path);if(s.isSymbolicLink()||s.size>16*1048576)continue;const b=await readFile(path);if(name.startsWith('dataset-')){const r=JSON.parse(b.toString()) as DatasetRecord;holdoutSchema.parse(r.dataset);this.project(r.projectId);if(digest(JSON.stringify(r.dataset))!==r.sha256)continue;this.datasets.set(r.dataset.id,r);}else if(name.startsWith('evaluation-')){const q=evaluationStatusSchema.parse(JSON.parse(b.toString()));this.project(q.projectId);if(q.report){try{await this.verifyReport(q);}catch{q.status='failed';q.report=null;q.error='STORED_EVALUATION_CHANGED';await this.persist(q);}}if(['queued','running'].includes(q.status)){q.status='interrupted';q.activeRunId=null;q.error='APP_RESTARTED';q.report=null;await this.persist(q);}this.jobs.set(q.id,q);this.published.set(q.id,structuredClone(q));}}catch{/* Invalid/stale ownership records do not authorize work. */}}}
 private async verifyReport(q:EvaluationStatus){const record=this.datasets.get(q.datasetId),report=q.report;if(!record||!report||record.projectId!==q.projectId||report.datasetSha256!==record.sha256||report.potentialId!==q.potentialId||report.datasetId!==q.datasetId)throw Error('EVALUATION_SCOPE_CHANGED');const policy=await readFile(join(this.root,'models/potentials/quality-policy.json')),p=effectiveRegistry(this.root).potentials.find(p=>p.id===q.potentialId)!;if(report.policySha256!==digest(policy)||report.potentialSha256!==p.weights.sha256)throw Error('EVALUATION_IDENTITY_CHANGED');
  for(const prediction of report.predictions){const run=this.runtime.get({projectId:q.projectId,runId:prediction.runId});if(run.job.status!=='completed'||!run.result||run.plan.task.kind!=='singlepoint'||run.result.potentialId!==prediction.potentialId||run.result.potentialSha256!==prediction.potentialSha256||geometryHash(run.structure)!==prediction.structureSha256||run.result.energyEv!==prediction.energyEv||JSON.stringify(run.result.forcesEvPerAngstrom)!==JSON.stringify(prediction.forcesEvPerAngstrom))throw Error('EVALUATION_PREDICTION_CHANGED');await this.runtime.view({kind:'artifact',projectId:q.projectId,runId:prediction.runId,artifactId:run.artifacts.find(a=>a.type==='atomic_structure')!.id});}
  const expected=evaluatePredictions(record.dataset,record.sha256,q.potentialId,p.weights.sha256!,p.energyReference.functional,report.predictions,JSON.parse(policy.toString()),digest(policy));expected.id=report.id;expected.createdAt=report.createdAt;if(JSON.stringify(expected)!==JSON.stringify(report))throw Error('EVALUATION_METRICS_CHANGED');
 }
 private async persist(q:EvaluationStatus){evaluationStatusSchema.parse(q);const path=join(this.directory,`evaluation-${q.id}.json`);await writeFile(path+'.tmp',JSON.stringify(q,null,2)+'\n',{mode:0o600});await rename(path+'.tmp',path);this.published.set(q.id,structuredClone(q));}
 async importDataset(projectId:string,path:string){this.project(projectId);const s=await lstat(path);if(s.isSymbolicLink()||!s.isFile()||s.size>16*1048576)throw Error('DATASET_SIZE_OR_SYMLINK');const bytes=await readOwnedBytes(dirname(path),path,null,16*1048576);const dataset=holdoutSchema.parse(JSON.parse(bytes.toString()));const sha256=digest(JSON.stringify(dataset));const old=this.datasets.get(dataset.id);if(old&&(old.sha256!==sha256||old.projectId!==projectId))throw Error('DATASET_ID_ALREADY_OWNED_OR_CHANGED');const r={projectId,dataset,sha256};await mkdir(this.directory,{recursive:true});await writeFile(join(this.directory,`dataset-${digest(dataset.id)}.json`),JSON.stringify(r,null,2)+'\n',{mode:0o600});this.datasets.set(dataset.id,r);return this.listDatasets(projectId);}
 listDatasets(projectId:string){this.project(projectId);return [...this.datasets.values()].filter(r=>r.projectId===projectId).map(r=>({id:r.dataset.id,title:r.dataset.title,kind:r.dataset.kind,functional:r.dataset.settings.functional,samples:r.dataset.samples.length,sha256:r.sha256}));}
 list(projectId:string){this.project(projectId);return [...this.published.values()].filter(j=>j.projectId===projectId).slice(-50).reverse().map(j=>structuredClone(j));}
 async start(input:unknown){const q=evaluationRequestSchema.parse(input);this.project(q.projectId);const record=this.datasets.get(q.datasetId);if(!record||record.projectId!==q.projectId)throw Error('DATASET_NOT_OWNED');if(this.controller)throw Error('VALIDATION_BUSY');if(this.runtime.list(q.projectId).some(j=>!['completed','failed','cancelled','interrupted'].includes(j.job.status)))throw Error('ATOMISTIC_BUSY');
 const job:EvaluationStatus={id:randomUUID(),...q,status:'queued',completedSamples:0,totalSamples:record.dataset.samples.length,activeRunId:null,error:null,report:null};const controller=new AbortController();this.controller=controller;try{await this.persist(job);}catch(e){this.controller=null;throw e;}this.jobs.set(job.id,job);void this.run(job,record,controller).catch(async()=>{if(job.activeRunId)this.runtime.cancel({projectId:job.projectId,runId:job.activeRunId});this.controller=null;this.published.set(job.id,evaluationStatusSchema.parse({...job,status:'failed',activeRunId:null,error:'EVALUATION_STATE_WRITE_FAILED',report:null}));await rm(join(this.directory,`inputs-${job.id}`),{recursive:true,force:true}).catch(()=>{});});return structuredClone(job);}
 cancel(projectId:string,id:string){this.project(projectId);const q=this.jobs.get(id);if(!q||q.projectId!==projectId)throw Error('EVALUATION_NOT_OWNED');if(!this.controller||!['running','queued'].includes(q.status))return false;this.controller.abort();if(q.activeRunId)this.runtime.cancel({projectId,runId:q.activeRunId});return true;}
 private async run(q:EvaluationStatus,r:DatasetRecord,controller:AbortController){const predictions:Prediction[]=[];const temp=join(this.directory,`inputs-${q.id}`),deadline=Date.now()+1800000;try{q.status='running';await this.persist(q);await mkdir(temp);const registry=effectiveRegistry(this.root),p=registry.potentials.find(p=>p.id===q.potentialId)!;if(!p.weights.sha256)throw Error('MODEL_IDENTITY_MISSING');
  for(const sample of r.dataset.samples){controller.signal.throwIfAborted();if(Date.now()>deadline)throw Error('EVALUATION_WALL_TIME_LIMIT');const s=sample.structure;if(!s.cell)throw Error('CELL_REQUIRED');const text=`${s.atoms.length}\nLattice="${s.cell.flat().join(' ')}" Properties=species:S:1:pos:R:3 pbc="T T T"\n`+s.atoms.map(a=>`${a.element} ${a.position.join(' ')}`).join('\n')+'\n';const path=join(temp,'source.extxyz');await writeFile(path,text,{mode:0o600});const imported=await this.runtime.importFile(q.projectId,path);if(geometryHash(imported)!==geometryHash(s))throw Error('DATASET_GEOMETRY_CHANGED_ON_IMPORT');controller.signal.throwIfAborted();const assessment=await this.runtime.assess({projectId:q.projectId,structureId:imported.id,domain:'inorganic-crystals',mode:'exploratory',task:'singlepoint'},controller.signal),candidate=assessment.selection.candidates.find(c=>c.potentialId===q.potentialId);if(!candidate)throw Error('POTENTIAL_EXCLUDED');const run=await this.runtime.startSelected({projectId:q.projectId,proposal:{assessmentId:assessment.id,selectedPotentialId:q.potentialId,evidenceIds:candidate.evidenceIds}},controller.signal);q.activeRunId=run.job.id;await this.persist(q);
   while(true){if(Date.now()>deadline){this.runtime.cancel({projectId:q.projectId,runId:run.job.id});throw Error('EVALUATION_WALL_TIME_LIMIT');}if(controller.signal.aborted){this.runtime.cancel({projectId:q.projectId,runId:run.job.id});throw Error('CANCELLED');}const current=this.runtime.get({projectId:q.projectId,runId:run.job.id});if(['completed','failed','cancelled','interrupted'].includes(current.job.status)){if(current.job.status!=='completed'||!current.result)throw Error('PREDICTION_JOB_FAILED');predictions.push(predictionSchema.parse({sampleId:sample.id,runId:run.job.id,potentialId:q.potentialId,potentialSha256:current.result.potentialSha256,structureSha256:geometryHash(imported),energyEv:current.result.energyEv,forcesEvPerAngstrom:current.result.forcesEvPerAngstrom}));break;}await new Promise(r=>setTimeout(r,100));}
   q.completedSamples=predictions.length;q.activeRunId=null;await this.persist(q);
  }
  const bytes=await readFile(join(this.root,'models/potentials/quality-policy.json')),report=evaluatePredictions(r.dataset,r.sha256,q.potentialId,p.weights.sha256,p.energyReference.functional,predictions,JSON.parse(bytes.toString()),digest(bytes));q.report=report;q.status='completed';
  const project=this.project(q.projectId);let output=await realpath(project);for(const part of ['materials-output','scientific-validation',q.id]){output=join(output,part);await mkdir(output,{recursive:true});const info=await lstat(output);if(info.isSymbolicLink()||!info.isDirectory())throw Error('UNSAFE_OUTPUT_DIRECTORY');}await writeFile(join(output,'report.json'),JSON.stringify(report,null,2)+'\n',{mode:0o600});const lines=report.domains.map(d=>`| ${d.domain} | ${d.samples}/${d.required} | ${d.energyMaeEvPerAtom??'—'} | ${d.forceRmseEvPerAngstrom??'—'} |`);for(const locale of ['zh','en'])await writeFile(join(output,`report.${locale}.md`),`# ${locale==='zh'?'科学保留集评测':'Scientific holdout evaluation'}\n\n${report.status} · needs_review · productionApproved=false\n\n${report.reasonCodes.join(', ')}\n\n| Domain | N/required | E MAE (eV/atom) | F RMSE (eV/Å) |\n| --- | --- | --- | --- |\n${lines.join('\n')}\n\n${locale==='zh'?'参考设置、来源和训练重叠声明由导入者提供，需要独立人工复核。本报告不改变正式计算准入。\n\n仅按冻结的能量/力阈值筛查；不拟合能量偏置，不验证应力、目标性质、优化、MD、分子或高分子。':report.limitations.join('\n\n')}\n`,{mode:0o600});
 }catch(e){q.status=controller.signal.aborted?'cancelled':'failed';q.error=controller.signal.aborted?'CANCELLED':e instanceof Error?e.message.slice(0,200):'VALIDATION_FAILED';q.report=null;}finally{if(q.activeRunId){this.runtime.cancel({projectId:q.projectId,runId:q.activeRunId});for(let n=0;n<300;n++){if(['completed','failed','cancelled','interrupted'].includes(this.runtime.get({projectId:q.projectId,runId:q.activeRunId}).job.status))break;await new Promise(r=>setTimeout(r,100));}}q.activeRunId=null;await this.persist(q);this.controller=null;await rm(temp,{recursive:true,force:true});}}
 async matrix(projectId:string){const bytes=await readFile(join(this.root,'models/potentials/quality-policy.json'));const reports=this.list(projectId);return qualityMatrixSchema.parse({version:'m6.6-v1',platform:this.runtime.platform,policySha256:digest(bytes),rows:this.runtime.status().filter(s=>["mace-mp-0b3-medium","chgnet-0.3.0","chgnet-r2scan"].includes(s.potentialId)).map(s=>{const p=effectiveRegistry(this.root).potentials.find(p=>p.id===s.potentialId)!;const report=reports.find(r=>r.potentialId===s.potentialId&&r.report)?.report;return {potentialId:s.potentialId,functional:p.energyReference.functional,installed:s.installed,portable:s.portable,domainStatus:report?.status==='passed-screening'?'passed-screening':report?.status==='failed'?'failed':'blocked-reference-data-missing',productionApproved:false,reportId:report?.id??null,devices:{cpu:s.installed?'available-unverified':'absent',cuda:'unverified',mps:'unverified'}};}),releaseGates:[{id:'heldout-reference-data',status:'pending',detail:'Independent licensed, theory-matched DFT holdouts and human scientific review required.'},{id:'windows-installer',status:'pending',detail:'Actual Windows installation and offline receipts must be collected on Windows.'},{id:'signed-production-release',status:'pending',detail:'Signing, notarization and final release approval are separate from development acceptance.'}]});}
 dispose(){this.controller?.abort();for(const q of this.jobs.values())if(q.activeRunId)this.runtime.cancel({projectId:q.projectId,runId:q.activeRunId});}
}
