package gateway

import "net/http"

func (h *HTTP) financeScript(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/javascript; charset=utf-8")
	_, _ = w.Write([]byte(financeJS))
}

const financeJS = `(()=>{const work=document.getElementById('work');if(!work)return;const panel=document.createElement('section'),title=document.createElement('h2'),note=document.createElement('p'),refreshButton=document.createElement('button'),output=document.createElement('pre'),input=document.createElement('input'),reason=document.createElement('input'),preview=document.createElement('pre'),review=document.createElement('button'),approve=document.createElement('button'),reject=document.createElement('button'),simulate=document.createElement('button'),recheck=document.createElement('button');title.textContent='订单与退款工作台';note.textContent='测试渠道不会发生真实扣款。审批前查看冻结积分和订单版本；超时由 Worker 使用原编号查询。正式退款规则和商户配置待确认。';refreshButton.textContent='刷新订单';input.placeholder='退款编号（测试支付时输入订单编号）';reason.placeholder='审批 / 拒绝原因';review.textContent='核算预览';approve.textContent='批准退款';reject.textContent='拒绝退款';simulate.textContent='仅测试：模拟收到付款';recheck.textContent='查询渠道 / 恢复待核对任务';panel.append(title,note,refreshButton,output,input,reason,review,preview,approve,reject,simulate,recheck);work.append(panel);let current=null,listing=null;async function load(){const v=await api('finance');listing=v;output.textContent=JSON.stringify(v,null,2);simulate.hidden=v.mode!=='test';current=null;preview.textContent='';}refreshButton.onclick=()=>action(load);review.onclick=()=>action(async()=>{current=await api('finance/preview',{refundId:input.value});preview.textContent=JSON.stringify(current,null,2)});for(const [button,decision] of [[approve,'approve'],[reject,'reject']])button.onclick=()=>action(async()=>{if(!current||current.refund.id!==input.value)throw Error('先预览');if(decision==='approve'&&!current.eligible)throw Error('不符合退款条件');if(!reason.value.trim())throw Error('请输入原因');if(!confirm('确认'+(decision==='approve'?'冻结积分并执行原路退款':'拒绝申请')+'？\n'+preview.textContent))return;await api('finance/decision',{decision,reason:reason.value,expectedVersion:current.refund.version,orderVersion:current.orderVersion},input.value);await load()});recheck.onclick=()=>action(async()=>{const item=listing?.items.find(i=>i.order.id===input.value);if(!item||!reason.value.trim())throw Error('先刷新并输入订单编号和原因');await api('finance/recheck',{orderId:input.value,reason:reason.value,expectedVersion:item.order.version},input.value);await load()});simulate.onclick=()=>action(async()=>{if(!confirm('仅模拟测试付款，不发生真实扣款。'))return;await api('finance/simulate',{orderId:input.value},input.value);await load()});})();`
