/** Host-owned facts shared by engine guidance and the read-only capability tool. */
export const SKILL_INSTALLATION_CAPABILITY = {
  kind: 'host-action',
  available: true,
  executor: 'application-chat-command',
  commands: { zh: '安装 Skill <名称、GitHub Skill 目录地址或本地绝对路径>', en: 'Install Skill <name, GitHub Skill directory URL, or absolute local folder>' },
  namedSources: ['anthropics/skills', 'k-dense-ai/scientific-agent-skills'],
  requiresAdministrator: false,
  requiresModelTool: false,
  authorization: 'An explicit human installation command; asking about capabilities does not authorize installation.',
  effects: ['download or copy', 'validate', 'register in Skills and @'],
  doesNotPerform: ['execute scripts', 'install Python/npm dependencies', 'grant extra permissions'],
} as const;
export const SKILL_INSTALLATION_GUIDANCE = `MaterialsX supports Skill installation as an APPLICATION action, separate from model tools. Human command: ${SKILL_INSTALLATION_CAPABILITY.commands.zh} / ${SKILL_INSTALLATION_CAPABILITY.commands.en}. No administrator or model tool named skill_installer is required. For questions about Skill installation/availability, read skill_capabilities when advertised and report the current host facts. An absent installation tool does not mean the application cannot install. Do not invent permission denials. Unknown names require an exact source; only a real host receipt proves installation. Asking whether installation is possible is not an installation command.`;

/** A capability question needs a factual answer, not a scientific execution plan. */
export function skillCapabilityQuestion(text: string) {
  const s = text.trim();
  return /\bskills?\b|技能/i.test(s) &&
    /(?:你|系统|软件|MaterialsX).{0,15}(?:能否|能不能|可以|会不会|是否|支持)|^(?:可以|可不可以|能否|能不能|是否)|^(?:can|could|do|does|are|is)\b|^(?:如何|怎么|怎样|how\b)/i.test(s) &&
    /安装|添加|下载|install|add|download/i.test(s) &&
    /[?？]|吗(?=\s|$)|能否|能不能|会不会|是否|^(?:can|could|do|does|how)\b|^(?:如何|怎么|怎样)/i.test(s);
}
/** Product help is rendered from host facts, not regenerated by a model. */
export function skillInstallationHelp(content: string) {
  const c = SKILL_INSTALLATION_CAPABILITY;
  if(/所有|全部|批量|\ball\b|\bbulk\b/i.test(content))return /[\u3400-\u9fff]/.test(content)
    ? '目前支持逐个安装 Skill，尚不支持从仓库根地址一键安装全部 Skills。请指定仓库内的具体 Skill 目录：\n\n`安装 Skill https://github.com/组织/仓库/tree/main/skills/名称`\n\n安装后会加入 Skills 页面和 @ 列表。安装不执行脚本，也不安装 Python/npm 依赖。本次只是查询能力，没有安装任何 Skill。'
    : 'MaterialsX currently installs one Skill directory per command; bulk installation from a repository root is not supported yet. Send `Install Skill https://github.com/owner/repo/tree/main/skills/name`. Installed Skills appear in Skills and @. Installation does not execute scripts or install Python/npm dependencies. This capability inquiry installed nothing.';
  return /[\u3400-\u9fff]/.test(content)
    ? `可以。请直接在对话框输入：\n\n\`安装 Skill frontend-design\`\n\n也支持 GitHub 上具体的 Skill 目录地址，或本地 Skill 文件夹的绝对路径。安装完成后，可在 Skills 页面查看，并通过 \`@名称\` 使用。\n\n安装由 MaterialsX 执行，无需管理员。仅提问不会触发安装；安装不会执行脚本或安装 Python/npm 依赖。未知名称请提供具体来源。`
    : `Yes. Send \`Install Skill frontend-design\` in the chat. You can also provide a GitHub Skill directory URL or an absolute local Skill folder path.\n\nMaterialsX handles installation without an administrator. Installed Skills appear in Skills and the @ list. A capability question does not install anything; installation does not execute scripts or install Python/npm dependencies. Unknown names need an exact source.\n\nCommand: \`${c.commands.en}\`.`;
}
