// Shared inputs for the existing UA.14 live evaluator; no alternate execution loop.
import {createHash} from 'node:crypto';
import type {CloudSelection} from '../../packages/pi-adapter/src/platform-session.js';
import {rootflowSourceText as dataText,repairPrompt} from './rootflow-fixtures.js';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
const skillText=`---\nname: coating-mass-balance-fixture\ndescription: Synthetic coating wet-mass scaling with exact solids accounting; not a validated formulation.\n---\nRead the approved recipe-source JSON through read_material_file. Preserve wet-mass basis. Scale every component to target wet mass. Sum solid mass using solidFraction, excluding volatile water. Write recipe.json with targetWetMassG, components (name,amountG,solidFraction), solidMassG, solidMassFraction and scientificStatus=needs_review. Write a brief Chinese README.md explaining this synthetic arithmetic fixture, not experimental performance. Read back both files and check the exact output. Do not invent densities, volume fractions, reflectance or real paper citations.\n`;
const dataAsset={id:'synthetic-coating-source',name:'recipe-source.json',text:dataText,sha256:sha(dataText)};
const skillAsset={id:'coating-mass-balance-fixture',name:'coating-mass-balance-fixture',text:skillText,sha256:sha(skillText)};
export type RootflowCase={id:string;prompt:string;selection:CloudSelection;kind:'advice'|'skill'|'repair'|'missing'|'science'|'proposals'|'inquiry'};
const proposalSkill=`---\nname: coating-proposal-fixture\ndescription: Three synthetic, source-linked coating proposals for host acceptance testing.\n---\nRead the approved synthetic recipe-source.json using read_material_file. Give exactly three distinct named suggestions, retaining all four source components and their original quantities/units. These are hypotheses, not validated recipes or performance. Write proposals.json with scientificStatus=needs_review, sourceSha256 equal to the approved file SHA, and proposals with name, components (name, originalAmountG, proposedAmountG), process (nonempty array of qualitative steps), assumptions (nonempty array) and evidenceType=synthetic_fixture. The consumer requires these exact key locations: {"scientificStatus":"needs_review","sourceSha256":"<actual approved SHA>","proposals":[{"name":"...","components":[{"name":"...","originalAmountG":0,"proposedAmountG":0}],"process":["..."],"assumptions":["..."],"evidenceType":"synthetic_fixture"}]}. Do not move sourceSha256 into a source object or evidenceType out of each proposal. Validate these keys and counts with actual file reads before completion. Use distinct component quantities across proposals, never claim invented source pages, density, cooling, execution or guaranteed optimality. Write a Chinese proposals.md explaining mechanisms, unknown densities/solids/film thickness, original versus proposed amounts, and suggested validation. Inspect both actual files before replying.\n`;
const proposalAsset={id:'coating-proposal-fixture',name:'coating-proposal-fixture',text:proposalSkill,sha256:sha(proposalSkill)};
export const rootflowCases:RootflowCase[]=[
  {id:'file-inquiry',kind:'inquiry',selection:{files:[],skills:[]},prompt:'How do I generate report.json in MaterialsX? Explain only. Do not execute commands or write files.'},
  {id:'skill-inquiry',kind:'inquiry',selection:{files:[],skills:[]},prompt:'你可以自己安装 Skill 吗？只需回答是否支持、如何操作以及安装的边界。本轮不要安装或下载。'},
  {id:'advice',kind:'advice',selection:{files:[],skills:[]},prompt:'如何设计水性辐射制冷涂料？我还没有确定应用基材、膜厚、成本和性能目标。请给出研究建议、影响因素和需要补充的条件，只给文字建议，不创建文件、不虚构实测性能或论文来源。'},
  {id:'advice-en',kind:'advice',selection:{files:[],skills:[]},prompt:'How can I design a waterborne radiative cooling coating for 95% reflectance? Advice only; do not simulate, create files, invent measurements or references. Treat 95% as a design target, not a measured result; discuss substrate, thickness, cost and unknown conditions.'},
  {id:'proposals',kind:'proposals',selection:{files:[dataAsset],skills:[proposalAsset]},prompt:'@coating-proposal-fixture 读取已批准的合成配方，根据它提出三个不同的配方工艺建议。保留来源原始用量，说明修改理由、未知条件与验证方式，输出 proposals.json 与中文 proposals.md，读回核对。只是假设，不要运行材料模拟或声称已验证性能。'},
  {id:'skill',kind:'skill',selection:{files:[dataAsset],skills:[skillAsset]},prompt:'@coating-mass-balance-fixture 根据已批准的合成 recipe-source.json，把湿配方等比例放大到 250 g。计算各组分原始湿用量、固体总质量和质量固含，按 Skill 生成 recipe.json 和中文 README.md，并读回检查。这是虚构测试数据，不需要模拟，不要声称是经过验证的制冷配方。'},
  {id:'repair',kind:'repair',selection:{files:[],skills:[]},prompt:repairPrompt},
  {id:'discovery-cn',kind:'missing',selection:{files:[dataAsset],skills:[]},prompt:'通过 find_tools 按“读取已选附件”发现实际工具，查看它的准确 Schema，再读取批准的合成 recipe-source.json。现有数据能否确定干膜颜填料体积分数？明确缺失条件，并给出质量固含。用中文回答，不假设密度，不把质量分数当体积分数，不写文件，不运行模拟。'},
  {id:'discovery-en',kind:'missing',selection:{files:[dataAsset],skills:[]},prompt:'Use find_tools with the purpose “read an attached file” to discover the actual tool and exact schema, then read the approved synthetic recipe-source.json. Can these data determine the dry pigment volume fraction? State the missing inputs and calculate mass solids fraction. Answer in Chinese, do not assume densities, do not write files or run simulations.'},
  {id:'missing',kind:'missing',selection:{files:[dataAsset],skills:[]},prompt:'读取批准的合成 recipe-source.json。没有提供任何组分密度，能否由现有数据确定干膜的颜填料体积分数？如果不可以，明确缺失条件；另外给出原配方的质量固含。不要假设密度，不要把质量分数当成体积分数，不需要输出文件。'},
  {id:'science',kind:'science',selection:{files:[],skills:[]},prompt:''},
];

export {dataAsset,skillAsset,proposalAsset};
