import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createPrivateKey} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {CatalogUpdateService,executionPins,signCatalog} from '../packages/atomistic/src/catalog-updates.js';import {AtomisticRuntime} from '../packages/atomistic/src/runtime.js';import {PotentialAnalysisService} from '../packages/atomistic/src/potential-workflow.js';
const root=process.cwd(),temp=await mkdtemp(join(tmpdir(),'mx-m611-runtime-')),state=join(temp,'state'),project=join(temp,'project');await mkdir(project);const updates=new CatalogUpdateService(root,state),runtime=new AtomisticRuntime(root,state,id=>id==='project'?project:null,id=>updates.assertUsable(id)),analysis=new PotentialAnalysisService(root,state,runtime);const id='sevennet-0-11jul2024';
const trust=JSON.parse(await readFile(join(root,'models/potentials/discovery-trust.json'),'utf8')),key=createPrivateKey(await readFile(join(root,'runtime/m6/catalog-publisher/signing-key.pem')));const now=new Date(),baseline=JSON.parse(await readFile(join(root,'models/potentials/catalog-release.json'),'utf8'));
const payload=(sequence:number,patch:Record<string,unknown>={})=>({...baseline.payload,sequence,issuedAt:now.toISOString(),expiresAt:new Date(now.getTime()+86400000).toISOString(),executionPins:executionPins(root),withdrawals:updates.status().withdrawals,...patch});
async function finish(runId:string){const end=Date.now()+180000;while(Date.now()<end){const r=runtime.get({projectId:'project',runId});if(['completed','failed','cancelled','interrupted'].includes(r.job.status))return r;await new Promise(r=>setTimeout(r,50));}throw Error('REAL_RUNTIME_TIMEOUT');}
try{
 await runtime.restore();await runtime.mountedPackages.importFile(id,join(root,'runtime/m6/m610-source/checkpoint.bin'));const r=JSON.parse(await readFile(join(root,'runtime/atomistic/macos-arm64/sevennet/RUNTIME.json'),'utf8'));const python=r.portable?join(root,'runtime/atomistic/macos-arm64/sevennet',r.python):r.python;
 execFileSync(python,['-I','-c',`from ase.io import read,write\na=read(${JSON.stringify(join(root,'samples/atomistic/si-diamond.POSCAR'))},format='vasp')\na.positions[0]+=[.15,-.06,.04]\nwrite(${JSON.stringify(join(project,'distorted.extxyz'))},a,format='extxyz',write_results=False)`],{timeout:30000});
 const structure=await runtime.importFile('project',join(project,'distorted.extxyz'));const first=await runtime.start({projectId:'project',structureId:structure.id,potentialId:id});const point=await finish(first.job.id);assert.equal(point.job.status,'completed');assert(Number.isFinite(point.result?.energyEv));
 const options={optimizer:'FIRE' as const,cellMode:'fixed' as const,cellConstraint:'none' as const,externalPressureGPa:null,maxSteps:100,fmaxEvPerAngstrom:.001};
 const active=await runtime.startRelaxation({projectId:'project',structureId:structure.id,potentialId:id,options});const deadline=Date.now()+60000;while(Date.now()<deadline&&!runtime.get({projectId:'project',runId:active.job.id}).relaxation?.progress)await new Promise(r=>setTimeout(r,20));assert(runtime.get({projectId:'project',runId:active.job.id}).relaxation?.progress);
 updates.accept(signCatalog(payload(2,{withdrawals:[{id,reason:{zh:'隔离验收用撤回，不改变正式目录',en:'Isolated acceptance withdrawal; production catalog unchanged'},evidenceUrl:'https://github.com/MDIL-SNU/SevenNet'}]}),trust.keys[0].id,key));
 assert(!runtime.isPotentialAllowed(id));await assert.rejects(runtime.start({projectId:'project',structureId:structure.id,potentialId:id}));await assert.rejects(runtime.mountedPackages.download(id),/POTENTIAL_WITHDRAWN/);await assert.rejects(runtime.mountedPackages.importFile(id,join(root,'runtime/m6/m610-source/checkpoint.bin')),/POTENTIAL_WITHDRAWN/);
 const request={projectId:'project',structureId:structure.id,prompt:'SevenNet analysis',locale:'en' as const,domain:'inorganic-crystals' as const,mode:'exploratory' as const,task:'singlepoint' as const,budget:{maxAtoms:256,maxSteps:1,maxWallSeconds:600,maxMemoryMiB:4096,maxOutputMiB:64,threads:4},maxDownloadBytes:20*1048576};const assessment=await analysis.assess(request);assert(!assessment.selection.candidates.some(c=>c.potentialId===id));
 const complete=await finish(active.job.id);assert.equal(complete.job.status,'completed',complete.job.error??'');assert(complete.result?.completedSteps);const comparison=await runtime.comparison({projectId:'project',runId:active.job.id});assert.equal(comparison.before.atoms.length,8);assert(Number.isFinite(comparison.summary.final.energyEv));
 const final=complete.artifacts.find(a=>a.relativePath.endsWith('/final.json'))!;const view=await runtime.view({kind:'artifact',projectId:'project',runId:complete.job.id,artifactId:final.id});assert.equal(view.structure.atoms.length,8);
 updates.accept(signCatalog(payload(3,{action:'rollback',rollbackOf:1}),trust.keys[0].id,key));assert.throws(()=>updates.assertUsable(id),/WITHDRAWN/);const restarted=new CatalogUpdateService(root,state);assert.throws(()=>restarted.assertUsable(id),/WITHDRAWN/);
 updates.accept(signCatalog(payload(4,{withdrawals:[...updates.status().withdrawals,{id:'mace-mp-0b3-medium',reason:{zh:'隔离验收用单权重撤回',en:'Isolated single-checkpoint withdrawal'},evidenceUrl:'https://github.com/ACEsuit/mace-foundations'}]}),trust.keys[0].id,key));assert(!runtime.isPotentialAllowed('mace-mp-0b3-medium'));assert(runtime.environmentReady('mace-mp-0b2-small'));
 const evidence=join(root,'runtime/m6/acceptance/m611');await mkdir(evidence,{recursive:true});await writeFile(join(evidence,'runtime.json'),JSON.stringify({stage:'M6.11',passed:true,platform:runtime.platform,realSevenNetSinglePoint:true,energyEv:point.result?.energyEv,withdrawalDuringActualFIRE:true,activeFrozenRunPreserved:true,newDownloadsAndImportsBlocked:true,newSelectionBlocked:true,sharedEnvironmentUnaffectedBySiblingWithdrawal:true,completedSteps:complete.result?.completedSteps,stopReason:complete.result?.stopReason,oldReportAnd3DPreserved:true,signedRollbackAndRestartPreserveWithdrawal:true,scientificQuality:'needs_review',supplierCalls:0,paymentCalls:0},null,2)+'\n');console.log('M6.11 real CPU withdrawal, active-run, report/3D and rollback acceptance passed');
}finally{analysis.dispose();runtime.dispose();updates.dispose();await rm(temp,{recursive:true,force:true});}
