import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {AtomisticRuntime} from '../packages/atomistic/src/runtime.js';import {PotentialDistributionService} from '../packages/atomistic/src/potential-distribution.js';import {inspectReproductionReceipt} from '../packages/atomistic/src/reproduction-receipt.js';import {canonical,hash} from '../packages/atomistic/src/discovery-io.js';
const root=process.cwd(),temp=await mkdtemp(join(tmpdir(),'mx-m612-real-')),state=join(temp,'state'),project=join(temp,'project');await mkdir(project);await mkdir(state);
let runtime=new AtomisticRuntime(root,state,id=>id==='project'?project:null);const service=new PotentialDistributionService(root,state,runtime.mountedPackages);
const sources=[['chgnet-r2scan','runtime/m6/extension-sources/chgnet-r2scan/checkpoint.bin'],['mace-mp-0b2-small','runtime/m6/m68-sources/mace-mp-0b2-small/checkpoint.bin'],['mace-mpa-0-medium','runtime/m6/m68-sources/mace-mpa-0-medium/checkpoint.bin'],['sevennet-0-11jul2024','runtime/m6/m610-source/checkpoint.bin']] as const;
const budget={maxAtoms:256,maxSteps:20,maxWallSeconds:180,maxMemoryMiB:4096,maxOutputMiB:64,threads:4};
async function finish(id:string){const until=Date.now()+200000;while(Date.now()<until){const run=runtime.get({projectId:'project',runId:id});if(['completed','failed','interrupted','cancelled'].includes(run.job.status)){assert.equal(run.job.status,'completed',run.job.error??'');return run;}await new Promise(r=>setTimeout(r,50));}throw Error('RUNTIME_TIMEOUT');}
try{
 // Exercise the original M6.6 single-file importer before the new collection path.
 await runtime.packages.importFile({potentialId:'chgnet-r2scan'},join(root,sources[0][1]));for(const [id,file] of sources.slice(1))await runtime.mountedPackages.importFile(id,join(root,file));
 const collection=await service.exportCollection(temp,sources.map(([id])=>id));const inventory=await service.inventory();await service.cleanup({ids:inventory.items.filter(i=>i.kind==='package').map(i=>i.id),inventorySha256:inventory.inventorySha256});assert.equal((await service.inventory()).items.filter(i=>i.kind==='package').length,0);assert.equal((await service.importCollection(collection.path)).imported.length,4);
 const structure=await runtime.importSample('project','si-diamond');const runs=[];let receipt;
 // This historical suite exercises the six crystalline interfaces; molecular acceptance is m613-runtime-test.
 const crystalStatuses=runtime.status().filter(s=>!['mace-mp-0b3-medium-d3-bj-pbe-si','ani-2x-ensemble','nep-si-2022-nep4-3body'].includes(s.potentialId));assert.equal(crystalStatuses.length,6);for(const status of crystalStatuses){assert(status.installed,status.error??'');const run=await finish((await runtime.start({projectId:'project',structureId:structure.id,potentialId:status.potentialId,budget})).job.id);assert(Number.isFinite(run.result?.energyEv));const r=await runtime.reproductionReceipt({projectId:'project',runId:run.job.id});assert(inspectReproductionReceipt(root,r).compatible);assert(r.payload.environment.sourceRevision);runs.push({potentialId:status.potentialId,task:'singlepoint',energyEv:run.result!.energyEv,artifacts:run.artifacts.length,runId:run.job.id});if(status.potentialId==='sevennet-0-11jul2024')receipt=r;console.log('Real CPU single point and receipt: '+status.potentialId);}
 const options={optimizer:'FIRE',cellMode:'fixed',cellConstraint:'none',externalPressureGPa:null,maxSteps:8,fmaxEvPerAngstrom:.05};const relax=await finish((await runtime.startRelaxation({projectId:'project',structureId:structure.id,potentialId:'sevennet-0-11jul2024',options,budget})).job.id);const rr=await runtime.reproductionReceipt({projectId:'project',runId:relax.job.id});assert(inspectReproductionReceipt(root,rr).compatible);assert(rr.payload.environment.registeredArtifact);
 const mdOptions={ensemble:'nve',steps:4,timestepFs:.5,temperatureK:300,sampleEvery:2,seed:20261002,frictionInverseFs:null};const md=await finish((await runtime.startMD({projectId:'project',structureId:structure.id,potentialId:'chgnet-0.3.0',mdOptions,budget})).job.id);const mr=await runtime.reproductionReceipt({projectId:'project',runId:md.job.id});assert(inspectReproductionReceipt(root,mr).compatible);assert.equal(mr.payload.taskOptions?.seed,20261002);
 const bad=structuredClone(receipt!);bad.payload.result.energyEv+=1;assert.throws(()=>inspectReproductionReceipt(root,bad),/CHANGED/);const forged=structuredClone(receipt!);forged.payload.structure.atoms[0]!.position[0]+=1;forged.payloadSha256=hash(canonical(forged.payload));assert.throws(()=>inspectReproductionReceipt(root,forged),/CHANGED/);
 const cleanup=await service.inventory();await service.cleanup({ids:cleanup.items.filter(i=>i.kind==='package').map(i=>i.id),inventorySha256:cleanup.inventorySha256});const saved=await runtime.reproductionReceipt({projectId:'project',runId:receipt!.payload.runId});assert.equal(saved.payloadSha256,receipt!.payloadSha256);runtime.dispose();runtime=new AtomisticRuntime(root,state,id=>id==='project'?project:null);await runtime.restore();assert.equal(runtime.list('project').filter(r=>r.job.status==='completed').length,8);const after=await runtime.reproductionReceipt({projectId:'project',runId:relax.job.id});assert(inspectReproductionReceipt(root,after).compatible);const final=relax.artifacts.find(a=>a.relativePath.endsWith('/final.json'))!;assert.equal((await runtime.view({kind:'artifact',projectId:'project',runId:relax.job.id,artifactId:final.id})).structure.atoms.length,8);
 const output=join(root,'runtime/m6/acceptance/m612');await mkdir(output,{recursive:true});await writeFile(join(output,'runtime.json'),JSON.stringify({stage:'M6.12',passed:true,platform:runtime.platform,actualRuntime:true,oldM66Importer:true,offlineCollectionRoundTrip:true,checkpoints:runs,sevenNetRelaxation:{stopReason:relax.result!.stopReason,steps:relax.result!.completedSteps},chgnetMD:{steps:md.result!.completedSteps,seed:20261002,verdict:md.md!.summary!.nveVerdict},receiptAfterUninstall:true,receiptAfterRestart:true,real3DAfterUninstall:true,tamperedReceiptRejected:true,scientificQuality:'needs_review',weightsDownloaded:0,supplierCalls:0,paymentCalls:0},null,2)+'\n');console.log('M6.12 actual six-checkpoint CPU, offline collection, relaxation, MD, receipt and restart acceptance passed');
}finally{runtime.dispose();await rm(temp,{recursive:true,force:true});}
