import assert from 'node:assert/strict';import { spawn } from 'node:child_process';import { mkdtemp,mkdir,readFile,writeFile,rm } from 'node:fs/promises';import { existsSync } from 'node:fs';import { tmpdir } from 'node:os';import { join,resolve,dirname } from 'node:path';import { randomUUID } from 'node:crypto';import { createServer } from 'node:net';
import { WorkspaceStore } from '../apps/desktop/main/store.js';
import { verifyOfflineBundle } from '../packages/atomistic/src/offline-bundle.js';import { AtomisticRuntime } from '../packages/atomistic/src/runtime.js';
const arg=process.argv.indexOf('--resources');const resources=arg>=0?resolve(process.argv[arg+1]!):process.platform==='darwin'?resolve('runtime/m6/m612-package/mac-arm64/MaterialsX.app/Contents/Resources'):resolve('runtime/m6/m612-package/win-unpacked/resources');
const temp=await mkdtemp(join(tmpdir(),'mx-m612-offline-')),project=join(temp,'project');await mkdir(project);const runtime=new AtomisticRuntime(resources,join(temp,'state'),id=>id==='project'?project:null);let appChild:ReturnType<typeof spawn>|undefined,ws:WebSocket|undefined;
async function freePort(){const s=createServer();await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));const port=(s.address() as {port:number}).port;await new Promise<void>(r=>s.close(()=>r()));return port;}
try{
 const verified=await verifyOfflineBundle(resources);assert.equal(verified.version,'m6.12-v1');await runtime.restore();assert(runtime.status().every(s=>s.installed&&s.portable));const structure=await runtime.importSample('project','si-diamond');const runs=[];
 for(const potentialId of ['mace-mp-0b3-medium','chgnet-0.3.0'] as const){const q=await runtime.start({projectId:'project',structureId:structure.id,potentialId});let result;for(let i=0;i<1200;i++){result=runtime.get({projectId:'project',runId:q.job.id});if(['completed','failed'].includes(result.job.status))break;await new Promise(r=>setTimeout(r,100));}assert.equal(result?.job.status,'completed',result?.job.error??'');runs.push(result!);}
 // macOS OS-level outbound denial, in addition to the worker's permanent Python socket guard.
 let osNetworkDenied=false;if(process.platform==='darwin'){assert(existsSync('/usr/bin/sandbox-exec'));for(const run of runs.slice(0,2)){const id=randomUUID(),dir=join(temp,id);await mkdir(dir);await writeFile(join(dir,'structure.json'),JSON.stringify(run.structure,null,2)+'\n');const family=run.plan.potentialId.startsWith('mace')?'mace':'chgnet',base=join(resources,'atomistic-runtime',family),installation=JSON.parse(await readFile(join(base,'RUNTIME.json'),'utf8'));const child=spawn('/usr/bin/sandbox-exec',['-p','(version 1) (allow default) (deny network*)',join(base,installation.python),'-I',join(resources,'atomistic/worker.py')],{cwd:dir,stdio:['pipe','pipe','pipe'],env:{PATH:process.env.PATH??'',PYTHONDONTWRITEBYTECODE:'1',MPLCONFIGDIR:dir,OMP_NUM_THREADS:'4',OPENBLAS_NUM_THREADS:'4'}});let output='';child.stdout.on('data',b=>output+=b.toString());child.stderr.resume();child.stdin.end(JSON.stringify({operation:'singlepoint',root:resources,runId:id,plan:{...run.plan,id},directory:dir,weight:join(base,'checkpoint.bin'),dependencyLockSha256:installation.dependencyLockSha256})+'\n');const timeout=setTimeout(()=>child.kill('SIGKILL'),60000);const code=await new Promise<number|null>((resolve,reject)=>{child.once('error',reject);child.once('close',resolve)});clearTimeout(timeout);assert.equal(code,0,'OS network-denied worker failed');assert(output.split('\n').some(l=>{try{return JSON.parse(l).event==='completed';}catch{return false;}}));}osNetworkDenied=true;}
 const profile=join(temp,'packaged-ui-state');await mkdir(profile);const store=new WorkspaceStore(join(profile,'materialsx.sqlite'));const packagedProject=store.createProject(project);store.close();
 const binary=process.platform==='darwin'?join(dirname(resources),'MacOS/MaterialsX'):join(dirname(resources),'MaterialsX.exe');const port=await freePort();appChild=spawn(binary,[`--user-data-dir=${join(temp,'packaged-ui-state')}`,`--remote-debugging-port=${port}`],{env:{...process.env,MATERIALSX_IDENTITY_URL:'http://127.0.0.1:1',MATERIALSX_RENDERER_URL:'',MATERIALSX_DISCOVERY_AUTOSYNC:'0',ROOTFLOWAI_API_KEY:''},stdio:'ignore'});
 let debuggerUrl:string|undefined;for(let i=0;i<150;i++){if(appChild.exitCode!==null)throw Error('PACKAGED_APP_EXITED');try{const pages=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json() as Array<{type:string;webSocketDebuggerUrl:string}>;debuggerUrl=pages.find(p=>p.type==='page')?.webSocketDebuggerUrl;if(debuggerUrl)break;}catch{}await new Promise(r=>setTimeout(r,100));}assert(debuggerUrl);ws=new WebSocket(debuggerUrl);await new Promise<void>((resolve,reject)=>{ws!.addEventListener('open',()=>resolve());ws!.addEventListener('error',reject);});let seq=0;const pending=new Map<number,{resolve:(v:any)=>void;reject:(e:unknown)=>void}>();ws.addEventListener('message',event=>{const message=JSON.parse(String(event.data));if(message.id){const q=pending.get(message.id);pending.delete(message.id);if(message.error)q?.reject(Error('CDP_COMMAND_FAILED'));else q?.resolve(message.result);}});const send=(method:string,params:unknown={})=>new Promise<any>((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws!.send(JSON.stringify({id,method,params}));});await send('Network.enable');await send('Network.setBlockedURLs',{urls:['http://*','https://*']});
 const evaluate=async(expression:string)=>{const value=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(value.exceptionDetails)throw Error('PACKAGED_RENDERER_EVALUATION_FAILED');return value.result.value;};for(let i=0;i<100;i++){if(await evaluate('typeof window.materialsx!=="undefined"'))break;await new Promise(r=>setTimeout(r,100));}
 const bootstrap=await evaluate('window.materialsx.bootstrap()');assert.equal(bootstrap.projects.length,1,'Packaged UI must use isolated userData');assert.equal(bootstrap.projects[0].id,packagedProject.id);assert.equal(bootstrap.skills.length,93);const statuses=await evaluate('window.materialsx.getAtomisticRuntime()');assert(statuses.every((s:any)=>s.installed&&s.portable));assert(await evaluate('document.body.innerText.includes("MaterialsX")'));const imported=await evaluate(`window.materialsx.importAtomicSample({projectId:${JSON.stringify(packagedProject.id)},sampleId:"si-diamond"})`);const packagedIpcRuns=[];
 for(const potentialId of ['mace-mp-0b3-medium','chgnet-0.3.0','chgnet-r2scan','mace-mp-0b2-small','mace-mpa-0-medium','sevennet-0-11jul2024']){const j=await evaluate(`window.materialsx.startAtomisticRun(${JSON.stringify({projectId:packagedProject.id,structureId:imported.id,potentialId})})`);let final;for(let i=0;i<1200;i++){final=await evaluate(`window.materialsx.getAtomisticRun(${JSON.stringify(packagedProject.id)},${JSON.stringify(j.job.id)})`);if(['completed','failed'].includes(final.job.status))break;await new Promise(r=>setTimeout(r,100));}assert.equal(final.job.status,'completed',final.job.error??'');packagedIpcRuns.push({potentialId,energyEv:final.result.energyEv,quality:final.result.quality});}
 const screenshot=await send('Page.captureScreenshot',{format:'png'});const out=resolve('runtime/m6/acceptance/m612');await mkdir(out,{recursive:true});await writeFile(join(out,'packaged-offline.png'),Buffer.from(screenshot.data,'base64'));
 const receipt={stage:'M6.12',passed:true,platform:runtime.platform,resourcesVerified:verified,actualPackagedBinaryLaunched:true,isolatedUserData:true,packagedDefaultSkills:93,allSixPortableCheckpointInterfaces:true,actualPackagedResourceCalculations:runs.map(r=>({potentialId:r.plan.potentialId,energyEv:r.result!.energyEv,weightSha256:r.plan.potentialSha256})),actualPackagedMainPreloadIpcCalculations:packagedIpcRuns,noGlobalPythonRequired:true,pythonWorkerNetworkDisabled:true,osNetworkDeniedForBothCores:osNetworkDenied,rendererHttpBlocked:true,scope:'Packaged app launch/default resources plus actual bundled portable Python CPU calculations; macOS core workers also run under sandbox-exec network denial. Unsigned unpacked app, not DMG installation/notarization.',signedRelease:false,fullInstallerTested:false,windowsInstallationTested:false,scientificQuality:'needs_review',realProviderCalls:0,paymentCalls:0};await writeFile(join(out,'offline-package.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
}finally{ws?.close();if(appChild&&appChild.exitCode===null){const closed=new Promise<void>(r=>appChild!.once('close',()=>r()));appChild.kill('SIGTERM');const force=setTimeout(()=>appChild?.kill('SIGKILL'),5000);await closed;clearTimeout(force);}runtime.dispose();await rm(temp,{recursive:true,force:true});}
