import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {AtomisticRuntime} from '../packages/atomistic/src/runtime.js';import {PotentialAnalysisService} from '../packages/atomistic/src/potential-workflow.js';import {molecularExpansion} from '../packages/atomistic/src/molecular-expansion.js';import {PotentialDistributionService} from '../packages/atomistic/src/potential-distribution.js';import {PotentialPackageManager} from '../packages/atomistic/src/package-manager.js';import {inspectReproductionReceipt} from '../packages/atomistic/src/reproduction-receipt.js';import {createScienceBridge} from '../packages/pi-adapter/src/science-bridge.js';
const root=process.cwd(),temp=await mkdtemp(join(tmpdir(),'mx-m613-')),project=join(temp,'project'),state=join(temp,'state');await mkdir(project);const runtime=new AtomisticRuntime(root,state,id=>id==='project'?project:null),service=new PotentialAnalysisService(root,state,runtime),id='ani-2x-ensemble';const rows:unknown[]=[],checks:string[]=[];
const options={optimizer:'FIRE' as const,cellMode:'fixed' as const,cellConstraint:'none' as const,externalPressureGPa:null,maxSteps:100,fmaxEvPerAngstrom:.05};
async function finish(runId:string){const end=Date.now()+600000;while(Date.now()<end){const s=runtime.get({projectId:'project',runId});if(['completed','failed','cancelled','interrupted'].includes(s.job.status)){assert.equal(s.job.status,'completed',s.job.error??'');return s;}await new Promise(r=>setTimeout(r,100));}throw Error('TIMEOUT');}
try{
 await runtime.restore();assert(runtime.environmentReady(id));if(process.argv.includes('--download')){await runtime.mountedPackages.download(id);checks.push('Cold download through the actual approved Hugging Face redirect allowlist passes exact byte count and SHA-256.');}else await runtime.mountedPackages.importFile(id,join(root,'runtime/m6/m613-source/checkpoint.bin'));
 const plain=await runtime.importSample('project','water');assert.equal(plain.charge,null);let a=await runtime.assess({projectId:'project',structureId:plain.id,domain:'molecules',mode:'exploratory',task:'singlepoint'});assert(a.selection.exclusions.find(c=>c.potentialId===id)?.reasonCodes.includes('ELECTRONIC_STATE_REQUIRED'));checks.push('Plain XYZ electronic state is unknown and blocked, never silently neutralized.');
 const water=await runtime.annotateElectronicState({projectId:'project',structureId:plain.id,charge:0,spinMultiplicity:1,addDisplayBox:true});assert.notEqual(water.id,plain.id);assert.equal(runtime.inspect({projectId:'project',structureId:plain.id}).charge,null);await runtime.view({kind:'import',projectId:'project',structureId:water.id});
 const ethanol=await runtime.importSample('project','ethanol-neutral');assert.equal(ethanol.charge,0);assert.equal(ethanol.spinMultiplicity,1);
 for(const s of [water,ethanol]){const run=await runtime.start({projectId:'project',structureId:s.id,potentialId:id});const done=await finish(run.job.id);assert.equal(done.result!.stress,null);assert(Number.isFinite(done.result!.energyEv));assert.equal(done.result!.forcesEvPerAngstrom.length,s.atoms.length);const receipt=await runtime.reproductionReceipt({projectId:'project',runId:done.job.id});assert(receipt.payload.environment.registeredArtifact);assert(inspectReproductionReceipt(root,receipt).compatible);rows.push({task:'singlepoint',atoms:s.atoms.length,result:done.result,environment:JSON.parse(await readFile(join(done.outputDirectory,'environment.json'),'utf8'))});}
 const relaxed=await finish((await runtime.startRelaxation({projectId:'project',structureId:water.id,potentialId:id,options})).job.id);assert.equal(relaxed.result!.stopReason,'converged');assert(relaxed.relaxation!.summary!.final.maxForceEvPerAngstrom<.05);assert.equal(relaxed.result!.stress,null);await runtime.comparison({projectId:'project',runId:relaxed.job.id});const final=JSON.parse(await readFile(join(relaxed.outputDirectory,'final.json'),'utf8'));assert.equal(final.charge,0);assert.equal(final.spinMultiplicity,1);assert.deepEqual(final.pbc,[false,false,false]);const exported=await runtime.importFile('project',join(relaxed.outputDirectory,'final.extxyz'));assert.equal(exported.charge,0);assert.equal(exported.spinMultiplicity,1);rows.push({task:'FIRE',result:relaxed.result,summary:relaxed.relaxation!.summary});checks.push('Real isolated water/ethanol single points, null stress, actual water FIRE convergence, preserved charge/spin export, comparison and compatible reproduction receipts.');
 const capped=await finish((await runtime.startRelaxation({projectId:'project',structureId:water.id,potentialId:id,options:{...options,maxSteps:1,fmaxEvPerAngstrom:.001}})).job.id);assert.equal(capped.result!.stopReason,'max_steps');
 for(const patch of [{domain:'inorganic-crystals'},{mode:'production'},{interaction:'long-range-required'},{task:'md'}]){a=await runtime.assess({projectId:'project',structureId:water.id,domain:'molecules',mode:'exploratory',task:'singlepoint',...patch});assert(!a.selection.candidates.some(c=>c.potentialId===id));}
 for(const [charge,spin] of [[1,1],[0,3]]){const s=await runtime.annotateElectronicState({projectId:'project',structureId:plain.id,charge:charge!,spinMultiplicity:spin!,addDisplayBox:true});a=await runtime.assess({projectId:'project',structureId:s.id,domain:'molecules',mode:'exploratory',task:'singlepoint'});assert(!a.selection.candidates.some(c=>c.potentialId===id));}
 const silicon=await runtime.importSample('project','si-diamond');a=await runtime.assess({projectId:'project',structureId:silicon.id,domain:'molecules',mode:'exploratory',task:'singlepoint'});assert(!a.selection.candidates.some(c=>c.potentialId===id));await assert.rejects(runtime.startRelaxation({projectId:'project',structureId:water.id,potentialId:id,options:{...options,cellMode:'variable',cellConstraint:'full',externalPressureGPa:0}}),/MOLECULAR_FIXED_BOX_REQUIRED/);checks.push('Ions, triplets, production, long range, molecular MD, periodic silicon and variable-cell molecular relaxation excluded; step cap never misreported as convergence.');
 const bridge=createScienceBridge(runtime,'project');const selection=await bridge.execute({action:'select',targetId:ethanol.id,secondaryId:'singlepoint',potentialId:null,domain:'molecules',mode:'exploratory',interaction:'short-range',evidenceIds:[]}) as {id:string;selection:{candidates:{potentialId:string;evidenceIds:string[]}[]}};assert(selection.selection.candidates.some(c=>c.potentialId===id));
 const picked=selection.selection.candidates.find(c=>c.potentialId===id)!;const dispatched=await bridge.execute({action:'singlepoint',targetId:selection.id,secondaryId:null,potentialId:id,domain:'molecules',mode:'exploratory',evidenceIds:picked.evidenceIds}) as {runId:string};await finish(dispatched.runId);assert.equal(bridge.completedSummary(true)[0]!.potentialId,id);
 const locked=createScienceBridge(runtime,'project',{projectId:'project',conversationId:'conversation',structureId:ethanol.id,domain:'molecules',mode:'exploratory',permission:'singlepoint',interaction:'long-range-required'});const excluded=await locked.execute({action:'select',targetId:ethanol.id,secondaryId:'singlepoint',potentialId:null,domain:'molecules',mode:'exploratory',interaction:'short-range',evidenceIds:[]}) as {selection:{candidates:{potentialId:string}[]}};assert(!excluded.selection.candidates.some(c=>c.potentialId===id));
 const distribution=new PotentialDistributionService(root,state,runtime.mountedPackages);const exportedCollection=await distribution.exportCollection(temp,[id]);const another=join(temp,'import-state');await mkdir(another);const manager=new PotentialPackageManager(root,another),importer=new PotentialDistributionService(root,another,manager);assert.deepEqual((await importer.importCollection(exportedCollection.path)).imported,[id]);assert.equal((await manager.status()).find(s=>s.potentialId===id)!.state,'installed');checks.push('Actual local science tool starts ANI single point; frozen long-range scope cannot be downgraded; real 54,982,957-byte weight collection exports and imports offline.');
 const request={projectId:'project',structureId:ethanol.id,prompt:'中性单重态乙醇单点',locale:'zh',domain:'molecules',mode:'exploratory',task:'singlepoint',interaction:'short-range',budget:{maxAtoms:128,maxSteps:1,maxWallSeconds:600,maxMemoryMiB:4096,maxOutputMiB:64,threads:4},maxDownloadBytes:0};const assessed=await service.assess(request),candidate=assessed.selection.candidates.find(c=>c.potentialId===id)!;assert(candidate);const w=await service.freeze('project',{assessmentId:assessed.id,potentialId:id,evidenceIds:candidate.evidenceIds,reason:'Reviewed isolated neutral singlet capability matches ethanol'});service.approve('project',w.id,w.plan.planSha256);for(let n=0;n<1800;n++){const v=service.get('project',w.id);if(['completed','failed'].includes(v.state)){assert.equal(v.state,'completed',v.error??'');break;}await new Promise(r=>setTimeout(r,100));}assert.equal(service.get('project',w.id).state,'completed');
 const long=await service.assess({...request,prompt:'long-range electrostatics are required'});assert(!long.selection.candidates.some(c=>c.potentialId===id));checks.push('Local science dispatcher and full frozen automatic analysis workflow execute the molecular adapter; long-range intent cannot downgrade to short-range.');
 const restored=new AtomisticRuntime(root,state,k=>k==='project'?project:null);await restored.restore();assert.equal(restored.get({projectId:'project',runId:relaxed.job.id}).job.status,'completed');await restored.comparison({projectId:'project',runId:relaxed.job.id});restored.dispose();await writeFile(join(relaxed.outputDirectory,'report.zh.md'),'altered');await assert.rejects(runtime.reproductionReceipt({projectId:'project',runId:relaxed.job.id}),/ARTIFACT_CHANGED/);
 const output={stage:'M6.13',passed:true,platform:runtime.platform,device:'cpu',model:id,weight:molecularExpansion(root)!.entry,checks,rows,scientificQuality:'needs_review',independentDFTAccuracyValidated:false,modelAPICalls:0,paymentCalls:0};await mkdir('docs/m6/evidence',{recursive:true});await writeFile('docs/m6/evidence/m613-molecular-cpu.json',JSON.stringify(output,null,2)+'\n');console.log('M6.13 real molecular CPU acceptance passed');
}finally{service.dispose();runtime.dispose();await rm(temp,{recursive:true,force:true});}
