import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {AtomisticRuntime} from '../packages/atomistic/src/runtime.js';import {PotentialAnalysisService} from '../packages/atomistic/src/potential-workflow.js';import {PotentialDistributionService} from '../packages/atomistic/src/potential-distribution.js';import {PotentialPackageManager} from '../packages/atomistic/src/package-manager.js';import {physicsExpansion} from '../packages/atomistic/src/physics-expansion.js';import {createScienceBridge} from '../packages/pi-adapter/src/science-bridge.js';import {inspectReproductionReceipt} from '../packages/atomistic/src/reproduction-receipt.js';
const root=process.cwd(),temp=await mkdtemp(join(tmpdir(),'mx-m615-')),state=join(temp,'state'),project=join(temp,'project');await mkdir(project);const runtime=new AtomisticRuntime(root,state,x=>x==='project'?project:null),service=new PotentialAnalysisService(root,state,runtime),id='mace-mp-0b3-medium-d3-bj-pbe-si',m=physicsExpansion(root)!;const checks:string[]=[],rows:unknown[]=[];
const options={optimizer:'FIRE' as const,cellMode:'fixed' as const,cellConstraint:'none' as const,externalPressureGPa:null,maxSteps:100,fmaxEvPerAngstrom:.05};
async function finish(runId:string){for(let n=0;n<3000;n++){const q=runtime.get({projectId:'project',runId});if(['completed','failed','cancelled','interrupted'].includes(q.job.status)){assert.equal(q.job.status,'completed',q.job.error??'');return q;}await new Promise(r=>setTimeout(r,100));}throw Error('TEST_TIMEOUT');}
try{
 await runtime.restore();assert(runtime.environmentReady(id));await runtime.mountedPackages.download(id);assert.equal(runtime.mountedPackages.weight(id),join(root,'runtime/atomistic/macos-arm64/mace/checkpoint.bin'));checks.push('Existing pinned MACE baseline reused; no new weights downloaded or duplicated.');
 const sample=await runtime.importSample('project','si-diamond');const file=join(temp,'perturbed.extxyz'),cell=sample.cell!.flat().join(' ');const positions=sample.atoms.map((a,i)=>a.position.map((v,k)=>v+(i===0?[.03,-.02,.01][k]!:0)));await writeFile(file,`${sample.atoms.length}\nLattice="${cell}" Properties=species:S:1:pos:R:3 pbc="T T T"\n`+positions.map(p=>'Si '+p.join(' ')).join('\n')+'\n');const perturbed=await runtime.importFile('project',file);
 const single=await finish((await runtime.start({projectId:'project',structureId:perturbed.id,potentialId:id})).job.id);assert(single.result!.stress?.values.every(Number.isFinite));assert.equal(single.result!.forcesEvPerAngstrom.length,8);const engine=JSON.parse(await readFile(join(single.outputDirectory,'native-engine.json'),'utf8'));assert.equal(engine.sourceRevision,m.engine.revision);const components=await runtime.composition({projectId:'project',runId:single.job.id});assert(components.correction.energyEv<0);assert.equal(components.total.energyEv,single.result!.energyEv);assert.equal(single.plan.dtype,'float64');const receipt=await runtime.reproductionReceipt({projectId:'project',runId:single.job.id});assert(inspectReproductionReceipt(root,receipt).compatible);assert(receipt.payload.environment.registeredArtifact);assert.match(await readFile(join(single.outputDirectory,'report.zh.md'),'utf8'),/硅/);rows.push({task:'singlepoint',result:single.result,engine});
 const relax=await finish((await runtime.startRelaxation({projectId:'project',structureId:perturbed.id,potentialId:id,options})).job.id);assert.equal(relax.result!.stopReason,'converged');assert(relax.relaxation!.summary!.final.maxForceEvPerAngstrom<.05);assert(relax.result!.completedSteps!>0);await runtime.comparison({projectId:'project',runId:relax.job.id});rows.push({task:'FIRE',result:relax.result,summary:relax.relaxation!.summary});
 const capped=await finish((await runtime.startRelaxation({projectId:'project',structureId:perturbed.id,potentialId:id,options:{...options,maxSteps:1,fmaxEvPerAngstrom:.001}})).job.id);assert.equal(capped.result!.stopReason,'max_steps');
 await assert.rejects(runtime.startRelaxation({projectId:'project',structureId:sample.id,potentialId:id,options:{...options,cellMode:'variable',cellConstraint:'full',externalPressureGPa:0}}),/COMPOSITION_FIXED_CELL_REQUIRED/);
 for(const patch of [{mode:'production'},{interaction:'long-range-required'},{interaction:'spin-required'},{interaction:'field-required'},{interaction:'delta-required'},{interaction:'multi-head-required'},{task:'md'}]){const a=await runtime.assess({projectId:'project',structureId:sample.id,domain:'inorganic-crystals',mode:'exploratory',task:'singlepoint',...patch});assert(!a.selection.candidates.some(c=>c.potentialId===id));}
 const carbon=await runtime.importSample('project','nacl-rocksalt');const excluded=await runtime.assess({projectId:'project',structureId:carbon.id,domain:'inorganic-crystals',mode:'exploratory',task:'singlepoint'});assert(!excluded.selection.candidates.some(c=>c.potentialId===id));checks.push('Actual composed SP and converged perturbed-silicon FIRE; capped run is nonconverged; wrong elements, MD, long range, production and variable cell rejected.');
 const bridge=createScienceBridge(runtime,'project'),args={action:'select',targetId:sample.id,secondaryId:'singlepoint',potentialId:null,domain:'inorganic-crystals',mode:'exploratory',interaction:'dispersion-required',evidenceIds:[]};const a=await bridge.execute(args) as {id:string;selection:{candidates:{potentialId:string;evidenceIds:string[]}[]}};const c=a.selection.candidates.find(c=>c.potentialId===id)!;assert(c);const j=await bridge.execute({...args,action:'singlepoint',targetId:a.id,secondaryId:null,potentialId:id,evidenceIds:c.evidenceIds}) as {runId:string};await finish(j.runId);assert.equal(bridge.completedSummary(true)[0]!.potentialId,id);
 const q={projectId:'project',structureId:perturbed.id,prompt:'纯硅 MACE + D3 色散修正固定晶胞优化',locale:'zh',domain:'inorganic-crystals',mode:'exploratory',task:'relaxation',options,budget:{maxAtoms:256,maxSteps:100,maxWallSeconds:300,maxMemoryMiB:4096,maxOutputMiB:64,threads:4},maxDownloadBytes:0};const assessed=await service.assess(q),candidate=assessed.selection.candidates.find(c=>c.potentialId===id)!;assert(candidate);assert.equal(assessed.selection.candidates.length,1);const w=await service.freeze('project',{assessmentId:assessed.id,potentialId:id,evidenceIds:candidate.evidenceIds,reason:'Audited additive PBE-D3(BJ) profile matches the required dispersion, pure Si and fixed cell.'});service.approve('project',w.id,w.plan.planSha256);for(let n=0;n<3000;n++){const f=service.get('project',w.id);if(['completed','failed'].includes(f.state)){assert.equal(f.state,'completed',f.error??'');break;}await new Promise(r=>setTimeout(r,100));}assert.equal(service.get('project',w.id).state,'completed');checks.push('Actual local Pi science tool dispatch and full frozen automatic analysis with bilingual real reports and final structure.');
 const distribution=new PotentialDistributionService(root,state,runtime.mountedPackages),collection=await distribution.exportCollection(temp,[id]),other=join(temp,'other');await mkdir(other);const importer=new PotentialDistributionService(root,other,new PotentialPackageManager(root,other));assert.deepEqual((await importer.importCollection(collection.path)).imported,[id]);
 const restored=new AtomisticRuntime(root,state,x=>x==='project'?project:null);await restored.restore();await restored.comparison({projectId:'project',runId:relax.job.id});await restored.composition({projectId:'project',runId:relax.job.id});restored.dispose();await writeFile(join(relax.outputDirectory,'composition.json'),'changed');await assert.rejects(runtime.composition({projectId:'project',runId:relax.job.id}),/ARTIFACT_CHANGED/);checks.push('Shared-baseline collection roundtrip, source-bound reproduction receipt, restart/3D recovery and tampered artifact rejection.');
 const out={stage:'M6.15',passed:true,platform:runtime.platform,model:id,package:m.entry,checks,rows,scientificQuality:'needs_review',independentDFTAccuracyValidated:false,newPythonEnvironment:false,realProviderCalls:0,paymentCalls:0};await mkdir('docs/m6/evidence',{recursive:true});await writeFile('docs/m6/evidence/m615-composed-cpu.json',JSON.stringify(out,null,2)+'\n');console.log('M6.15 composed CPU engineering acceptance passed');
}finally{service.dispose();runtime.dispose();await rm(temp,{recursive:true,force:true});}
