import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,rm,copyFile} from 'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{createHash}from'node:crypto';
import {AtomisticRuntime} from '../packages/atomistic/src/runtime.js';
const root=process.cwd(),temp=await mkdtemp(join(tmpdir(),'mx-m63-')),project=join(temp,'project'),state=join(temp,'state');await mkdir(project);
const runtime=new AtomisticRuntime(root,state,id=>id==='project'?project:null);await runtime.restore();
const receiptDir=resolve('runtime/m6/acceptance/m63');await mkdir(receiptDir,{recursive:true});
const sha=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
const checks:string[]=[],runs:unknown[]=[];
async function finish(runId:string){const deadline=Date.now()+600_000;while(Date.now()<deadline){const r=runtime.get({projectId:'project',runId});if(['completed','failed','cancelled','interrupted'].includes(r.job.status))return r;await new Promise(r=>setTimeout(r,100));}throw Error('Acceptance timeout');}
const fixed={optimizer:'FIRE',cellMode:'fixed',cellConstraint:'none',externalPressureGPa:null,maxSteps:100,fmaxEvPerAngstrom:.03} as const;
try{
 const {execFileSync}=await import('node:child_process');const profile=JSON.parse(await readFile(join(root,`runtime/atomistic/${runtime.platform}/chgnet/RUNTIME.json`),'utf8')) as {portable:boolean;python:string};const python=profile.portable?join(root,`runtime/atomistic/${runtime.platform}/chgnet`,profile.python):profile.python;
 execFileSync(python,['-c',`from ase.io import read,write\na=read(${JSON.stringify(join(root,'samples/atomistic/si-diamond.POSCAR'))},format='vasp')\na.positions[0]+=[.15,-.06,.04]\nwrite(${JSON.stringify(join(project,'perturbed.extxyz'))},a,format='extxyz',write_results=False)`],{timeout:30_000});
 const input=join(project,'perturbed.extxyz'),before=sha(await readFile(input)),s=await runtime.importFile('project',input);
 const request={projectId:'project',structureId:s.id,potentialId:'chgnet-0.3.0',options:fixed};
 await assert.rejects(runtime.startRelaxation({...request,options:{...fixed,cellMode:'variable'}}));
 await assert.rejects(runtime.startRelaxation({...request,budget:{maxAtoms:256,maxSteps:1,maxWallSeconds:600,maxMemoryMiB:4096,maxOutputMiB:64,threads:4}}),/STEP_BUDGET/);
 for(const potentialId of ['chgnet-0.3.0','mace-mp-0b3-medium'] as const){
  const job=await runtime.startRelaxation({...request,potentialId});const r=await finish(job.job.id);assert.equal(r.job.status,'completed',r.job.error??'result missing');assert.equal(r.result?.stopReason,'converged');assert.equal(r.result?.quality,'needs_review');assert(r.result.completedSteps>0);
  const comparison=await runtime.comparison({projectId:'project',runId:r.job.id});assert.deepEqual(comparison.after.cell,comparison.before.cell);assert(comparison.summary.final.energyEv<comparison.summary.initial.energyEv);assert(comparison.summary.final.maxForceEvPerAngstrom<.03);assert.equal(comparison.history.length,r.result.completedSteps+1);
  const final=r.artifacts.find(a=>a.relativePath.endsWith('/final.json'))!;const view=await runtime.view({kind:'artifact',projectId:'project',runId:r.job.id,artifactId:final.id});assert.equal(view.structure.id,comparison.after.id);assert.deepEqual(view.forcesEvPerAngstrom,r.result.forcesEvPerAngstrom);
  const exported=await runtime.originalStructure({kind:'artifact',projectId:'project',runId:r.job.id,artifactId:final.id});assert.equal(sha(exported.bytes),comparison.after.source.sha256);
  const afterImport=await runtime.useOutputStructure({projectId:'project',runId:r.job.id});assert.equal(afterImport.atoms.length,s.atoms.length);assert.notEqual(afterImport.id,s.id);
  const folder=join(receiptDir,potentialId);await mkdir(folder,{recursive:true});for(const file of ['source.extxyz','structure.json','plan.json','environment.json','final.json','final.extxyz','result.json','relaxation.json','steps.json','validation.json','report.zh.md','report.en.md'])await copyFile(join(r.outputDirectory,file),join(folder,file));
  runs.push({potentialId,stopReason:r.result.stopReason,steps:r.result.completedSteps,initialEnergyEv:comparison.summary.initial.energyEv,finalEnergyEv:comparison.summary.final.energyEv,maxForceEvPerAngstrom:comparison.summary.final.maxForceEvPerAngstrom,artifacts:r.artifacts.map(({relativePath,...a})=>({...a,file:relativePath.split('/').at(-1)}))});
 }
 checks.push('two real core MLIPs: nonzero-force distorted Si relaxation converges; fixed cell preserved; step records, final force/geometry/hash/exports and new-task geometry verified');
 for(const cellConstraint of ['hydrostatic','full'] as const){const job=await runtime.startRelaxation({...request,options:{...fixed,cellMode:'variable',cellConstraint,externalPressureGPa:1,maxSteps:2,fmaxEvPerAngstrom:.001}});const r=await finish(job.job.id);assert.equal(r.job.status,'completed',r.job.error??'');assert.equal(r.result?.stopReason,'max_steps');assert.equal(r.result.completedSteps,2);const c=await runtime.comparison({projectId:'project',runId:r.job.id});assert.notDeepEqual(c.after.cell,c.before.cell);assert.equal(c.history.length,3);for(const row of c.history)assert(Math.abs(row.objectiveEv-(row.energyEv+.006241509074460762*row.volumeAngstrom3))<1e-8);if(cellConstraint==='hydrostatic'){const scale=c.after.cell![0][0]/c.before.cell![0][0];c.after.cell!.forEach((row,i)=>row.forEach((v,k)=>assert(Math.abs(v-c.before.cell![i]![k]!*scale)<1e-7)));}}
 checks.push('explicit pressure + isotropic/full cell modes produce real strained structures; enthalpy objective checked; maximum-step output remains NOT converged');
 const capped=await runtime.startRelaxation({...request,options:{...fixed,maxSteps:1,fmaxEvPerAngstrom:.001}});assert.equal((await finish(capped.job.id)).result?.stopReason,'max_steps');
 const cancelJob=await runtime.startRelaxation({...request,options:{...fixed,maxSteps:500,fmaxEvPerAngstrom:.001}});
 const deadline=Date.now()+60_000;while(Date.now()<deadline&&!runtime.get({projectId:'project',runId:cancelJob.job.id}).relaxation?.progress)await new Promise(r=>setTimeout(r,50));assert(runtime.get({projectId:'project',runId:cancelJob.job.id}).relaxation?.progress);
 const queued=await runtime.startRelaxation(request);assert(runtime.cancel({projectId:'project',runId:queued.job.id}));assert.equal((await finish(queued.job.id)).job.status,'cancelled');
 assert(runtime.cancel({projectId:'project',runId:cancelJob.job.id}));const cancelled=await finish(cancelJob.job.id);assert.equal(cancelled.job.status,'cancelled');assert.equal(cancelled.result,null);assert.equal(cancelled.relaxation?.summary,null);assert(cancelled.artifacts.length===2&&cancelled.artifacts.every(a=>a.partial));assert(cancelled.relaxation?.partialArtifactId);
 const recovered=await runtime.useOutputStructure({projectId:'project',runId:cancelled.job.id});assert.equal(recovered.atoms.length,s.atoms.length);
 checks.push('queued/running cancellation has no completed result; only actual last-valid checkpoint registered as partial and reusable as a NEW task');
 const low=await runtime.startRelaxation({...request,budget:{maxAtoms:256,maxSteps:100,maxWallSeconds:1,maxMemoryMiB:4096,maxOutputMiB:64,threads:4}});const failed=await finish(low.job.id);assert.equal(failed.job.status,'failed');assert.equal(failed.result,null);assert.equal(failed.job.error,'WALL_TIME_LIMIT');
 checks.push('real relaxation worker time limit fails cleanly without false success');
 const restored=new AtomisticRuntime(root,state,id=>id==='project'?project:null);await restored.restore();assert.equal(restored.get({projectId:'project',runId:capped.job.id}).result?.stopReason,'max_steps');await assert.rejects(restored.comparison({projectId:'other',runId:capped.job.id}),/UNKNOWN_PROJECT/);restored.dispose();
 const running={...runtime.get({projectId:'project',runId:cancelJob.job.id})};running.job={...running.job,status:'running',finishedAt:null,error:null};running.artifacts=[];running.relaxation!.partialArtifactId=null;await writeFile(join(state,'atomistic/jobs',`${running.job.id}.json`),JSON.stringify(running));
 const restarted=new AtomisticRuntime(root,state,id=>id==='project'?project:null);await restarted.restore();const interruption=restarted.get({projectId:'project',runId:running.job.id});assert.equal(interruption.job.status,'interrupted');assert(interruption.relaxation?.partialArtifactId);restarted.dispose();
 checks.push('restart: completed/nonconverged tasks retain identity; interrupted tasks recover only actual partial geometry');
 const cappedResult=runtime.get({projectId:'project',runId:capped.job.id});await writeFile(join(cappedResult.outputDirectory,'final.json'),'{}');await assert.rejects(runtime.comparison({projectId:'project',runId:capped.job.id}),/ARTIFACT_CHANGED/);
 const damaged=new AtomisticRuntime(root,state,id=>id==='project'?project:null);await damaged.restore();assert.equal(damaged.get({projectId:'project',runId:capped.job.id}).job.status,'failed');damaged.dispose();
 assert.equal(sha(await readFile(input)),before);checks.push('changed final bytes rejected immediately and on restore; original scientific input unchanged');
 const receipt={stage:'M6.3',platform:`${process.platform}-${process.arch}`,passed:true,checks,runs,scientificQuality:'needs_review',llmCalls:0,paymentCalls:0};await writeFile(join(receiptDir,'relaxation-runtime.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({passed:true,checks,runs:runs.length,receipt:join(receiptDir,'relaxation-runtime.json')}));
}finally{runtime.dispose();await rm(temp,{recursive:true,force:true});}
