import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,rm,cp} from 'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{execFileSync}from'node:child_process';
import {AtomisticRuntime} from '../packages/atomistic/src/runtime.js';import{createScienceBridge}from'../packages/pi-adapter/src/science-bridge.js';import{PiPlatformSessionService,type PlatformTransport}from'../packages/pi-adapter/src/platform-session.js';import{responseFixtureEvents}from'../packages/pi-adapter/src/platform-probe.js';import{cloudCatalogSchema}from'../packages/contracts/src/platform.js';import{digest}from'../packages/atomistic/src/selection.js';
const root=process.cwd(),temp=await mkdtemp(join(tmpdir(),'mx-m64-')),project=join(temp,'project');await mkdir(project);
const runtime=new AtomisticRuntime(root,join(temp,'state'),id=>id==='project'?project:null);await runtime.restore();
const dir=resolve('runtime/m6/acceptance/m64');await mkdir(dir,{recursive:true});const checks:string[]=[];
const base={domain:'inorganic-crystals' as const,mode:'exploratory' as const,potentialId:null,secondaryId:null,evidenceIds:[]};
const args=(action:string,targetId:string,extra={})=>({...base,action,targetId,...extra});
async function done(runId:string){for(let i=0;i<1200;i++){const j=runtime.get({projectId:'project',runId});if(['completed','failed','cancelled','interrupted'].includes(j.job.status))return j;await new Promise(r=>setTimeout(r,100));}throw Error('Test timeout');}
try{
 const si=await runtime.importSample('project','si-diamond');
 const original=await readFile(join(root,'samples/atomistic/si-diamond.POSCAR'));
 const production=await runtime.assess({projectId:'project',structureId:si.id,domain:'inorganic-crystals',mode:'production',task:'singlepoint'});
 assert.equal(production.selection.candidates.length,0);assert(production.selection.exclusions.every(e=>e.reasonCodes.includes('DOMAIN_NOT_VALIDATED')));
 const local=createScienceBridge(runtime,'project');const selected=await local.execute(args('select',si.id)) as any;assert.equal(selected.selection.candidates.length,2);
 const a=await local.execute(args('singlepoint',selected.id,{potentialId:'chgnet-0.3.0',evidenceIds:selected.selection.candidates.find((c:any)=>c.potentialId==='chgnet-0.3.0').evidenceIds})) as {runId:string};const first=await done(a.runId);assert.equal(first.job.status,'completed',first.job.error??'');
 const b=await local.execute(args('singlepoint',selected.id,{potentialId:'mace-mp-0b3-medium',evidenceIds:selected.selection.candidates.find((c:any)=>c.potentialId==='mace-mp-0b3-medium').evidenceIds})) as {runId:string};const second=await done(b.runId);assert.equal(second.job.status,'completed',second.job.error??'');
 const comparison=await local.execute(args('compare',a.runId,{secondaryId:b.runId})) as any;assert(Number.isFinite(comparison.forceDifferenceRmsEvPerAngstrom));assert.match(comparison.totalEnergyComparison,/blocked/);assert.match(comparison.accuracy,/not establish/);
 for(const j of [first,second]){assert.equal(j.result?.quality,'needs_review');assert(j.artifacts.some(a=>a.relativePath.endsWith('/selection.json')));const trace=JSON.parse(await readFile(join(j.outputDirectory,'selection.json'),'utf8'));assert.equal(trace.selection.selectedPotentialId,j.plan.potentialId);assert.equal(trace.structureSha256,digest(JSON.stringify(j.structure)));}
 const restored=new AtomisticRuntime(root,join(temp,'state'),id=>id==='project'?project:null);await restored.restore();assert.equal(restored.get({projectId:'project',runId:first.job.id}).job.status,'completed');restored.dispose();
 checks.push('real checkpoint-derived element coverage; formal mode blocks both cores; two real CPU singlepoints with hashed selection provenance and force-only comparison; restart verification');
 const scope={projectId:'project',conversationId:'conversation',structureId:si.id,domain:'inorganic-crystals' as const,mode:'exploratory' as const,permission:'singlepoint' as const};
 const bridge=createScienceBridge(runtime,'project',scope);
 for(const call of [args('inspect','outside'),args('get',first.job.id),args('cancel',first.job.id),args('import_sample','water'),args('inspect',si.id,{domain:'molecules'}),args('inspect',si.id,{path:'/etc/passwd'})])await assert.rejects(bridge.execute(call));
 const cancelledBridge=createScienceBridge(runtime,'project',scope);const selectedScope=await cancelledBridge.execute(args('select',si.id)) as any;
 const controller=new AbortController();const scopedJob=await cancelledBridge.execute(args('singlepoint',selectedScope.id,{potentialId:'chgnet-0.3.0',evidenceIds:selectedScope.selection.candidates.find((c:any)=>c.potentialId==='chgnet-0.3.0').evidenceIds}),controller.signal) as {runId:string};controller.abort();const cancelled=await done(scopedJob.runId);assert.equal(cancelled.job.status,'cancelled');assert.equal(cancelled.result,null);assert.throws(()=>cancelledBridge.completedSummary(),/INCOMPLETE/);
 checks.push('aborting a scoped tool stops its own real child job; cancelled computation cannot produce a successful final summary');
 const fakeRoot=join(temp,'changed-weight');await mkdir(join(fakeRoot,'models/potentials'),{recursive:true});await mkdir(join(fakeRoot,'atomistic/environments/chgnet'),{recursive:true});await writeFile(join(fakeRoot,'models/potentials/registry.json'),await readFile('models/potentials/registry.json'));await writeFile(join(fakeRoot,'atomistic/environments/chgnet/uv.lock'),await readFile('atomistic/environments/chgnet/uv.lock'));
 await cp(join(root,'docs/m6/licenses'),join(fakeRoot,'docs/m6/licenses'),{recursive:true});await cp(join(root,'models/potentials/extensions-m66.json'),join(fakeRoot,'models/potentials/extensions-m66.json'));await cp(join(root,'models/potentials/packages-m68.json'),join(fakeRoot,'models/potentials/packages-m68.json'));await cp(join(root,'atomistic/environments/mace'),join(fakeRoot,'atomistic/environments/mace'),{recursive:true});
 const realBase=join(root,`runtime/atomistic/${runtime.platform}/chgnet`),fakeBase=join(fakeRoot,`runtime/atomistic/${runtime.platform}/chgnet`);await mkdir(fakeBase,{recursive:true});const profile=JSON.parse(await readFile(join(realBase,'RUNTIME.json'),'utf8'));profile.python=profile.portable?join(realBase,profile.python):profile.python;profile.portable=false;await writeFile(join(fakeBase,'RUNTIME.json'),JSON.stringify(profile));const weight=await readFile(join(realBase,'checkpoint.bin'));weight[0]=weight[0]!^1;await writeFile(join(fakeBase,'checkpoint.bin'),weight);
 const corruptRuntime=new AtomisticRuntime(fakeRoot,join(temp,'state'),id=>id==='project'?project:null);await corruptRuntime.restore();assert(corruptRuntime.status().find(s=>s.potentialId==='chgnet-0.3.0')!.installed);const rejectedWeight=await corruptRuntime.assess({projectId:'project',structureId:si.id,domain:'inorganic-crystals',mode:'exploratory',task:'singlepoint'});assert.equal(rejectedWeight.selection.candidates.length,0);corruptRuntime.dispose();checks.push('same-size altered checkpoint rejected by actual SHA before deserialization; real installed checkpoints not modified');
 const validateExe=join(temp,process.platform==='win32'?'sciencecheck.exe':'sciencecheck');execFileSync('go',['build','-o',validateExe,'./cmd/sciencecheck'],{cwd:join(root,'services/control-plane'),timeout:120000});
 const catalog=cloudCatalogSchema.parse({items:[],nextCursor:null,alpha:{configured:true,available:true,remainingRequests:16,expiresAt:new Date(Date.now()+600000).toISOString(),limits:{maxRequests:8,maxOutputTokensPerRequest:512,maxDurationSeconds:180}}});
 const payloads:any[]=[],records=new Map<string,any>();let state='created',round=0;const createdAt=new Date().toISOString(),deadline=new Date(Date.now()+180000).toISOString();
 const transport:PlatformTransport={origin:'http://127.0.0.1:18788',async platformRequest(path,init){
  const task=()=>({id:'task-fixture',clientTaskId:'client-fixture',modelId:'materials-research',billingMode:'alpha-test',budget:catalog.alpha.limits,consent:{policyVersion:'cloud-alpha-v1',prompt:true,history:'platform-only',fileCount:0,skillCount:1},state,scientificQuality:'not_evaluated',createdAt,deadline,requestCount:round});
  if(path==='/v1/tasks')return Response.json(task());if(path.endsWith('/finish')){state=JSON.parse(String(init?.body)).state;return Response.json(task());}if(path.endsWith('/cancel')){state='cancelled';return Response.json(task());}
  if(path.startsWith('/v1/model-requests/'))return Response.json(records.get(path.split('/').at(-1)!));
  assert.equal(path,'/v1/model-gateway/responses');const payload=JSON.parse(String(init?.body));payloads.push(payload);execFileSync(validateExe,[],{input:JSON.stringify(payload),timeout:10000});round++;state='running';
  const id=new Headers(init?.headers).get('X-Materialsx-Request-Id')!;records.set(id,{id,taskId:'task-fixture',modelId:'materials-research',billingMode:'alpha-test',execution:'completed',settlement:'not_billed',scientificQuality:'not_evaluated',usage:{source:'responses',inputTokens:10,outputTokens:4,cachedInputTokens:2,uncachedInputTokens:8,reasoningTokens:1},reservedCredits:'0',chargedCredits:null,salesPriceVersionId:null,routeVersionId:'offline-fixture',terminalReceived:true,errorCode:null,dispatched:true});
  const outputs=payload.input.filter((i:any)=>i.type==='function_call_output');const last=outputs.length?JSON.parse(outputs.at(-1).output):null;
  const call=round===1?args('select',si.id):round===2?args('singlepoint',last.id,{potentialId:last.selection.candidates[0].potentialId,evidenceIds:last.selection.candidates[0].evidenceIds}):round===3?args('get',last.runId):null;
  const events=JSON.parse(JSON.stringify(responseFixtureEvents(call?'tool':'text')));let delta=0;
  for(const e of events){if(e.item?.type==='function_call'){e.item.name='materials_science';e.item.call_id=`science-${round}`;e.item.arguments=e.item.status==='in_progress'?'':JSON.stringify(call);}if(e.response?.output)for(const i of e.response.output)if(i.type==='function_call'){i.name='materials_science';i.call_id=`science-${round}`;i.arguments=JSON.stringify(call);}if(e.type==='response.function_call_arguments.delta')e.delta=delta++===0?JSON.stringify(call):'';if(e.type==='response.function_call_arguments.done')e.arguments=JSON.stringify(call);}
  const bytes=new TextEncoder().encode(events.map((e:any)=>`data: ${JSON.stringify(e)}\n\n`).join(''));return new Response(new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=7)c.enqueue(bytes.slice(i,i+7));c.close();}}),{headers:{'Content-Type':'text/event-stream'}});
 }};
 const service=new PiPlatformSessionService(transport);const skillText=await readFile('vendor/materialsx-default-skills/skills/materials-mlip-singlepoint/SKILL.md','utf8');
 const answer=await service.prompt('account','conversation','materials-research','Run an explicitly authorized exploratory singlepoint and read the true result.',{files:[],skills:[{id:'materials-mlip-singlepoint',name:'materials-mlip-singlepoint',text:skillText,sha256:digest(skillText)}]},catalog,()=>{},'10000',bridge);
 assert.match(answer,/本机工具核验/);assert.equal(payloads.length,4);assert.equal(service.snapshot('conversation')?.task.state,'completed');
 const wire=JSON.stringify(payloads);assert(wire.includes('materials_science 受控本地计算工具'));assert(!wire.includes('只能通过已批准的只读工具'));for(const forbidden of ['"position"','"atoms"','forcesEvPerAngstrom','outputDirectory',project,temp,root])assert(!wire.includes(forbidden),`private geometry/path leaked: ${forbidden}`);
 assert.equal(runtime.list('project').filter(j=>j.job.status==='completed').length,3);
 checks.push('actual Pi Responses streaming -> frozen Go gateway validator -> approved local dispatcher -> real CPU job -> bounded result -> final response; no atom coordinates/full arrays/paths in outbound wire');
 // Unknown or unsettled usage must stop before local tools, even when the model returns a tool call.
 for(const pending of ['unknown','unsettled']){
  let executions=0;const denied=createScienceBridge(runtime,'project',scope);const execute=denied.execute;denied.execute=async(...a)=>{executions++;return execute(...a)};
  const wrapped:PlatformTransport={origin:transport.origin,async platformRequest(path,init){const response=await transport.platformRequest(path,init);if(path.startsWith('/v1/model-requests/')){const r=await response.json();return Response.json(pending==='unknown'?{...r,execution:'unknown',terminalReceived:false}:{...r,billingMode:'paid-credits',settlement:'reconciliation_pending',salesPriceVersionId:'fixture-price',chargedCredits:null});}return response;}};
  round=0;payloads.length=0;const session=new PiPlatformSessionService(wrapped);await assert.rejects(session.prompt('account','conversation-'+pending,'materials-research','read approved structure',{files:[],skills:[]},catalog,()=>{},'10000',denied),/未完成或用量/);assert.equal(executions,0);session.dispose();
 }
 checks.push('foreign structure/job/cancel/import, mode/domain change and extra path fields rejected; unknown/unsettled model usage blocks local tool continuation');
 const actual=runtime.list('project')[0]!;await writeFile(join(actual.outputDirectory,'selection.json'),'{}\n');const changed=new AtomisticRuntime(root,join(temp,'state'),id=>id==='project'?project:null);await changed.restore();assert.equal(changed.get({projectId:'project',runId:actual.job.id}).job.status,'failed');changed.dispose();
 assert.equal(digest(original),digest(await readFile(join(root,'samples/atomistic/si-diamond.POSCAR'))));
 checks.push('selection artifact tampering rejected on restore; original sample immutable');
 await writeFile(join(dir,'selection-runtime.json'),JSON.stringify({stage:'M6.4',platform:`${process.platform}-${process.arch}`,passed:true,checks,models:production.capabilities.map(c=>({potentialId:c.potentialId,elements:c.elements,loadedMemoryMiB:c.loadedMemoryMiB,sha256:c.sha256,dependencyLockSha256:c.dependencyLockSha256})),comparison,scientificQuality:'needs_review',realLocalCalculations:3,realProviderCalls:0,paymentCalls:0,platformTransport:'offline synthetic Responses, real Pi SDK/Go validation/local inference'},null,2)+'\n');
 console.log(JSON.stringify({passed:true,checks,receipt:join(dir,'selection-runtime.json')}));
}finally{runtime.dispose();await rm(temp,{recursive:true,force:true});}
