import {spawn,spawnSync} from 'node:child_process';import {mkdtemp,mkdir,rm} from 'node:fs/promises';import {existsSync} from 'node:fs';import {randomBytes} from 'node:crypto';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{createServer}from'node:net';
const root=process.cwd(),dir=await mkdtemp(join(tmpdir(),'mx-m64-cloud-'));let server:ReturnType<typeof spawn>|undefined,startedPg=false;
const pgBin=process.env.MATERIALSX_POSTGRES_BIN??['/opt/homebrew/opt/postgresql@16/bin','/usr/local/opt/postgresql@16/bin','/usr/lib/postgresql/16/bin'].find(p=>existsSync(join(p,'pg_ctl')));
const pgData=join(dir,'pgdata'),socket=join(dir,'socket');
function cmd(binary:string,args:string[],options:{env?:NodeJS.ProcessEnv;input?:string}={}){const result=spawnSync(binary,args,{cwd:root,encoding:'utf8',timeout:120000,...options});if(result.status!==0)throw Error(`Isolated fixture command failed: ${binary.split(/[\\/]/).at(-1)}`);return result.stdout;}
async function freePort(){const s=createServer();await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));const port=(s.address()as {port:number}).port;await new Promise<void>(r=>s.close(()=>r()));return port;}
try{
 let dsn=process.env.MATERIALSX_IDENTITY_TEST_DATABASE_URL;
 if(dsn){if(!new URL(dsn).pathname.includes('test'))throw Error('Only an isolated test database is accepted');}
 else{if(!pgBin)throw Error('Set MATERIALSX_POSTGRES_BIN to PostgreSQL 16 tools, or MATERIALSX_IDENTITY_TEST_DATABASE_URL to an isolated test database');await mkdir(socket);const pgPort=await freePort();cmd(join(pgBin,'initdb'),['-D',pgData,'--username=mx_fixture_owner','--auth-host=trust','--auth-local=trust']);cmd(join(pgBin,'pg_ctl'),['-D',pgData,'-l',join(dir,'postgres.log'),'-o',`-h 127.0.0.1 -p ${pgPort} -k '${socket.replaceAll("'","''")}'`,'start']);startedPg=true;cmd(join(pgBin,'createdb'),['-h','127.0.0.1','-p',String(pgPort),'-U','mx_fixture_owner','materialsx_m64_test']);dsn=`postgres://mx_fixture_owner@127.0.0.1:${pgPort}/materialsx_m64_test?sslmode=disable`;}
 const port=await freePort(),url=`http://127.0.0.1:${port}`,email=`m64-${randomBytes(6).toString('hex')}@example.invalid`,password=randomBytes(24).toString('base64url');
 const env={...process.env,MATERIALSX_ENV:'development',MATERIALSX_DEV_MODE:'0',MATERIALSX_M64_FIXTURE:'1',MATERIALSX_DATABASE_URL:dsn,MATERIALSX_IDENTITY_ADDR:`127.0.0.1:${port}`,MATERIALSX_IDENTITY_PUBLIC_URL:url,MATERIALSX_IDENTITY_MASTER_KEY:randomBytes(32).toString('base64'),MATERIALSX_CLOUD_MODE:'disabled',ROOTFLOWAI_API_KEY:'',MATERIALSX_METERING_PRICE_VERSION:'',MATERIALSX_PROCUREMENT_PRICE_VERSION:'',MATERIALSX_PAID_PRICE_VERSION:'',MATERIALSX_IDENTITY_FIXTURE_URL:url,MATERIALSX_IDENTITY_FIXTURE_EMAIL:email,MATERIALSX_IDENTITY_FIXTURE_PASSWORD:password};
 const go=(args:string[],input?:unknown)=>cmd('go',['-C','services/control-plane',...args],{env,...(input?{input:JSON.stringify(input)}:{})});go(['run','./cmd/identityctl','--command','migrate']);const user=go(['run','./cmd/identityctl','--command','create-user'],{email,displayName:'Synthetic M64 desktop fixture',password});const accountId=user.match(/id=([A-Za-z0-9_-]+)/)?.[1];if(!accountId)throw Error('Fixture account missing');go(['run','./cmd/identityctl','--command','grant-cloud'],{accountId,requestLimit:16,expiresAt:new Date(Date.now()+3600000).toISOString()});
 const binary=join(dir,process.platform==='win32'?'gateway.exe':'gateway');go(['build','-o',binary,'./internal/gateway/testfixture']);server=spawn(binary,[],{env,stdio:'ignore'});
 let ready=false;for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error('Fixture exited');try{if((await fetch(url+'/health',{signal:AbortSignal.timeout(500)})).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}if(!ready)throw Error('Fixture not ready');
 const md=process.argv.includes('--md');
 const electron=spawnSync(resolve('node_modules/electron/dist',process.platform==='darwin'?'Electron.app/Contents/MacOS/Electron':process.platform==='win32'?'electron.exe':'electron'),[md?'apps/desktop/m65-cloud-smoke.cjs':'apps/desktop/m64-cloud-smoke.cjs'],{cwd:root,env,stdio:'inherit',timeout:300000});if(electron.status!==0)throw Error('Scientific desktop integration failed');console.log((md?'M6.5 MD':'M6.4')+' native consent + real PKCE/PostgreSQL/gateway + synthetic Responses + real CPU passed; no real provider/payment.');
}finally{if(server&&server.exitCode===null){server.kill('SIGTERM');await new Promise<void>(r=>server!.once('exit',()=>r()));}if(startedPg&&pgBin)cmd(join(pgBin,'pg_ctl'),['-D',pgData,'-m','fast','stop']);await rm(dir,{recursive:true,force:true});}
