import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';
import {AtomisticRuntime} from '../packages/atomistic/src/runtime.js';
import {defaultMDOptions,mdOptionsSchema,scientificSnapshotSchema} from '../packages/contracts/src/atomistic-dynamics.js';
import {digest} from '../packages/atomistic/src/selection.js';
const root=process.cwd(),temp=await mkdtemp(join(tmpdir(),'mx-m65-')),project=join(temp,'project');await mkdir(project);
const runtime=new AtomisticRuntime(root,join(temp,'state'),id=>id==='project'?project:null);await runtime.restore();
const directory=resolve('runtime/m6/acceptance/m65');await mkdir(directory,{recursive:true});const checks:string[]=[],summaries:unknown[]=[];
async function done(runId:string){const deadline=Date.now()+650000;while(Date.now()<deadline){const run=runtime.get({projectId:'project',runId});scientificSnapshotSchema.parse(run);if(['completed','failed','cancelled','interrupted'].includes(run.job.status))return run;await new Promise(r=>setTimeout(r,100));}throw Error('TEST_TIMEOUT');}
try{
 const source=await readFile('samples/atomistic/si-diamond.POSCAR'),si=await runtime.importSample('project','si-diamond');
 const mdOptions={...defaultMDOptions,steps:process.argv.includes('--quick')?10:2000,sampleEvery:process.argv.includes('--quick')?3:10};const ids:string[]=[];
 for(const potentialId of ['chgnet-0.3.0','mace-mp-0b3-medium'] as const){const run=await runtime.startMD({projectId:'project',structureId:si.id,potentialId,mdOptions});const result=await done(run.job.id);assert.equal(result.job.status,'completed',result.job.error??'');assert.equal(result.md!.summary!.completedSteps,mdOptions.steps);const payload=await runtime.trajectory({projectId:'project',runId:run.job.id});assert.equal(payload.index.entries.at(-1)!.timeFs,mdOptions.steps*.5);const final=await runtime.trajectoryFrame({projectId:'project',runId:run.job.id,frame:payload.index.entries.length-1});assert.equal(final.step.step,mdOptions.steps);assert.equal(final.positionsAngstrom.length,si.atoms.length);assert.notDeepEqual(final.positionsAngstrom,si.atoms.map(a=>a.position));const chunks:Buffer[]=[];await runtime.trajectoryExport({projectId:'project',runId:run.job.id},async b=>{chunks.push(b);});assert.equal(digest(Buffer.concat(chunks)),result.artifacts.find(a=>a.relativePath.endsWith('/trajectory.extxyz'))!.sha256);ids.push(run.job.id);summaries.push(result.md!.summary);console.log(JSON.stringify({model:potentialId,summary:result.md!.summary}));}
 const comparison=await runtime.compareMD({projectId:'project',runIds:ids});assert.equal(comparison.energyDefinition,'within-model-total-energy-change-per-atom');assert.equal(comparison.series[0].length,mdOptions.steps+1);
 checks.push('Two actual core checkpoints: NVE trajectory, real lazy initial/final frames, units/time/sampling, exact archive export, matching initial velocities and within-model energy-change comparison');
 const nvt=mdOptionsSchema.parse({...defaultMDOptions,ensemble:'nvt',steps:process.argv.includes('--quick')?10:1000,frictionInverseFs:.01});const nvtJob=await runtime.startMD({projectId:'project',structureId:si.id,potentialId:'chgnet-0.3.0',mdOptions:nvt});const nvtRun=await done(nvtJob.job.id);assert.equal(nvtRun.job.status,'completed',nvtRun.job.error??'');assert.equal(nvtRun.md!.summary!.nveVerdict,'not_applicable');summaries.push(nvtRun.md!.summary);console.log(JSON.stringify({nvt:nvtRun.md!.summary}));checks.push('Actual CHGNet NVT Langevin, explicit fs^-1 friction and separate temperature diagnostic');
 await assert.rejects(runtime.trajectoryFrame({projectId:'outside',runId:ids[0],frame:0}));await assert.rejects(runtime.trajectoryFrame({projectId:'project',runId:ids[0],frame:2000}));await assert.rejects(runtime.startMD({projectId:'project',structureId:si.id,potentialId:'chgnet-0.3.0',mdOptions:{...defaultMDOptions,frictionInverseFs:.01}}));
 const cancelled=await runtime.startMD({projectId:'project',structureId:si.id,potentialId:'chgnet-0.3.0',mdOptions:{...defaultMDOptions,steps:2000,sampleEvery:1}});const waitDeadline=Date.now()+30000;while(Date.now()<waitDeadline){const j=runtime.get({projectId:'project',runId:cancelled.job.id});if(j.md?.progress&&j.md.progress.step>=1)break;await new Promise(r=>setTimeout(r,100));}assert(runtime.cancel({projectId:'project',runId:cancelled.job.id}));const partial=await done(cancelled.job.id);assert.equal(partial.job.status,'cancelled');assert.equal(partial.result,null);const partialPayload=await runtime.trajectory({projectId:'project',runId:cancelled.job.id});assert(partialPayload.partial);const last=await runtime.trajectoryFrame({projectId:'project',runId:cancelled.job.id,frame:partialPayload.index.entries.length-1});assert(last.step.step<2000);const reused=await runtime.useOutputStructure({projectId:'project',runId:cancelled.job.id});assert(reused.source.transformations.some(s=>s.includes('NOT resumed')));checks.push('Actual child cancellation retains hashed real partial frames; geometry reuse explicitly starts a new segment without velocity/integrator/RNG resume');
 const timeout=await runtime.startMD({projectId:'project',structureId:si.id,potentialId:'chgnet-0.3.0',mdOptions:defaultMDOptions,budget:{maxAtoms:256,maxSteps:200,maxWallSeconds:1,maxMemoryMiB:4096,maxOutputMiB:64,threads:4}});const timed=await done(timeout.job.id);assert.equal(timed.job.status,'failed');assert.match(timed.job.error??'',/WALL_TIME_LIMIT/);checks.push('Real one-second process timeout does not publish success');
 const outputLimited=await runtime.startMD({projectId:'project',structureId:si.id,potentialId:'chgnet-0.3.0',mdOptions:{...defaultMDOptions,steps:2000,sampleEvery:1},budget:{maxAtoms:256,maxSteps:2000,maxWallSeconds:600,maxMemoryMiB:4096,maxOutputMiB:1,threads:4}});const limited=await done(outputLimited.job.id);assert.equal(limited.job.status,'failed');assert.match(limited.job.error??'',/OUTPUT_SIZE_LIMIT/);assert.equal(limited.result,null);const limitedPayload=await runtime.trajectory({projectId:'project',runId:limited.job.id});assert(limitedPayload.partial);checks.push('Actual output-byte budget stops the real worker and preserves partial valid frames without a completed result');
 const hPath=join(project,'hydrogen.extxyz');await writeFile(hPath,'2\nLattice="4 0 0 0 4 0 0 0 4" Properties=species:S:1:pos:R:3 pbc="T T T"\nH 0 0 0\nH 1 0 0\n');const h=await runtime.importFile('project',hPath);await assert.rejects(runtime.startMD({projectId:'project',structureId:h.id,potentialId:'chgnet-0.3.0',mdOptions:defaultMDOptions}),/LIGHT_ELEMENT_TIMESTEP/);checks.push('Hydrogen time-step preflight rejects 0.5 fs before launching dynamics');
 const restored=new AtomisticRuntime(root,join(temp,'state'),id=>id==='project'?project:null);await restored.restore();assert.equal(restored.get({projectId:'project',runId:ids[0]}).job.status,'completed');assert.equal(restored.get({projectId:'project',runId:cancelled.job.id}).job.status,'cancelled');await restored.trajectory({projectId:'project',runId:cancelled.job.id});restored.dispose();
 // Replay a persisted nonterminal MD record after a simulated app crash; never resume or claim completion.
 const statePath=join(temp,'state/atomistic/jobs',`${cancelled.job.id}.json`),crashed={...partial,job:{...partial.job,status:'running',finishedAt:null,error:null,resultArtifactId:null},result:null,artifacts:[],md:{...partial.md!,summary:null,trajectoryArtifactId:null}};await writeFile(statePath,JSON.stringify(crashed));const interrupted=new AtomisticRuntime(root,join(temp,'state'),id=>id==='project'?project:null);await interrupted.restore();assert.equal(interrupted.get({projectId:'project',runId:cancelled.job.id}).job.status,'interrupted');const interruptedPayload=await interrupted.trajectory({projectId:'project',runId:cancelled.job.id});assert(interruptedPayload.partial);interrupted.dispose();checks.push('Persisted running MD restores as interrupted and retains only the validated real frame prefix; no integrator continuation');
 const first=runtime.get({projectId:'project',runId:ids[0]}),path=join(first.outputDirectory,'frames.ndjson'),bytes=await readFile(path);bytes[bytes.length-20]=bytes[bytes.length-20]!^1;await writeFile(path,bytes);await assert.rejects(runtime.trajectoryFrame({projectId:'project',runId:ids[0],frame:first.md!.summary!.frameCount-1}),/CHANGED/);const changed=new AtomisticRuntime(root,join(temp,'state'),id=>id==='project'?project:null);await changed.restore();assert.equal(changed.get({projectId:'project',runId:ids[0]}).job.status,'failed');changed.dispose();checks.push('Restore verifies real frame/observable/diagnostic/plan/manifest hashes; same-size modified final frame rejected; foreign IDs rejected');
 assert.equal(digest(source),digest(await readFile('samples/atomistic/si-diamond.POSCAR')));
 await writeFile(join(directory,process.argv.includes('--quick')?'runtime-quick.json':'runtime.json'),JSON.stringify({stage:'M6.5',passed:true,platform:`${process.platform}-${process.arch}`,checks,summaries,scientificQuality:'needs_review',realProviderCalls:0,paymentCalls:0},null,2)+'\n');console.log(JSON.stringify({passed:true,checks}));
}finally{runtime.dispose();for(let i=0;i<200&&runtime.list('project').some(r=>!['completed','failed','cancelled','interrupted'].includes(r.job.status));i++)await new Promise(r=>setTimeout(r,50));await rm(temp,{recursive:true,force:true});}
