import assert from 'node:assert/strict';import { execFile } from 'node:child_process';import { promisify } from 'node:util';
import { mkdtemp,mkdir,readFile,writeFile,rm } from 'node:fs/promises';import { tmpdir } from 'node:os';import { join,resolve } from 'node:path';
import { AtomisticRuntime } from '../packages/atomistic/src/runtime.js';import { ScientificValidationService } from '../packages/atomistic/src/scientific-validation.js';import { defaultMDOptions } from '../packages/contracts/src/atomistic-dynamics.js';import { extensionManifest } from '../packages/atomistic/src/model-packages.js';
const root=process.cwd(),dir=await mkdtemp(join(tmpdir(),'mx-m66-')),project=join(dir,'project'),state=join(dir,'state'),out=resolve('runtime/m6/acceptance/m66');await mkdir(project);await mkdir(out,{recursive:true});
const runtime=new AtomisticRuntime(root,state,id=>id==='project'?project:null);await runtime.restore();const validation=new ScientificValidationService(root,state,runtime,id=>id==='project'?project:null);await validation.restore();const checks:string[]=[];
async function done(id:string){for(let i=0;i<3000;i++){const r=runtime.get({projectId:'project',runId:id});if(['completed','failed','cancelled','interrupted'].includes(r.job.status))return r;await new Promise(r=>setTimeout(r,100));}throw Error('TEST_TIMEOUT');}
try{
 const e=extensionManifest(root).entries[0]!;let source=join(root,'runtime/m6/extension-sources/chgnet-r2scan/checkpoint.bin');try{await readFile(source);}catch{source=join(root,'runtime/scientific-packages',e.potentialId,e.sha256,'checkpoint.bin');}await runtime.packages.importFile({potentialId:e.potentialId},source);assert.equal((await runtime.packages.status())[0]!.state,'installed');assert(runtime.status().find(s=>s.potentialId===e.potentialId)?.installed);checks.push('Actual pinned r2SCAN import, license/hash verification and shared existing portable CHGNet runtime');
 const si=await runtime.importSample('project','si-diamond');const assessment=await runtime.assess({projectId:'project',structureId:si.id,domain:'inorganic-crystals',mode:'exploratory',task:'singlepoint'});assert.equal(assessment.selection.candidates.length,3);assert.equal((await runtime.assess({...assessment.request,mode:'production'})).selection.candidates.length,0);const start=await runtime.start({projectId:'project',structureId:si.id,potentialId:e.potentialId}),single=await done(start.job.id);assert.equal(single.job.status,'completed',single.job.error??'');assert(single.result?.energyEv);checks.push('Three actual capability receipts; real r2SCAN energy/forces; production remains blocked');
 const md=await runtime.startMD({projectId:'project',structureId:si.id,potentialId:e.potentialId,mdOptions:{...defaultMDOptions,steps:20,sampleEvery:5}}),trajectory=await done(md.job.id);assert.equal(trajectory.job.status,'completed',trajectory.job.error??'');const payload=await runtime.trajectory({projectId:'project',runId:md.job.id});assert.equal(payload.index.entries.length,5);checks.push('Real r2SCAN NVE/true frames with offline-enforced worker');
 const base=join(root,'runtime/atomistic',runtime.platform,'chgnet'),receipt=JSON.parse(await readFile(join(base,'RUNTIME.json'),'utf8'));await promisify(execFile)(join(base,receipt.python),[join(root,'atomistic/probe.py'),root,e.potentialId,runtime.packages.weight(e.potentialId),join(out,'r2scan-numerical.json')],{timeout:300000,maxBuffer:1048576,env:{...process.env,OMP_NUM_THREADS:'4',OPENBLAS_NUM_THREADS:'4',PYTHONDONTWRITEBYTECODE:'1'}});const numerical=JSON.parse(await readFile(join(out,'r2scan-numerical.json'),'utf8'));assert(numerical.numericalPassed);checks.push('Actual r2SCAN three perturbed finite-difference/invariance probes; not DFT accuracy');
 await runtime.packages.setDisabled({potentialId:e.potentialId},true);await assert.rejects(runtime.start({projectId:'project',structureId:si.id,potentialId:e.potentialId}),/EXCLUDED/);assert.equal((await runtime.view({kind:'artifact',projectId:'project',runId:single.job.id,artifactId:single.artifacts.find(a=>a.type==='atomic_structure')!.id})).structure.atoms.length,8);await runtime.packages.setDisabled({potentialId:e.potentialId},false);checks.push('Disable/re-enable changes new-job eligibility, keeps actual historical results');
 await validation.importDataset('project',join(root,'docs/m6/holdout.example.json'));await assert.rejects(validation.start({projectId:'outside',datasetId:'synthetic-format-demo',potentialId:'chgnet-0.3.0'}));const evaluation=await validation.start({projectId:'project',datasetId:'synthetic-format-demo',potentialId:'chgnet-0.3.0'});let result;for(let i=0;i<1200;i++){result=validation.list('project').find(j=>j.id===evaluation.id);if(result&&['completed','failed','cancelled'].includes(result.status))break;await new Promise(r=>setTimeout(r,100));}assert.equal(result?.status,'completed',result?.error??'');assert.equal(result?.report?.status,'blocked');assert(result.report.reasonCodes.includes('SYNTHETIC_NOT_DFT'));assert.equal(result.report.completedSamples,1);const matrix=await validation.matrix('project');assert(matrix.rows.every(r=>!r.productionApproved));checks.push('Real CPU prediction/evaluator pipeline; explicitly synthetic demo remains blocked, records all reference/quota limitations and bilingual files');
 const restored=new ScientificValidationService(root,state,runtime,id=>id==='project'?project:null);await restored.restore();assert.equal(restored.list('project')[0]?.report?.status,'blocked');restored.dispose();
 const cancelJob=await validation.start({projectId:'project',datasetId:'synthetic-format-demo',potentialId:'chgnet-0.3.0'});for(let n=0;n<300;n++){if(validation.list('project').find(j=>j.id===cancelJob.id)?.activeRunId)break;await new Promise(r=>setTimeout(r,100));}assert(validation.cancel('project',cancelJob.id));for(let n=0;n<300;n++){if(validation.list('project').find(j=>j.id===cancelJob.id)?.status==='cancelled')break;await new Promise(r=>setTimeout(r,100));}assert.equal(validation.list('project').find(j=>j.id===cancelJob.id)?.status,'cancelled');assert.equal(validation.list('project').find(j=>j.id===cancelJob.id)?.report,null);checks.push('Actual active CPU evaluation cancellation does not publish a successful report');
 const statusPath=join(state,'scientific-validation',`evaluation-${evaluation.id}.json`),corrupt=JSON.parse(await readFile(statusPath,'utf8'));corrupt.report.status='passed-screening';corrupt.report.reasonCodes=[];await writeFile(statusPath,JSON.stringify(corrupt));const damaged=new ScientificValidationService(root,state,runtime,id=>id==='project'?project:null);await damaged.restore();assert.equal(damaged.list('project').find(j=>j.id===evaluation.id)?.error,'STORED_EVALUATION_CHANGED');assert.equal(damaged.list('project').find(j=>j.id===evaluation.id)?.report,null);damaged.dispose();checks.push('Restore recomputes real prediction provenance and frozen metrics; modified scientific report rejected');
 await writeFile(join(out,'runtime.json'),JSON.stringify({stage:'M6.6',passed:true,platform:`${process.platform}-${process.arch}`,checks,extension:{potentialId:e.potentialId,bytes:e.bytes,sha256:e.sha256,energyEv:single.result!.energyEv,realTrajectoryFrames:payload.index.entries.length},scientificQuality:'needs_review',independentDftHoldoutAvailable:false,productionApproved:false,realProviderCalls:0,paymentCalls:0,newLargePythonEnvironments:false},null,2)+'\n');console.log(JSON.stringify({passed:true,checks}));
}finally{validation.dispose();runtime.dispose();for(let i=0;i<100&&runtime.list('project').some(r=>!['completed','failed','cancelled','interrupted'].includes(r.job.status));i++)await new Promise(r=>setTimeout(r,100));await rm(dir,{recursive:true,force:true});}
