import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm,writeFile,access} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';
import {AtomisticRuntime} from '../packages/atomistic/src/runtime.js';
import {PotentialAnalysisService} from '../packages/atomistic/src/potential-workflow.js';
import {createScienceBridge} from '../packages/pi-adapter/src/science-bridge.js';
const root=process.cwd(),temp=await mkdtemp(join(tmpdir(),'mx-m68-real-')),project=join(temp,'project'),state=join(temp,'state');await mkdir(project);await mkdir(state);
const runtime=new AtomisticRuntime(root,state,id=>id==='project'?project:null);await runtime.restore();const automation=new PotentialAnalysisService(root,state,runtime);
const evidence=resolve('runtime/m6/acceptance/m68-m69');await mkdir(evidence,{recursive:true});const rows:unknown[]=[];
const done=async(id:string)=>{for(;;){const s=runtime.get({projectId:'project',runId:id});if(['completed','failed','cancelled','interrupted'].includes(s.job.status)){assert.equal(s.job.status,'completed',s.job.error??'');return s;}await new Promise(r=>setTimeout(r,250));}};
try{
 const r2=runtime.mountedPackages.entry('chgnet-r2scan');let r2source:string|null=null;for(const path of [resolve('runtime/m6/extension-sources/chgnet-r2scan/checkpoint.bin'),resolve('runtime/scientific-packages/chgnet-r2scan',r2.sha256,'checkpoint.bin')]){try{await access(path);r2source=path;break;}catch{}}if(r2source)await runtime.mountedPackages.importFile('chgnet-r2scan',r2source);else await runtime.mountedPackages.download('chgnet-r2scan');
 for(const id of ['mace-mp-0b2-small','mace-mpa-0-medium']){console.log('Cold official download',id);await runtime.mountedPackages.download(id);}
 const structure=await runtime.importSample('project','si-diamond');
 const a=await runtime.assess({projectId:'project',structureId:structure.id,domain:'inorganic-crystals',mode:'exploratory',task:'singlepoint'});assert.equal(a.capabilities.length,5);assert.equal(a.selection.candidates.length,5);
 for(const c of a.selection.candidates){console.log('Real single point',c.potentialId);const run=await runtime.startSelected({projectId:'project',proposal:{assessmentId:a.id,selectedPotentialId:c.potentialId,evidenceIds:c.evidenceIds}});const s=await done(run.job.id);assert(s.result);const artifact=s.artifacts.find(a=>a.type==='atomic_structure')!;await runtime.view({kind:'artifact',projectId:'project',runId:s.job.id,artifactId:artifact.id});rows.push({potentialId:c.potentialId,result:s.result,capability:a.capabilities.find(r=>r.potentialId===c.potentialId),artifacts:s.artifacts});}
 await runtime.mountedPackages.uninstall('mace-mp-0b2-small');assert(!runtime.status().find(s=>s.potentialId==='mace-mp-0b2-small')!.installed);
 for(const locale of ['zh','en'] as const){const options={optimizer:'FIRE' as const,cellMode:'fixed' as const,cellConstraint:'none' as const,externalPressureGPa:null,maxSteps:3,fmaxEvPerAngstrom:.05};const scope={projectId:'project',conversationId:'conversation-'+locale,structureId:structure.id,domain:'inorganic-crystals' as const,mode:'exploratory' as const,permission:'relaxation' as const,options};const autoScope={projectId:'project',conversationId:scope.conversationId,structureId:structure.id,maxDownloadBytes:200*1048576,maxSteps:3,permission:'relaxation' as const};const bridge=createScienceBridge(runtime,'project',scope,undefined,{service:automation,scope:autoScope,prompt:locale==='zh'?'选择小型 MACE 模型对这个无机晶体做固定晶胞弛豫，输出报告与3D结构。':'Choose a small MACE potential and relax the inorganic bulk crystal at fixed cell. Produce reports and a 3D structure.'});const args=(action:string,targetId:string,potentialId:string|null=null,evidenceIds:string[]=[])=>({action,targetId,secondaryId:null,potentialId,domain:scope.domain,mode:scope.mode,evidenceIds});const assessment=await bridge.execute(args('auto_plan',structure.id)) as any;const c=assessment.selection.candidates.find((c:any)=>c.potentialId==='mace-mp-0b2-small');assert(c);const started=await bridge.execute(args('auto_run',assessment.id,c.potentialId,c.evidenceIds)) as any;console.log('Automatic bilingual workflow',locale,started);let last:any;do{last=await bridge.execute(args('auto_get',started.workflowId));console.log(locale,last.state);}while(!['completed','failed','cancelled','interrupted'].includes(last.state));assert.equal(last.state,'completed',JSON.stringify(last));bridge.completedSummary(true);const w=automation.get('project',started.workflowId),job=runtime.get({projectId:'project',runId:w.runId!});assert(job.relaxation?.summary);assert(job.artifacts.some(a=>a.relativePath.endsWith('/report.zh.md'))&&job.artifacts.some(a=>a.relativePath.endsWith('/report.en.md')));const final=job.artifacts.find(a=>a.relativePath.endsWith('/final.json'))!;const view=await runtime.view({kind:'artifact',projectId:'project',runId:job.job.id,artifactId:final.id});assert.equal(view.structure.atoms.length,structure.atoms.length);rows.push({locale,workflow:w,view,job});}
 const rejected=await automation.assess({projectId:'project',structureId:structure.id,prompt:'Analyze polymer',locale:'en',domain:'polymers',mode:'exploratory',task:'singlepoint',budget:{maxAtoms:256,maxSteps:1,maxWallSeconds:600,maxMemoryMiB:4096,maxOutputMiB:64,threads:4},maxDownloadBytes:200*1048576});assert.equal(rejected.selection.candidates.length,0);
 automation.dispose();runtime.dispose();const restored=new AtomisticRuntime(root,state,id=>id==='project'?project:null);await restored.restore();assert.equal(restored.list('project').filter(r=>r.job.status==='completed').length,7);const service=new PotentialAnalysisService(root,state,restored);service.restore();assert.equal(service.list('project').filter(w=>w.state==='completed').length,2);restored.dispose();
 await writeFile(join(evidence,'runtime.json'),JSON.stringify({stage:'M6.8/M6.9',passed:true,platform:`${process.platform}-${process.arch}`,checkpoints:5,realCalculations:7,coldOfficialDownloads:3,bilingualAutomaticWorkflows:2,realProviderCalls:0,scientificQuality:'needs_review',rows},null,2)+'\n');console.log('M6.8/M6.9 real runtime acceptance passed');
}finally{automation.dispose();runtime.dispose();await rm(temp,{recursive:true,force:true});}
