import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,rm,access} from 'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{execFileSync}from'node:child_process';
import {AtomisticRuntime} from '../packages/atomistic/src/runtime.js';import {PotentialAnalysisService} from '../packages/atomistic/src/potential-workflow.js';import{createScienceBridge}from'../packages/pi-adapter/src/science-bridge.js';import{PiPlatformSessionService,type PlatformTransport}from'../packages/pi-adapter/src/platform-session.js';import{responseFixtureEvents}from'../packages/pi-adapter/src/platform-probe.js';import{cloudCatalogSchema}from'../packages/contracts/src/platform.js';import{digest}from'../packages/atomistic/src/selection.js';
const sevennet=process.argv.includes('--sevennet'),potentialId=sevennet?'sevennet-0-11jul2024':'mace-mp-0b2-small';
const root=process.cwd(),temp=await mkdtemp(join(tmpdir(),'mx-m69-pi-')),project=join(temp,'project');await mkdir(project);
const runtime=new AtomisticRuntime(root,join(temp,'state'),id=>id==='project'?project:null);await runtime.restore();const automation=new PotentialAnalysisService(root,join(temp,'state'),runtime);
const dir=resolve(sevennet?'runtime/m6/acceptance/m610/pi':'runtime/m6/acceptance/m68-m69');await mkdir(dir,{recursive:true});const checks:string[]=[];const base={domain:'inorganic-crystals' as const,mode:'exploratory' as const,potentialId:null,secondaryId:null,evidenceIds:[]};const args=(action:string,targetId:string,extra={})=>({...base,action,targetId,...extra});
try{
const path=resolve(sevennet?'runtime/m6/m610-source/checkpoint.bin':'runtime/m6/m68-sources/mace-mp-0b2-small/checkpoint.bin');let cached=false;try{await access(path);cached=true;}catch{}if(cached)await runtime.mountedPackages.importFile(potentialId,path);else await runtime.mountedPackages.download(potentialId);
const si=await runtime.importSample('project','si-diamond');const options={optimizer:'FIRE' as const,cellMode:'fixed' as const,cellConstraint:'none' as const,externalPressureGPa:null,maxSteps:3,fmaxEvPerAngstrom:.05};const scope={projectId:'project',conversationId:'conversation',structureId:si.id,domain:'inorganic-crystals' as const,mode:'exploratory' as const,permission:'relaxation' as const,options};const bridge=createScienceBridge(runtime,'project',scope,undefined,{service:automation,scope:{projectId:'project',conversationId:'conversation',structureId:si.id,permission:'relaxation',maxSteps:3,maxDownloadBytes:200*1048576},prompt:'选择小模型，固定晶胞弛豫 / choose a small potential and relax at fixed cell'});
 const validateExe=join(temp,process.platform==='win32'?'sciencecheck.exe':'sciencecheck');execFileSync('go',['build','-o',validateExe,'./cmd/sciencecheck'],{cwd:join(root,'services/control-plane'),timeout:120000});
 const catalog=cloudCatalogSchema.parse({items:[],nextCursor:null,alpha:{configured:true,available:true,remainingRequests:16,expiresAt:new Date(Date.now()+600000).toISOString(),limits:{maxRequests:8,maxOutputTokensPerRequest:512,maxDurationSeconds:180}}});
 const payloads:any[]=[],records=new Map<string,any>();let state='created',round=0;const createdAt=new Date().toISOString(),deadline=new Date(Date.now()+180000).toISOString();
 const transport:PlatformTransport={origin:'http://127.0.0.1:18788',async platformRequest(path,init){
  const task=()=>({id:'task-fixture',clientTaskId:'client-fixture',modelId:'materials-research',billingMode:'alpha-test',budget:catalog.alpha.limits,consent:{policyVersion:'cloud-alpha-v1',prompt:true,history:'platform-only',fileCount:0,skillCount:1},state,scientificQuality:'not_evaluated',createdAt,deadline,requestCount:round});
  if(path==='/v1/tasks')return Response.json(task());if(path.endsWith('/finish')){state=JSON.parse(String(init?.body)).state;return Response.json(task());}if(path.endsWith('/cancel')){state='cancelled';return Response.json(task());}
  if(path.startsWith('/v1/model-requests/'))return Response.json(records.get(path.split('/').at(-1)!));
  assert.equal(path,'/v1/model-gateway/responses');const payload=JSON.parse(String(init?.body));payloads.push(payload);execFileSync(validateExe,[],{input:JSON.stringify(payload),timeout:10000});round++;state='running';
  const id=new Headers(init?.headers).get('X-Materialsx-Request-Id')!;records.set(id,{id,taskId:'task-fixture',modelId:'materials-research',billingMode:'alpha-test',execution:'completed',settlement:'not_billed',scientificQuality:'not_evaluated',usage:{source:'responses',inputTokens:10,outputTokens:4,cachedInputTokens:2,uncachedInputTokens:8,reasoningTokens:1},reservedCredits:'0',chargedCredits:null,salesPriceVersionId:null,routeVersionId:'offline-fixture',terminalReceived:true,errorCode:null,dispatched:true});
  const outputs=payload.input.filter((i:any)=>i.type==='function_call_output');const last=outputs.length?JSON.parse(outputs.at(-1).output):null;
  const call=round===1?args('auto_plan',si.id):round===2?args('auto_run',last.id,{potentialId,evidenceIds:last.selection.candidates.find((c:any)=>c.potentialId===potentialId).evidenceIds}):round===3?args('auto_get',last.workflowId):null;
  const events=JSON.parse(JSON.stringify(responseFixtureEvents(call?'tool':'text')));let delta=0;
  for(const e of events){if(e.item?.type==='function_call'){e.item.name='materials_science';e.item.call_id=`science-${round}`;e.item.arguments=e.item.status==='in_progress'?'':JSON.stringify(call);}if(e.response?.output)for(const i of e.response.output)if(i.type==='function_call'){i.name='materials_science';i.call_id=`science-${round}`;i.arguments=JSON.stringify(call);}if(e.type==='response.function_call_arguments.delta')e.delta=delta++===0?JSON.stringify(call):'';if(e.type==='response.function_call_arguments.done')e.arguments=JSON.stringify(call);}
  const bytes=new TextEncoder().encode(events.map((e:any)=>`data: ${JSON.stringify(e)}\n\n`).join(''));return new Response(new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=7)c.enqueue(bytes.slice(i,i+7));c.close();}}),{headers:{'Content-Type':'text/event-stream'}});
 }};
 const service=new PiPlatformSessionService(transport);const skillText=await readFile('vendor/materialsx-default-skills/skills/materials-mlip-singlepoint/SKILL.md','utf8');
 const answer=await service.prompt('account','conversation','materials-research','请选择适用机器学习势，对这个无机晶体进行固定晶胞弛豫并读取真实报告 / Choose an eligible potential, relax this bulk crystal at fixed cell, then read real reports.',{files:[],skills:[{id:'materials-mlip-singlepoint',name:'materials-mlip-singlepoint',text:skillText,sha256:digest(skillText)}]},catalog,()=>{},'10000',bridge);
 assert.match(answer,/本机工具核验/);assert(answer.includes(potentialId));assert(!answer.includes("本轮未执行本地计算"));assert.equal(payloads.length,4);assert.equal(service.snapshot('conversation')?.task.state,'completed');
 const wire=JSON.stringify(payloads);assert(wire.includes('materials_science 受控本地计算工具'));assert(!wire.includes('只能通过已批准的只读工具'));for(const forbidden of ['"position"','"atoms"','forcesEvPerAngstrom','outputDirectory',project,temp,root])assert(!wire.includes(forbidden),`private geometry/path leaked: ${forbidden}`);
 assert.equal(runtime.list('project').filter(j=>j.job.status==='completed').length,1);
 checks.push('Real Pi Responses streaming and current Go validator drive auto_plan -> auto_run -> auto_get -> actual FIRE calculation -> final response; no geometry, arrays or paths leave the host.');
 const w=automation.list('project')[0]!;assert.equal(w.state,'completed');assert(runtime.get({projectId:'project',runId:w.runId!}).relaxation?.summary);await writeFile(join(dir,'pi-flow.json'),JSON.stringify({stage:sevennet?'M6.10':'M6.9',passed:true,realPiSDK:true,realGoValidator:true,realLocalRelaxation:true,modelTransport:'offline scripted Responses',providerCalls:0,checks,workflow:w},null,2)+'\n');service.dispose();
 console.log(`${sevennet?'M6.10 SevenNet':'M6.9 MACE'} real Pi/Go/local calculation workflow passed`);
}finally{automation.dispose();runtime.dispose();await rm(temp,{recursive:true,force:true});}
