import {dialog,ipcMain,type BrowserWindow} from 'electron';
import {z} from 'zod';
import {ownedText} from '../../../packages/atomistic/src/discovery-io.js';
import {researchProjectSchema,moosRefSchema} from '../../../packages/contracts/src/research-project.js';
import type {ResearchService} from './research-service.js';
export function registerResearchIpc(service:ResearchService,window:()=>BrowserWindow|null){
  const id=z.uuid();
  const view=async<T>(p:unknown,read:(id:string)=>T)=>{const project=id.parse(p);try{await service.authorizeProject(project,false);}catch{/* Team authorization marks remote snapshots denied before views are returned. */}return read(project);};
  const preview=async<T>(p:unknown,read:(id:string)=>T)=>{const project=id.parse(p);await service.authorizeProject(project,false);return read(project);};
  ipcMain.handle('campaign:logs',(_e,p,j)=>service.campaigns.logs(id.parse(p),id.parse(j)));
  ipcMain.handle('campaign:list',(_e,p)=>service.campaigns.overview(id.parse(p)));
  ipcMain.handle('campaign:configure',(_e,p,input)=>service.campaigns.configure(id.parse(p),input));
  ipcMain.handle('campaign:example',(_e,p)=>service.campaigns.installExample(id.parse(p)));
  ipcMain.handle('campaign:query',(_e,p,j)=>service.campaigns.query(id.parse(p),id.parse(j)));
  ipcMain.handle('campaign:cancel',(_e,p,j)=>service.campaigns.cancel(id.parse(p),id.parse(j)));
  ipcMain.handle('campaign:preview',(_e,p,j,path)=>service.campaigns.preview(id.parse(p),id.parse(j),z.string().min(1).max(2000).parse(path)));
  ipcMain.handle('campaign:file',async(_e,p)=>{const project=id.parse(p),w=window();service.campaigns.overview(project);if(!w)return null;const selected=await dialog.showOpenDialog(w,{properties:['openFile'],filters:[{name:'Local Node script or input',extensions:['mjs','js','json','csv','dat','txt']}]});return selected.canceled||!selected.filePaths[0]?null:service.campaigns.selectFile(project,selected.filePaths[0]);});
  ipcMain.handle('method-packages:list',()=>service.methodPackages.overview());
  ipcMain.handle('method-packages:verify',(_e,pin)=>service.methodPackages.verify(pin));
  ipcMain.handle('method-packages:review',(_e,input)=>service.methodPackages.review(input));
  ipcMain.handle('method-packages:import',async()=>{const w=window();if(!w)return null;const result=await dialog.showOpenDialog(w,{properties:['openFile'],filters:[{name:'Method metadata or signed release',extensions:['json']}]});
    return result.canceled||!result.filePaths[0]?null:service.methodPackages.import(JSON.parse(ownedText(result.filePaths[0],512*1024)));});
  ipcMain.handle('next-experiment:list',(_e,p)=>service.nextExperiments.overview(id.parse(p)));
  ipcMain.handle('next-experiment:study',(_e,p,input)=>service.nextExperiments.saveStudy(id.parse(p),input));
  ipcMain.handle('next-experiment:design',(_e,p,input)=>service.nextExperiments.design(id.parse(p),null,input));
  ipcMain.handle('next-experiment:feedback',(_e,p,input)=>service.nextExperiments.feedback(id.parse(p),input));
  ipcMain.handle('next-experiment:preview',(_e,p,d,path)=>service.nextExperiments.preview(id.parse(p),id.parse(d),z.string().min(1).max(2000).parse(path)));
  ipcMain.handle('experiment:list',(_e,p)=>service.experiments.overview(id.parse(p)));
  ipcMain.handle('experiment:configure',(_e,p,input)=>service.experiments.configure(id.parse(p),input));
  ipcMain.handle('experiment:run',(_e,p,input)=>service.experiments.run(id.parse(p),null,input));
  ipcMain.handle('experiment:preview',(_e,p,r,path)=>service.experiments.preview(id.parse(p),id.parse(r),z.string().min(1).max(2000).parse(path)));
  ipcMain.handle('experiment:import',async(_e,p)=>{const projectId=id.parse(p);service.overview(projectId);const w=window();if(!w)return null;
    const selected=await dialog.showOpenDialog(w,{properties:['openFile'],filters:[{name:'Engineering tensile data',extensions:['csv','xlsx']}]});
    return selected.canceled||!selected.filePaths[0]?null:service.experiments.importFile(projectId,selected.filePaths[0]);});
  ipcMain.handle('research:scientific',(_e,p)=>view(p,id=>service.scientific.overview(id)));
  ipcMain.handle('research:audit',(_e,p,input)=>service.scientific.audit(id.parse(p),null,input));
  ipcMain.handle('research:source-notice',(_e,p,input)=>service.scientific.notice(id.parse(p),input));
  ipcMain.handle('research:methods',(_e,p,input)=>service.scientific.assess(id.parse(p),null,input));
  ipcMain.handle('research:method-run',(_e,p,input)=>service.scientific.run(id.parse(p),null,input));
  ipcMain.handle('research:scientific-preview',(_e,p,r,path)=>preview(p,pid=>service.scientific.preview(pid,id.parse(r),z.string().min(1).max(2000).parse(path))));
  const papers=()=>{if(!service.papers)throw Error('PAPER_SERVICE_UNAVAILABLE');return service.papers;};
  ipcMain.handle('papers:cancel',(_e,p)=>papers().cancel(id.parse(p)));
  ipcMain.handle('papers:list',(_e,p)=>papers().library.list(id.parse(p)));
  ipcMain.handle('papers:search',(_e,p,q)=>papers().operation(id.parse(p),signal=>papers().library.search(id.parse(p),q,signal)));
  ipcMain.handle('papers:get',(_e,p,q)=>papers().operation(id.parse(p),signal=>papers().library.get(id.parse(p),q,signal)));
  ipcMain.handle('papers:fetch',(_e,p,q)=>papers().operation(id.parse(p),signal=>papers().library.fetch(id.parse(p),q,signal)));
  ipcMain.handle('papers:read',(_e,p,q)=>papers().operation(id.parse(p),signal=>papers().library.read(id.parse(p),q,signal)));
  ipcMain.handle('papers:export',(_e,p,q)=>papers().library.export(id.parse(p),q));
  ipcMain.handle('papers:document',(_e,p,q)=>{service.overview(id.parse(p));return papers().library.document(q);});
  ipcMain.handle('papers:environment',(_e,action)=>z.enum(['check','repair']).parse(action)==='check'?papers().environment.check():papers().environment.repair());
  ipcMain.handle('research:deliveries',(_e,p)=>view(p,id=>service.deliveries(id)));
  ipcMain.handle('research:revision-inputs',(_e,p)=>service.revisionBinding(id.parse(p)));
  ipcMain.handle('research:project',(_e,p)=>view(p,id=>service.overview(id)));
  ipcMain.handle('research:save',(_e,p,expected)=>service.save(researchProjectSchema.parse(p),z.number().int().positive().parse(expected)));
  ipcMain.handle('research:search',(_e,input)=>{const q=z.strictObject({projectId:id,query:z.string().max(160),reviewScope:z.enum(['verified','include-unreviewed']),cursor:z.string().max(2048).optional()}).parse(input);return service.router.search(q.projectId,null,{query:q.query,reviewScope:q.reviewScope,...(q.cursor?{cursor:q.cursor}:{})});});
  ipcMain.handle('research:select',(_e,p,ref)=>service.select(id.parse(p),moosRefSchema.parse(ref)));
  ipcMain.handle('research:import',async(_e,p)=>{const projectId=id.parse(p);service.overview(projectId);const w=window();if(!w)return null;
    const selected=await dialog.showOpenDialog(w,{properties:['openFile'],filters:[{name:'Project research input JSON',extensions:['json']}]});
    return selected.canceled||!selected.filePaths[0]?null:service.import(projectId,selected.filePaths[0]);});
  ipcMain.handle('research:refresh',(_e,p,s)=>service.refresh(id.parse(p),id.parse(s)));
  ipcMain.handle('research:image',(_e,p,s,media)=>service.image(id.parse(p),id.parse(s),z.string().min(1).max(220).parse(media)));
  ipcMain.handle('research:preview',(_e,p,d,kind)=>preview(p,pid=>service.preview(pid,id.parse(d),z.enum(['table','chart','report']).parse(kind))));
}
